### ISSUE TITLE
monitoring(ping): amélioration du health point et système d'alertes

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1002]
**Description du problème**

En cas de crash (mongo par exemple), on n'est pas alerté automatiquement.

Le health checkpoint n'est pas efficace, ni standard.

**Comportement attendu**

TODO:
- déplacer le health checkpoint ici: /healthz
- ajouter un check mongo/pg
- mettre en place un système d'alerte

**Recette PO**

- [x] provoquer un crash volontaire de mongo
- [x] s'assurer que le /healthz est KO
- [x] s'assurer que l'on est averti par mail et/ou mattermost

**Comment by ledugong** [comment]
@Toub que dois-je faire pour la recette ? tu lances un crash et je vérifie mes mails et mattermost ?

**Comment by Toub** [comment]
Tu peux voir que les cases sont cochées, c'est que j'ai fait la recette.

C'est donc ok

**Comment by ledugong** [comment]
Non recettable PO
