### ISSUE TITLE
feat(email): better batchs & email management 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1015]
**Situation Actuelle**

- les mails sont envoyées immédiatement
- pas de trace des envois de notre côté
- en cas d'erreur, pas de retry
- difficile d'analyser les problèmes

**Comportement souhaité**

- [x] décomposer l'opération en 2 étapes: stockage du mail en bdd, puis un cron vient les consommer
- [x] retry en cas d'erreur

**Recette PO**

- [x] vérifier que l'envoi de tous les emails fonctionne
- [x] yassine ou nicolas: vérifier que les données en base (tables `monitor_batch_process` + `message_email`) sont correctes

**Comment by ledugong** [comment]
Mails OK
Mail création d'une structure
Mail validation d'une structure
Mail guide utilisateur
Mail import
Mail demande de nouveau mot de passe
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Validation d'une demande d'ajout à une structure

@Toub par contre celui là n'est pas arrivé : 
Inscription à une structure déjà existante : les administrateurs reçoivent un mail leur demandant de valider ce nouvel utilisateur

**Comment by ledugong** [comment]
Mails OK

Mail création d'une structure
Mail validation d'une structure
Mail guide utilisateur
Mail import
Mail demande de nouveau mot de passe
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Validation d'une demande d'ajout à une structure
Inscription à une structure déjà existante

Pour info, je me suis basée sur ls objets des mails car les mails ne s'affichent pas sur yopmail.

**Comment by ledugong** [comment]
Mails OK

Mail création d'une structure
Mail validation d'une structure
Mail demande de nouveau mot de passe
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Validation d'une demande d'ajout à une structure
Inscription à une structure déjà existante
