### ISSUE TITLE
feat(email): support des pièces joints dans MessageEmailSender

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1021]
**Situation Actuelle**

`MessageEmailSender` ne supporte pas les pièces jointes, donc ne peut pas être utilisé par `UsagersMailsService`

**Comportement souhaité**

Description du comportement souhaité

- [x] supporter les pièces joints dans `MessageEmailSender` (stockage disque ou en bdd)
- [x] mise à jour de `UsagersMailsService`
- [x] migration de tipimail template vers un local template 

**Recette PO**

- [x] test du mail de prise de RV avec pièce jointe
- [x] test des autres mail (car impact possible)

**Comment by ledugong** [comment]
@Toub dans la section recette je lis "test du mail de prise de RV avec pièce jointe". 
Je reçois bien le mail mais aucune pièce jointe : 
<img width="689" alt="Capture d’écran 2021-01-07 à 10 47 55" src="https://user-images.githubusercontent.com/59437305/103877773-ce0ac300-50d5-11eb-8e0d-34a8bd2f4efd.png">

Sinon mails OK :
Mail création d'une structure
Mail validation d'une structure
Mail guide utilisateur
Mail import
Mail demande de nouveau mot de passe
Mail prise de RDV
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Validation d'une demande d'ajout à une structure
Inscription à une structure déjà existante

**Comment by ledugong** [comment]
Recette PO OK

Mail de prise rdv OK
Affichage pj OK
Ajout rdv dans calendrier OK
Changement et ajout du nouveau rdv dans calendrier OK

Autre mail (ajout utilisateur à une structure) OK

**Comment by ledugong** [comment]
Mail prise de rdv (pj, ajout calendrier) OK

Sinon mails OK :
Mail création d'une structure
Mail validation d'une structure
Mail guide utilisateur
Mail import
Mail demande de nouveau mot de passe
Mail prise de RDV
Ajout d'un nouvel utilisateur via section "Utilisateurs"

Mails toujours en attente : 
Validation d'une demande d'ajout à une structure
Inscription à une structure déjà existante

**Comment by ledugong** [comment]
Mail prise de rdv (pj, ajout calendrier) OK

Sinon mails OK :
Mail création d'une structure
Mail validation d'une structure
Mail demande de nouveau mot de passe
Mail prise de RDV
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Validation d'une demande d'ajout à une structure
Inscription à une structure déjà existante

Mails à vérifier plus tard :
Mail guide utilisateur
Mail import
