### ISSUE TITLE
feat(MAIL_AUTO): retirer le profil facteur lors de l'envoi du mail import

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1022]
**Situation Actuelle**

Actuellement, le mail automatique concernant l'import est envoyé à tous les membres d'une structure, même ceux qui n'ont pas accès à la fonctionnalité import.

**Comportement souhaité**

Envoyer le mail import seulement aux instructeurs, gestionnaires et administrateurs. Pas aux facteurs.

**Recette PO**

Tester la réception du mail avec les différents profils.

**Comment by ledugong** [comment]
@Toub

Mes différents tests : 
- Je crée une structure : l'admin reçoit bien les mails guide + import

- J'ajoute des utilisateurs depuis la section structure
Admin reçoit bien les mails guide + import
Gestionnaire reçoit bien le mail guide + import
Instructeur reçoit le mail guide seulement --> il doit recevoir les 2 mails guide + import
Facteur reçoit le mail guide + import --> il ne doit pas recevoir le mail d'import

<img width="956" alt="Capture d’écran 2021-03-18 à 15 02 27" src="https://user-images.githubusercontent.com/59437305/111638803-f8c27780-87fa-11eb-86aa-4882939518f7.png">

<img width="604" alt="Capture d’écran 2021-03-18 à 15 02 45" src="https://user-images.githubusercontent.com/59437305/111638838-02e47600-87fb-11eb-8b6e-162b7c129712.png">

- En tant que nouvel utilisateur, je m'ajoute à une structure via le bouton "inscription" et on valide mon inscription. Je suis par défaut instructeur et je reçois seulement le mail guide et pas le mail import. Mais cette fonctionnalité visant à être supprimée, à la limite c'est pas grave.

**Comment by Toub** [comment]
Exact, j'ai corrigé un autre problème détecté en voulant corriger celui-là (la détection d'usagers en doublons qui était cassée) et j'en ai oublié le problème initial!

**Comment by ledugong** [comment]
@Toub 

J'ajoute des utilisateurs depuis la section structure mais les 4 profils n'ont reçu que le guide utilisateur.
Et je retrouve pas les mails de l'import dans la liste d'attente de tipimail.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Structure et comptes crées, en attente des mails pour validation en prod.

**Comment by ledugong** [comment]
Recette Prod OK
