### ISSUE TITLE
feat(AJOUT_PJ): clarifier le besoin d'écrire le nom de la pj

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1024]
**Situation Actuelle**

Actuellement, on ajoute un pj sans mettre le nom du document, le bouton "Ajouter" est grisé mais on ne comprend pas pourquoi.
<img width="955" alt="Capture d’écran 2020-12-02 à 13 26 54" src="https://user-images.githubusercontent.com/59437305/100872561-46acad00-34a2-11eb-8b79-ffdf56fbe8b6.png">

**Comportement souhaité**

Ne jamais griser le bouton "Ajouter" mais à la place mettre le champ "nom du document" en rouge s'il n'est pas rempli.

ATTENTION, à faire à 2 endroits : création d'une demande de domiciliation + fiche domicilié.

**Recette PO**

Ajout d'une pj aux 2 endroits.

**Comment by ledugong** [comment]
@pYassine petit bug d'affichage sur l'ajout de pj lors d'une création de domiciliation (testé sur Chrome)
<img width="889" alt="Capture d’écran 2020-12-22 à 10 20 27" src="https://user-images.githubusercontent.com/59437305/102871920-52571800-443f-11eb-888a-a429553a2593.png">

**Comment by ledugong** [comment]
@pYassine j'ai toujours le même bug d'affichage (testé sous Safari et Chrome)

**Comment by pYassine** [comment]
Corrigé @ledugong

**Comment by ledugong** [comment]
@pYassine je vois un bug lors de la création d'une dom, scénario pour le reproduire : 
- lancer une création de domiciliation
- arrivée à l'étape 4 des pj, ajouter un document et son nom mais cliquer sur "suivant" au lieu de "ajouter"
- je tombe sur une page blanche 
Il faudrait qu'on arrive sur la page récapitulative, sans que la pj ait été prise en compte.

**Comment by ledugong** [comment]
Recette PO OK
Testé ETQ admin, gestionnaire et instructeur

**Comment by ledugong** [comment]
Recette Prod OK
Testé ETQ admin, gestionnaire et instructeur
