### ISSUE TITLE
bug(CREATION_STRUCTURE): bug réception mail

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1026]
**Description du problème**

Test fait en PP le 03/12 : 
- création d'une structure appelée "test 2 0312" (voir le mail en PP)
- je reçois bien le mail de demande de validation sur la boite contact PP
- en cliquant sur "valider le compte, je tombe sur cette page" (à noter que je suis bien connectée en tant qu'admin donc la question du non-accès car non connectée ne se pose pas) : 
<img width="1266" alt="Capture d’écran 2020-12-03 à 14 06 29" src="https://user-images.githubusercontent.com/59437305/101022012-13851f00-3571-11eb-8986-b3834208ffa9.png">
- en parallèle je surveille la boite yopmail correspondante, aucun mail pour le moment
- je reclique sur "valider mon compte" sur la boite contact PP et je tombe sur cette page : 
<img width="1270" alt="Capture d’écran 2020-12-03 à 14 09 38" src="https://user-images.githubusercontent.com/59437305/101022119-3ca5af80-3571-11eb-8e68-d4dbc9b8f0b7.png">
- par contre là je reçois une validation de création de compte à l'adresse yopmail
- et je peux me connecter à la PP avec mon adresse yopmail, la structure est en effet validée

pas normal tout ça 

**Recette PO**

- [ ] création et activation d'une structure
- [ ] création des interractions

**Comment by Toub** [comment]
Log associé
```log
TypeError: Cannot read property 'status' of undefined
    at /app/dist/structures/structures.controller.js:93:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by Toub** [comment]
Il faudra aussi re-tester la création des interractions, car j'ai fais quelques modifications pour corriger les tests.

**Comment by ledugong** [comment]
Création structure OK
Interactions OK (testé via fiche domicilié + liste usagers)
