### ISSUE TITLE
bug(export): problèmes export domifa

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1034]
**Description du problème**

Retours export https://mattermost.fabrique.social.gouv.fr/default/pl/8r91asjc9jrb5ytinarrtmzzze

- colonnes domiciliés/comptes inversés sur onglet "structures"
- problème colonne "vérifié" sur onglet "users"

**Comportement attendu**

Description du comportement souhaité

- [x] corriger les colonnes de l'onglet "structures"
- [x] corriger les colonnes de l'onglet "users"

**Scénario de reproduction du problème**

1. Se connecter en tant que 'admin domifa'
2. Aller sur la page 'stats domifa'
3. Cliquer sur 'export'
4. Vérifier les onglets du fichier excel

**Recette PO**

- [x] vérifier les colonnes de l'onglet "structures"
- [x] vérifier les colonnes de l'onglet "users"

**Comment by ledugong** [comment]
@Toub 
Dans l'export en PP : 
- la colonne structure ID n'a pas les bonnes infos
- la colonne structure nom a les résultats de la colonne structure ID
- les noms des structures sont décalées
<img width="717" alt="Capture d’écran 2020-12-14 à 15 50 23" src="https://user-images.githubusercontent.com/59437305/102095844-4c03e300-3e24-11eb-8972-d0c1d81e22df.png">

**Comment by ledugong** [comment]
@Toub dans l'onglet Liste Structures, la colonne Date import est parfois vide même si les structures ont importées, est-ce que c'est parce qu'on a pas la donnée ?

**Comment by Toub** [comment]
Probablement, car ça ne concerne que les plus vieilles structures.

@pYassine tu confirmes?

**Comment by pYassine** [comment]
@Toub @ledugong  exactement, on n'enregistrait pas la date au début

**Comment by ledugong** [comment]
Ok merci, recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
