### ISSUE TITLE
feat(smtp): migrer l'API tipimail vers le SMTP

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1039]
**Situation Actuelle**

On utilise l'API de tipimail

Inconvénients:
- dépendance à l'api
- pas possible d'envoyer les mails vers mailtrap ou autre sur les environnements de test

Pas urgent, mais à tester en cas d'ajout d'un nouveau mail.

**Comportement souhaité**

Description du comportement souhaité

- [x] tester d'abord sur un seul mail (un nouveau ou un ancien):
- [x] rappatrier les templates en local
- [x] générer le contenu dans l'appli
- [x] nettoyer le code tipimail restant

**Recette PO**

- [x] tester quelques envois de mail
- [x] en prod, vérifier que les mails partent bien vers la vrai adresse

**Comment by Toub** [comment]
La migration a déjà était faite, il ne restait plus que du nettoyage de code. Juste un rapide test d'envoi de mail.

**Comment by ledugong** [comment]
Recette PO OK

Mails OK

Mail création d'une structure
Mail validation d'une structure
Mail guide utilisateur
Mail import
Mail demande de nouveau mot de passe
Mail prise de RDV
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Validation d'une demande d'ajout à une structure
Inscription à une structure déjà existante
Hard reset

**Comment by ledugong** [comment]
Recette Prod OK

Mails OK

Mail création d'une structure
Mail validation d'une structure
Mail guide utilisateur (en attente)
Mail import (en attente)
Mail demande de nouveau mot de passe
Mail prise de RDV
Ajout d'un nouvel utilisateur via section "Utilisateurs"
Hard reset
