### ISSUE TITLE
feat(maintenance): afficher une popup de maintenance si l'API est down

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1042]
**Description du problème**

Vérifier côté frontend que l'API est bien connectée
Si elle ne l'est pas, afficher une page de maintenance ou un bandeau qui indique qu'une opération de maintenance est en cours

**Comportement attendu**

Description du comportement souhaité

- [x] Afficher un message si l'API est déconnectée
- [x] Adapter les messages d'erreurs vides pour qu'ils indiquent que le site est en maintenance

**Implémentation technique**

Service `BackendHealthChecker` chargé de vérifier l'état de l'api:
- [x] méthode healthCheck permettant de vérifier le statut du backend via un appel au endpoint /healthz
- [x] déclenchement périodique dans le constructeur, du style:
```ts
 timer(5000, 60000).pipe(concatMap(()=>this.healthCheck()).subscribe();
```
- [x] désactivé sur les env de test via une variable d'environnement
- [x] exposition du currentStatusCheck$ via un BehaviorSubject (comme dans `AuthService`)
- [x] écouter ce check depuis le composant principal, et si currentStatusCheck vaut false, afficher le message expliquant que l'application est en cours de maintenance

**Recette PO**

1. Déconnecter l'API
2. Aller sur différentes pages
3. Vérifier l'affichage de la popup

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Pas encore vu en prod, un jour perhaps
