### ISSUE TITLE
bug(tests): réparer les tests du frontend

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1056]
**Description du problème**

Les tests du frontend sont cassés, et désactiver dans le fichier `.gitlab-ci.yml`

**Comportement attendu**

- [x] réparer les tests
- [x] réactiver les tests sur gitalb-ci

Note: pour les réactiver, il suffit de retirer le point en début de ligne:

![image](https://user-images.githubusercontent.com/367762/102110970-1cf66d00-3e36-11eb-8fb8-505e8e419a87.png)

**Recette PO**

- [x] les tests unitaires du frontend passent sur gitlab

**Comment by ledugong** [comment]
Non recettable PO
