### ISSUE TITLE
feat(tech): décrire la stack technique 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1064]
**Situation Actuelle**

Créer un fichier yaml qui décrit la stack technique du projet.

Partir d'un copier/coller de: 
- https://gist.github.com/revolunet/6c4bd6e69f40f80c9bd801cd5cc6c639
- https://github.com/SocialGouv/code-du-travail-numerique/pull/3225/files
- https://github.com/SocialGouv/emjpm/pull/2425/files

 
Puis la communiquer à @revolunet

**Comment by ledugong** [comment]
Non recettable PO
