### ISSUE TITLE
bug(CRÉATION_STRUCTURE): champs rouges par défaut

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1071]
**Description du problème**

Quand je clique sur "l'adresse de réception est différente", les nouveaux champs apparaissent tous en rouges comme si j'avais déjà essayé de valider sans les remplir.
<img width="827" alt="Capture d’écran 2020-12-29 à 10 46 24" src="https://user-images.githubusercontent.com/59437305/103275031-7d071a80-49c3-11eb-9242-6958e69e3efd.png">

**Comportement attendu**

Laisser les champs normaux par défaut, les rendre rouge seulement si j'ai essayé de valider sans les remplir.

**Comment by pYassine** [comment]
@ledugong  done

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
