### ISSUE TITLE
bug(PRISE_ENTRETIEN_RENOUVELLEMENT): écran de prise de rdv s'affiche au lieu de l'entretien

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1075]
**Description du problème**

Bug vu avec une structure lors d'une prise de rendez-vous d'un renouvellement. L'utilisateur n'est pas redirigé vers la page d'entretien, mais le rdv est bien pris en compte.

**Recette PO**

Valider avec la structure

**Comment by ledugong** [comment]
Non recettable PO, à valider avec la structure

**Comment by ledugong** [comment]
La structure a toujours le souci, nouveau call à planifier

**Comment by Toub** [comment]
Corrigé par @pYassine sur la v2

**Comment by ledugong** [comment]
Non recettable PO, à valider avec la structure

**Comment by ledugong** [comment]
Recette Prod OK
