### ISSUE TITLE
feat(NOTIF_SMS): ETQ utilisateur, je peux demander à l'usager s'il veut recevoir ou non un SMS

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1089]
**Situation Actuelle**

Sur la page profil et création de demande, une structure doit pouvoir indiquer si l'usager souhaite être informé par SMS ou non.

**Comportement souhaité**

- [x] Remettre la partie "souhaitez-vous recevoir des notifications SMS" sur le formulaire de création de demande avec en réponse OUI / NON
- [x] Ajouter la question à la page profil d'un usager
- [x] Si le domicilié accepte les notifications, ajouter un nouveau champ OBLIGATOIRE "Numéro de téléphone pour les notifications SMS", 
- [x] Sur ce champ, seulement permettre les numéros français en 06 ou 07,

- [x] renommer le champ actuel "Numéro de téléphone" en "Autre numéro de contact", le rendre non obligatoire et permettre tous les numéros (même étrangers).

**Recette PO**

- [x]  Activer les SMS depuis une création de domiciliation
- [x]  Activer les SMS depuis le profil
- [x]  Modifier le numéro de téléphone portable
- [x] Vérifier l'affichage de l'info sur la page profil

**Comment by ledugong** [comment]
@pYassine 

Sur l'étape 1 de la création d'une demande de dom, remplacer la question "Envoyer un SMS au domicilié à l'arrivée d'un courrier ?" par "Le demandeur souhaite-t-il recevoir un SMS à l'arrivée d'un courrier ?".

Sur la fiche domicilié, mettre un accent sur le A dans "A quel numéro de téléphone ?".

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
