### ISSUE TITLE
feat(NOTIF_SMS): ETQ Domifa, je dois pouvoir activer ou désactiver l'envoi de SMS pour une structure

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1090]
**Situation Actuelle**

Afin de réaliser les premiers tests et pour éviter la consommation de tous les crédits, il faut ajouter dans le dashboard un bouton pour désactiver l'envoi de SMS (Mail aussi ?)

**Comportement souhaité**
- [x] Par défaut, désactiver l'envoi de SMS pour toutes les structures 
- [x] Ajouter une fonctionnalité au Dashboard permettant de désactiver / activer l'envoi de SMS pour une structure

**Recette PO**

- [x] Aller sur le DashBoard Domifa, désactiver / Activer l'envoi de SMS
- [x] Actualiser la page, cliquer sur le menu et vérifier que la rubrique "notifications" apparait (url : structure/sms)
- [x] Aller sur l'url structure/sms et vérifier qu'on ne peut pas y accéder si Domifa ne nous a pas donné l'accès

**Comment by ledugong** [comment]
@pYassine 

En allant sur la page Stats DomiFa, si je désactive les SMS pour DomiFa Compte Test, le bandeau de confirmation dit "SMS activés".

Sinon recette PO OK : 
Test activation / désactivation des SMS
Test accès des différents profils : seul l'admin a bien accès
Test accès via URL si SMS désactivés, impossible de modifier les paramètres pour l'admin
Test accès via URL si SMS activés pour les autres profils, bandeau d'erreur
Tableau des différents profils à jour avec l'ajout des SMS que pour l'admin

**Comment by ledugong** [comment]
Recette Prod OK :
Test activation / désactivation des SMS
Bandeau d'activation et de désactivation des SMS
Test accès des différents profils : seul l'admin a bien accès
Test accès via URL si SMS désactivés, impossible de modifier les paramètres pour l'admin
Test accès via URL si SMS activés pour les autres profils, bandeau d'erreur
Tableau des différents profils à jour avec l'ajout des SMS que pour l'admin
