### ISSUE TITLE
feat(NOTIF_SMS): ETQ structure, je peux activer les SMS et paramétrer l'expéditeur

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1092]
**Situation Actuelle**

La structure doit pouvoir activer l'envoi des SMS depuis son interface. Un "OUI" fera apparaitre l'option SMS sur chaque fiche domicilié. Un "NON" la fera disparaître.

L'API permet de paramétrer le nom de l'expéditeur : 11 caractères max

Par défaut, nous pouvons en générer un à partir du nom de la structure 
Exemple : CCAS de nantes -> CCAS NANTES

**Comportement souhaité**

- [x] Créer une section "Paramètres d'envoi des notifications SMS"
- [x] Dans cette section, ajouter une option "Activer l'envoi des notifications SMS aux domiciliés" OUI/NON
- [x] Sous cette option, ajouter la phrase "Une fois que la fonctionnalité d'envoi de SMS au sein de votre structure est activée, il vous faudra la valider sur chacune des fiches des domiciliés lorsqu'ils vous en ont fait la demande".
- [x] Si la structure clique sur OUI, ajouter l'option "Le domicilié souhaite-t-il recevoir des notifications SMS ?" sur chaque fiche domicilié.
- [x] Si la structure clique sur NON, cacher l'option sur chaque fiche domicilié

- [x] Ajouter un champs "expediteur" au modèle des structures
- [x] Générer un expéditeur par défaut à partir du nom de la structure : supprimer les stop words, mettre tout en majuscule
- [x] Créer un formulaire permettant de paramétrer le nom de l'expéditeur (11 caractères max) ex: Croix-rouge

**Recette PO**

- [x] Tester l'activation / la désactivation des SMS côté structure
- [x] Vérifier l'apparition de l'option sur les fiches domiciliés
- [x] Changer le nom de la structure dans les paramètres
- [x] Exécuter l'envoi d'un SMS pour vérifier le nom de l'expéditeur

**Comment by ledugong** [comment]
@pYassine 

Le champ "Signature du message" n'est pas limité à 30 caractères, donc je peux m'amuser à tout remplir.
Aussi, remplacer le message d'erreur sous le champ par "La signature du message est obligatoire (maximum 30 caractères)".
<img width="768" alt="Capture d’écran 2021-03-19 à 16 46 53" src="https://user-images.githubusercontent.com/59437305/111810463-524ba480-88d6-11eb-8536-2ffc6ddd4bfe.png">

Il manque un des points du ticket : 
Sous cette option, ajouter la phrase "Une fois que la fonctionnalité d'envoi de SMS au sein de votre structure est activée, il vous faudra la valider sur chacune des fiches des domiciliés lorsqu'ils vous en ont fait la demande".

**Comment by ledugong** [comment]
@pYassine 

La plupart des premiers retours ont pas été traités 🤔 

Remplacer le message d'erreur sous le champ par "La signature du message est obligatoire (maximum 30 caractères)"
![Capture d’écran 2021-03-30 à 17 03 40](https://user-images.githubusercontent.com/59437305/113011232-e1c84180-9179-11eb-9207-872e38df609e.png)

Si j'entre 30 caractères dans la signature du mail, le texte dépasse du cadre.
![Capture d’écran 2021-03-30 à 17 04 39](https://user-images.githubusercontent.com/59437305/113011377-06241e00-917a-11eb-99b4-56f938fc4f9d.png)

Dans la liste des SMS en attente, colonne "type interaction", est-ce qu'on pourrait juste écrire "colis", "courrier" ou "avis de passage" plutôt que le language technique "colisin" etc. ?
En plus, si c'est un avis de passage, on lit actuellement "recommandein". Or, les recommandés vont arriver, donc ça va brouiller les pistes.
https://user-images.githubusercontent.com/59437305/111818565-9b542680-88df-11eb-8f0a-cccde991c7ed.png

Certains envois à 23h03 d'autres à 19h03, on peut envoyer le tout à 20h ?
![Capture d’écran 2021-03-30 à 17 08 22](https://user-images.githubusercontent.com/59437305/113011907-8c406480-917a-11eb-9024-d23b05be9455.png)

**Comment by ledugong** [comment]
@pYassine du coup à recetter il manque 

Dans la liste des SMS en attente, colonne "type interaction", est-ce qu'on pourrait juste écrire "colis", "courrier" ou "avis de passage" plutôt que le language technique "colisin" etc. ?
En plus, si c'est un avis de passage, on lit actuellement "recommandein". Or, les recommandés vont arriver, donc ça va brouiller les pistes.
https://user-images.githubusercontent.com/59437305/111818565-9b542680-88df-11eb-8f0a-cccde991c7ed.png

Certains envois à 23h03 d'autres à 19h03, on peut envoyer le tout à 20h ?
Capture d’écran 2021-03-30 à 17 08 22

**Comment by ledugong** [comment]
Enregistrements des courriers OK.
Non enregistrement OK si les SMS sont désactivés.

@pYassine par contre, pourquoi je lis envoi à 19h04 aujourd'hui pour un courrier que j'ai déclaré à 20h ? 
![Capture d’écran 2021-04-06 à 20 05 08](https://user-images.githubusercontent.com/59437305/113757846-646d7580-9713-11eb-91e7-7e6f85ae2bb3.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK car un nouveau ticket a été crée pour le dernier souci (envoi à 18h au lieu de 19h) : https://github.com/SocialGouv/domifa/issues/1321
