### ISSUE TITLE
feat(NOTIF_SMS): ETQ utilisateur, je vois un historique des SMS envoyés à un usager

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1093]
**Situation Actuelle**

Les SMS envoyés à chaque usager ne sont pas repertoriés 

**Comportement souhaité**
Les utilisateurs de Domifa doivent pouvoir avoir un historique des SMS envoyés.
Plusieurs petites alertes sont à créer pour avertir l'utilisateur en cas de souci avec le numéro de téléphone

- [x] Afficher l'historique des SMS : date d'envoi / type / contenu / statut

**Recette PO**

- [x] Aller sur un profil, regarder l'historique de SMS envoyé

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod partiellement OK, le statut du SMS reste en "envoi prévu" même après 19h
