### ISSUE TITLE
feat(NOTIF_SMS): ETQ dev, je planifie l'envoi d'un SMS suite à une interaction

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1097]
**Comportement souhaité**

Afin de gérer les envois de SMS, il faudra mettre en place un enregistrement des infos en BDD et une file d'attente comme pour les emails

- [x] Définir le modèle de donnée
- [x] Générer le contenu du SMS, déterminer l'heure d'envoi prévue et enregistrer en BDD
- [x] Si un SMS est déjà prévu pour le même domicilié, éditer le contenu pour indiquer "des courriers"

**Recette PO**

- Non recettable côté PO
- Côté dév, vérifier le contenu enregistrer dans la BDD

**Comment by ledugong** [comment]
Non recettable PO

**Comment by ledugong** [comment]
Non recettable Prod
