### ISSUE TITLE
feat(RECHERCHE): permettre un recherche de prénom + nom

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1098]
**Situation Actuelle**

Il n'est pas possible de chercher un ayant droit par son nom ET son prénom ce qui pose problème lorsque plusieurs ayants droit de familles différentes ont le même prénom OU nom.
Exemple si j'écris Ryan je vais avoir toutes les familles qui ont un ayant droit qui s'appelle Ryan car je ne peux pas écrire Ryan GOSLING dans le filtre de recherche
À tester aussi avec des prénom nom composés comme Don Quichotte de la Mancha. 

**Comportement souhaité**

Etendre la recherche à prénom + nom et pas juste l'un ou l'autre

**Recette PO**

Chercher Ryan, Gosling, Ryan Gosling, Don quichotte, De la mancha, Don quichotte de la mancha.

**Comment by Toub** [comment]
Ce ticket a été résolu avec la migration de la recherche côté frontend

**Comment by ledugong** [comment]
@Toub en cherchant "test 2" je tombe sur "test 5" dans les résultats
![Capture d’écran 2021-03-02 à 15 48 44](https://user-images.githubusercontent.com/59437305/109665748-c82ddd00-7b6e-11eb-9969-e9987de98601.png)

**Comment by Toub** [comment]
C'est normal, l'ID contient "2".

Suivant les paramètres qu'on active ou non (numéro de téléphone ou email par exemple), il y a aura toujours des faux positifs. Donc ce qui compte, c'est qu'on ai bien dans les premiers résultats les fiches recherchées.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
