### ISSUE TITLE
feat(IMPORT): refactor de la validation des données du fichier d'import

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1127]
**Situation Actuelle**

Actuellement les données sont toutes filtrés via un système manuel.

**Comportement souhaité**

- [x] Refactor validation des données: harmoniser et renforcer le filtrage des données
- [x] Au passage, re-vérifier et patcher si nécessaire les données, exemple:

```sql
select "typeDom", count (*) from usager u where decision is not null group by "typeDom" order by count (*) desc;
select "decision"->>'motif', count (*) from usager u where decision is not null group by "decision"->>'motif' order by count (*) desc;
select entretien->>'typeMenage', count (*) from usager u where decision is not null group by entretien->>'typeMenage' order by count (*) desc;
select entretien->>'residence', count (*) from usager u where decision is not null group by entretien->>'residence' order by count (*) desc;
select entretien->>'cause', count (*) from usager u where decision is not null group by entretien->>'cause' order by count (*) desc;
```

(voir `1611568677140-create-usager.migration.ts` pour les patchs)

- [x] Export des données : testé sur DomiFa Compte Test avec environ 8000 domiciliés, l'export mouline puis message d'erreur.
https://user-images.githubusercontent.com/59437305/108862304-65799600-75f0-11eb-94d7-08b34bce1549.mov
Fonctionne correctement avec 3000 domiciliés.

- [x] Il faudrait gérer toute la validation seulement côté serveur, et probablement aussi faire de l'asynchrone pour éviter le timeout si c'est trop long.

- [x] Regarder aussi du côté des transactions postgres

## Validation: 

__Comparaison__: <https://github.com/colinhacks/zod#comparison>

__zod__

- https://github.com/colinhacks/zod : typescript first

zod v1 requiers `strictNullChecks` et le futur zod v3 (la v2 a été abandonnée) requiers le `strict` mode.

Cependant, l'impact est juste que [tous les attributs du type seront optionnels](https://github.com/colinhacks/zod/issues/276), ce qui n'est pas forcément un problème pour domifa

Par contre, zod ne supporte pas le parsing avancé de date, ni les transformers (ça vient en v3), ce qui est problématique pour domifa.

__joi__

- https://joi.dev
- https://github.com/mrjono1/joi-to-typescript

Joi ne supporte pas nativement le parsing de dates en utc.
L'ajout d'une méthode de parsing maison pour les dates est complexes, et ne supporte pas typescript (Joi.extend() renvoit `anyè.

Il est possible de gérérer le type des schémas via joi-to-typescript fonctionne bien. Mais l'outil n'est pas non plus très complets (configuration limitée, problème avec validateurs maison).

__yup__

- https://github.com/jquense/yup
- https://github.com/jquense/yup/blob/master/docs/typescript.md

**Recette PO**

__Faire des tests avancés__

- [x] Tester des fichiers d'import valides:
  - vérifier que les données en base sont bien celles du fichier, pour chaque type de colonne
- [x] Tester des fichiers d'import corrompus
  - vérifier les règles avancées (champs obligatoires, dates mini/maxi...)
- [x] Tester l'export avec plusieurs milliers de domiciliés (10000)

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Toub** [comment]
En profiter pour traiter l'import de fichiers volumineux: https://github.com/SocialGouv/domifa/issues/1189

**Comment by ledugong** [comment]
- [ ] Il n'y a plus d'écran de confirmation avant de valider l'import, j'upload mon fichier et c'est direct importé sur DomiFa (quel que ce soit la taille de l'import, 3 ou 10k de doms).

- [ ] Si j'importe un fichier avec la colonne "Statut de la domiciliation" vide, l'import fonctionne quand même et on voit le domicilié seulement dans la section "Tous"
[Test_StatutDomVide.xlsx](https://github.com/SocialGouv/domifa/files/6361436/Test_StatutDomVide.xlsx)
<img width="1265" alt="Test_StatutDomVide" src="https://user-images.githubusercontent.com/59437305/115789126-e40e6c00-a3c4-11eb-9636-d1b0550c4d72.png">

**Comment by Toub** [comment]
>  Pareil pour la colonne "Date de début de dom actuelle"

Je ne reproduis pas le problème avec le jeu de données fourni, l'erreur est bien affichée (date début dom obligatoire si statut valide):

![image](https://user-images.githubusercontent.com/367762/116064035-ebb06800-a685-11eb-874b-ae6b8e379174.png)

**Comment by Toub** [comment]
> Si je mets des dates de début de dom postérieures aux dates de fin de dom, l'import passe sans erreur

C'était déjà le cas auparavant (tu peux le vérifier sur l'environnement formation) mais ça semble logique d'ajouter cette vérification.

Par contre, ce champ peut aussi correspondre à 
- Date de fin de domiciliation
- Date de radiation si radié
- Date de refus si refusé

![image](https://user-images.githubusercontent.com/367762/116065479-544c1480-a687-11eb-86e9-2e8424b69f13.png)

Du coup cette règle n'est valable que si le statut est VALIDE?

**Comment by ledugong** [comment]
> > Pareil pour la colonne "Date de début de dom actuelle"
> 
> Je ne reproduis pas le problème avec le jeu de données fourni, l'erreur est bien affichée (date début dom obligatoire si statut valide):
> 
> ![image](https://user-images.githubusercontent.com/367762/116064035-ebb06800-a685-11eb-874b-ae6b8e379174.png)

J'ai refait le test et ça passe en effet, donc ce point est OK 👌

**Comment by ledugong** [comment]
> > J'ai mis 3 dates futures différents dans la colonne "Date de fin de dom" et seulement une date future est catchée
> 
> Normal, la date de fin de dom est autorisée 1 an après la date du jour (contrairement à la date de début de dom qui doit être passée ou aujourd'hui)

Ah ouais bien vu, point OK alors 👌

**Comment by ledugong** [comment]
> > Si je mets des dates de début de dom postérieures aux dates de fin de dom, l'import passe sans erreur
> 
> C'était déjà le cas auparavant (tu peux le vérifier sur l'environnement formation) mais ça semble logique d'ajouter cette vérification.
> 
> Par contre, ce champ peut aussi correspondre à
> 
> * Date de fin de domiciliation
> * Date de radiation si radié
> * Date de refus si refusé
> 
> ![image](https://user-images.githubusercontent.com/367762/116065479-544c1480-a687-11eb-86e9-2e8424b69f13.png)
> 
> Du coup cette règle n'est valable que si le statut est VALIDE?

Je pense que c'est mieux de mettre cette règle seulement en cas de statut VALIDE. Car si un domicilié a été radié ou refusé, il peut quand même redemander une domiciliation, donc dans le future on pourrait potentiellement retrouver des cas de dates de radiation/refus antérieures à la date de domiciliation actuelle.

**Comment by ledugong** [comment]
> > J'ai mis 3 dates futures différents dans la colonne "Date de fin de dom" et seulement une date future est catchée
> 
> Normal, la date de fin de dom est autorisée 1 an après la date du jour (contrairement à la date de début de dom qui doit être passée ou aujourd'hui)

J'ai refait le test avec le fichier ci-dessous et j'ai une erreur. Du coup, quelle est la règle qui s'est appliquée ici ? Car la date de fin de dom peut être future.
[Test_DateFinDomDatesFutures.xlsx](https://github.com/SocialGouv/domifa/files/6412200/Test_DateFinDomDatesFutures.xlsx)
<img width="506" alt="Capture d’écran 2021-05-02 à 22 45 05" src="https://user-images.githubusercontent.com/59437305/116827284-7b7b7800-ab98-11eb-8298-35a9d80695b9.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
@Toub j'ai l'impression que ya un nouveau souci

Ce fichier ne passe pas (bandeau message d'erreur) alors qu'aucune erreur n'est détectée
[modele_import_domifa.xlsx](https://github.com/SocialGouv/domifa/files/6420690/modele_import_domifa.xlsx)

C'est peut-être lié à la colonne date de fin de dom / date de refus / date de radiation. 
Ce champ doit être obligatoire dans tous les cas. Alors que dans le fichier test, l'erreur n'est pas catchée.

**Comment by ledugong** [comment]
@pYassine 

[modele_import_domifa 2.xlsx](https://github.com/SocialGouv/domifa/files/6452353/modele_import_domifa.2.xlsx)
J'ai fait un test et en effet, si la colonne n'est pas remplie, c'est la date d'import qui compte comme date de refus / date de radiation. 
De même, je peux mettre une date future même si la personne est radiée ou refusée. La date maximum doit être celle du jour en cas de domicilié refusé / radié. Seulement en cas de dom valide, la date peut être future (car est la date de fin de domiciliation).

**Comment by ledugong** [comment]
@pYassine 

J'ai testé avec le fichier ci-dessous pour tester la détection des erreurs et la page affichant les erreurs ne s'affiche pas, j'ai juste le bandeau "le fichier n'a pas pu être importé".
[erreur_import_domifa.xlsx](https://github.com/SocialGouv/domifa/files/6466303/erreur_import_domifa.xlsx)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
