### ISSUE TITLE
bug(auth): ignorer la casse lors de l'authentification et l'envoi du mail de reset

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1128]
**Description du problème**

Il semble que l'authentification et/ou le reset password soit sensible à la casse 

**Comportement attendu**

- [ ] le rendre insensible à la casse
- [ ] en profiter pour ajuster le code de retour

**Recette PO**

- [x] vérifier que le système n'est plus sensible à la casse

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
