### ISSUE TITLE
bug(batch): Rapport d'erreur envoyé quotidiennement

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1135]
**Description du problème**

Le mail de rapport d'erreur est envoyé quotidiennement

**Comportement attendu**

Le mail de rapport d'erreur est envoyé seulement une fois pour chaque erreur

**Recette PO**

- [x] le mail d'erreur n'est envoyé qu'une fois

**Comment by ledugong** [comment]
Recette Prod OK
