### ISSUE TITLE
bug(import): freeze du frontend si gros fichier

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1140]
**Description du problème**

Si on importe un gros fichier, le frontend freeze pendant quelques secondes.

C'est lié à l'affichage sur la page de l'intégralité du fichier.

**Comportement attendu**

- [ ] ajouter un indicateur de progression le temps du check des données
- [x] si il y a des erreurs, on n'affiche que les 20 premières lignes en erreur
- [x] si pas d'erreurs, on n'affiche que les 20 premières lignes
- [x] si on n'affiche pas tout, afficher un message pour indiquer le nombre total

**Recette PO**

- [x] importer un gros fichier avec des erreurs
- [x] seules les lignes en erreur sont affichées
- [x] seules les 20 premières erreurs sont affichées
- [ ] importer un gros fichier sans erreurs
- [ ] seules les 20 premières lignes sont affichées

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Recette PO OK

Testé avec imports de 500 et 3700 domiciliés

Sans erreurs, seules les 50 premières lignes sont affichées
Avec erreurs, seules les 50 premières lignes sont affichées

**Comment by ledugong** [comment]
@Toub ya écrit "les 20 premières lignes" dans la recette PO mais je vois les 50 premières lignes, normal ?

**Comment by Toub** [comment]
Oui j'ai mis 50 au final

**Comment by ledugong** [comment]
Recette Prod OK
