### ISSUE TITLE
bug(MIGRATION): recette PP part 1

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1149]
**Description du problème**

En vue de la migration, plusieurs vagues de recettes en PP sont prévues.

**Comportement attendu**

Description du comportement souhaité

**toub**

- [x] Inscription d’une structure :
> Une fois le mail de demande d’activation envoyé, si je clique sur “Supprimer le compte”, la connexion est bien impossible avec un message “Compte non activé par l’administrateur”. PAR CONTRE, si après je retourne sur le mail et que je clique sur ”Valider le compte”, le premier clic est annulé et la structure est validée. Donc, en cliquant sur “Supprimer le compte”, il n’a pas été supprimé et l’action est réversible. Il faut qu’une fois le bouton “Supprimer le compte” cliqué, la structure soit bien supprimée et que le bouton “Valider le compte” ne mène nul part.

- Notifications par mail : 
Déplacé ici: https://github.com/SocialGouv/domifa/issues/1142

- [x] Mot de passe oublié :
> Le test était de créer un compte, le supprimer et vérifier que l’adresse mail n’existait bien plus. Le compte a donc été créé puis supprimé dans la section “Utilisateurs”.
En allant dans la section “Mot de passe oublié”, j’entre l’adresse mail en question et je vois le bandeau “Une erreur inattendue est survenue”, ce qui n’est pas le message d’erreur approprié.

**yassine**

- [x] Rôles utilisateurs :
> En se connectant en tant que facteur, la liste des usagers charge sans fin.

- [x] Création de demande :
> En cliquant sur le “l’entretien a lieu maintenant”, la fenêtre d’un entretien programmé pour plus tard apparait.
À ce moment-là, en cliquant sur “modifier la date de rdv”, on retombe sur l’étape 2, comme si aucun rdv n’avait été programmé.
Une fois l’entretien rempli, en cliquant sur suivant, le bandeau de confirmation apparaît mais on reste sur la même page (celle de l’entretien). Il faut cliquer sur “continuer plus tard” et retrouver la demande dans le statut “à compléter” pour pouvoir continuer.

**Recette PO**

- [x] Inscription d’une structure
- [x] Notifications par mail
- [x] Mot de passe oublié
- [x] Rôles utilisateurs
- [ ] Création de demande

**Comment by ledugong** [comment]
Inscription de la structure : 
- Suite à la demande d'inscription, DomiFa ne reçoit pas le mail de validation/refus de la structure sur le mail preprod.domifa
- Par contre le mail de l'administrateur de la structure reçoit bien les mails de guide utilisateur / import, comme si la structure avait été validée

De manière + générale, tous les mails partant de la PP doivent arriver sur la boite mail prepod.domifa, ce qui n'est plus le cas.

**Comment by ledugong** [comment]
Création de demande :
Une fois l'état civil rempli, j'arrive direct sur la page entretien programmé. De plus, le nom de l'utilisateur n'apparait pas. 
<img width="847" alt="Capture d’écran 2021-02-23 à 15 29 27" src="https://user-images.githubusercontent.com/59437305/108857955-eda96c80-75eb-11eb-902e-7bfb1f348b8a.png">

**Comment by Toub** [comment]
Je ferme, point restant déplacé ici: https://github.com/SocialGouv/domifa/issues/1199
