### ISSUE TITLE
bug(MIGRATION): recette PP part 1 - les statistiques

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1154]
**Description du problème**

En vue de la migration, plusieurs vagues de recettes en PP sont prévues.

**Scénario de reproduction du problème**

- [x] Une structure a été créée le 10/02 avec le mail xurrommeza-1725@yopmail.com (mdp à demander à AL si besoin) avec un actif radié. Les stats le lendemain devaient donc être 1 attestation délivrée dans l’année et 1 radiation, ce qui n’est pas le cas (voir screenshot dans le document migration).

- [x] Puis le 11/02 j’ai ajouté un domicilié actif avec un ayant-droit mineur et le 15/02 je vois que toutes les stats sont à 0 (alors que l’usager en question est bien dans la liste des usagers, donc ya pas eu de hard reset entre temps). Test fait le 14/01 vers 23h59, à voir si le passage à minuit a fait que tout a planté je sais pas (voir screenshot dans le document migration).

- [x] Connecté en tant que gestionnaire, en cliquant sur “exporter les statistiques”, je me retrouve avec un fichier comprenant le rapport 2020 et non les stats du 16/04/2020 au 13/02/2021 comme demandé. Alors que ça fonctionne bien en tant qu’admin et instructeur.

**Comment by Toub** [comment]
Voir aussi les messages d'erreur lors du batch nocturne:

> Dernier message d'erreur:
> duplicate key value violates unique constraint "UQ_102c69c2491695e723e3b7ed4ec"

**Comment by Toub** [comment]
A faire sur la v2 pour régler efficacement le problème de UK:
- ne plus utiliser lastExport mais regarder directement dans la table des stats si la stat existe ou non

**Comment by Toub** [comment]
>  Connecté en tant que gestionnaire, en cliquant sur “exporter les statistiques”, je me retrouve avec un fichier comprenant le rapport 2020 et non les stats du 16/04/2020 au 13/02/2021 comme demandé. Alors que ça fonctionne bien en tant qu’admin et instructeur.

Je ne reproduis pas ce point

**Comment by ledugong** [comment]
@Toub j'ai toujours le souci, ci-dessous une vidéo qui reproduit le point : 
https://user-images.githubusercontent.com/59437305/109030897-827f9900-76c4-11eb-81ce-9c91ed84bb59.mov

**Comment by Toub** [comment]
Du coup ce point est corrigé en 2.0.0?

**Comment by ledugong** [comment]
Yes recette OK

**Comment by ledugong** [comment]
Recette Prod OK
