### ISSUE TITLE
bug(IMPORT): [V1] pas d'erreurs signalées mais bandeau d'erreur lors de la validation

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1164]
**Description du problème**

Structure ID : 261
Nom de structure : Centre Communal d'Action Sociale
Fichier en question dans la channel support.

**Scénario de reproduction du problème**

Le fichier import est ajouté, aucune erreur est détectée mais en cliquant sur "Cliquez ici pour finaliser l'import", on se retrouve avec un bandeau d'erreur "Le fichier n'a pas pu être importé".

**Recette PO**

Tester l'import, prévenir la structure

**Comment by Toub** [comment]
Tu peux visualiser le rapport d'erreur du serveur ici: https://sentry.fabrique.social.gouv.fr/incubateur/domifa-backend/issues/20321/?query=server_name:prod%20is:unresolved

**Comment by Toub** [comment]
Le fichier est erroné, mais le check est fait seulement côté serveur:

![image](https://user-images.githubusercontent.com/367762/108681108-0122dd80-74ef-11eb-87e2-8a31b4da77e6.png)

Les valeurs autorisées sont:

"EXERCICE_DROITS", "PRESTATIONS_SOCIALES", "AUTRE"

Je suggère:
- de ne pas toucher à la validation côté frontend
- en cas d'erreur backend, renvoyer errorIds au client
- côté client, récupérer errorIds et l'afficher comme dans l'ancienne validation côté frontend

@pYassine je t'affecte ce ticket, à toi de le chiffrer, on en parle si ma suggestion n'est pas claire

**Comment by ledugong** [comment]
Recette PO (formation) OK

**Comment by ledugong** [comment]
Souci réglé avec la structure
