### ISSUE TITLE
bug(TRI): bouton tri croissant/décroissant ne fonctionne pas toujours

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1167]
**Description du problème**

Dans certains cas, les tris ne fonctionnent pas. En PP, le tri par ID par exemple : 
<img width="69" alt="Capture d’écran 2021-02-21 à 21 22 11" src="https://user-images.githubusercontent.com/59437305/108637427-def77400-748a-11eb-804a-77476ce3a7ae.png">

Repasser sur les tris.

**Recette PO**

Tester les différents tris.

**Comment by Toub** [comment]
@pYassine je t'affecte ce ticket, à toi de le chiffrer

**Comment by Toub** [comment]
A traiter en v2 uniquement

**Comment by Toub** [comment]
Je transforme les chaines en entiers si possible, et sinon le tri s'effectue en chaine de caractères.

Mais du coup y'a pas de miracles, les chaines seront toujours avant les nombres:

![image](https://user-images.githubusercontent.com/367762/108857541-7e337d00-75eb-11eb-8074-d49b8cf32ce2.png)

**Comment by Toub** [comment]
Je ne vois pas d'autre problème de tri, merci de préciser.

**Comment by ledugong** [comment]
Recette PO OK (PP)

**Comment by ledugong** [comment]
Recette Prod OK
