### ISSUE TITLE
bug(RECHERCHE): bugs divers

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1168]
**Description du problème**

En PP, en cherchant "ji tunk" dans "actifs" dans la barre de recherche, je tombe sur un seul résultat. Et ce résultat affiche une étiquette "ayant-droit". Or, le domicilié en question n'a pas d'ayant-droit.

En PP, je tape le chiffre 2 dans la barre de recherche et je retombe sur de nombreux résultats avec l'étiquette "ayant-droit" alors que les personnes concernées n'ont pas d'ayant-droits.
De même, dans la liste des résultats, certains n'ont aucun lien avec le chiffre 2.

**Recette PO**

Retester la recherche

**Comment by Toub** [comment]
Premier problème corrigé.

Le second problème était lié au fait qu'on cherchait aussi dans l'email et le téléphone, c'est désactivé.

**Comment by ledugong** [comment]
Recette PO OK (PP)

**Comment by ledugong** [comment]
Recette Prod OK
