### ISSUE TITLE
bug(UPLOAD): lors d'un upload de document la liste ne se met pas à jour

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1169]
**Description du problème**

Quand on upload un document depuis le formulaire de création, la liste des documents ne se met pas à jour, on ne peut pas télécharger le document ou le supprimer

**Comportement attendu**

- [x] Uploader et télécharger sans avoir à recharger la page

**Comment by ledugong** [comment]
Recette PO OK (PP)
Test PJ lors de la création + sur la fiche domicilié.

**Comment by ledugong** [comment]
Recette Prod OK
