### ISSUE TITLE
bug(usager): [V2] fix espace usagers 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1170]
__Recette DEV - @pYassine__ :
- [x] passage général sur l'espace usager
- [x] uniformiser et documenter dans le modèle `usager.etapeDemande`
- [x] rv
- [x] Ajouter / editer / supprimer une procuration ou un transfert
- [x] suppression
- [x] creation
- [x] vérifier l'affichage des ayant droits sur fiche usager
- [x] Edition des Cerfa

**Bugs à corriger**

- [x] Il faut désactiver le transfert de courrier / procuration pour les refusés
- [x] Il faut cliquer 2 fois sur "rendez-vous maintenant" pour que ça soit prit en compte
- Les documents ne se mettent pas à jour quand on vient de les uploader dans le formulaire https://github.com/SocialGouv/domifa/issues/1169

**Comment by Toub** [comment]
@pYassine à chiffrer et terminer en priorité

**Comment by pYassine** [comment]
@Toub  il ne reste plus qu'un passage + la documentation + upload de doc

**Comment by ledugong** [comment]
Recette PO OK (PP)

Transfer/procu désactivées pour les réfusés
Upload documents OK
Création de demande encore en bug mais ticket crée https://github.com/SocialGouv/domifa/issues/1203

**Comment by ledugong** [comment]
Recette Prod OK
