### ISSUE TITLE
bug(STATS): différence de statistiques entre formation et PP

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1176]
**Description du problème**

Structure ID : 14
Compte utilisé : user-45@domifa-fake.fabrique.social.gouv.fr
Même nombre de domiciliés, d'utilisateurs, informations de structure.
MAIS, sur la page stats, la partie 2 est différente (alors que les parties 1 et 3 sont pareilles).
De même, les rapports 2020 ne sont pas les mêmes entre PP et formation.

Structure ID : 2
Compte utilisé : user-32@domifa-fake.fabrique.social.gouv.fr
Même situation

**Copies d'écran**

Screenshots disponibles sur mattermost.

**Recette PO**

Nouvelle comparaison entre ces 2 structures et 2 autres.

**Comment by ledugong** [comment]
@pYassine 
En PP, si je mets date de fin au 22/02, les stats s'affichent avec une date de fin au 21/02, alors qu'en formation la date de fin est bien 22/02. Est-ce que c'est lié à ce ticket ou je dois en créer un autre ?
<img width="1039" alt="Capture d’écran 2021-02-23 à 18 32 55" src="https://user-images.githubusercontent.com/59437305/108883290-8ef0ec80-7605-11eb-9221-2197cf66ba16.png">

**Comment by Toub** [comment]
Je corrige sur ce ticket

**Comment by Toub** [comment]
Ce ticket était corrigé en 2.0.0

**Comment by ledugong** [comment]
Recette PO OK
