### ISSUE TITLE
bug(stats): Invalid stats day

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1180]
**Description du problème**

Une erreur intervient dans les logs lors de la génération des stats à minuit. Elles ne sont générées correctemen qu'à 1h.

> Error during "generate-structures-stats" process: Invalid stats day 'Mon, 22 Feb 2021 23:58:59 GMT' > 'Mon, 22 Feb 2021 23:00:00 GMT (dateExport=Mon, 22 Feb 2021 10:59:59 GMT, statsDay=Mon, 22 Feb 2021 10:59:59 GMT)'

**Comportement attendu**

Il ne devrait pas y avoir d'erreur, et les stat devraient être correctement générées.

**Comment by ledugong** [comment]
@Toub comment je peux recetter en PP ? Car je reçois toujours un mail quotidien mais c'est pour la prod.

**Comment by Toub** [comment]
Pas de mail reçu, test OK

**Comment by ledugong** [comment]
@Toub mail de rapport d'erreur "preprod" du 22/02 reçu le 23/02 sur la boite preprod.domifa, recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
