### ISSUE TITLE
bug(PP_COURRIERS): réception et remise de courrier/colis/adp

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1195]
**Scénario de reproduction du problème**

Sur la liste des usagers, en cliquant la première fois sur l'icône de réception d'un courrier, le bandeau vert apparait mais l'icône signifiant un courrier en attente n'apparait pas. Elle apparaitra à partir du 2eme courrier mais n'affichera qu'un seul courrier en attente. Même chose sur la fiche domicilié.
Aussi, sur la fiche domicilié, en déclarant la réception de courrier/colis/adp, la liste des interactions se met à jour mais le bandeau bleu permettant la remise du courrier n'apparait pas.
Les interactions de passages et d'appels sont OK.

Ci-dessous 2 vidéos montrant la situation : 
https://user-images.githubusercontent.com/59437305/108884638-1ee36600-7607-11eb-9fe4-ae5871de4610.mov
https://user-images.githubusercontent.com/59437305/108884693-2c005500-7607-11eb-9304-cc89c7e7abe3.mov

**Recette PO**

Retester toutes les interactions, sur la liste des usagers et la fiche domicilié.

**Comment by Toub** [comment]
Non reproductible, est-ce à tous les coup? Avec un navigateur précis?

Si tu reproduis, peux-tu stp:
- ouvrir la console de développement
- me faire un copier/coller du contenu

**Comment by Toub** [comment]
Reproductible sur les usagers importés, sur lesquels on n'a pas encore ajouté d'interaction

**Comment by ledugong** [comment]
Recette PO OK (PP)

**Comment by ledugong** [comment]
Recette Prod OK
