### ISSUE TITLE
bug(usager): création de demande

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1199]
**Description du problème**

Une fois l'état civil rempli, j'arrive direct sur la page entretien programmé. De plus, le nom de l'utilisateur n'apparait pas. 
<img width="847" alt="Capture d’écran 2021-02-23 à 15 29 27" src="https://user-images.githubusercontent.com/59437305/108857955-eda96c80-75eb-11eb-902e-7bfb1f348b8a.png">

**Recette PO**

- [ ]  Création de demande

**Comment by Toub** [comment]
@yassine, bug apparu avec ce bout de code supprimé il y a 7 jours, je te laisse voir pourquoi tu l'as fait et l'impact de remettre le code précédent:

![image](https://user-images.githubusercontent.com/367762/108980287-cbffc200-768b-11eb-8eca-2c278eb54ed6.png)

**Comment by ledugong** [comment]
Recette PO OK (PP)

**Comment by ledugong** [comment]
Recette Prod OK
