### ISSUE TITLE
bug(FILTRE_LISTE_USAGERS): Filtre courrier à récupérer

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1215]
**Description du problème**

Si j'ajoute du courrier depuis la liste des usagers puis que j'utilise le filtre "courrier à récupérer", les usagers en question n'apparaissent pas. De même, en retirant ce filtre par la suite, les usagers ont perdu leur courrier à récupérer.

**Recette PO**

Retester ce filtre

**Comment by Toub** [comment]
Corrigé, à tester en preprod

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
