### ISSUE TITLE
bug(usagers): [PROD] erreur suppression usager ayant des interactions 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1219]
**Description du problème**

https://sentry.fabrique.social.gouv.fr/incubateur/domifa-backend/issues/16800/?query=server_name:prod%20is:unresolved

**Comportement attendu**

On doit pouvoir supprimer un usager qui a des interactions

**Scénario de reproduction du problème**

1. Essayer de supprimer un usager ayant des interactions

**Recette PO**

- [x] essayer de supprimer un usager ayant des interactions

Problème rare, donc essayer avec pas mal d'usagers différents, sur les structures anonymisées

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Toub** [comment]
Pas reproduit sur un cas simple, à creuser. Lié à https://github.com/SocialGouv/domifa/issues/1172 ?

**Comment by Toub** [comment]
Problème lié à la migration, identifié via:

```sql
select i."structureId", i."usagerRef", u."ref", i."structureId", u."structureId" from interactions i join usager u on i."usagerUUID" = u.uuid where i."usagerRef" <> u."ref" or i."structureId" <> u."structureId" ;
```

Requête fautive:

```sql
UPDATE interactions
      SET "usagerUUID"=u.uuid
      FROM (select uuid, ref, "structureId" from usager) AS u
      WHERE interactions."usagerRef" = u."ref"; -- il manque la contrainte "structureId"
```

Correction:

```sql
UPDATE interactions
      SET "usagerUUID"=u.uuid
      FROM (select uuid, ref, "structureId" from usager) AS u
      WHERE interactions."usagerRef" = u."ref" and interactions."structureId" = u."structureId";
```

**Comment by Toub** [comment]
Et nettoyage de 9 interactions obsolètes via:
```sql
delete from interactions where not exists (select 1 from usager u where interactions."usagerRef" = u."ref" and interactions."structureId" = u."structureId");
```

**Comment by Toub** [comment]
Intégré au tag 2.0.4

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
