### ISSUE TITLE
feat(dat): mise à jour DAT (suppression mongo)

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1221]
**Situation Actuelle**

DAT pas à jour avec suppression mongo

**Comportement souhaité**

Mettre à jour le DAT

**Comment by Toub** [comment]
Pas d'office à ma disposition pour le mettre à jour, je vais voir si on peut trouver un template open-document

**Comment by Toub** [comment]
Fichier mis à jour via l'éditeur en ligne de nextcloud: https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Juridique%20-%20S%C3%A9curit%C3%A9%20-%20RGPD/DAT&fileid=8215

**Comment by ledugong** [comment]
Recette OK, transmis à l'équipe SRE
