### ISSUE TITLE
bug(usager): errorTypeError: e.content is undefined

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1224]
**Description du problème**

Description du problème

https://sentry.fabrique.social.gouv.fr/incubateur/domifa-frontend/issues/20979/?query=is:unresolved

**Comportement attendu**

Proteger le code si content n'est pas défini

**Recette PO**

- [ ] tester la non-régression sur la page usagers, et en particulier procuration et transfert courrier

**Comment by ledugong** [comment]
@Toub si je supprime la procuration et que je ferme la section, elle réapparaît par la suite
https://user-images.githubusercontent.com/59437305/109663691-ac293c00-7b6c-11eb-9cdf-2ce627772f81.mov

Le transfert c'est l'inverse, si j'en crée un, que je le modifie puis que je referme la section, en la rouvrant le transfert n'existe plus.

**Comment by ledugong** [comment]
Ticket bug crée : https://github.com/SocialGouv/domifa/issues/1246
