### ISSUE TITLE
feat(NOTIF_SMS): Supprimer / mettre à jour un SMS à envoyé si on supprimer une interaction 

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1227]
**Situation Actuelle**

Les SMS sont enregistrés dans la file d'attente à chaque nouvelle interaction.

**Comportement souhaité**

Si une interaction est supprimée, il faut que le SMS soit aussi supprimé de la file d'attente

- [x] Supprimer le SMS de la file d'attente si on supprime une interaction
- [x] Supprimer le SMS de la file d'attente si le courrier a été distribué

**Recette PO**

- [x] Ajouter une interaction
- [x] Supprimer l'interaction
- [x] Vérifier qu'on ne reçoit pas de SMS à l'heure prévue

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Recette PO OK

Je crée une interaction, le SMS apparait bien dans la liste d'attente, je la supprime, elle disparait bien de la liste.

**Comment by ledugong** [comment]
Recette Prod OK
