### ISSUE TITLE
bug(AUTH): forcer le refresh du Token au lancement de l'app

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1230]
**Description du problème**

Le token étant stocké localement, l'utilisateur est loggué d'office, même si le token n'est pas à jour
Cela entraine des bugs et déconnexion intempestives 

**Comportement attendu**

- [x] Forcer le rafraichissement du Token
- [x] Se déconnecter si celui-ci n'est pas à jour
- [x] Mettre à jour le menu

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
