### ISSUE TITLE
feat(metrics): diffuser des métriques techniques et applicative sur grafana

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1232]
**Besoin**

Exposer des métriques techniques et métier de l'application sur le grafana de la fabrique.

Voir: https://socialgouv.github.io/support/#/kubernetes?id=exposer-les-m%C3%A9triques-de-mon-application

- [ ] technique: exposer le temps de réponse: https://blog.risingstack.com/node-js-performance-monitoring-with-prometheus/
- [ ] métier: exposer le nombre d'emails envoyés par type

Cela sera ensuite élargit à d'autres métriques (sms, usagers, interactions...).

**Recette PO**

- [ ] les métriques sont dispo sur grafana

**Comment by revolunet** [comment]
Les temps de réponse sont déjà accessibles via les [stats grafana de votre ingress](https://grafana.fabrique.social.gouv.fr/d/4Qj03wsMz/nginx-ingress-controller?orgId=1&var-cluster=prod2&var-namespace=ingress-basic&var-controller_class=nginx&var-controller=All&var-ingress=domifa-prod) (reverse-proxy)
