### ISSUE TITLE
feat(INFOS_STRUCTURE): ajouter des exemples pour encourager les structures à mettre un nom plus clair

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1235]
**Situation Actuelle**

Les structures ont tendance à mettre des noms génériques comme "CCAS" ou autre, ce qui rend entre autres les stats moins claires.

**Comportement souhaité**

Dans la section "Modifier les informations de votre structure", ajouter une phrase en italique sous le champ "Raison sociale". Diminuer la police du texte pour essayer de tout caler sur une ligne.

Ci-dessous le texte : 

"Préciser le nom de votre ville / de votre unité locale en cas de réseau / de votre association. Ex : CCAS du Havre / Croix Rouge de Paris / Association Aurore"

**Recette PO**

Vérifier le texte sous le champ "Raison sociale".

**Comment by Toub** [comment]
Affichage dans un cadre d'information?

![image](https://user-images.githubusercontent.com/367762/111284102-1ac3ca80-8640-11eb-864d-e0d58693a269.png)

**Comment by Toub** [comment]
Je l'ajoute aussi lors de l'inscription:

![image](https://user-images.githubusercontent.com/367762/111284596-8ad25080-8640-11eb-9d4f-c66fd6fd7457.png)

Pour que ça passe sur une ligne, j'élargis légérèrement le cadre (800px => 900px):

![image](https://user-images.githubusercontent.com/367762/111285102-121fc400-8641-11eb-8135-c06613e80957.png)

**Comment by Toub** [comment]
Pour mesurer l'amélioration, on peut utiliser cette requête: 

```sql
select trim(lower("nom")) as "nom", count(*) as "nb" FROM public."structure"
group by trim(lower("nom"))
ORDER BY count(*) desc;
```

![image](https://user-images.githubusercontent.com/367762/111285678-ac800780-8641-11eb-95b6-8b4115571174.png)

**Comment by Toub** [comment]
Sans le bandeau, ça donne ça:

![image](https://user-images.githubusercontent.com/367762/111289104-1a79fe00-8645-11eb-88de-7b8db184c976.png)

**Comment by Toub** [comment]
Message affiché en rouge si la valeur saisie est en minuscules "ccas" ou "centre communal d'action sociale":

![Peek 16-03-2021 11-08](https://user-images.githubusercontent.com/367762/111292104-21eed680-8648-11eb-9220-353b0b82acd3.gif)

Mais non-bloquant, on peut quand même enregistrer

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
