### ISSUE TITLE
feat(NOTIF_SMS): ETQ utilisateur, je peux éditer les préférences de contact d'un usager

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1249]
**Situation Actuelle**

Je ne peux pas éditer les infos de contact d'un usager .

**Comportement souhaité**

- [x] Pouvoir éditer mes préférences de contact sur le profil
- [x] Pouvoir éditer mes préférences de contact dans la création de dossier
- [x] Pouvoir ajouter un numéro de téléphone dédié à la réception de SMS. 

Par défaut il reprend le numéro déjà présent dans le dossier s'il s'agit d'un numéro de mobile

**Recette PO**

- [x] Activer les SMS depuis une création de domiciliation
- [x] Activer les SMS depuis le profil
- [x] Modifier le numéro de téléphone portable 

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@pYassine 

Sur la fiche domicilié, si je remplis le champ numéro de téléphone puis je le vide, je ne peux pas désactiver les notifications.
https://user-images.githubusercontent.com/59437305/112302730-b0dc9e00-8c9b-11eb-8b9f-8e4484d8ecdb.mov

**Comment by ledugong** [comment]
@pYassine 
Est-ce que dans la création d'une demande de dom, tu peux ajouter la phrase "Numéro de portable uniquement" comme sur la fiche domicilié ?
![Capture d’écran 2021-03-30 à 16 41 54](https://user-images.githubusercontent.com/59437305/113007843-d9bad280-9176-11eb-9e4d-007084df60ca.png)

Autre point, ci-dessous les étapes pour reproduire (accroche toi) : 
- je commence une demande de domiciliation en cliquant sur OUI pour les notifs et en entrant un téléphone valide
- je continue ma demande jusqu'à l'étape 3 ou 4
- je décide de revenir sur l'étape 1 pour finalement dire NON pour les notifs
- je finis ma demande et je la valide dans la foulée
- je me rends sur la fiche domicilié dans la sections notifications, on voit bien le NON mais le numéro de téléphone apparait quand même alors que normalement, si c'est non rien ne s'affiche (comme ci-dessous)
![Capture d’écran 2021-03-30 à 16 45 32](https://user-images.githubusercontent.com/59437305/113008471-5a79ce80-9177-11eb-9f7f-41a705959699.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
