### ISSUE TITLE
bug(usager): la détection des "doublons" ne fonctionne plus

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1254]
**Description du problème**

La détection des "doublons" ne fonctionne plus

**Comportement attendu**

Lors de la création d'un usager, les doublons potentiels 'même nom et prénom' sont affichés.

**Recette PO**

- [x] lors de la création d'un usager, les doublons potentiels 'même nom et prénom' sont affichés.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
