### ISSUE TITLE
feat(MODELES_COURRIER): format adresse de la structure, mettre le CP avant la ville

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1260]
**Situation Actuelle**

Une structure nous a remonté que le CP apparaissait après la ville de la structure, ce qui n'es pas conventionnel. Normalement le format devrait être : 

Nom de la structure
Adresse
CP, ville

**Comportement souhaité**

Changer le format de l'adresse en mettant le CP avant la ville. ATTENTION à faire à plusieurs endroits : 

__attestation postale__
- [x] en haut à gauche
- [x] dans le corps du courrier

__courrier de radiation__
- [x] en haut à droite
- [x] dans le corps du courrier

__application__:
- [x] page Structure `/structure-edit`
- [x] page d'inscription de structure (recherche par code postal)

**Recette PO**

Vérifier le nouveau format de l'adresse aux 4 endroits.

**Comment by Toub** [comment]
Je modifie au passage l'ordre à 2 endroits sur l'application:

![image](https://user-images.githubusercontent.com/367762/112288876-13c73880-8c8e-11eb-9eab-96e7b842c2c4.png)

Les modèles à mettre à jour sont ici: 
- https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/custom-docs/attestation_postale.template.docx?raw=true
- https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/custom-docs/courrier_radiation.template.docx?raw=true

**Comment by Toub** [comment]
L'autre page est la page d'inscription:

![image](https://user-images.githubusercontent.com/367762/112289713-d44d1c00-8c8e-11eb-8591-a582ac95a158.png)

**Comment by ledugong** [comment]
@Toub top merci

@pYassine tu t'occupes de changer les modèles du coup ? 
Tu pourras vérifier le point de Chiraz dans la Channel support sur le courrier de radiation : la date qui s'affiche en début de courrier semble être celle du jour et non celle de début de domiciliation actuelle.

**Comment by ledugong** [comment]
@pYassine 
Tu peux aussi faire le changement dans le mail d'inscription d'une structure ?
![Capture d’écran 2021-03-30 à 16 16 49](https://user-images.githubusercontent.com/59437305/113003881-6cf20900-9173-11eb-8b04-49c5e9122f11.png)

La date dans le courrier de radiation (en haut et en bas du courrier) n'est pas la bonne.
Dans le corps du texte, on dit que la radiation est à compter de ce jour et donc la date affichée doit être celle du jour de la radiation. Ci-dessous une personne radiée le 30/06/2008 mais c'est la date d'aujourd'hui qui s'affiche.
[courrier_radiation (3).docx](https://github.com/SocialGouv/domifa/files/6229690/courrier_radiation.3.docx)

**Comment by pYassine** [comment]
@ledugong le 30/06/2008 correspond à la date du début de la domiciliation, pas la date du jour.

**Comment by ledugong** [comment]
@pYassine ya une parenthèse en trop
![Capture d’écran 2021-04-01 à 18 22 42](https://user-images.githubusercontent.com/59437305/113324319-4240b580-9317-11eb-80f7-cd102fe371c9.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
