### ISSUE TITLE
feat(MAQUETTE_DESIGN): nouvelles sections de la fiche domicilié

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1261]
**Situation Actuelle**

C'est parti pour la mise en place des nouvelles maquettes design !
Une des étapes serait de mettre en place les nouvelles sections de la fiche domicilié en gardant les éléments actuels pour le moment. 

**Comportement souhaité**

Les nouvelles sections sont : 
- Vue d'ensemble
Les bandeaux d'information (domiciliation arrive à échéance, renouvellement en cours, procuration, transfert).
Section dossier avec statut, date d'échéance de la domiciliation et date de dernier passage.
Section courriers en attente (en gardant l'ancienne structure des courriers pour le moment).
La section notes internes sera mise à jour dans un autre ticket.
Section historique des interactions (en gardant l'ancienne structure des interactions pour le moment).

- Courrier
Historique des courriers, appels, passages. On ajoutera les notes liées aux courriers dans un second temps.  

- Dossier
Etat civil, ayant-droit, entretien, procuration, transfert, pièce jointes, documents disponibles (mettre l'attestation d'élection de domicile + l'attestation postale)

- Historique
Historique de la domiciliation, notes internes

**Recette PO**

Vérifier les sections.

**Comment by pYassine** [comment]
@ledugong  https://feat-profil-page-dev2-domifa.dev2.fabrique.social.gouv.fr/profil/general/2

**Comment by ledugong** [comment]
@pYassine https://feat-profil-page-dev2-domifa.dev2.fabrique.social.gouv.fr/profil/general/2 mène à une 404

**Comment by ledugong** [comment]
Lien https://feat-profil-page-dev2-domifa.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

- [ ] la section Notes n'a pas de bouton "voir tout l'historique" qui mène à la section "Dossier" dans laquelle on pourra lire toutes les notes internes liées au dossier
<img width="643" alt="Capture d’écran 2021-06-21 à 10 51 23" src="https://user-images.githubusercontent.com/59437305/122734738-a0c66180-d27e-11eb-96f2-208c540aafcf.png">

- [ ] si je laisse un commentaire lors de la réception de courrier, je ne vois pas le commentaire sur la pop-up de distribution de courrier (mais j'imagine que c'est lié au fait que les tickets soient séparés)
<img width="674" alt="Capture d’écran 2021-06-21 à 10 53 53" src="https://user-images.githubusercontent.com/59437305/122735072-f995fa00-d27e-11eb-8b88-2ef0c6853761.png">

- [ ] si je clique sur "modifier les infos" de l'état civil, les infos disparaissent et je ne peux pas enregistrer de modifications
<img width="1256" alt="Capture d’écran 2021-06-21 à 10 54 39" src="https://user-images.githubusercontent.com/59437305/122735185-16323200-d27f-11eb-850e-ea12b5a82f61.png">

- [ ] je ne peux pas ajouter d'AD, est-ce qu'ils sont inclus dans l'état civil ?
<img width="1253" alt="Capture d’écran 2021-06-21 à 10 55 18" src="https://user-images.githubusercontent.com/59437305/122735274-2c3ff280-d27f-11eb-8933-e300599bf809.png">

- [ ] si je modifie une donnée de l'entretien, une fois enregistré il n'y a plus aucun bouton permettant de modifier l'état civil ou l'entretien
<img width="1260" alt="Capture d’écran 2021-06-21 à 10 56 10" src="https://user-images.githubusercontent.com/59437305/122735400-4aa5ee00-d27f-11eb-863f-32eaf0430b24.png">

- [ ] tous les boutons de modification sont noirs sauf ceux du transfert et procuration. Peux-tu passer les boutons en noir et renommer "modifier le transfert" et "modifier la procuration", pour être homogène avec tous les autres boutons ?
<img width="310" alt="Capture d’écran 2021-06-21 à 10 58 12" src="https://user-images.githubusercontent.com/59437305/122735708-93f63d80-d27f-11eb-81ba-afcbc278e15c.png">

- [ ] le domicilié n'a aucun transfert activé, du coup le bouton de suppression du transfert est grisé mais je peux quand même cliquer dessus et ça ajoute une interaction dans l'historique du transfert
<img width="1258" alt="Capture d’écran 2021-06-21 à 10 59 25" src="https://user-images.githubusercontent.com/59437305/122735910-c011be80-d27f-11eb-957a-2183abc3667b.png">

- [ ] pareil pour la procuration

- [ ] lorsque je supprime une interaction, mettre de l'espace entre les boutons OUI et NON
<img width="1258" alt="Capture d’écran 2021-06-21 à 11 02 30" src="https://user-images.githubusercontent.com/59437305/122736302-2dbdea80-d280-11eb-8293-2807715591c4.png">

- [ ] si le domicilié est en cours de renouvellement, corriger la phrase pour "Demande de renouvellement actuellement en cours"
<img width="1245" alt="Capture d’écran 2021-06-21 à 11 03 38" src="https://user-images.githubusercontent.com/59437305/122736453-5645e480-d280-11eb-9b50-59f2899f4815.png">

- [ ] si je lance un renouvellement puis que je supprime la demande en cours, le domicilié ne retourne pas en actif mais reste en à compléter. Mais je pense que c'est lié au bug qui a été corrigé entre temps, à valider.

**Comment by ledugong** [comment]
Lien https://domifa-feat-profil-page.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

- [ ] Si je déclare un courrier puis je supprime l'interaction, elle reste visible dans la vue d'ensemble dans la partie interactions.
Si je supprime l'interaction, garder le suivi seulement dans l'onglet "courriers", pas la peine d'afficher le suivi des suppressions dans la vue d'ensemble (ça prendra trop de place et pas le genre d'infos qu'on a besoin de savoir dès la vue d'ensemble).

**Comment by ledugong** [comment]
@pYassine 

- [ ] Si je supprime une interaction puis je la restaure, elle réapparait en double à la fois dans la vue d'ensemble et dans la section Courriers

**Comment by ledugong** [comment]
https://domifa-feat-profil-page.dev.fabrique.social.gouv.fr/profil/general/7

**Comment by ledugong** [comment]
@pYassine 

Si je prends une fiche domicilié avec une échéance à X par exemple, on voit bien son historique avec une échéance à X.
Par contre, si je fais un renouvellement, l'échéance change bien sur la vue d'ensemble mais dans l'historique de la fiche domicilié, le renouvellement remplace l'ancienne domiciliation.
Le renouvellement écrase les anciennes lignes dans l'historique du domicilié (notamment sa première domiciliation par exemple).
https://user-images.githubusercontent.com/59437305/131508297-9333751e-21db-4dae-8aab-f37eb91e8505.mov

**Comment by ledugong** [comment]
@pYassine correction de front
<img width="563" alt="Capture d’écran 2021-09-06 à 09 03 29" src="https://user-images.githubusercontent.com/59437305/132174413-d204f9c9-e032-4204-9da2-40c50a8c8ce0.png">

**Comment by ledugong** [comment]
@pYassine 

Rôle facteur : 
- [ ] ne peut pas modifier la procuration ni le transfert
- [ ] pas d'accès à l'onglet Documents (aux pj du dossier + cerfa + attestation postale)
- [ ] masquer l'entretien social
- [ ] accès à la section "préférences de contact" en lecture seule si les notifs SMS sont activées au sein de la structure

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
