### ISSUE TITLE
feat(MAQUETTE_DESIGN): nouveau système de courriers - Part 1

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1262]
**Situation Actuelle**

Ce nouveau système de courriers est divisé en plusieurs tickets car lié à la fois à la liste des domiciliés et à la fiche domicilié. Cette première partie consiste à ajouter la notion de commentaires sur la pop-up de courrier mais ne concerne pas l'ajout de la nouvelle typologie des recommandés.

**Comportement souhaité**

Action : sur la fiche domicilié

Si je clique sur le bouton "nouveau courrier" en haut de la fiche domicilié, faire apparaitre la pop-up de réception de courrier avec les options courrier, colis, avis de passage ainsi que l'ajout d'une note associée.
<img width="281" alt="Capture d’écran 2021-03-22 à 11 29 09" src="https://user-images.githubusercontent.com/59437305/111976358-d33ab400-8b01-11eb-86e3-bc02a7fc94a0.png">
<img width="284" alt="Capture d’écran 2021-03-22 à 11 30 15" src="https://user-images.githubusercontent.com/59437305/111976496-fa918100-8b01-11eb-9cb6-53141b09c485.png">

**Recette PO**

**Comment by ledugong** [comment]
@pYassine 

- [ ] Si je mets un commentaire sur un courrier, il faut pouvoir le voir en cliquant sur "distribuer" depuis la liste des domiciliés. Juste afficher le commentaire en lecture seule.
<img width="573" alt="Capture d’écran 2021-06-01 à 16 08 54" src="https://user-images.githubusercontent.com/59437305/120337506-abcb4900-c2f3-11eb-8439-0f7c210bfeee.png">

**Comment by pYassine** [comment]
https://feat-display-cont-jz4ipq-domifa.dev2.fabrique.social.gouv.fr/manage

**Comment by ledugong** [comment]
@pYassine 

- [ ] Si je réceptionne 1 courrier, 1 colis et 1 adp avec le même commentaire, il s'affiche bien lorsque je veux distribuer. Par contre, si je ne distribue que le courrier par exemple, et qu'il me reste 1 colis et 1 adp, en répliquant sur "distribuer", je vois encore le commentaire du courrier déjà distribué.
Lorsqu'un courrier/colis/adp est distribué mais qu'il reste du courrier, retirer le commentaire associé de la pop-up de distribution.

<img width="563" alt="Capture d’écran 2021-06-18 à 10 26 38" src="https://user-images.githubusercontent.com/59437305/122531655-010b9800-d020-11eb-9436-07aa2d657eb3.png">

<img width="557" alt="Capture d’écran 2021-06-18 à 10 26 50" src="https://user-images.githubusercontent.com/59437305/122531682-0832a600-d020-11eb-9add-a04d5f7bc359.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
