### ISSUE TITLE
feat(MAQUETTE_DESIGN): ajout système de notes internes

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1264]
**Situation Actuelle**

Les notes internes se trouveront dans la section "Historique".

**Comportement souhaité**

- [x] Garder la possibilité de mettre des notes internes pour les radiés

- [x] En cliquant sur nouvelle note, une pop-up s'ouvre comme celle du courrier mais avec seulement un champ texte pour ajouter une note. Puis celle-ci s'ajoute dans la partie "Notes internes". 

- [x] Limiter les notes à 1 000 caractères (comme l'entretien)

- [x] Ajouter le texte de sensibilisation RGPD (vu sur la page entretien) en haut de la pop-up
![Capture d’écran 2021-06-25 à 15 04 54](https://user-images.githubusercontent.com/59437305/123428984-b4e3c900-d5c6-11eb-8dbf-265b5fcd6672.png)

- [x] Les notes internes qui s'affichent sur la vue d'ensemble de la fiche domicilié sont seulement les notes internes non archivées.

- [x] Une fois archivées, les notes internes sont listées dans la section "Historique". Pour l'affichage des notes archivées, reprendre le visuel de l'historique des interactions, en mettant comme votre "Notes archivées" et lister par date, en mettant la plus récente en premier.

<img width="358" alt="Capture d’écran 2021-03-22 à 18 49 13" src="https://user-images.githubusercontent.com/59437305/112034912-4d3d5e00-8b3f-11eb-96eb-03cd589175ae.png">

**Recette PO**

**Comment by Toub** [comment]
![image](https://user-images.githubusercontent.com/367762/132347096-490fbf34-5610-4790-8955-ae06727eda3d.png)
https://www.figma.com/file/UcGnQt8yBzSHuuon1rRiN4/Domifa?node-id=72%3A312

**Comment by Toub** [comment]
A tester ici:: https://domifa-feat-notes-internes-1264.dev.fabrique.social.gouv.fr

**Comment by ledugong** [comment]
Recette PO en cours @Toub 

- [ ] ajout d'une note puis annulée : le message de confirmation apparait quand même
https://user-images.githubusercontent.com/59437305/133622224-fae0f3c1-f72e-4a06-84d0-48c1e19bfc9b.mov
- [ ] ajout d'une note puis validée
- [ ]

**Comment by ledugong** [comment]
@Toub pour info, notes internes validées côté Thomas H 👌

**Comment by Toub** [comment]
A re-tester en preprod

**Comment by ledugong** [comment]
@Toub 
J'ai oublié de te demander de mettre la liste des accès à jour pour ajouter les notes internes, tu peux le faire ? 
Voici la liste des accès à jour : https://nextcloud.fabrique.social.gouv.fr/apps/onlyoffice/8218?filePath=%2FDomiFa%2FJuridique%20-%20S%C3%A9curit%C3%A9%20-%20RGPD%2FDoc%20Fonctionnelle%2FDomiFa_R%C3%B4les_Acc%C3%A8s.docx

**Comment by pYassine** [comment]
Corrigé!

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
