### ISSUE TITLE
feat(NOTIFS_SMS): permettre la modification des notifs sms pour les radiés / cas du pli non distribuable

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1317]
**Situation Actuelle**

Lorsqu'un domicilié actif se fait radier, garder la section "Notifications" telle quelle (active et modifiable par tous sauf facteur) car le domicilié peut encore recevoir du courrier.
Pareil quand on déclare un pli non distribuable, ne pas toucher à la section "Notifications".

- [x] Si le domicilié est radié, garder la sections des notifications disponible et modifiable (sauf pour le profil facteur), se référer aux rôles ici https://domifa.fabrique.social.gouv.fr/admin
- [x] Pareil si on clique sur le bouton "pli non distribuable" sur la fiche du radié, ne pas modifier la section du courrier
Car parfois, même radiés, les domiciliés reçoivent encore du courrier donc ils doivent encore pouvoir bénéficier des notifs par SMS

**Recette PO**

Vérifier les notifs SMS sur des fiches de radiés + tester le pli non distribuable.

**Comment by pibouu** [comment]
https://domifa-1317-modif-notif-radies.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
