### ISSUE TITLE
bug(STATS): stats du nombre de renouvellements négatives

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1322]
**Description du problème**

Une structure a des statistiques négatives : 
![image009-2](https://user-images.githubusercontent.com/59437305/115401724-ff258400-a1ea-11eb-84f7-4545eee2384d.jpg)
En PP, les stats sont aussi négatives.

**Comportement souhaité**

- [x] refaire une analyse complète du traitement des stats (métier et technique)
- [x] introduire un nouveau type de stats dynamique (non stocké en base): calculé sur une période (actuellement, soit à 1 date, soit le différentiel entre 2 dates)
- [x] ajouter un historique usager complet (basé sur l'état et pas seulement sur les décisions)
- [x] migrer la partie 2 des stats en dynamique périodique en se basant sur le nouvel historique
- [x] supprimer stats stockées sur la structure, et impact stats domifa
- [x] vérifier stats structure 45 et 74
- [x] mise à jour page historique usager (retirer le dernier état qui va apparaitre en doublon maintenant)
- [x] export excel: formater le document (largeurs de colonne, gras...)
- [x] export excel: ajouter une colonne référence enquête dgcs 2019
- [ ] ajouter quelque part une description précise du calcul des chiffres des stats

**Recette PO**

- [x] tests approfondis des stats
- [x] export stats
- [ ] annulation de renouvellement en cours
- [x] création d'usager
- [x] suppression d'usager

Le format de stockage de la date de naissance des ayants droits ayant changé, vérifier la non-régression lors de:

- [x] la création d'ayant droits via l'interface graphique
- [x] la création via l'import
- [x] l'affichage sur la fiche domicilié
- [x] l'export des usagers

**Comment by Toub** [comment]
Y'a bien un saut dans les stats sur la base de prod:

```sql
SELECT x."date", questions->>'Q_10_B' as "Dont renouvellement"
FROM public.structure_stats x
WHERE "structureId" = 230 and x.date >= '2021-03-01' and x.date < '2021-04-01'
order by x."date";
```
![Image collée à 2021-4-20 15-00](https://user-images.githubusercontent.com/59437305/115401886-2bd99b80-a1eb-11eb-9bbc-28de0a93b2b6.png)

En regardant la requête, on prend les domiciliés avec typeDom="RENOUVELLEMENT" qui sont dans le status :
- VALIDE
- INSTRUCTION ou ATTENTE_DECISION (et était valide avant)

![Image collée à 2021-4-20 15-06](https://user-images.githubusercontent.com/59437305/115401988-49a70080-a1eb-11eb-827e-da008bcfe17e.png)

**Comment by Toub** [comment]
La requête complète: 

```sql
SELECT COUNT("uuid") AS "count" FROM "usager" "u" WHERE ("structureId" = 230) AND ("typeDom" = 'RENOUVELLEMENT') AND (decision->>'statut' = 'VALIDE' and (decision->>'dateDebut')::timestamptz <= '2021-03-22'
      OR (
        decision->>'statut' = 'INSTRUCTION'
        and (historique->>0)::jsonb->>'statut' = 'VALIDE' and ((historique->>0)::jsonb->>'dateDebut')::timestamptz <= '2021-03-22'
      )
      OR (
        decision->>'statut' = 'ATTENTE_DECISION'
        and (historique->>1)::jsonb->>'statut' = 'VALIDE' and ((historique->>1)::jsonb->>'dateDebut')::timestamptz <= '2021-03-22'
      )
    );
```

**Comment by Toub** [comment]
Le problème majeur vient du fait que la stat prend en compte les radiés aussi.

La solution à terme serait de ne plus faire un traitement différentiel entre 2 dates, mais de chercher directement et dynamiquement à l'intérieur de cette tranche de dates dans l'historique, après nettoyage de celui-ci.

En attendant, la solution serait de stocker le nombre total d'usagers ayant été renouvellés dans le passé, pour chaque date (même si ils ont été radiés depuis). Ainsi, la différence nous donnera le nombre de nouveaux (limitation: ne comptera pas un renouvellé qui l'est pour la seconde fois)

**Comment by ledugong** [comment]
Recette des stats : 

- [ ] création d'une nouvelle structure, les stats sont bien à 0
- [ ] export des stats
- [ ] hard reset

Partie 1
- [ ] création de domiciliés, vérifier l'incrémentation du nombre de domiciliés
- [ ] suppression de domiciliés, vérifier la décrémentation du nombre de domiciliés
- [ ] ajout d'AD, vérifier l'incrémentation du nombre de domiciliés
- [ ] suppression d'AD, vérifier la décrémentation du nombre de domiciliés
- [ ] suppression d'un domicilié avec plusieurs AD, vérifier la décrémentation du nombre de domiciliés et du nombre d'AD
- [ ] ajout de domiciliés hommes
- [ ] ajout de domiciliés femmes
- [ ] suppression de domiciliés hommes
- [ ] suppression de domiciliés femmes
- [ ] ajout de domiciliés majeurs
- [ ] ajout de domiciliés mineurs
- [ ] suppression de domiciliés majeurs
- [ ] suppression de domiciliés mineurs
- [ ] ajout d'AD majeurs
- [ ] ajout d'AD mineurs
- [ ] suppression d'AD majeurs
- [ ] suppression d'AD mineurs
- [ ] ajout de domiciliés par tranche d'âge
- [ ] suppression de domiciliés par tranche d'âge
- [ ] ajout de domiciliés par type de ménage
- [ ] suppression de domiciliés par type de ménage
- [ ] ajout / suppression pour situation résidentielle
- [ ] ajout / suppression pour cause de l'instabilité du logement
- [ ] ajout / suppression pour motif principal de la demande

Partie 2
- [ ] ajout d'une première demande
- [ ] suppression d'une première demande
- [ ] ajout d'un renouvellement
- [ ] suppression d'un renouvellement
- [ ] ajout d'une première demande avec AD
- [ ] suppression d'une première demande avec AD
- [ ] ajout d'un renouvellement avec AD
- [ ] suppression d'un renouvellement avec AD
- [ ] radiation d'un domicilié
- [ ] radiation due domicilié avec AD : compteur des AD doit changer ?
- [ ] ajout / suppression pour motif de radiation
- [ ] refus d'une première demande
- [ ] refus d'un renouvellement
- [ ] test des motifs de refus
- [ ] test des orientations

Partie 3
- [ ] ajout d'un appel
- [ ] ajout d'un passage
- [ ] réception d'un courrier
- [ ] distribution d'un courrier
- [ ] réception d'un colis
- [ ] distribution d'un colis
- [ ] réception d'un avis de passage
- [ ] distribution d'un avis de passage
- [ ] déclaration d'un pli non distribuable

**Comment by ledugong** [comment]
@Toub

- [ ] j'ai ajouté un ayant-droit de chaque type sur cette fiche mais seulement 2 AD sont comptabilisés dans les stats.
C'est l'AD "enfant" qui n'est pas comptabilisé
<img width="792" alt="Capture d’écran 2021-06-07 à 16 27 08" src="https://user-images.githubusercontent.com/59437305/121034303-35c05980-c7ad-11eb-8fa5-8a5873985ba5.png">
<img width="850" alt="Capture d’écran 2021-06-07 à 16 27 31" src="https://user-images.githubusercontent.com/59437305/121034375-4375df00-c7ad-11eb-944d-1500a8312b81.png">

**Comment by ledugong** [comment]
@pYassine

- [ ] si je mets un domicilié né le 11/06/2003 (et donc mineur), il est comptabilisé comme majeur dans les stats.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
