### ISSUE TITLE
bug(requetes): rafraichissement en boucle si déconnecté mais page recherche ouverte

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1333]
**Description du problème**

Rafraichissement horaire, avec retry chaque 5s en cas d'erreur. Si on est déconnecté, ça peut tourner en boucle.

**Comportement attendu**

A vérifier et corriger.

**Review PO**

Test basique de non-régression:

- [x] vérifier que l'écran de recherche s'affiche
- [x] ajouter un domicilié et vérifier qu'il apparait dans la recherche

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
