### ISSUE TITLE
bug(interactions): quand on supprime une interaction la date de dernier passage ne se met pas à jour

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1345]
**Description du problème**

En supprimant une interaction de type "distribution de courrier" ou "appel" ou "visite", la date de dernier passage ne se met pas à jour

**Comportement attendu**

Remettre l'ancienne date de dernier passage

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
