### ISSUE TITLE
feat(IMPORT): mise à jour du fichier explicatif + lien du doc en cas d'erreurs

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1354]
**Situation Actuelle**

Suite à la refacto de l'import, le fichier a été mis à jour.

**Comportement souhaité**

- [x] Nouveau fichier ci-dessous, le remplacer dans le lien sur la page https://domifa.fabrique.social.gouv.fr/import
[Tutoriel_importer_vos_domiciliés.pdf](https://github.com/SocialGouv/domifa/files/6415663/Tutoriel_importer_vos_domicilies.pdf)

- [x] En cas d'erreur, ajouter une phrase avec un lien vers le document : 
" N'hésitez pas à consulter ce document explicatif en cas de souci."

![Capture d’écran 2021-05-03 à 16 50 46](https://user-images.githubusercontent.com/59437305/116892056-b67cba80-ac2f-11eb-87b6-e4f4be3572e4.png)

**Recette PO**

- [x] vérifier le nouveau document sur la page d'import
- [x] vérifier le lien du document en cas d'erreur

**Comment by Toub** [comment]
### Règles de validation

@ledugong voici quelques remarques sur l'implémentation dans le code, là où ça diffère avec ce qui est décrit dans le tutoriel pdf

Règles générales
- toutes les dates  >= 01/01/1900
 
Date de naissance:​ 
- date maxi: aujourd'hui

Numéro de téléphone + email:
- Doublons interdits? (je ne crois pas que c'est vérifié dans le code, et je ne suis pas sûr de la pertinence) => à discutter avec @pYassine 

Date début dom actuelle
- si "statut dom" VALIDE: champ obligatoire
- date maxi: aujourd'hui

Date fin de domiciliation OU Date de radiation si radié OU Date de refus si refusé
- si "statut dom" VALIDE: champ obligatoire
- si "statut dom" VALIDE: date mini = date début de dom
- si "statut dom" RADIE: valuer par défaut = aujourd'hui
- date maxi: aujourd'hui

Date première dom
- date maxi: aujourd'hui

Date dernier passage
- date maxi: aujourd'hui

Date de naissance AYANT DROIT:​ 
- date maxi: aujourd'hui

**Comment by ledugong** [comment]
Numéro de téléphone + email:
> 
> * Doublons interdits? (je ne crois pas que c'est vérifié dans le code, et je ne suis pas sûr de la pertinence) => à discuter avec @pYassine

<img width="356" alt="Capture d’écran 2021-05-04 à 11 05 17" src="https://user-images.githubusercontent.com/59437305/116982113-b1b81500-acc8-11eb-9f24-970a3b765107.png">

Je confirme que les doublons téléphone et email sont autorisés. Il n'est pas nécessaire de les interdire, ça créera + de support qu'autre chose....

**Comment by ledugong** [comment]
@Toub j'ai l'impression que ya un nouveau souci

Ce fichier ne passe pas (bandeau message d'erreur) alors qu'aucune erreur n'est détectée
[modele_import_domifa.xlsx](https://github.com/SocialGouv/domifa/files/6420690/modele_import_domifa.xlsx)

C'est peut-être lié à la colonne date de fin de dom / date de refus / date de radiation. 
Ce champ doit être obligatoire dans tous les cas. Alors que dans le fichier test, l'erreur n'est pas catchée.

**Comment by ledugong** [comment]
@Toub Ci-dessous le fichier à jour : 
[Tutoriel_importer_vos_domiciliés.pdf](https://github.com/SocialGouv/domifa/files/6420741/Tutoriel_importer_vos_domicilies.pdf)

Aussi disponible sur le lien https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Import%20_%20Tutos/Import&fileid=8260

**Comment by ledugong** [comment]
@pYassine 
C'est pas le bon document. Pour rappel, il est juste au-dessus (document + lien nextcloud).

**Comment by ledugong** [comment]
@pYassine je ne peux pas recetter ce ticket car le fichier avec erreurs ne passe pas, voir ce ticket : https://github.com/SocialGouv/domifa/issues/1127

**Comment by ledugong** [comment]
@pYassine
- [ ] faute d'orthographe "votre fichier ne peut pas être importé !"
- [ ] il n'y a pas de lien vers le document explicatif
<img width="485" alt="Capture d’écran 2021-05-17 à 13 17 44" src="https://user-images.githubusercontent.com/59437305/118480354-68c57f00-b712-11eb-9230-c6e501336642.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
