### ISSUE TITLE
feat(healthcheck): séparer healthcheck back & front 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1355]
**Situation Actuelle**

Le healthcheck de l'appli se fait via le back, qui fait appel au front

L'équipe SRE souhaiterait un retour du back dès qu'il est prêt, pour initialiser les données

On ne peut pas supprimer le ping back->front (impact pour la popup de maintenance, par contre, car si le ping retourne ok, mais que le nouveau front n'est pas prêt, on va rafraichir trop tôt)

Donc il faut dupliquer le healthcheck, et en avoir un global pour l'appli, et l'autre juste pour le backend.

**Comportement souhaité**

- [x] dupliquer le healthcheck et retirer le ping du front de l'original
- [x] faire pointer le ping du frontend sur le nouveau healthcheck

**Comment by ledugong** [comment]
Recette PO OK.
2 urls de check : OK
pop-up maintenance s'affiche bien en coupant internet : OK

**Comment by ledugong** [comment]
Recette Prod OK
2 urls de check : OK
pop-up maintenance s'affiche bien en coupant internet : OK
