### ISSUE TITLE
feat(PROCURATION): permettre l'ajout d'une deuxième procuration sur la fiche domicilié

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1374]
**Situation Actuelle**

L'ajout de seulement une procuration est possible pour le moment, mais les structures demandent la possibilité d'en ajouter une seconde. 

**Comportement souhaité**

![Capture d’écran 2021-05-12 à 16 56 09](https://user-images.githubusercontent.com/59437305/117997063-f4ba5e00-b342-11eb-93bb-af906854cfaa.png)
A gauche du bouton "modifier la procuration", ajouter un bouton "Ajouter une procuration", ce qui affichera les champs à remplir en-dessous de la première procuration déjà entrée.
En cliquant sur "modifier la procuration", tous les champs des deux procurations apparaissent comme éditables (ne pas demander quelle procuration modifier, trop compliqué).
En cas de procurations multiples, supprimer le bouton "Supprimer la procuration" et ajouter des icônes poubelle à côté de chaque procuration (comme pour les AD).

**Recette PO**

Tester 0, 1 et 2 procurations

**Liste des domiciliés** 

- [x] Je dois voir une pastille "procurations". Au survol je dois voir toutes les procurations

- [x] Distribution du courrier : si j'indique que c'est un mandataire qui le récupère, je dois voir le nom et prénom du mandataire dans l'historique des courriers

- [x] Si des mandataires sont présents, je dois pouvoir indiquer qui a réceptionné le courrier

- [x] Dans la création de documents personnalisés, je dois voir le premier mandataire s'afficher si j'utilise le mot "PROCURATION_NOM"

**Fiche domicilié** 
- [x] Affichage des panneaux procurations dans la fiche domicilié

**Interface domicilié**
- [x] Affichage des panneaux procurations dans l'interface domicilié

**Comment by pibouu** [comment]
inverser les boutons supprimer et modifier (edit) pour pour transfert

**Comment by ledugong** [comment]
Tag de la liste domicilié : afficher les 2 procurations avec le même affichage que les AD.
<img width="710" alt="Capture d’écran 2022-02-07 à 09 54 41" src="https://user-images.githubusercontent.com/59437305/152755986-92cd487d-4837-4fdb-8fc3-98ee041cb14c.png">

Lors de la remise de courrier, bien afficher les 2 mandataires.
<img width="678" alt="Capture d’écran 2022-02-07 à 09 54 14" src="https://user-images.githubusercontent.com/59437305/152755928-fa42e8bd-038a-4363-8ca7-d93d0004afea.png">

Lorsqu'un mandataire récupère un courrier, la date de dernier passage ne change pas, vérifier que ça bouge pas.
La date de dernier passage ne change que si le domicilié vient récupérer son courrier. 

En cas de 2eme mandataire, afficher une seconde ligne en-dessous de la première.
<img width="809" alt="Capture d’écran 2022-02-07 à 09 55 55" src="https://user-images.githubusercontent.com/59437305/152756160-3f12ef5f-2510-49e5-b3f4-4dfa1d8420da.png">

**Comment by celinelr** [comment]
- Liste = Procuration est au pluriel meme s'il y en a qu'une -> 
    

- [ ] Je propose que Procuration soit au singulier si nous avons une procuration
- [ ] Je propose que Procurations soit au pluriel si nous avons deux procurations

- Fiche domicilié: La domicilié à deja une procuration,  si je clique sur modifier une procuration > Ajouter une procuration > les champs du second mandataire sont par défaut en erreur 

- [ ] Je propose que toutes les champs soient en erreur que si nous cliquons sur enregistrer la procuration sans avoir renseigné les champs 
<img width="1357" alt="Capture d’écran 2022-04-04 à 12 23 23" src="https://user-images.githubusercontent.com/86293911/161527260-283623c7-33eb-4b13-b509-c68edd9d2750.png">


Questions : 

Je remarque que l'on peut renseigner des chiffres dans les champs nom et prenom des mandataires pour la procuration. Il n'y a pas de regles type majuscule que en debut de mot etc ?

**Comment by celinelr** [comment]
Je n'arrive pas à ouvrir mon document personnalisé pour vérifier le point suivant : 

- [ ]  Dans la création de documents personnalisés, je dois voir le premier mandataire s'afficher si j'utilise le mot "PROCURATION_NOM"

En effet, je rencontre deux difficultés : 
- Le format doc n'est pas accepté 
- le format docx n'est pas ouvrable une fois téléchargé "Attestation procuration.vnd.openxmlformats-officedocument.wordprocessingml (2).document"

**Comment by celinelr** [comment]
Je ne vois pas s'afficher les panneaux procurations dans l'interface domicilié
- [ ] Affichage des panneaux procurations dans l'interface domicilié
![Capture d’écran 2022-04-04 à 17 16 53](https://user-images.githubusercontent.com/86293911/161575948-7c569c17-ec05-4f3a-8039-3eed930d7f69.png)

**Comment by celinelr** [comment]
Suite à la recette de ce ticket, j'ouvre ce ticket https://github.com/SocialGouv/domifa/issues/2190

**Comment by celinelr** [comment]
Je close ce ticket meme s'il les deux tickets liés ne sont pas encore fix 

- Suite à la recette de ce ticket, j'ouvre ce ticket https://github.com/SocialGouv/domifa/issues/2190
- Le format doc n'est pas accepté > https://github.com/SocialGouv/domifa/issues/2186
