### ISSUE TITLE
bug(TRI): tri liste des domiciliés ne fonctionne plus

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1375]
**Description du problème**

Ticket crée au cours de la mise en place de la maquette de la liste des domiciliés. Souci à voir en préprod.

Tri par ID : 
- [x] le tri par ID ne fonctionne plus, si j'entre un ID personnalisé le tri reste par ID DomiFa
![Capture d’écran 2021-04-29 à 15 11 06](https://user-images.githubusercontent.com/59437305/116559950-3853a780-a901-11eb-9f27-d5ebe4bd9a3b.png)

Tri par Nom : 
- [x] le tri par nom ne semble pas fonctionner, ci-dessous un test du tri par nom décroissant sur l'onglet Tous (testé aussi avec Actifs et Radiés).
![Capture d’écran 2021-05-14 à 14 43 40](https://user-images.githubusercontent.com/59437305/118272359-c82d5000-b4c2-11eb-8aca-a1424ec81f9c.png)

**Comment by Toub** [comment]
La partie tri par "nom" est corrigée, il s'agissait d'un problème de `casse`, "zoro" étant trié devant "ALBAN" par défaut.

Pour le tri par ID, c'est un problème de fond, car on veut trier de façon magique les chaînes de caractères et les entiers.

La correction fait donc ceci:
- séparer les usagers dont les ID personnalisés sont des entiers des autres
- tri des entiers entre eux
- tri des chaînes (non-entiers) entre eux
- affichage des entiers, puis des chaînes (si tri ascendant, sinon l'inverse)

Ainsi, les IDs sont triés comme ceci:
- 01
- 8
- 50
- AB5
- Ab6

L'inconvénient, c'est ce genre de cas:
- 1
- 2
- 3
- 4
- 10
- 1a
- 1b
- 2a
- 2b
- 10c

On voudrait ici avoir `1a` et `1b` avant le 2, j'imagine, mais y'a pas de solution magique, le tri parfait "attendu" par notre cerveau est difficile à implémenter.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
