### ISSUE TITLE
feat(HOMEPAGE): mise en place maquette desktop + mobile

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1379]
**Situation Actuelle**

C'est parti pour la mise en place de la nouvelle HomePage. Lien de la maquette : https://www.figma.com/file/NvTVd9GVDVPoaap4dOxnlf/Page-Accueil-DomiFa?node-id=401%3A34909
Bien prendre la version 3.0.

**Comportement souhaité**
Pré-requis
- [x] enlever la pop-up actuellement en bas à droite de l'écran et seulement l'afficher une fois connecté (le point d'interrogation dans la bulle bleue).
<img width="618" alt="Capture d’écran 2021-05-17 à 13 56 26" src="https://user-images.githubusercontent.com/59437305/118484723-d922cf00-b717-11eb-88a8-0ddeb4abe845.png">

Redirection des différents CTA : 
Header
- [x] Logo DomiFa en haut de page doit toujours rediriger vers la HP
- [x] "En savoir plus" à rediriger vers la FAQ : https://domifa.fabrique.social.gouv.fr/faq
- [x] "Me connecter" à rediriger vers la page de connexion : https://domifa.fabrique.social.gouv.fr/connexion
Bandeau haut de page
- [x] "Découvrir la plateforme" à rediriger vers la page d'inscription : https://domifa.fabrique.social.gouv.fr/inscription
Bandeau protection des données
- [x] "Lire notre politique de confidentialité" à rediriger vers la PC : https://domifa.fabrique.social.gouv.fr/confidentialite
Bandeau facilitation de l'autonomie
- [x] "Voir notre centre d'aide" à rediriger vers la FAQ : https://domifa.fabrique.social.gouv.fr/faq
- [x] "S'inscrire" à rediriger vers la page d'inscription : https://domifa.fabrique.social.gouv.fr/inscription
Bandeau statistiques
- [x] Concernant le CTA "Voir nos statistiques", le renommer en "Voir nos statistiques (en cours de construction)" et griser le bouton ? Comme ça on tease les structures
Bandeau gestion des domiciliations
- [x] "S'inscrire" à rediriger vers la page d'inscription : https://domifa.fabrique.social.gouv.fr/inscription
- [x] "Contacter l'équipe" à rediriger vers le mail contact.domifa@fabrique.social.gouv.fr
Strate "Nos partenaires" en bas de page
- [x] logo de la Fabrique Numérique à rediriger vers https://www.fabrique.social.gouv.fr
- [x] logo beta.gouv.fr à rediriger vers https://beta.gouv.fr
- [x] logo DIHAL à rediriger vers https://www.gouvernement.fr/delegation-interministerielle-a-l-hebergement-et-a-l-acces-au-logement
- [x] logo DGCS à rediriger vers https://www.gouvernement.fr/le-ministere-des-solidarites-et-de-la-sante
- [x] logo UNCCAS à rediriger vers https://www.unccas.org
Footer
- [x]  "Mentions légales" à rediriger vers https://domifa.fabrique.social.gouv.fr/mentions-legales
- [x] "CGU" à rediriger vers https://domifa.fabrique.social.gouv.fr/cgu
- [x] Remplacer "Recrutement" par "Nouveautés" et rediriger vers https://domifa.fabrique.social.gouv.fr/news
- [x] Remplacer "Statistiques" par "Statistiques (prochainement)" et griser le bouton

**Recette PO**

Vérifier la page et tous les CTA

**Comment by Toub** [comment]
Sur tablette, on aligne à gauche, comme sur la maquette
![image](https://user-images.githubusercontent.com/367762/119646381-61435b80-be1f-11eb-828e-6da7fa31025e.png)

Mais sur grand écran (non représenté sur la maquette), ça ne rend pas terrible, donc je propose un centrage, comme ceci:

![image](https://user-images.githubusercontent.com/367762/119646508-8932bf00-be1f-11eb-9bbd-5ebfd6014000.png)

**Comment by Toub** [comment]
Review sur https://toub-feat-homepag-6zkiq8-domifa.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@Toub

- [ ] tu pourrais mettre + de marges sur les côtés ? Le texte parait très "collé" sur les côtés.

- [ ]partie "libérez du temps pour l'accompagnement social", les textes et les bulles sont pas alignées de manière symétrique, on voit beaucoup de blanc par rapport à la maquette. Ci-dessous un screenshot de la Homepage puis celui de la maquette.

<img width="1273" alt="Capture d’écran 2021-06-01 à 14 31 49" src="https://user-images.githubusercontent.com/59437305/120323747-1c6b6900-c2e6-11eb-9034-e2e4b38e8c74.png">

<img width="605" alt="Capture d’écran 2021-06-01 à 14 34 26" src="https://user-images.githubusercontent.com/59437305/120324060-78ce8880-c2e6-11eb-95ad-cf230e9bba26.png">

**Comment by Toub** [comment]
Corrigé, à tester sur https://toub-feat-homepag-6zkiq8-domifa.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK desktop et mobile
