### ISSUE TITLE
bug(STRUCTURE): date expiration de domiciliation n'apparait pas, domicilié dans la mauvaise section

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1404]
**Description du problème**

Bug transféré par une structure puis vérifier en PP.

- [x] Ci-dessous le message de la structure : 
"Tous nos domiciliés à renouveler avec barre rouge ont aujourd'hui la mention : Domiciliation expirée depuis le , il y a 59 jours.
EX.:                           
M. XX XXX
Numéro domicilié : 43
Domiciliation expirée depuis le , il y a 59 jours
Dernier passage le 08/05/2021
Quelque soit leur date d'échéance. Hier 58, aujourd'hui 59, demain? 60 très certainement. D’où le lien avec notre date de démarrage."

Testé en PP avec l'adresse admin admin-75-165@domifa-fake.fabrique.social.gouv.fr, en retrouvant le domicilié en question via l'ID, on voit bien que la date depuis laquelle la dom est expirée n'apparait pas.
![Capture d’écran 2021-05-25 à 16 25 01](https://user-images.githubusercontent.com/59437305/119514986-c3478680-bd75-11eb-8a88-9aad36c25d8c.png)

De même, le domicilié en question se trouve en instruction en tant que renouvellement alors que le renouvellement n'a pas encore été commencé.
![Capture d’écran 2021-05-25 à 16 25 49](https://user-images.githubusercontent.com/59437305/119515124-dfe3be80-bd75-11eb-884d-d2a4e6ffd53d.png)

De mon côté, j'ai testé la création d'une dom expirée : on voit bien "dom expirée depuis le xx/xx/xxxx". Je tente un renouvellement et il apparait bien dans la bonne section.
Aussi testé un import avec une domiciliation expirée, la phrase s'affiche bien et le renouvellement fonctionne correctement. 

**Recette PO**

- [x] Validation par la structure

**Comment by pYassine** [comment]
![Capture d’écran 2021-05-26 à 10 14 37](https://user-images.githubusercontent.com/11486845/119626551-a3fb3880-be0b-11eb-9663-584ab24ed41d.jpg)
![Capture d’écran 2021-05-26 à 10 18 06](https://user-images.githubusercontent.com/11486845/119626587-ae1d3700-be0b-11eb-92d9-b5a50e478e38.jpg)

**Comment by ledugong** [comment]
En cours de vérification auprès de la structure

**Comment by ledugong** [comment]
Souci réglé chez la structure
