### ISSUE TITLE
feat(usagers): cache de la liste des usagers

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1416]
**Situation Actuelle**

La recherche est lente, suivant la volumétrie, et à lorsque l'on ouvre une fiche, puis revient à la liste, il faut recommencer

**Comportement souhaité**

Mettre les données dans un cache en mémoire.

**Recette PO**

- [x] la liste et la fiche usager s'affiche très rapidement, même avec un gros volume de données (exemple: structure 113)
- [x] pas de régression sur ces 2 écrans

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@Toub 
Testé avec plus de 20k de domiciliés, vitesse de chargement ok et retour sur la liste ok.
Par contre, les courriers enregistrés sur une fiche domicilié ne s'affiche plus sur la liste, bug ou lenteur car beaucoup de domiciliés ?
https://user-images.githubusercontent.com/59437305/121153170-1f1a1100-c846-11eb-90c8-ff9250f84817.mov

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
