### ISSUE TITLE
bug(BANDEAU_ERREUR): message d'erreur lors de la réception d'un courrier

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1419]
**Description du problème**

Retour de la structure ID 11 : 
Lorsque les utilisateurs déclarent l'arrivée de courriers sur la liste des domiciliés, le courrier est bien comptabilisé MAIS un bandeau d'erreur apparait (et non le bandeau vert de confirmation).
Le souci est généralisé à tous les utilisateurs de la structure (donc ce n'est pas une histoire de poste).

Par contre, je n'arrive pas à recréer le souci en PP, peut-être la version en PP n'est pas assez récente ?
Pour faire des tests, le mail de l'admin de la structure : admin-11-700@domifa-fake.fabrique.social.gouv.fr

**Recette PO**

- [x] vérifier avec la structure

**Comment by Toub** [comment]
Problème non reproduis avec un dump anonymisé de la prod et la version de prod actuelle 2.5.7

Le problème intervient-il avec tous les usagers, et sinon avec quel id usager?

**Comment by ledugong** [comment]
@Toub Questions envoyées, en attente d'un retour structure

**Comment by ledugong** [comment]
@pYassine @Toub réponse de la structure : 
"A priori, ce souci apparait chez tous les collègues utilisant DOMIFA ;
Nous utilisons Firefox."

**Comment by ledugong** [comment]
@Toub document d'enregistrement de la session envoyée à la structure, en attente de réponse.

**Comment by Toub** [comment]
Lié à l'envoi des SMS, des usagers ont l'option activée, mais pas le numéro.

Il semble s'agir d'un vieux problème.

Un patch a été appliqué en base de données.

**Comment by ledugong** [comment]
Recette Prod OK
