### ISSUE TITLE
bug(COMPTEUR_COURRIER): souci entre nbre de courriers enregistrés et nbre de courriers affichés en attente

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1420]
**Description du problème**

Souci de la structure ID 45 : 
Une personne domiciliée à 3 lettres présentes dans notre service, 3 courriers sont aussi notés sur le suivi du courriers et des passages.
Cependant le nombre de courriers affichés à remettre est de 5 courriers, il est impossible de rectifier cette erreur.

Testé en PP mais aucun souci détecté (réception de courrier en rapide et en détaillé depuis la liste des domiciliés, depuis la fiche domicilié etc.). Mail admin utilisé pour le test : admin-45-125@domifa-fake.fabrique.social.gouv.fr 

**Recette PO**

- [ ] vérifier avec la structure

**Comment by Toub** [comment]
Les screenshots fournis par la structure montrent que seuls 3 courriers ont été ajoutés depuis la dernière distribution, alors qu'on en voit 5 sur le compteur.

L'explication techniquement la plus probable serait que quelqu'un ai supprimé une distribution antérieure sur l'historique. Peut-être faudrait-il tracer ces actions, et les afficher dans l'historique?

**Comment by Toub** [comment]
Du style:
"Paul DURAND a supprimé l'interaction suivante le 15/04/2021:"
> 1 courrier remis...

**Comment by ledugong** [comment]
@Toub du coup le souci vient du fait que les interactions supprimées sur la fiche domicilié ne sont pas comptabilisées sur la liste des domiciliés ?

**Comment by Toub** [comment]
> @Toub du coup le souci vient du fait que les interactions supprimées sur la fiche domicilié ne sont pas comptabilisées sur la liste des domiciliés ?

Non, ça serait plutôt qu'ils auraient supprimé par erreur une __distribution__ de courrier antérieure, ce qui aurait fait remonter artificiellement le compteur.

Quelque soit la raison, le problème disparaîtra à la prochaine remise de courrier.

**Comment by ledugong** [comment]
> > @Toub du coup le souci vient du fait que les interactions supprimées sur la fiche domicilié ne sont pas comptabilisées sur la liste des domiciliés ?
> 
> Non, ça serait plutôt qu'ils auraient supprimé par erreur une **distribution** de courrier antérieure, ce qui aurait fait remonter artificiellement le compteur.
> 
> Quelque soit la raison, le problème disparaîtra à la prochaine remise de courrier.

Ok j'ai prévenu la structure et créé un ticket pour tracer la suppression des interactions : https://github.com/SocialGouv/domifa/issues/1432 
Je ferme celui là.
