### ISSUE TITLE
bug(usager): suppression d'un renouvellement 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1422]
**Description du problème**

Lors de la suppression d'un fiche demande de renouvellement, rien ne se passe quand on clique sur le bouton de confirmation du popup.

**Comportement attendu**

L'usager repasse à son statut précédent et la popup se ferme.

**Scénario de reproduction du problème**

1. ouvrir une fiche domicilié en cours de renouvellement
2. cliquer sur le bouton de suppression de la demande tout en bas de la page
3. la popup de confirmation s'ouvrir, clique sur le bouton de confirmation
4. la popup reste ouverte, et rien ne se passe visuellement

**Copies d'écran**

![image](https://user-images.githubusercontent.com/367762/120986567-0560c700-c77d-11eb-8ff0-085bb7fba97c.png)

**Recette PO**

- [x] la fenêtre de confirmation se ferme
- [x] l'usager à retrouvé son statut précédent

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
