### ISSUE TITLE
bug(DOMICILIÉ): bug suppression d'un renouvellement ou d'une demande

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1427]
**Description du problème**

Les pop-up apparaissant lors d'une suppression de renouvellement ne semblent pas correctes.

**Scénario de reproduction du problème**

Ci-dessous plusieurs scénarios testés : 

Scénario 1 : OK
- je crée une première demande de domiciliation
- je la valide
- je la supprime
- la suppression se fait correctement

Scénario 2 : NOT OK
- je crée une première demande de domiciliation
- je la valide
- je lance une demande de renouvellement
- je supprime cette demande avant de prendre une décision
- cette pop-up apparait alors que le domicilié ne doit pas retourné en instruction mais en statut valide
<img width="572" alt="Capture d’écran 2021-06-07 à 16 04 42" src="https://user-images.githubusercontent.com/59437305/121030775-1411a300-c7aa-11eb-9830-819119c6530c.png">
- de plus, le bouton "supprimer cette demande" de la pop-up ne semble pas fonctionner (en tout cas la pop-up ne se ferme pas quand je clique dessus)

Scénario 3 : NOT OK
- je crée une première demande de domiciliation
- je la valide
- je lance une demande de renouvellement
- je la valide
- je supprime le domicilié
- la même pop-up apparait
<img width="572" alt="Capture d’écran 2021-06-07 à 16 04 42" src="https://user-images.githubusercontent.com/59437305/121030775-1411a300-c7aa-11eb-9830-819119c6530c.png">
- elle est correcte mais le bouton "supprimer cette demande" ne semble pas fonctionner (en tout cas la pop-up ne se ferme pas quand je clique dessus)
- de plus, je vois un message d'erreur "la demande de renouvellement n'a pas pu être supprimée"
- par contre si je reviens sur la liste des domiciliés, le domicilié en question est bien retourné dans l'onglet "à compléter"

**Recette PO**

- [x] scénario 1
- [x] scénario 2
- [x] scénario 3

**Comment by Toub** [comment]
lié à https://github.com/SocialGouv/domifa/issues/1422

**Comment by ledugong** [comment]
@Toub 
Scénario 2 :

**Comment by pYassine** [comment]
Selon s'il s'agit d'un import ou pas il y a un bug

Le statut "IMPORT" est dans l'historique, et il provoque des bugs quand on fait un retour en arrière lors de la suppression d'une demande de renouvellement

Il faudrait extraire l'info sur l'import de l'historique et la retirer complètement, cela réglerait le souci

**Comment by pYassine** [comment]
https://fix-dates-echeance-dev2-domifa.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK
Scénario 2 OK
Scénario 3 OK
Import OK

**Comment by ledugong** [comment]
Recette Prod OK
