### ISSUE TITLE
feat(FICHE_DOMICILIÉ): tracer la suppression des interactions

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1432]
**Situation Actuelle**

Suite à un bug de structure qui montrait un compteur différent dû à une suppression de courrier antérieure, il serait utile de tracer la suppression des courriers sur la fiche domicilié.

**Comportement souhaité**

- [x] dans la section interactions, afficher une phrase du style "Paul DURAND a supprimé un courrier / un colis / un passage etc. le 15/04/2021"
- [x] comme la suppression d'anciennes interactions pose problème, limiter à la suppression / restauration de la dernière interaction seulement
- [x] permettre de restaurer une interaction
- [x] si on restaure une interaction entrante (nouveau courrier), re-programmer le sms
- [x] si on restaure une interaction sortante (courrier remis), et que l'interaction entrante était aujourd'hui, re-programmer le sms
- [x] pour @yassine: avant de merger, gérer le cas "restauration npai" indiqué ici: https://github.com/SocialGouv/domifa/pull/1485
- [x] pour @yassine: prendre en compte ces modifications sur la nouvelle interface (ne pas l'afficher sur la vue d'ensemble, seulement dans la section interactions)

**Recette PO**

- [x] ajouter et supprimer le dernier courrier, vérifier le compteur
- [x] permettre de restaurer la dernière interaction
- [x] si on restaure une interaction entrante (nouveau courrier), le sms doit partir
- [x] si on restaure une interaction sortante (courrier remis), et que l'interaction entrante était aujourd'hui, le sms doit partir (si elle est de la veille, il ne doit pas partir)
- [x] vérifier l'affichage des suppressions dans interactions
- [x] vérifier l'impact sur les stats
- [x] vérifier l'impact sur la date de dernier passage

**Comment by Toub** [comment]
Fait sur la version actuelle, "avant nouveau profil" (donc à adapter sur nouvelle fiche domicilié)

**Comment by Toub** [comment]
En attente de revue par @pYassine mais peut déjà être testé ici en attendant: https://domifa-feat-tracer-suppression-interactions-1432.dev2.fabrique.social.gouv.fr/usager/7

**Comment by ledugong** [comment]
@pYassine une fois l'interaction supprimée, si je la restaure elle apparait en double
https://user-images.githubusercontent.com/59437305/126159505-8001daee-5053-470f-b7de-28e2aeb371ec.mov

**Comment by ledugong** [comment]
@pYassine 

- [ ] Si je réceptionne un courrier avec un commentaire, je le distribue puis je supprime l'interaction : le colis revient bien dans les courriers à distribuer mais le commentaire a disparu.
https://user-images.githubusercontent.com/59437305/126340669-0f7d5e2f-51b1-4fe8-8fda-111b7c8c9954.mov

**Comment by pYassine** [comment]
@ledugong  https://domifa-fix-delete-interactio.dev.fabrique.social.gouv.fr/manage

**Comment by ledugong** [comment]
@pYassine j'ai toujours ce souci

 Si je réceptionne un courrier avec un commentaire, je le distribue puis je supprime l'interaction : le colis revient bien dans les courriers à distribuer mais le commentaire a disparu.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Reste le point : Si je réceptionne un courrier avec un commentaire, je le distribue puis je supprime l'interaction : le colis revient bien dans les courriers à distribuer mais le commentaire a disparu.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
