### ISSUE TITLE
bug(sentry): la plupart des messages du backend ne sont pas présents dans sentry

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1435]
**Description du problème**

Très peu de messages sont loggés sur le backend

**Comportement attendu**

On devrait retrouver toutes les traces des logs du container sur le backend

- https://sentry.fabrique.social.gouv.fr/settings/incubateur/domifa-backend/install/node/
- https://docs.sentry.io/platforms/node/guides/express/
- https://docs.sentry.io/platforms/node/

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Non recettable PO
