### ISSUE TITLE
feat(NUMÉRO_TÉL): formater les champs numéro pour une meilleure visibilité

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1440]
**Comportement souhaité**

- [x] champ "numéro de contact", afficher les numéros sous forme XX XX XX XX XX (avec espace)
- [x] pareil pour le champ "numéro d'envoi de notification SMS"

**Recette PO**

- [x] vérifier champ contact
- [x] vérifier champ notification SMS

**Comment by pYassine** [comment]
@ledugong  Good pour toi :) ?
![Capture d’écran 2021-07-13 à 15 26 22](https://user-images.githubusercontent.com/11486845/125459878-7d985b8e-b088-4e41-89c0-b5e0bd8ec6c0.jpg)

**Comment by ledugong** [comment]
@pYassine le champ est formaté dans la partie état civil mais pas dans la partie notifications sms
![Capture d’écran 2021-07-19 à 11 23 04](https://user-images.githubusercontent.com/59437305/126136860-2e2ddfc9-0be7-4d01-a9fb-0765502050ed.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
