### ISSUE TITLE
feat(FICHE_DOM): fonction impression de la section interactions (suivi passage et courriers)

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1458]
**Situation Actuelle**

Permettre l'impression de la section "Historique des courriers" dans l'onglet "Courriers" sur la fiche domicilié.

**Comportement souhaité**

- [x] ajouter une icône impression (prendre celle de la liste des domiciliés)
- [x] ajouter une balise texte "impression" pour l'accessibilité
- [x] permettre une impression paysage avec le suivi des interactions (courriers, passages, appels)

**Recette PO**

- [x] vérifier l'impression
- [x] tester sur différentes fiches domicilié

**Comment by pibouu** [comment]
https://domifa-1458-print-interactions.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
@pibouu ya un souci en production, tu peux regarder ?

https://user-images.githubusercontent.com/59437305/147815383-715eef14-41b5-4315-b47f-b83a528f32f1.mov

**Comment by ledugong** [comment]
Recette Prod OK
