### ISSUE TITLE
feat(prod): migraton VM

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1463]
## Préparation

- [x] mise à disposition d'une VM prod_new + installation et configuration générale - @gary-van-woerkens
- [x] configuration de l'env, déploiement - @Toub 
- [x] tests de l'environnement
- [x] test: un fichier ajouté sur la prod doit être présent aussi sur le filesystem prod2, et vice versa
- [x] Préparer PR migration DNS  - @gary-van-woerkens 
- [x] mettre à jour PROD2 sur la même version que la prod (2.6.4?)

## Mise en prod

- [x] Stopper l'application sur la VM de prod
- [x] Stopper l'application sur la VM de prod_new
- [ ] merger PR migration DNS
- [x] Backup de prod
- [x] Mise à jour du dump sur prod_new
- [x] Configuration de l'environnement

```
mv .env .env.PROD2
mv .env.PROD .env
```
- [x] Démarrage de l'application
- [x] tests de l'environnement

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
