### ISSUE TITLE
bug(STATS_DOMIFA): affichage du boutons stats 2020

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1468]
**Description du problème**

Les boutons SMS et Stats 2020 se chevauchent.
<img width="1222" alt="Capture d’écran 2021-06-16 à 15 31 09" src="https://user-images.githubusercontent.com/59437305/122228184-e3bbba00-ceb7-11eb-9685-deae718f525e.png">

**Comportement attendu**

- [x] corriger l'affichage 

**Recette PO**

- [x] vérifier l'affichage

**Comment by Toub** [comment]
Suivant la résolution, l'affichage peut aussi donner:
![image](https://user-images.githubusercontent.com/367762/123660275-cda4e680-d833-11eb-9c59-d561e2724769.png)

ou carrément ne pas être visible du tout:

![image](https://user-images.githubusercontent.com/367762/123660384-e6ad9780-d833-11eb-9e6f-07f865dc4db2.png)

En vérité, il faudrait surtout revoir complètement cet écran, par exemple:
- séparer les stats de la liste des structures
- pour la liste des structures, réduire le nombre de colonne, et permettre d'accéder à davantage d'infos en un clic (il peut s'agir d'une fiche, que l'on affiche soit directement dans le tableau, soit sur le côté de l'écran, dans un dialog, une nouvelle page...)

Et en profiter aussi pour ajouter un lien vers cette page dans le menu.

**Comment by ledugong** [comment]
@Toub 
J'ai envoyé un message à Chiraz pour qu'elle donne son avis

**Comment by Chirazh** [comment]
Je dois donner mon avis sur quoi du coup ?! les colonnes à réduire ? 
Je n'ai pas compris toute cette partie "et permettre d'accéder à davantage d'infos en un clic (il peut s'agir d'une fiche, que l'on affiche soit directement dans le tableau, soit sur le côté de l'écran, dans un dialog, une nouvelle page...)"

**Comment by ledugong** [comment]
@Toub est-ce qu'on peut pas juste mettre les boutons côte à côté horizontalement ? 
On refera cette page dans un second temps, pour l'instant le but c'est juste de bien séparer les boutons, que j'active pas les SMS sans faire exprès en voulant cliquer sur stats 2020 par exemple

**Comment by Toub** [comment]
Ok, je croyais que c'était un retour purement esthétique, et comme c'est très spécifique à la résolution et à la taille de l'écran, je voyais plus ça dans le cadre d'une refonte complète.

Du coup, je te fais un fix pour bien isoler les boutons:

![image](https://user-images.githubusercontent.com/367762/124474197-8c1abb00-dda0-11eb-91e0-77cdd6b47fb9.png)

**Comment by Toub** [comment]
A tester ici: https://domifa-fix-boutons-stats-2020-1468.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
