### ISSUE TITLE
bug(PROCURATION): on voit encore le tag procu même si elle est expirée

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1502]
**Description du problème**

Suite au ticket https://github.com/SocialGouv/domifa/issues/1471, un souci persiste.
Si la procuration est expirée, le tag "procuration" s'affiche encore sur la liste des domiciliés.

**Recette PO**

- [x] vérifier la disparition du tag procuration une fois celle-ci expirée

**Comment by Toub** [comment]
A tester ici: https://domifa-fix-transfert-expiration-1501.dev2.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
