### ISSUE TITLE
bug(DATE_PASSAGE): date de dernier passage affiche date du renouvellement

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1556]
**Description du problème**

Bug soulevé par une structure, ci-dessous la reproduction du bug : 
- je suis sur une fiche domicilié avec une date de dernier passage au 19/07
- je lance un renouvellement, puis je le valide avec une date de début antérieure (disons 13/07)
- alors la date de dernier passage change et passe au 13/07, alors qu'un passage avait été comptabilisé au 19/07

**Comportement attendu**

Au cours d'un renouvellement, garder la même date de dernier passage visible avant la demande de renouvellement.

**Copies d'écran**

![Capture d’écran 2021-07-19 à 13 58 35](https://user-images.githubusercontent.com/59437305/126156606-a6e644e3-21f1-469f-b441-bb361e54e238.png)

![Capture d’écran 2021-07-19 à 13 59 12](https://user-images.githubusercontent.com/59437305/126156653-7261a76d-3615-44dd-b9e8-9155de6b6418.png)

![Capture d’écran 2021-07-19 à 13 59 24](https://user-images.githubusercontent.com/59437305/126156670-944d5551-3c76-4f93-a266-3dad0bddfe28.png)

**Recette PO**

- [x] tester un renouvellement avec date dernier passage postérieure à la date de début de nouvelle dom

**Comment by pYassine** [comment]
@ledugong  ça n'est pas un bug, c'est volontaire. La date de dernier passage est remise à zéro par la nouvelle instruction d'un dossier

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
