### ISSUE TITLE
feat(INT_DOM): ETQ dev, logguer la consultation des infos de connexion.

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1676]
**Situation Actuelle**

Actuellement il n'y pas de logs sur les actions des utilisateurs. Une personne peut se connecter et supprimer toutes les datas et il n'y a aucun moyen de tracer ces actions.

**Comportement souhaité**

Traquer les actions des utilisateurs, en commençant par la connexion.

Description du comportement souhaité

- [x] définir le modèle de data des logs
- [x] créer le service Log
- [x] ajouter les loggers dans les endpoints concernés

**Recette PO**

- [x] supprimer un document uploadé va créer un log
- [x] regarder dans la DB si le log a bien été enregistré

**Comment by pibouu** [comment]
Liste des actions logger : 

- connexion
- créer demande
- accepter dossier
- refuser dossier
- ajouter pièce jointe
- supprimer pièce jointe
- ajouter note
- supprimer note
- supprimer domicilié
- demande renouvellement
- radier domicilié

**Comment by ledugong** [comment]
Recette Prod OK
