### ISSUE TITLE
feat(INT_DOM): ETQ dev, définir un nom de domaine + vérifier son intégration par les OPS

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1677]
**Situation Actuelle**

Description de la situation actuelle

**Comportement souhaité**

Description du comportement souhaité

- [x] https://mon-domifa.fabrique.social.gouv.fr/

**Recette PO**

**Comment by pYassine** [comment]
@ledugong  voici l'url de test en préprod
Quelques bugs ont été corrigé par rapport à La version en prod sera mise à jour lors de la prochaine MEP

https://mon-domifa-domifa-preprod.dev.fabrique.social.gouv.fr/auth/login

**Comment by ledugong** [comment]
@pYassine 

ça sera quoi le lien en prod ? car dans celui en PP ya "domifa" 2 fois....

**Comment by ledugong** [comment]
Lien prod : https://mon-domifa.fabrique.social.gouv.fr/auth/login

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
URL ok en prod
