### ISSUE TITLE
refactor: renommer app_user en user_structure

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1681]
**Situation Actuelle**

Il n'y a qu'un seule type d'utilisateur, mais ça va changer avec l'interface domicilié. Hors, l'user actuel à un nom générique: "app_user", ce qui va devenir ambigu.

**Comportement souhaité**

Pour que le code reste compréhensible:

- [x] renommer toutes les entités `AppUser*` en `UserStructure*`
- [x] renommer les dossiers `app-user` en `user-structure`
- [x] renommer le nom de table `app_user` en `user_structure`

**Recette PO**

- [x] test basique de l'application, sur ce qui concerne les utilisateurs structure (connexion, création d'un nouvel utilisateur, reset password...)

**Comment by Toub** [comment]
A tester ici: https://domifa-refactor-renommer-app-user-1681.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO 

- [ ] Connexion
- [ ] Déconnexion
- [ ] Mot de passe oublié
- [ ] Création d'un utilisateur
- [ ] Suppression d'un utilisateur

**Comment by Toub** [comment]
A tester en preprod

**Comment by ledugong** [comment]
Recette PO en cours

- [ ] Connexion
- [ ] Déconnexion
- [ ] Modification informations personnelles
- [ ] Mot de passe oublié
- [ ] Changement mot de passe
- [ ] Changement rôle profil
- [ ] Création d'un utilisateur
- [ ] Suppression d'un utilisateur
- [ ] Test import
- [ ] Export base des domiciliés
- [ ] Suppression base des domiciliés
- [ ] Ajout/téléchargement/suppression documents internes
- [ ] Modification informations structure
- [ ] Changement paramètres (ID cerfa)

**Comment by ledugong** [comment]
@Toub j'en ai trouvé un autre, avec le fichier en pj, 3eme on a un refus sans date de refus et l'import passe quand même
[modele_import_domifa.xlsx](https://github.com/SocialGouv/domifa/files/7234784/modele_import_domifa.xlsx)

**Comment by pYassine** [comment]
@ledugong  en effet, c'était pas géré, corrigé!

**Comment by ledugong** [comment]
@pYassine 

- [ ] en cas de refus, le bouton "télécharger le cerfa" en haut à droite de la fiche domicilié ne fonctionne toujours pas

- [ ] bug date de refus dans l'import OK

**Comment by ledugong** [comment]
Recette PO OK
