### ISSUE TITLE
feat(security): gestion générique des guards

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1683]
**Situation Actuelle**

Côté backend, il faut définir un guard pour chaque type de vérification de profil.

**Comportement souhaité**

En utilisant des décorators NestJS custom, créer un guard générique intégrant les différents roles et profils utilisateurs (usager, structure, super-admin).

TODO:

- [x] création nouveau guard
- [x] mise en place de tests unitaires de sécurité sur les controlleurs
- [x] application du nouveau guard pour remplacer FacteurGuard sur tous les controlleurs
- [x] application du nouveau guard pour remplacer AdminGuard sur tous les controlleurs
- [x] application du nouveau guard pour remplacer ResponsableGuard sur tous les controlleurs
- [x] application du nouveau guard pour remplacer DomifaGuard sur tous les controlleurs
- [x] application des tests de sécurité sur tous les controlleurs
- [x] test de connexion en tant que facteur
- [x] test de connexion en tant que structure
- [x] test de connexion en tant que admin domifa

<https://docs.nestjs.com/guards#putting-it-all-together>

**Recette PO**

- [x] se connecter en tant que facteur et vérifier que tout fonctionne
- [x] se connecter en tant qu'admin structure et vérifier que tout fonctionne
- [x] se connecter en tant qu'admin domifa et vérifier que tout fonctionne

**Comment by Toub** [comment]
A tester en preprod

**Comment by ledugong** [comment]
@Toub le bouton "supprimer le transfert" est gris
<img width="1179" alt="Capture d’écran 2021-09-27 à 11 28 50" src="https://user-images.githubusercontent.com/59437305/134882705-a18f1df0-fb4b-4fdd-a3e0-14c9f9288366.png">

**Comment by pYassine** [comment]
@ledugong  Corrigé ! 
En traitant les retours, je me suis rendu compte d'un comportement dont je suis pas sur

Quand on commence un renouvellement, la date affichée dans la colonne échéance est celle de la date du début de renouvellement : quand on clique sur "Demander un renouvellement"

Est-ce qu'on garde ça ou on affiche la date de fin de domiciliation ?

**Comment by ledugong** [comment]
@pYassine 
- [ ]  le bouton "supprimer le transfert" est toujours gris

- [ ] j'arrive pas à reproduire ton cas : j'ai testé un renouvellement et la colonne "échéance" affiche bien la date de fin de la dom actuelle
<img width="1225" alt="Capture d’écran 2021-10-04 à 14 27 16" src="https://user-images.githubusercontent.com/59437305/135851180-1e09217f-c1ed-4501-8f9b-11484838be09.png">

**Comment by ledugong** [comment]
Recette PO OK
