### ISSUE TITLE
bug(NOTIFS_SMS): l'historique des sms ne s'affiche plus sur la fiche domicilié

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1690]
**Description du problème**

Description du problème

**Comportement attendu**

Description du comportement souhaité

- [ ] action 1
- [ ] action 2...

**Scénario de reproduction du problème**

1. Se connecter en tant que '...'
2. Aller sur la page '....'
3. Cliquer sur '....'
4. Le ... est incorrect

**Copies d'écran**

**Informations complémentaires:**

**Recette PO**

- [ ] test 1
- [ ] test 2...

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@pYassine je fais un test avec mon numéro (qui est valide du coup) mais le SMS arrive directement en échec
![Capture d’écran 2021-09-23 à 13 45 39](https://user-images.githubusercontent.com/59437305/134501381-9fb78f64-65e2-4d5b-be48-dc513c8e54cf.png)

**Comment by pYassine** [comment]
@ledugong  done !

**Comment by ledugong** [comment]
@pYassine j'ai toujours le même souci, je déclare un courrier avec mon numéro valide et je vois écrit "échec"
<img width="1018" alt="Capture d’écran 2021-10-04 à 11 44 07" src="https://user-images.githubusercontent.com/59437305/135829662-a5938f02-92b7-44ec-8fa9-9a607179272d.png">

Testé sur https://preprod.domifa.fabrique.social.gouv.fr/profil/historique/4

**Comment by ledugong** [comment]
Souci réglé depuis
