### ISSUE TITLE
refactor(frontend): remplacer fontawesome

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1702]
**Situation Actuelle**

Le bundle est trop gros, notamment à cause des icones et de la librairie moment.

```bash
npm run build:analyze
npm run analyze
```
![image](https://user-images.githubusercontent.com/367762/134137888-c51a562e-345d-46ce-b824-8531868a2e87.png)

**Comportement souhaité**

Remplacer les icônes par quelque chose de plus léger.

**Comment by ledugong** [comment]
Recette PO icônes OK

- [ ] homepage
- [ ] liste des domiciliés
- [ ] fiche domicilié
- [ ] création d'une domiciliation 
- [ ] stats domifa
- [ ] compte structure
