### ISSUE TITLE
refactor(frontend): remplacer momentjs

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1703]
**Situation Actuelle**

Le bundle est trop gros, notamment à cause des icones et de la librairie moment.

```bash
npm run build:analyze
npm run analyze
```
![image](https://user-images.githubusercontent.com/367762/134137888-c51a562e-345d-46ce-b824-8531868a2e87.png)

**Comportement souhaité**

Remplacer moment par quelque chose de plus léger (date-fns, luxon...).

**Comment by ledugong** [comment]
recette PO vérification des dates : 
- [ ] tri colonnes liste domiciliés
- [ ] date de naissance
- [ ] date de naissance AD
- [ ] date début de domiciliation
- [ ] date refus domiciliation
- [ ] dates transfert
- [ ] dates pocuration

**Comment by ledugong** [comment]
Recette PO OK
