### ISSUE TITLE
feat(CREATION_STRUCTURE): Ajout des horaires d'ouverture côté structures

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1711]
**Situation Actuelle**

But : permettre aux structures d'ajouter leur horaires d'ouverture et les rendre visibles sur l'interface domicilié.
<img width="1246" alt="Capture d’écran 2022-03-07 à 22 40 18" src="https://user-images.githubusercontent.com/59437305/157122309-d8487fbe-01f7-4335-a848-c4d242e58bf0.png">

**Comportement souhaité**

En bas de la section structure et avant la section responsable légal
- [ ] ajouter "Jours et horaires d'ouverture" avec les jours de la semaine à cocher (de lundi à dimanche)
- [ ] un fois le jour coché, afficher 2 cases "de XX à XX" pour y ajouter les horaires
- [ ] ne pas pouvoir mettre une horaire de fermeture antérieure à l'horaire d'ouverture
- [ ] garder cette section facultative
- [ ] une fois validée, cette section reste modifiable dans la section Structure

Potentiellement travail technique en amont (c'était déjà dans le ticket alors je le laisse)
- [ ] Créer le modèle de donnée
- [ ] Créer le formulaire d'édition des horaires

**Recette PO**

- [ ] tester plusieurs jours / horaires d'ouverture
- [ ] tester une horaire de fermeture antérieure à l'horaire d'ouverture
- [ ] tester la modification une fois la structure validée

**Comment by Chirazh** [comment]
Préférable de mettre les horaires de la structure dans les informations de la structure sur DomiFa plutôt que dès le formulaire de la création car cela risque d'allonger le temps d'inscription et donc de dissuader.

**Comment by pYassine** [comment]
Permettre d'ajouter des horaires par catégorie
- Réception des courriers
- Accueil du public / dépôt des dossiers

**Comment by Chirazh** [comment]
Finalement nous avons fait passer le ticket permettant aux structures d'ajouter un message sur le portail, elles peuvent utiliser cette fonctionnalité pour ajouter les horaires.
