### ISSUE TITLE
bug(export): l'export plante sur les grosses structures

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1739]
**Description du problème**

L'export plante sur les grosses structures (et est très lent sur les autres)

**Comportement attendu**

Optimiser le traitement, pour qu'il soit plus rapide et passe même sur les plus grosses structures.

**Scénario de reproduction du problème**

Exporter les usagers de la structure 113

**Recette PO**

- [x] exporter les usagers de la structure 113 et vérifier que ça ne plante pas
- [x] exporter les usagers d'une plus petite structure avant et après le correctif, et vérifier que les données sont les même (surtout onglet 3 "courriers")

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Recette PO OK
