### ISSUE TITLE
feat(design): Refonte graphique du formulaire de domiciliation

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1743]
**Situation Actuelle**

Le design du formulaire a été retravaillé par Jérémie suite aux retours & ateliers.

**Comportement souhaité**
Maquette:
https://www.figma.com/file/UcGnQt8yBzSHuuon1rRiN4/Domifa?node-id=1003%3A3003

Il faudrait intégrer le nouveau design sur toutes les étapes du formulaires

**Formulaire de création de dom (Écran 1 : état-civil) ** 

- [x] Ajouter une liste déroulante "type de demande" : Première dom ou renouvellement
- [x] Ajouter un champs "ID personnalisé"

**Page de décision :**

_0. Boutons d'actions_ 
- [x] Contrairement à la maquette, il faut bien remettre le bouton "soumettre à décision" à côté de "Valider ou refuser la décision"

_1 : Etat-civil & ayant-droit_
- [x] Ajouter le numéro de domicilié + son type de demande en haut comme sur la maquette
- [x] Mettre Etat-civil & Ayant-droit côte à côte
- [x] Quand on clique sur modifier : Editer les informations + Ayant-droit

_2. Entretien_
- [x] Editer les données de l'entretien

_3. Pièces-jointes :_
- [x] Afficher les docs + un bouton en haut à droite "Modifier les pièces-jointes"

_Autre_
- [x] Commentaires privés : ajouter le module de notes internes en bas de page

**⚠️ Présent dans la maquette mais pas encore dév / validé par l'équipe :**
- Boutons ronds : on harmonisera tout le site d'un coup sur les boutons, refactor de la gestion de Bootstrap a prévoir cc Ticket XXX

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
