### ISSUE TITLE
feat(CERFA): Permettre le téléchargement des 2 types de Cerfa, quelque soit mon statut

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1749]
### **Situation Actuelle**

Aujourd'hui, le Cerfa que vous pouvez télécharger dépend de votre statut.
- Valide : [Attestation l'élection de domicile :](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/attestation.pdf)  
- Instruction : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf)
- Attente de décision : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf)
- Refus : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf)
- Radiation : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf)

### **Comportement souhaité**

On doit pouvoir générer n'importe quel Cerfa pour tout type de statut:

- Valide : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf) + [Attestation l'élection de domicile :](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/attestation.pdf)  
- Instruction : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf) + [Attestation l'élection de domicile](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/attestation.pdf)  
- Attente de décision : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf) + [Attestation l'élection de domicile](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/attestation.pdf)  
- Refus : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf)
- Radiation : [Demande d'élection de domicilie](https://github.com/SocialGouv/domifa/blob/master/packages/backend/src/_static/static-docs/demande.pdf)

 **Boutons "Télécharger le Cerfa" actuellement sur le site**
Ils ne doivent pas changer de comportement, il faut télécharger le Cerfa par défaut selon le statut du domicilié

**Nouveaux boutons à créer**

**1. Ecran de décision :**
- [x] Ajouter un bouton pour télécharger le cerfa d'attestation provisoire. Il s'agit du fichier "src/_static/static-docs/attestation.pdf"
![Capture d’écran 2021-10-09 à 12 24 40](https://user-images.githubusercontent.com/11486845/136654352-7b6fbe61-2c3b-4f47-b5ea-0cf71a7e621c.jpg)

**2. Page profil, section documents :** 
- [x] Pour les domiciliés ACTIFS uniquement, ajouter un bouton pour télécharger le Cerfa "Demande d'élection de domicilie"

**3. Modifier la taille de la police du champs ville*
- [x] Modifier les 2 Cerfas d'origine, réduire la taille de la police d'écriture des champs VILLE

**Recette PO**

- [x] Aller sur un domicilié actif : télécharger les 2 Cerfas
- [x] Aller sur un domicilié en instruction : télécharger les 2 Cerfas
- [x] Aller sur un domicilié en attente de décision : télécharger les 2 Cerfas
- [x] Aller sur un radié / refusé, vérifier qu'on ne peut télécharger qu'un seul Cerfa

**Comment by ledugong** [comment]
@pibouu 

Cas d'un domicilié actif
![Capture d’écran 2021-11-20 à 11 38 02](https://user-images.githubusercontent.com/59437305/142723246-358f24bb-0344-4752-9d6e-e06d2c5a0f88.png)
- [ ] garder le wording de base "Télécharger le cerfa", puisque le domicilié est actif, ce n'est pas un cerfa provisoire
- [ ] garder le bouton bleu et non blanc

Cas d'un domicilié en cours d'instruction
![Capture d’écran 2021-11-20 à 11 41 51](https://user-images.githubusercontent.com/59437305/142723337-4463cb3d-ebfb-469e-828a-c0c460c4fad2.png)
- [ ] garder le bouton bleu et non blanc
![Capture d’écran 2021-11-20 à 11 42 38](https://user-images.githubusercontent.com/59437305/142723350-781a3d62-bdba-47a6-81e5-1af9eb2204a4.png)
- [ ] garder les champs "date de validité de l'attestation" vides, il se rempliront automatiquement seulement en cas de validation de la demande

Cas d'un domicilié en attente de décision
- [ ] garder le bouton bleu et non blanc
- [ ] garder les champs "date de validité de l'attestation" vides, il se rempliront automatiquement seulement en cas de validation de la demande
![Capture d’écran 2021-11-20 à 11 43 56](https://user-images.githubusercontent.com/59437305/142723382-83e63c65-dfca-4f9a-9bd7-5e44c88ec025.png)

Cas d'un domicilié refusé
ATTENTION tu as mis un cerfa d'attestation de domicilié et non le cerfa de refus de domiciliation en PP.
- [ ] enlever le cerfa provisoire d'attestation de domiciliation car le domicilié est refusé
- [ ] remettre le cerfa de refus
![Capture d’écran 2021-11-20 à 11 46 44](https://user-images.githubusercontent.com/59437305/142723467-aa8a9750-715a-4d1e-8dca-1eda1106bd64.png)
- [ ] dans la section documents, aussi remettre le cerfa de refus
![Capture d’écran 2021-11-20 à 11 47 08](https://user-images.githubusercontent.com/59437305/142723480-29484a8b-de9d-44c7-aa98-e32641633620.png)
- [ ] ajouter le cerfa de demande d'attestation de domicile
- [ ] remettre le bouton bleu et non blanc

Cas d'un domicilié radié
ATTENTION tu as mis un cerfa d'attestation de domicilié en PP.
- [ ] enlever le cerfa d'attestation de domiciliation car le domicilié est radié, il n'en a plus
- [ ] ajouter le cerfa de demande d'attestation de domicile
- [ ] remettre le bouton bleu et non blanc

**Comment by pYassine** [comment]
@ledugong  
https://domifa-feat-correction-pre-mep.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
