### ISSUE TITLE
feat(BACK_OFFICE): mieux isoler les profils admin domifa

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1756]
**Situation Actuelle**

Les admins domifa sont ceux de la structure domifa, mélange des genres.

**Comportement souhaité**

Pouvoir activer séparément les admins structure et les admins domifa.

**Recette PO**

TODO

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@Toub pour celui là, je dois juste vérifier qu'un admin hors domifa n'ait pas accès au back office ?

**Comment by Toub** [comment]
Non, c'est purement technique, de ton côté tu peux juste constater que la connexion de l'admin domifa se fait sur le nouveau backoffice.

**Comment by ledugong** [comment]
Ok merci, recette PO OK

**Comment by ledugong** [comment]
Non recettable prod
