### ISSUE TITLE
feat(BACK_OFFICE): espace dédié

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1757]
**Situation Actuelle**

L'espace admin domifa est constitué d'une seule page intégré au site des stuctures.

**Comportement souhaité**

Extraire dans un espace dédié, multi-pages.

TODO

- [x] #1756 mieux isoler les profils admin domifa
- [x] nouvel espace backoffice admin
- [x] page des structures
- [x] page des stats 
- [x] quelques bugs à corriger 
- [x] optimiser la vitesse de chargement
- [x] lien de connexion depuis l'espace domifa des structures (via le menu comme actuellement)
- [x] ajouter la recherche sur la liste des structures
- [x] n'afficher que les N premières structures pour accélérer l'affichage et le tri
- [x] mettre les structures en cache pour + de performance
- [x] déplacer le bouton d'export dans la topbar

__confirmation de nouvelle structure + suppression structure__

- [x] déplacer la page dans le nouvel espace
- [x] déplacer le end-point api
- [x] modifier l'url dans le mail
- [x] mise au point + tests actions admin (activation, suppression, sms, espace usager...)

__ops__
- [x] déployer nouvelle url PROD

**Recette PO**

- [x] accéder à la page de connection du nouvel espace depuis le menu de l'application des "structures" (connecté en tant que super admin)
- [x] se connecter
- [x] perfomances: les pages s'affichent beaucoup plus rapidement qu'avant
- [x] cache: une fois chargées, les pages se rechargent quasi instantanément
- [x] test téléchargement export stats et structures
- [x] test page stats: vérifier quelques chiffres
- [x] test page liste structure: vérifier quelques chiffres
- [x] test page liste structure: tri
- [x] test page liste structure: recherche par #id, nom, email, région...
- [x] test page liste structure: téléchargement stats structure
- [x] test page liste structure: activation sms
- [x] test page liste structure: activation espace domicilié
- [x] test page liste structure: création structure + confirmation par mail => activation
- [x] test page liste structure: création structure + confirmation par mail => refus: suppression
- [x] test page liste structure: suppression structure depuis page d'admin + confirmation par mail

**Comment by Toub** [comment]
Voici les URLs pour les tests: 

- https://domifa-feat-espace-admin.dev.fabrique.social.gouv.fr
- https://admin-domifa-feat-espace-admin.dev.fabrique.social.gouv.fr
- https://mon-domifa-domifa-feat-espace-admin.dev.fabrique.social.gouv.fr

**Comment by Toub** [comment]
Cette PR à été mergée, à tester sur la preprod.

**Comment by ledugong** [comment]
@Toub 

- [ ] arrivée en bas de page je ne peux pas accéder au reste des structures, normal ? tu as fait comme pour les radiés ?
![Capture d’écran 2021-12-06 à 16 56 27](https://user-images.githubusercontent.com/59437305/144878701-ddda9971-7379-4d38-b1b2-776fa17aec9b.png)

- [ ] bug de front avec les icônes croix et loupe (testé sous Safari)
![Capture d’écran 2021-12-06 à 16 57 09](https://user-images.githubusercontent.com/59437305/144878805-daea38dc-3393-444d-89d4-7d405ca7d9a0.png)

- [ ] si je me déconnecte et que j'essaye de me reconnecter, j'ai un bandeau de confirmation mais je reste sur la même page (testé plusieurs fois)
![Capture d’écran 2021-12-06 à 16 58 25](https://user-images.githubusercontent.com/59437305/144879261-8802b4a6-7dbc-4d5c-9959-af26843c4417.png)

**Comment by Toub** [comment]
@ledugong retours pris en compte, à tester ici: https://admin-domifa-toub-feat-back-office-retours-espace-d-5.dev.fabrique.social.gouv.fr/structures

- [x] arrivée en bas de page je ne peux pas accéder au reste des structures, normal ? tu as fait comme pour les radiés ?
![Capture d’écran 2021-12-06 à 16 56 27](https://user-images.githubusercontent.com/59437305/144878701-ddda9971-7379-4d38-b1b2-776fa17aec9b.png)

=> oui on ne peux pas afficher les structures à l'infi, donc j'ai limité à 50, et il faut utiliser les filtres et le tri (ou l'export si on a vraiment besoin de tout voir)

- [x] bug de front avec les icônes croix et loupe (testé sous Safari)
![Capture d’écran 2021-12-06 à 16 57 09](https://user-images.githubusercontent.com/59437305/144878805-daea38dc-3393-444d-89d4-7d405ca7d9a0.png)

- [x] si je me déconnecte et que j'essaye de me reconnecter, j'ai un bandeau de confirmation mais je reste sur la même page (testé plusieurs fois avec les 2 options de déconnexion, via le menu et en bas de page)
![Capture d’écran 2021-12-06 à 16 58 25](https://user-images.githubusercontent.com/59437305/144879261-8802b4a6-7dbc-4d5c-9959-af26843c4417.png)

- [x] en cherchant par ID 314 je tombe sur ces résultats : la structure 314 est certes dedans mais pourquoi j'ai les autres ? La structure 80 par exemple ? 
![Capture d’écran 2021-12-06 à 17 05 51](https://user-images.githubusercontent.com/59437305/144880244-3126572b-8699-46b8-80b0-6fd1abda74fa.png)

C'est à cause du numéro de téléphone, je le retire de la recherche. Par contre si 314 est contenu dans l'email par exemple, ça sera retourné.

A noter que pour chercher uniquement par ID, tu peux taper `#314`

- [x] en testant le bouton Stats 2020, je remarque l'heure de l'export affichée n'est pas la bonne
![Capture d’écran 2021-12-06 à 17 08 36](https://user-images.githubusercontent.com/59437305/144880663-adc7a438-631b-4b78-a359-83726b7e8be5.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
