### ISSUE TITLE
feat(interactions): amélioration gestion et suivi des courriers

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1761]
**Situation Actuelle**

Le modèle de données des interactions et la façon dont le compteur d'interaction et les stats sont gérés posent problème pour implémenter certaines fonctionnalités.

**Solution proposée**

- [x] Associer chaque interaction sortante à toutes les interactions entrantes distribués : j'ai reçu 3 courriers, quand je les distribue, on indique dans les 3 courriers, l'id de la distribution
- [x] Recalcul à chaque ajout / distribution
- [x] Traitement des valeurs incohérentes
- [x] Adapter le calcul des stats

**Comportement souhaité**

- [x] permettre de supprimer n'importe quelle interaction passée, tout en conservant des valeurs cohérentes pour les stats et l'interface usager

**Recette PO**

- [ ] ajout de courrier, retrait de courrier
- [ ] Ajout de commentaires dans les courriers
- [ ] suppression d'interactions
- [ ] Calculer les stats après avoir ajouter / distribuer ou supprimer des courriers

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
Lien : https://domifa-fix-migration-test.dev.fabrique.social.gouv.fr/manage

**Comment by ledugong** [comment]
@pYassine 

- [ ] coquilles d'orthographe
"Êtes-vous sûr de vouloir supprimer cette interaction ?"
"Cette interaction sera retirée des interactions en attente de distribution."
<img width="520" alt="Capture d’écran 2021-12-27 à 16 27 24" src="https://user-images.githubusercontent.com/59437305/147485591-25bea57b-57d9-4a1c-9fab-85a659daacb7.png">

**Comment by ledugong** [comment]
@pYassine 

- [ ] les mêmes coquilles sur la pop-up de restauration
"Êtes-vous sûr de vouloir supprimer cette interaction ?"
"Le compteur d'interactions en attente sera remis à jour."
<img width="678" alt="Capture d’écran 2021-12-29 à 16 28 17" src="https://user-images.githubusercontent.com/59437305/147677768-dee92356-5130-48e1-99eb-a69f590bd4be.png">

**Comment by ledugong** [comment]
@pYassine 

- [ ] il manque un point en fin de phrase
"Tous les courriers, colis ou avis de passage liés à cette distribution seront de nouveau marqués comme "à distribuer"."

- [ ] coquilles sur la pop-up de restauration
"Êtes-vous sûr de vouloir restaurer cette interaction ?"
"Le compteur d'interactions en attente sera remis à jour."

**Comment by pYassine** [comment]
Retours corrigés sur cette branche : https://domifa-fix-cannot-delete-file.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
