### ISSUE TITLE
bug(env): faire le ménage dans les environnement et preset

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1775]
**Description du problème**

La configuration est trop complexe car configurée à différents endroits:
- preset
- fichier de conf kosko/k8s
- valeurs par défaut dans `domifaConfig.service.ts`

**Comportement attendu**

Description du comportement souhaité

- [x] supprimer les preset de prod
- [x] mettre les valeurs par défaut (issues des preset de prod) dans les fichiers backend.ts / frontend.ts
- [x] supprimer les valeurs par défaut de `domifaConfig.service.ts`

voir aussi #1774

__Note__: la preprod a ses propres fichiers de conf k8s

**Recette PO**

NA

**Comment by pYassine** [comment]
@ledugong  impossible à review de ton côté

**Comment by ledugong** [comment]
Non recettable PO

**Comment by ledugong** [comment]
Recette Prod OK
