### ISSUE TITLE
bug(maintenance): rafraichissement automatique de la page après la maintenance

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1783]
**Description du problème**

Lors de la mise à jour de l'application, ou en cas d'interruption du service, une popup de maintenance s'affiche.

La page devrait se rafraichir automatiquement ensuite, mais ce n'est plus le cas.

D'après @pYassine c'est lié à la version qui n'est plus récupérée correctement par l'application via une variable d'environnement.

- [x] mise à jour du numéro de version côté frontend (affiché en bas de page)
- [x] mise à jour du numéro de version sur le healthcheck

**Comportement attendu**

- [x] la page devrait se rafraichir automatiquement ensuite, mais ce n'est plus le cas.

**Comment by Toub** [comment]
La solution proposée par @pYassine est de configurer le plugin semantic release pour également mettre à jour les packages de chaque projet du mono-repo.

Ce n'est visiblement pas possible via la configuration standard: https://semantic-release.gitbook.io/semantic-release/usage/configuration

Il faudrait donc passer par un plugin "mono-repo", il y en a plusieurs, mais c'est complexe.

Une autre solution serait de faire comme avant, et de positionner la variable d'environnement DOMIFA_DOCKER_IMAGE_VERSION lors du build du frontend (et également sur l'espace usager et admin).

**Comment by Toub** [comment]
Pour positionner la variable d'environnement `DOMIFA_DOCKER_IMAGE_VERSION` au moment du build dans `review.yml`, via `dockerbuildargs`:

- https://docs.github.com/en/actions/learn-github-actions/environment-variables
- https://github.com/SocialGouv/actions/search?q=GITHUB_REF

**Comment by Toub** [comment]
__Test 1__: https://domifa-toub-fix-maintenance-rafraichissement-5k9b67.dev.fabrique.social.gouv.fr/

- [ ] vérifier le numéro de version en bas de page

__Test 2__: https://domifa-api-domifa-toub-fix-maintenance-rafraichisseme.dev.fabrique.social.gouv.fr/healthz

- [ ] vérifier le numéro de version dans la réponse json

**Comment by Toub** [comment]
Sur les PR, la variable est le sha-1, mais en preprod et en prod ça devrait être le tag: 
![image](https://user-images.githubusercontent.com/367762/143902359-c1cedc3e-be79-4028-9676-ff6ff8ee5ba2.png)

**Comment by ledugong** [comment]
en attente du merge d'une PR pour la recette

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Non recettable en prod
