### ISSUE TITLE
feat(Dossier): Ajouter les commentaires + le nom dans le header

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1790]
**Situation Actuelle**

Suite aux changements de Design, il reste certaines modifs à faire 

**Comportement souhaité**

Modifier le header dans la demande de dom : 

**Quand on débute une première domiciliation**
- [x] Afficher "Nouvelle domiciliation"

**Pour toutes les autres étapes** 
- [x] Si première demande: "Première demande de " le nom prénom + ref"
- [x] Si renouvellement: "Renouvellement de " le nom prénom + ref"

Notes 

- [x] Ajouter les commentaires privés comme [sur la maquette](https://www.figma.com/file/UcGnQt8yBzSHuuon1rRiN4/Domifa?node-id=1003%3A3246)

- [x] Mettre les notes en bas de page dans toutes les étapes du formulaire

**Recette PO**

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@pibouu comme dit ce matin, finalement on cache tout ID pour le moment donc le retirer du bandeau, juste laisser le prénom nom (que ce soit pour une première demande ou un renouvellement)
![Capture d’écran 2021-11-01 à 18 19 51](https://user-images.githubusercontent.com/59437305/139712804-15114cce-21a5-479c-9b03-8d1f0e402d63.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
