### ISSUE TITLE
feat(FAQ): MAJ guide utilisateur + MAJ vidéos tutos + ajout vidéo tuto fiche domicilié

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1800]
**Situation Actuelle**

Sur la page https://domifa.fabrique.social.gouv.fr/faq le guide utilisateur et les vidéos tutos ne sont plus à jour, les changer.
Page Github : https://github.com/SocialGouv/domifa/blob/master/packages/frontend/src/app/modules/general/components/faq/faq.component.html 

**Comportement souhaité**

- [x] Mettre à jour le guide utilisateur en cliquant sur le bouton ci-dessous
![Capture d’écran 2021-10-25 à 17 27 25](https://user-images.githubusercontent.com/59437305/138724882-78223d70-6108-4a15-a195-43db9ed067e2.png)
Le nouveau guide est disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Support/GUIDE%20UTILISATEURS&openfile=112878

- [x] Mettre à jour la vidéo "Inscription d'une nouvelle structure"
![Capture d’écran 2021-10-25 à 17 28 32](https://user-images.githubusercontent.com/59437305/138725059-b3ee9006-7a7b-494f-a47b-4b1a6048542e.png)
La nouvelle vidéo est disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Import%20_%20Tutos/Tutos/Nouveau_DomiFa&openfile=98295 

- [x] Mettre à jour la vidéo "Créer une domiciliation"
![Capture d’écran 2021-10-25 à 17 34 05](https://user-images.githubusercontent.com/59437305/138725988-c04f222e-e26e-4749-94cf-71c310111307.png)
La nouvelle vidéo est disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Support/Tutos/Nouveau_DomiFa&openfile=113056

- [x] Mettre à jour la vidéo "Importer vos domiciliés"
![Capture d’écran 2021-10-25 à 17 35 04](https://user-images.githubusercontent.com/59437305/138726175-75a1bd51-00e3-4966-a971-b9a6552fd8cc.png)
La nouvelle vidéo est disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Import%20_%20Tutos/Tutos/Nouveau_DomiFa&openfile=98306

- [x] Mettre à jour la vidéo "Gestion des domiciliés"
![Capture d’écran 2021-10-25 à 17 35 46](https://user-images.githubusercontent.com/59437305/138726277-cd79f3ef-10f2-4d0d-a1bb-23ea320dfddd.png)
La nouvelle vidéo est disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Import%20_%20Tutos/Tutos/Nouveau_DomiFa&openfile=111070

- [x] Après la vidéo sur la gestion des domiciliés, ajouter une nouvelle vidéo intitulée "Fiche domicilié" avec la vidéo disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Import%20_%20Tutos/Tutos/Nouveau_DomiFa&openfile=111091

- [x] Mettre à jour la vidéo "Compte"
![Capture d’écran 2021-10-25 à 17 36 20](https://user-images.githubusercontent.com/59437305/138726363-7d2bd4c9-7891-4605-a27a-c547a19ff0b8.png)
La nouvelle vidéo est disponible ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/Import%20_%20Tutos/Tutos/Nouveau_DomiFa&openfile=111038

**Recette PO**

- [x] vérifier le guide utilisateur
- [x] vérifier la vidéo "Inscription d'une nouvelle structure"
- [x] vérifier la vidéo "Créer une domiciliation"
- [x] vérifier la vidéo "Importer vos domiciliés"
- [x] vérifier la vidéo "Gestion des domiciliés"
- [x] vérifier la nouvelle video "Fiche domicilié"
- [x] vérifier la vidéo "Compte"

**Comment by Chirazh** [comment]
@ledugong @pibouu lien vers la VF du guide utilisateur ajouté.

**Comment by ledugong** [comment]
@pibouu @pYassine les nouvelles vidéos n'apparaissent pas sur https://domifa-preprod.dev.fabrique.social.gouv.fr/faq

**Comment by pYassine** [comment]
@ledugong  
https://domifa-feat-correction-pre-mep.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

- [ ] les photos "still" sur la FAQ correspondent aux anciennes vidéos (exemple, la liste des domiciliés ci-dessous)
![Capture d’écran 2021-11-29 à 15 16 04](https://user-images.githubusercontent.com/59437305/143883668-dc8e2034-0df3-494a-8e0e-becf2469f0f4.png)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
