### ISSUE TITLE
feat(ID_VALIDATION): ajout ID personnalisé pop up + date de fin fixe

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1826]
**Situation Actuelle**

Plutôt que de devoir assigner l'ID personnalisé sur la fiche domicilié, il serait plus pratique de pouvoir l'ajouter dès la validation de la demande de domiciliation. 

Aussi, quelques corrections sur la pop-up de validation.

**Comportement souhaité**

Cas d'une demande de domiciliation à valider
![Capture d’écran 2021-11-01 à 14 25 00](https://user-images.githubusercontent.com/59437305/139678759-22209215-cf19-4a8e-9501-a560d8b63b5b.png)

- [x] figer le champ "date de fin de la domiciliation", la personne validant la demande ne peut changer QUE la date de début de domiciliation. La date de fin se met automatiquement à jour à 1 an (moins un jour) plus tard.

Pas besoin de demander à la structure si elle veut utiliser l'ID personnalisé ou pas, trop compliqué, on laisse le champ toujours visible en optionnel
- [x] sous les champs de dates, ajouter un champ "ID personnalisé" avec une mention "optionnel" sous le champ
- [x] par défaut, c'est l'ID DomiFa qui sera prérempli dans ce champ, libre à la structure de le modifier ou pas
- [x] sous le champ ID perso, afficher les 5 dernières fiches : "M. XXX XXX - ID perso de la dernière fiche enregistrée à titre indicatif - STATUT"
- [x] si la structure vide le champ puis valider la domiciliation, c'est du coup l'ID DomiFa qui sera attribué par défaut

Cas d'une demande de domiciliation à refuser
- [x] ne pas toucher à la pop-up

Cas d'une demande en cours de renouvellement d'un domicilié actif
- [x] garder le même processus de création de nouvelle domiciliation, avec l'ID qui arrive seulement à la fin
- [x] une fois arrivé sur la pop-up de confirmation, le champ ID sera prérempli avec soit l'ID perso précédemment assigné, soit l'ID DomiFa par défaut
- [x] aussi remettre les 5 dernières fiches disponibles, comme pour une validation de première demande
- [x] ainsi la structure peut garder le même ID, le changer ou ne rien mettre

Cas d'un refusé ou d'un radié avec un ID perso qui souhaite faire une nouvelle demande
- [x] dans ces deux cas, suite au ticket https://github.com/SocialGouv/domifa/issues/1812, les demandes seront des premières demandes par défaut donc se référer au processus d'une demande normale à valider

Sur la fiche domicilié
- [x] garder l'ID perso sur le bandeau bleu en haut de fiche
- [x] garder la référence dossier sur la vue d'ensemble
- [x] garder le champ dans la section dossier

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] valider une demande de domiciliation
- [x] tester les dates de début et de fin
- [x] vérifier les 5 derniers ID perso affichés
- [x] refuser une demande de domiciliation
- [x] faire un renouvellement
- [x] faire une nouvelle demande suite à un refus
- [x] faire une nouvelle demande suite à une radiation

**Comment by pYassine** [comment]
@ledugong  pour ce point " l'ID est donc remis à zéro (en cas de refus pas de souci car ya pas d'ID, en cas de radiation elle annule l'ID perso)"

Actuellement, le système ne permet pas de faire ça. Etant donné qu'on réutilise la même fiche pour garder l'historique, on reprend le même ID qu'avant.

**Comment by ledugong** [comment]
- [ ] corriger la phrase pour "Veuillez indiquer la date de début de la domiciliation."
![Capture d’écran 2021-11-16 à 13 43 38](https://user-images.githubusercontent.com/59437305/141987306-04363f47-a81e-41c8-9dec-a4fb3e530070.png)

**Comment by ledugong** [comment]
@pYassine

- [ ] la date de fin de domiciliation, c'est un an moins un jour. ça se met à jour si je change de date mais pas pour la date affichée par défaut.
<img width="628" alt="Capture d’écran 2021-11-22 à 08 48 02" src="https://user-images.githubusercontent.com/59437305/142822776-f5f31ab8-ca9c-4753-88a2-56fff9e1c0ca.png">

Cette histoire de dossier "à compléter", en fait il apparaitra dans la liste mais pas par rapport à la date de validation de demande de domiciliation, par rapport à la création de la demande. Donc si le dossier a été crée ya longtemps et qu'entre temps plus de 5 demandes ont été validées, il n'apparaitra pas dans la liste des derniers IDs une fois validé.

**Comment by pYassine** [comment]
@ledugong  
https://domifa-feat-correction-pre-mep.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK
