### ISSUE TITLE
feat(MESSAGE_NAVIGATEUR): en cas de navigateur /version non gérés, ajouter un bandeau + FAQ

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1829]
**Situation Actuelle**

Plusieurs structures se retrouvent face à un DomiFa très laid car le navigateur ou la version n'est pas géré. Il faudrait afficher un bandeau message pour annoncer à la structure que ce DomiFa n'est pas optimale et qu'elle doit passer sur autre chose.

**Comportement souhaité**

- [x] établir la liste des navigateurs et versions gérés par DomiFa
- [x] ajouter cette liste dans la FAQ : https://domifa.fabrique.social.gouv.fr/faq
Dans la section "L’inscription", sous la question "Y a-t-il un logiciel à installer préalablement ?"
, ajouter "Sous quel navigateur faut-il utiliser DomiFa ?" avec la liste.
![Capture d’écran 2021-11-01 à 15 17 03](https://user-images.githubusercontent.com/59437305/139686174-073a2066-2b4b-4740-8617-ab4879b04318.png)
- [x] si on arrive sur un DomiFa pas géré, afficher un bandeau rouge en haut de page avec le message
"DomiFa n'est pas accessible sous ce navigateur / cette version, merci de changer en vous référant à la liste disponible sur notre FAQ : https://domifa.fabrique.social.gouv.fr/faq"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester des navigateurs valides
- [x] tester des navigateurs non valides
- [x] tester des versions valides
- [x] tester des versions non valides

**Comment by pYassine** [comment]
@pibouu  j'ai pas trouvé dans le code où c'était. Est-ce que c'est dans un branche qui a pas été pushée par hasard :) ?

**Comment by pibouu** [comment]
Tester sur toutes les dernières version de Chrome, Firefox, Opéra et Safari. Tout marche très bien.

**Comment by pibouu** [comment]
https://domifa-1829-faq-browsers.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pibouu 

- [ ] on écrit "DomiFa" et non Domifa, tu peux corriger ? 
<img width="956" alt="Capture d’écran 2021-12-09 à 11 19 52" src="https://user-images.githubusercontent.com/59437305/145378232-a57491f6-c4ba-4ee7-9c77-c2adb02e608d.png">

**Comment by ledugong** [comment]
À voir en production

**Comment by ledugong** [comment]
Message FAQ OK en prod
Nouveaux tickets crées par la suite : https://github.com/SocialGouv/domifa/issues/1968 et https://github.com/SocialGouv/domifa/issues/1975
