### ISSUE TITLE
bug: fix k8s env data init 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1838]
**Description du problème**

Les données ne sont pas correctemetn initialisées sur les environnements de PR.

**Comportement attendu**

Les données sont initialisées, et il est possible de faire des modifications.

Après dépoiement d'une nouvelle version, la base est de nouveau ré-initialisée.

**Recette PO**

Les données sont initialisées, et il est possible

- [x] de se connecter
- [x] de visualiser les users existant
- [x] de créer un user
- [x] de créer une structure

De plus, après re-déploiement de la branche

- [x] les données ont été restaurées (les modifications faites dans la partie précédente ne sont plus présentes)

**Comment by Toub** [comment]
A tester ici: 

- https://domifa-toub-sec-backend-ameliorer-la-secu-sur-l-image-b-l483t3.dev.fabrique.social.gouv.fr
- https://mon-domifa-domifa-toub-sec-backend-ameliorer-la-secu-sur-l-imag.dev.fabrique.social.gouv.fr

**Comment by ledugong** [comment]
En attente que les liens refonctionnent

**Comment by ledugong** [comment]
Non recettable PO au final

**Comment by ledugong** [comment]
Non recettable prod
