### ISSUE TITLE
feat(NOTIFS_SMS): notification SMS 2 mois avant l'échéance de domiciliation

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1850]
**Situation Actuelle**

Maintenant qu'on a diminué la périodicité des notifications SMS en cas de réception d'un courrier, il est temps de s'attaquer au nouveau template : l'échéance de domiciliation.

**Comportement souhaité**

- [x] mise en place du template
"Bonjour, 

Votre domiciliation expire dans 2 mois, nous vous invitons à vous rendre dans votre structure.

XXXX"

- [x] envoi à date de fin de domiciliation - 2 mois à 19h
Si expiration le 12/08, envoyer le SMS le 12/06 à 19h
Prévoir le cas des 30 et 31 du mois, si expiration le 31/08, envoyer le SMS le 30/06 (car le 31 n'existe pas) à 19h

- [x] sur l'étape 1 de la création de demande de dom, modifier la question pour "Le demandeur souhaite-t-il recevoir des notifications par SMS (arrivée d'un courrier, échéance de domiciliation) ?"
<img width="440" alt="Capture d’écran 2021-11-03 à 18 17 25" src="https://user-images.githubusercontent.com/59437305/140142041-a99e4926-625c-4e88-b294-9a6abe7160aa.png">

- [x] sur la fiche domicilié, dans la section "Courriers", modifier la question pour "Le demandeur souhaite-t-il recevoir des notifications par SMS (arrivée d'un courrier, échéance de domiciliation) ?"
<img width="1186" alt="Capture d’écran 2021-11-03 à 18 19 51" src="https://user-images.githubusercontent.com/59437305/140145268-a52b3fb6-e26e-4b94-92a4-a441efa4d610.png">

- [x] sur la fiche domicilié, dans la section "Historique", remettre le titre "Historique des envois de SMS" et en-dessous mettre 2 bullets points : 
" - pour l'arrivée d'un courrier, envoi les mardis et jeudis à 19h
   - pour le rappel d'échéance de domiciliation, envoi 2 mois avant la date de fin"
<img width="1140" alt="Capture d’écran 2021-11-03 à 18 21 12" src="https://user-images.githubusercontent.com/59437305/140147016-5d2e9eb7-c221-456b-9576-f42945fcdcc6.png">

- [x] relier Spothit et DomiFa pour activer l'envoi

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] tester les notifications de réception de courrier
- [ ] tester les notifications d'échéance de dom

**Comment by pibouu** [comment]
L'URL pour tester la feature 	
https://domifa-1850-notif-sms-end-dom.dev.fabrique.social.gouv.fr/connexion

**Comment by pibouu** [comment]
https://domifa-1850-feedback-notif-end-dom.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pibouu 
Petite question sur le fonctionnement au niveau de l'historique : https://domifa-1850-feedback-notif-end-dom.dev.fabrique.social.gouv.fr/profil/historique/5 

A quel moment le sms de rappel d'échéance va apparaitre comme "en attente d'envoi" ? Comme lorsque on reçoit du courrier, des SMS d'envoi se mettent automatiquement dans l'historique avec écrit "envoi prévu".
Est-ce que tous les soirs on calcule ceux qui seront envoyés le lendemain ?

**Comment by pibouu** [comment]
Les SMS seront en attente pendant 1h environ.
Tous les soirs à 18h nous crée les SMS à envoyer.
Puis tous les soirs à 19h, ils sont envoyés.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
En attente de recette en prod

**Comment by ledugong** [comment]
Recette Prod OK
