### ISSUE TITLE
feat(courriers personnalisés): terminer l'ajout de courriers personnalisés

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1875]
**Description du problème**

**Lien de la préprod : https://domifa-feat-docs-custom.dev.fabrique.social.gouv.fr/**

**Comportement attendu**

**Attestation postale** 

- [x] Par défaut, je peux télécharger une attestation postale complétée par Domifa
- [x] ETQ structure, je peux télécharger un modèle de courrier
- [x] ETQ structure, je peux uploader une nouvelle attestation postale
- [x] Quand je clique sur télécharger l'attestation, je télécharge la nouvelle attestation complétée par Domifa

**Courrier de radiation** 

- [x] Par défaut, je peux télécharger une attestation postale complétée par Domifa
- [x] ETQ structure, je peux télécharger un modèle de courrier
- [x] ETQ structure, je peux uploader un nouveau courrier de radiation
- [x] Quand je clique sur télécharger le courrier de radiation, je télécharge le nouveau courrier complété par Domifa

**Autres documents pré-remplis** 
- [x] ETQ structure, je peux uploader un autre type de document
- [x] Le document apparait dans le dossier d'un usager
- [x] Quand je le télécharge, les variables du document sont complétés, le format du word d'origine est respecté

**Autres documents statiques**
- [x] Je peux uploader / télécharger / supprimer un document

**Comment by ledugong** [comment]
@pYassine pourquoi ya une ligne en gras ? 
<img width="1239" alt="Capture d’écran 2021-11-22 à 10 20 25" src="https://user-images.githubusercontent.com/59437305/142835167-01770076-d0b0-4c73-85db-26157dc372b5.png">

**Comment by pYassine** [comment]
@ledugong la ligne en gras met en avant les docs importants de Domifa. Attestation et courrier de radiation

**Comment by ledugong** [comment]
@pYassine du coup je suis perdue là, va falloir qu'en parle demain, je mets le doc explicatif en pause

**Comment by pYassine** [comment]
@ledugong attestation postale et courrier de radiation sont toujours proposés selon le statut du domicilié
Je les ai mis en gras pour les mettre en avant si y'a plein de documents, c'est plus visible. Après c'est pas forcément une bonne idée

En gros attestation et courrier radiation sont ceux qu'on propose chez Domifa par défaut. S'ils sont remplacés par la structure, on utilise leur modèle à eux.

**Comment by pYassine** [comment]
Section docs personnalisable masquée, retours corrigés 
@ledugong  
https://domifa-feat-correction-pre-mep.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette ici : https://domifa-feat-review-docs.dev.fabrique.social.gouv.fr/structures/documents

**Comment by ledugong** [comment]
@pYassine 

- [ ] les colonnes sont échangées
<img width="370" alt="Capture d’écran 2021-12-07 à 10 40 41" src="https://user-images.githubusercontent.com/59437305/145004999-6c78640d-025a-47c6-be8e-d04f9359aece.png">

**Comment by ledugong** [comment]
@pYassine 

- [ ] le nom que je mets sur la pop-up n'est pas le nom qui s'affiche dans la liste
![Capture d’écran 2021-12-13 à 14 31 50](https://user-images.githubusercontent.com/59437305/145821644-0d475da4-da82-438f-bfc1-d357ee99ae9c.png)
![Capture d’écran 2021-12-13 à 14 32 12](https://user-images.githubusercontent.com/59437305/145821716-78f65060-c729-4237-af84-d05c64d35569.png)

- [ ] si je veux supprimer le fichier, je cliquer sur "supprimer", un message de confirmation apparait mais rien ne change. Et si je reclique, je vois le message "impossible de télécharger"
![Capture d’écran 2021-12-13 à 14 33 27](https://user-images.githubusercontent.com/59437305/145821760-e3d57942-2f45-4f7d-8ad3-e752daf9ee46.png)

**Comment by ledugong** [comment]
@pYassine en tant que gestionnaire je ne peux plus du tout accéder à la sections Documents alors que je dois pouvoir voir les documents internes et pouvoir les télécharger.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK (malgré quelques corrections à passer après : https://github.com/SocialGouv/domifa/issues/1960)
