### ISSUE TITLE
feat(REFUS): ajouter une option "Autre" dans l'orientation proposée

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1882]
**Situation Actuelle**

Dans la pop-up de refus actuelle, il n'y a que 2 options dans "orientation proposée", ce qui ne prend pas en compte plusieurs cas (Par exemple lorsqu’on refuse une domiciliation pour motif que la personne dispose déjà d’une adresse stable chez un particulier : si nous disposons la possibilité de sélectionner AUTRE ORIENTATION avec un espace d’écriture afin de pouvoir écrire « conserver l’adresse actuellement utilisée »).

**Comportement souhaité**

![Capture d’écran 2021-11-20 à 11 17 00](https://user-images.githubusercontent.com/59437305/142722748-83bea720-428f-49d4-a472-5ef0e2fb9c2a.png)

- [x] dans "orientation proposée", ajouter une réponse "Autre"
- [x] garder le champ "Précisez", ce qui permettra aux structures d'entrer des détails aussi pour l'option "Autre"
- [x] ajouter l'option "Autre" dans les statistiques de refus
- [x] rien ne change sur la fiche domicilié car seulement le motif apparait
- [x] rien ne change sur le cerfa car seulement le motif et le champ "précisez" apparaissent

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester les 3 orientations possibles
- [x] tester le champ "précisez" dans les 3 cas
- [x] vérifier les stats de refus

**Comment by pibouu** [comment]
https://domifa-1882-modal-deny-dom.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette Prod OK
