### ISSUE TITLE
feat(test): amélioration du jeu de données de test

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#1894]
**Situation Actuelle**

Le jeu de données de test est incomplet.

**Comportement souhaité**

Avoir par défaut, dans la structure 1:

- [x] 1 utilisateur de chaque profil
- [x] 2 domiciliés dans chaque statut 

**Recette PO**

- [x] les données demandées sont bien présentes

**Comment by ledugong** [comment]
@Toub 

- [ ] pourquoi on parle de "simple" et "responsable" et pas "instructeur" et "gestionnaire" pour rester homogène ?
<img width="657" alt="Capture d’écran 2021-12-06 à 11 17 43" src="https://user-images.githubusercontent.com/59437305/144828786-441793a1-09a6-4173-a2f1-93965342f36d.png">

- [ ] est-ce qu'il y a une page GitHub avec les jeux de données que je pourrais garder, pour m'en souvenir ?

**Comment by Toub** [comment]
![image](https://user-images.githubusercontent.com/367762/144856703-12311dc5-8f5e-4e53-afbb-c2b41cf7a2c7.png)

>  est-ce qu'il y a une page GitHub avec les jeux de données que je pourrais garder, pour m'en souvenir ?

![image](https://user-images.githubusercontent.com/367762/144857978-77477f95-09be-433c-a93a-139f21e3338d.png)

Je te fournirai le lien définitif après le merge de la PR.

**Comment by Toub** [comment]
Pour le test:
- voici la documentation (URL temporaire, je te fournirai l'autre une fois mergé): https://github.com/SocialGouv/domifa/blob/274e9e4a47d505c2b1f9a1439ab328bf25399e96/_docs/dev/31_tests-users.md
- environnement: https://domifa-toub-feat-test-amelioration-jeu-donnee-q81zs9.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@Toub tests faits avec les comptes ici https://github.com/SocialGouv/domifa/blob/274e9e4a47d505c2b1f9a1439ab328bf25399e96/_docs/dev/31_tests-users.md sur le lien https://domifa-toub-feat-test-amelioration-jeu-donnee-q81zs9.dev.fabrique.social.gouv.fr/

- [ ] Sur la structure s1, est-ce que je peux avoir 2 domiciliés dans chaque onglet ? Actif, A compléter, En attente de décision etc.

- [ ] Structure 3, le compte s3-gestionnaire@yopmail.com ne fonctionne pas
![Capture d’écran 2021-12-06 à 15 51 56](https://user-images.githubusercontent.com/59437305/144867492-f70ab456-cc02-4760-bd47-1786a62a9756.png)

**Comment by Toub** [comment]
J'ai fusionné ces modifications avec la PR de changement de mot de passe, car elle intervenait aussi sur cette base: https://github.com/SocialGouv/domifa/pull/1914

A tester désormais ici avec les dernières corrections: https://domifa-toub-feat-int-dom-forcer-le-changement-37t2xa.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@Toub

- [ ] compte s3-facteur@yopmail.com ne fonctionne pas
![Capture d’écran 2021-12-06 à 16 41 28](https://user-images.githubusercontent.com/59437305/144876084-4644279b-595f-4e4b-98fa-bdbabbad4c2e.png)

**Comment by Toub** [comment]
Corrigé

**Comment by ledugong** [comment]
Recette PO OK
