### ISSUE TITLE
bug(POPUP): pop-up maintenance apparait en production

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1918]
**Description du problème**

La pop-up de maintenance apparait en production sans mise en prod ou autre.

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] pop-up de maintenance n'apparait plus sans raison

**Comment by Toub** [comment]
Plus de problème depuis la dernière mise en prod, on peut fermer ce ticket @ledugong

**Comment by ledugong** [comment]
Ok
