### ISSUE TITLE
feat(POP_UP_VALIDATION): permettre une dom de moins de 1 an + phrase de prévention

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1934]
**Situation Actuelle**

Suite au ticket https://github.com/SocialGouv/domifa/issues/1826, il faut rendre possible une domiciliation à moins de un an.

**Comportement souhaité**

Sur la pop-up de validation d'une demande de dom : 
- [x] garder la date de fin automatiquement à un an moins un jour
- [x] cependant, permettre le changement de la date de fin si celle-ci est antérieure à un an moins un jour
- [x] si je met une date de fin antérieure à un an moins un jour, afficher une phrase de prévention sous les champs dates de ce style <img width="459" alt="Capture d’écran 2021-12-06 à 10 56 00" src="https://user-images.githubusercontent.com/59437305/144825669-f747b5c5-2e62-4891-b894-7eed285c12d3.png"> avec la phrase
" D'après la réglementation, une attestation de domiciliation doit être valable pendant un an."
- [x] si je mets une date de fin "correcte" à un an moins un jour, le message de prévention ne s'affiche pas

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier que la date de fin s'affiche automatiquement à un an moins un jour par défaut
- [x] vérifier qu'il est possible de mettre une date antérieure
- [x] vérifier qu'il n'est pas possible de mettre une date après un an
- [x] vérifier l'apparition du message de prévention
- [x] vérifier le wording du message de prévention

**Comment by pibouu** [comment]
https://domifa-1934-less-1year-dom.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pibouu 

- [ ] yaura moyen de faire tenir la phrase sur une seule ligne en diminuant la taille ?
<img width="643" alt="Capture d’écran 2021-12-09 à 11 11 43" src="https://user-images.githubusercontent.com/59437305/145376957-38d90c43-d669-4d35-a679-e097e90d1174.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
