### ISSUE TITLE
feat(ACCES): ajouter le doc officiel de l'audit dans le footer

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1956]
**Situation Actuelle**

Suite à l'audit, ils nous ont envoyé un document qu'il faut officiellement mettre à disposition. 

**Comportement souhaité**

Sur la Homepage, dans le footer :
<img width="1179" alt="Capture d’écran 2021-12-14 à 14 15 46" src="https://user-images.githubusercontent.com/59437305/146005302-d229f25a-0274-486e-8028-0024428c91c0.png">

- [x] rendre la mention "Accessibilité: non conforme" cliquable
- [x] en cliquant dessus, télécharger le document ci-dessous
[domifa_declaration-d-accessibilite.pdf](https://github.com/SocialGouv/domifa/files/7711866/domifa_declaration-d-accessibilite.pdf)

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester le footer
- [x] vérifier le document

**Comment by pibouu** [comment]
https://domifa-1956-doc-accessbilite.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
