### ISSUE TITLE
bug(STATS): manque un label sur une statistique

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1957]
**Description du problème**

![image](https://user-images.githubusercontent.com/59437305/146008823-577909db-cb49-439e-a37e-5ec54b3d8586.png)

**Comportement attendu**

- [x] remettre le label

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier le label

**Comment by pibouu** [comment]
https://domifa-1957-missing-label-stats.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pibouu sans trait d'union 😛 (je viens de l'apprendre hein)
https://www.larousse.fr/dictionnaires/francais/ayant_droit/7205

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
