### ISSUE TITLE
feat(COURRIERS_PERSOS): corrections courriers sur la fiche domicilié

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1960]
**Situation Actuelle**

Si je mets une attestation postale personnalisée au sein de ma structure, l'ancienne attestation postale (celle proposée par défaut par DomiFa) est toujours visible, ce qui rend le truc bien complexe.
<img width="1181" alt="Capture d’écran 2021-12-14 à 16 07 09" src="https://user-images.githubusercontent.com/59437305/146024584-cb1215e8-660a-4e62-95a9-cc0bcf0a35d0.png">

Pour le courrier de radiation, il apparait sur des fiches de domiciliés actifs.

**Comportement souhaité**

ATTESTATION POSTALE
- [x] Déjà, si j'ajoute une nouvelle attestation postale, écrire "Attestation postale" dans le nom du document et non "attestation_postale" sur la fiche domicilié
- [x] Si j'ajoute une nouvelle attestation postale, faire en sorte qu'elle remplace l'attestation postale par défaut de DomiFa
- [x] Par contre, si je décide de supprimer cette attestation postale personnalisée, remettre automatiquement l'attestation postale par défaut de DomiFa

COURRIER DE RADIATION

- [x] Déjà, si j'ajoute un nouveau courrier de radiation, écrire "Courrier de radiation" dans le nom du document et non "courrier_radiation" sur la fiche domicilié
- [x] Afficher ce courrier seulement chez les radiés

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier attestation postale
- [x] vérifier courrier de radiation

**Comment by pYassine** [comment]
Test des docs : 
https://domifa-fix-mep-12-12.dev.fabrique.social.gouv.fr/profil/documents/4

J'ai créer un courrier de radiation personnalisé 


@ledugong

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
