### ISSUE TITLE
feat(SUPPORT): création du formulaire de contact + mail automatique à l'équipe

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1964]
**Situation Actuelle**

Au lieu de donner une adresse de contact, on va créer un formulaire de support simple, ce qui nous permettra d'avoir plus d'informations avant de répondre.

**Comportement souhaité**

- [x] créer la page https://domifa.fabrique.social.gouv.fr/contact

- [x] reprendre le template ci-dessous avec le bandeau bleu (écrire "Formulaire de contact") et la section blanche sur fond gris
<img width="1277" alt="Capture d’écran 2021-12-15 à 15 11 06" src="https://user-images.githubusercontent.com/59437305/146201827-4ebc034f-bf7d-419c-a638-ea863806e4b7.png">

- [x] mettre la phrase en haut de page "Un problème ? Une suggestion ? Avez-vous consulté notre FAQ ? Si la réponse ne s'y trouve pas, merci de remplir les champs ci-dessous en nous donnant un maximum d'informations, ce qui nous permettra de vous répondre plus rapidement." avec le "notre FAQ" qui dirige vers https://domifa.fabrique.social.gouv.fr/faq
<img width="1165" alt="Capture d’écran 2021-12-15 à 15 13 03" src="https://user-images.githubusercontent.com/59437305/146202144-1f22a75c-cfce-4a16-a382-4b23716906ae.png">

- [x] pour les champs à remplir, se référer au type form https://startupdetat.typeform.com/to/eaTp1XB1 
ATTENTION ya des liens entre les questions, bien regarder, idéalement afficher les champs un par un (demander les accès à Lala)

- [x] préremplir les champs "nom de la structure" et "adresse mail" avec les informations sur la personne est connectée (mais lui permettre de modifier les champs)

- [x] une fois le document validé, afficher un message de confirmation "Votre demande a bien été envoyée à l'équipe DomiFa."

- [x] envoyer un mail à contact.domifa avec les champs et leurs réponses (pas la peine de faire un truc élaboré, c'est un mail interne, juste reprendre le template des autres mails et voilà)

- [x] stocker les entrées du formulaire côté BDD du back-office pour de futurs tickets d'affichage et suivi des tickets en BO

- [x] changer le texte de la pop-up : enlever l'adresse mail et écrire "Contactez-nous via notre formulaire de contact" avec le "notre formulaire de contact" qui dirige vers notre page contact.
<img width="568" alt="Capture d’écran 2021-12-15 à 15 01 17" src="https://user-images.githubusercontent.com/59437305/146200578-c47f9bde-98a4-4864-87ea-b8745db73013.png">

- [x] dans la FAQ, changer la phrase surinée pour "Si vous ne trouvez pas de réponse dans notre guide, merci de consulter les sections ci-dessous ou bien contactez-nous via notre formulaire de contact." avec le "notre formulaire de contact" qui dirige vers notre page contact.
<img width="1095" alt="Capture d’écran 2021-12-15 à 15 09 06" src="https://user-images.githubusercontent.com/59437305/146201499-06779fb2-bed5-4746-a12b-78eb56ebf684.png">

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier l'URL de la page
- [x] vérifier le wording de la page
- [x] tester les champs du formulaire
- [x] vérifier le texte de la FAQ
- [x] vérifier le texte de la pop-up
- [x] vérifier le mail reçu sur contact.domifa

**Comment by ledugong** [comment]
@pYassine 

- [ ] mettre un point à la fin de la phrase.
<img width="1207" alt="Capture d’écran 2022-01-27 à 18 35 48" src="https://user-images.githubusercontent.com/59437305/151412911-bbec9f07-badd-4279-99b3-477decf278a3.png">

- [ ] ajouter le champ "nom de la structure" que si la personne a cliqué "oui" dans "avez-vous un compte sur DomiFa?"
<img width="840" alt="Capture d’écran 2022-01-27 à 18 37 13" src="https://user-images.githubusercontent.com/59437305/151413169-aa835019-4bf8-4d41-b34b-4e87de39fdf6.png">

- [ ] le titre d'onglet n'est pas le bon
<img width="635" alt="Capture d’écran 2022-01-27 à 18 38 10" src="https://user-images.githubusercontent.com/59437305/151413334-4989ab44-7f83-471b-9717-0d3cab0bccda.png">

- [ ] corriger "message"
<img width="659" alt="Capture d’écran 2022-01-27 à 18 39 03" src="https://user-images.githubusercontent.com/59437305/151413477-d0adb141-d614-498d-b3a1-84260a6be49a.png">

- [ ] les champs sont préremplis au lieu d'avoir le texte en fond grisé
<img width="860" alt="Capture d’écran 2022-01-27 à 18 42 35" src="https://user-images.githubusercontent.com/59437305/151414057-5fb7dafe-231d-4e21-8b2d-ba663d6b2030.png">

**Comment by ledugong** [comment]
@pYassine 

- [ ] les champs sont toujours préremplis au lieu d'avoir le texte en fond grisé. Il faut proposer les champs vides avec "accueil.social@test.fr" en filigrane, comme dans le champ "Votre message".

**Comment by ledugong** [comment]
Mettre le champ "Votre nom" et "Le nom de votre structure" dans tous les cas.
Préremplir le champ nom avec celui de la personne connectée.
Préremplir le champ adresse mail avec celui de la personne connectée.

**Comment by pYassine** [comment]
https://domifa-fix-portail-usager-activation.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 
Sur la PP, en cliquant sur OUI dans la première question, j'ai un NON qui apparait sur le mail.
Et j'avais mis "ma structure" dans le nom de la structure et il n'apparait pas sur le mail.
<img width="606" alt="Capture d’écran 2022-02-10 à 09 26 47" src="https://user-images.githubusercontent.com/59437305/153367336-444dced3-f216-4589-8264-bb04b375ea5c.png">

**Comment by ledugong** [comment]
@pYassine 

Au final la question structure existante OUI / NON se met à jour en fonction de si la personne est connectée ou pas.
Non connectée = structure existante à non et les champs ne sont pas préremplis
Connectée = structure existante à oui et les champs sont préremplis

Du coup retirer la question structure existante du formulaire MAIS le garder dans le mail envoyé au support.

**Comment by ledugong** [comment]
Recette Prod OK
