### ISSUE TITLE
bug(IE): écran IE blanc

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1968]
**Description du problème**

Description du problème

**Comportement attendu**

Description du comportement souhaité

- [ ] action 1
- [ ] action 2...

**Scénario de reproduction du problème**

1. Se connecter en tant que '...'
2. Aller sur la page '....'
3. Cliquer sur '....'
4. Le ... est incorrect

**Copies d'écran**

**Informations complémentaires:**

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] test 1
- [ ] test 2...

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pibouu** [comment]
https://domifa-1968-fix-ie-white-screen-35jiaa.dev.fabrique.social.gouv.fr/ à tester sur IE

**Comment by ledugong** [comment]
Après investigation, on est passé à angular v13 et cette version ne supporte plus IE donc la bannière ne peut pas s'afficher car tout le site ne se charge pas. Après discussion, la solution serait de créer une autre page et quand on détecte ce navigateur il redirige vers la nouvelle page qui dit de passer à un navigateur plus récent.
Nouveau ticket : https://github.com/SocialGouv/domifa/issues/1975
