### ISSUE TITLE
feat(RGAA): Images 1.1 - Chaque image porteuse d'information a-t-elle une alternative textuelle ?

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1973]
▶️▶️▶️▶️  **https://domifa-1973-rgaa-images.dev.fabrique.social.gouv.fr/**

**Situation Actuelle**

Au moins une image porteuse d'information n'a pas d'alternative textuelle.
Par exemple :
- Les images de checkmarks dans le tableau des rôles utilisateurs.

**Comportement souhaité**

Corrections :
**Implémenter des <title>Oui</title> à l'intérieur des balises <svg> ; Supprimer les propriétés aria-hidden="true" et ajouter des propriétés aria-labelledby="[id-title]".**
OU garder les aria-hidden="true" sur les images <svg> et implémenter des textes cachés hors écran avant ou après celles-ci : <span class="sr-only">Oui</span>.

- [x] Aller voir le PDF de l'audit pour avoir plus d'informations

- [x] Homepage et header --> logo DomiFa : <title>DomiFa</title>

Homepage dans la section "ces structures nous font confiance" -->
- [x] Logo samusocial paris : <title>Samu Social Paris </title>
- [x] Logo CCAS Clermont : <title>CCAS Clermont-Ferrand</title>
- [x] Logo Le Havre : <title>CCAS Le Havre</title>
- [x] Logo Aurore : <title>CCAS Le Havre</title>
- [x] Logo Annecy : <title>Association Aurore</title>

FAQ https://domifa.fabrique.social.gouv.fr/faq 
- [x] Bouton guide utilisateur : <title>Téléchargez le guide utilisateur</title>
- [x] Boutons sections FAQ : <title>La domiciliation</title>, <title>Le projet DomiFa</title>, etc.
- [x] Bouton du centre d'aide en bas à droite : <title>Centre d'aide</title>
<img width="108" alt="Capture d’écran 2021-12-20 à 18 18 55" src="https://user-images.githubusercontent.com/59437305/146806681-7b08db53-63d3-482f-ae17-b36f12192ed9.png">

Liste des domiciliés
- [x] Barre de recherche, si j'écris quelque chose dedans, un logo avec une croix apparait pour réinitialiser la recherche : <title>Réinitialiser la recherche</title>
<img width="439" alt="Capture d’écran 2021-12-20 à 17 57 06" src="https://user-images.githubusercontent.com/59437305/146803939-b166cf9b-5efc-431c-a5c7-d99963e76b04.png">

- [x] Icône impression : <title>Impression</title>
<img width="1125" alt="Capture d’écran 2021-12-20 à 17 58 24" src="https://user-images.githubusercontent.com/59437305/146804138-59411565-6fd9-4bd9-8f3f-24aa96a7b18c.png">

- [x] Icônes tri croissant / décroissant : <title>Tri croissant</title> et <title>Tri décroissant</title>
<img width="228" alt="Capture d’écran 2021-12-20 à 18 02 30" src="https://user-images.githubusercontent.com/59437305/146804654-cfe873c7-172f-40f2-9139-4aacbc3d9b7a.png">

Pastille de couleur colonne échéance
- [x] Pastille orange : <title>Moins de 2 mois</title>
- [x] Pastille rouge : <title>Moins de 2 semaines ou dépassée</title>
<img width="138" alt="Capture d’écran 2021-12-20 à 18 15 25" src="https://user-images.githubusercontent.com/59437305/146806239-48159170-fe5a-4063-852b-39285d8a3fec.png">

- [x] La croix sur les filtres : <title>Réinitialiser le filtre</title>
<img width="781" alt="Capture d’écran 2021-12-20 à 18 17 38" src="https://user-images.githubusercontent.com/59437305/146806497-6a4eae11-1bff-4067-ae04-08b749e77d85.png">

Sur la fiche domicilié
- [x] Icône en cas de message important sur le domicilié : <title>Important</title>
<img width="703" alt="Capture d’écran 2021-12-20 à 18 20 51" src="https://user-images.githubusercontent.com/59437305/146806897-6c0b263c-90be-49b1-b718-9a5d0d6bdce4.png">

Page utilisateurs
- [x] Icône de suppression : <title>Supprimer</title>
<img width="1197" alt="Capture d’écran 2021-12-20 à 18 22 25" src="https://user-images.githubusercontent.com/59437305/146807112-d81d0c42-9440-4982-ae18-0adf27e920b7.png">

- [x] Tableau des profils et accès, la checkbox : <title>Oui</title>

<img width="397" alt="Capture d’écran 2021-12-20 à 18 30 31" src="https://user-images.githubusercontent.com/59437305/146808114-a741decd-23ad-4a0c-a486-678bf36d39bc.png">

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Homepage et header --> logo DomiFa : <title>DomiFa</title>

Homepage dans la section "ces structures nous font confiance" -->
- [x] Logo samusocial paris : <title>Samu Social Paris </title>
- [x] Logo CCAS Clermont : <title>CCAS Clermont-Ferrand</title>
- [x] Logo Le Havre : <title>CCAS Le Havre</title>
- [x] Logo Aurore : <title>CCAS Le Havre</title>
- [x] Logo Annecy : <title>Association Aurore</title>

FAQ https://domifa.fabrique.social.gouv.fr/faq 
- [x] Bouton guide utilisateur : <title>Téléchargez le guide utilisateur</title>
- [x] Boutons sections FAQ : <title>La domiciliation</title>, <title>Le projet DomiFa</title>, etc.
- [x] Bouton du centre d'aide en bas à droite : <title>Centre d'aide</title>

Liste des domiciliés
- [x] Barre de recherche, si j'écris quelque chose dedans, un logo avec une croix apparait pour réinitialiser la recherche : <title>Réinitialiser la recherche</title>
- [x] Icône impression : <title>Impression</title>
- [x] Icônes tri croissant / décroissant : <title>Tri croissant</title> et <title>Tri décroissant</title>
Pastille de couleur colonne échéance
- [x] Pastille orange : <title>Moins de 2 mois</title>
- [x] Pastille rouge : <title>Moins de 2 semaines ou dépassée</title>
- [x] La croix sur les filtres : <title>Réinitialiser le filtre</title>

Sur la fiche domicilié
- [x] Icône en cas de message important sur le domicilié : <title>Important</title>

Page utilisateurs
- [x] Icône de suppression : <title>Supprimer</title>
- [x] Tableau des profils et accès, la checkbox : <title>Oui</title>✅▶️

**Comment by pYassine** [comment]
@ledugong  https://domifa-1973-rgaa-images.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pibouu 

Il manque des titres j'ai l'impression 
 
FAQ https://domifa.fabrique.social.gouv.fr/faq
- [ ] Bouton guide utilisateur : <title>Téléchargez le guide utilisateur</title>
- [ ] Boutons sections FAQ : <title>La domiciliation</title>, <title>Le projet DomiFa</title>, etc.

- [ ] Icône impression : <title>Impression</title>

- [ ] Icône en cas de message important sur le domicilié : <title>Important</title>

**Comment by ledugong** [comment]
@pibouu 

- [ ]  Icône impression sur la liste des domiciliés : <title>Impression</title>

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
