### ISSUE TITLE
feat(RGAA): module création d'une demande de domiciliation

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1976]
** ▶️  ▶️ Lien de test : https://domifa-feat-dossier-access.dev.fabrique.social.gouv.fr/**

**Situation Actuelle**

Toutes les fonctionnalités développées avec JavaScript doivent être utilisables au clavier qui est un mode 
d'utilisation très répandu parmi les personnes en situation de handicap, notamment les personnes aveugles et les 
personnes handicapées motrices. 
Lorsque l'élément qui déclenche une fonctionnalité est un élément nativement interactif ou qu'il fait partie d'un 
composant qui utilise un motif de conception ARIA, la fonctionnalité est utilisable au clavier. 
Dans le cas inverse il sera nécessaire de rendre l'élément interactif, c’est-à-dire capable de recevoir le focus de 
tabulation, au moyen de l'attribut tabindex="0". 
Certaines pages contiennent des éléments qui déclenchent des fonctionnalités, mais qui ne sont pas utilisables 
au clavier. 

**Comportement souhaité**

- [x] Aller voir le PDF de l'audit pour avoir plus d'informations et le doc https://www.notion.so/fabnummas/Accessibilit-7ca5939493af4c1f98bdd0143870da02 

- [x] Corriger la navigation au clavier sur le processus de création d'une demande de domiciliation
 La tooltip apparaît au survol uniquement, elle ne peut pas être affichée au clavier : utiliser un élément 
<button> autour de l’icône (?) ; 
Dans la partie "ayants-droit", les boutons de suppression et le bouton "Ajouter" ;
Boutons "Réaliser l'entretien maintenant" et "Modifier la date du rendez-vous" ;

Corrections :
Utiliser des liens <a>. Inclure le texte des étapes dans ces liens.
Utiliser des <button>.
Donner un intitulé au bouton au moyen d'un aria-label="info". La propriété aria-describedby ajoutée sur l'icône à l'affichage de la tooltip doit être déplacée sur ce bouton.
Donner des intitulés aux boutons de suppression au moyen d'attributs title reprenant les légendes de regroupements (voir 11.5), par exemple : "Supprimer ayant-droit 2".

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Tester la création d'une demande de domiciliation

**Comment by pYassine** [comment]
A tester :

Navigation au clavier sur toutes les étapes du formulaire
Champs à compléter bien paramétrés : tous les labels manquant ont été ajouté
Contraste : toutes les étapes du formulaire respectent les contrastes au niveau AA (sauf bandeaux alertes, qui seront corrigés asap)

Référence du tableau : P07 
3.2 ; 3.3 ; 5.4 ; 7.3

**Comment by ledugong** [comment]
@pYassine 

Recette sous Google Chrome

- [ ] Navigation au clavier sur toutes les étapes du formulaire

Etape 1 : avec la navigation clavier dans le bons sens, je ne passe pas par Madame.
Mais si j'inverse le sens de la navigation clavier, d'accède à Madame mais pas à Monsieur.
https://user-images.githubusercontent.com/59437305/149942975-49ac8f25-87e3-4b4a-80f8-15cf9d711143.mov

Etape 1 : pareil pour la partie AD, je n'ai pas accès aux deux réponses OUI / NON, seulement l'un ou l'autre en fonction du sens de la navigation clavier
https://user-images.githubusercontent.com/59437305/149943220-dc55fcaf-7464-4f56-ac0c-6589597d2f87.mov

- [ ] Champs à compléter bien paramétrés : tous les labels manquant ont été ajouté

- [ ] Contraste : toutes les étapes du formulaire respectent les contrastes au niveau AA (sauf bandeaux alertes, qui seront corrigés asap)

**Comment by pYassine** [comment]
Référence du tableau : P07
- 3.2
- 3.3
- 5.4
- 5.7
- 7.1
- 7.3
- 8.2
- 9.1
- 9.2 
- 11.1 
- 11.5
- 11.6
- 11.11

Accueil du site : P0
3.2 ; 10.3 ;

Connexion : P05
3.2

**Comment by pYassine** [comment]
https://domifa-refacto-bootstrap-frontend.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
