### ISSUE TITLE
feat(RGAA): Script 7.5 : Dans chaque page web, les messages de statut sont-ils correctement restitués par les technologies d'assistance ?

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1977]
**Situation Actuelle**

Au moins un message de statut n'est pas correctement restitué aux technologies d'assistance.
Par exemple :
- Les notifications qui apparaissent en haut de l'écran suite à une action (par exemple : ajout d'un passage/appel/courrier, ajout détaillé d'un courrier, distribution, ...)
Corrections :
- Pour les messages qui informent du résultat d'une action ou de l'état d'une application, ajouter le role="status".
- Pour les messages qui présentent une suggestion ou avertissent d'une erreur, ajouter le role="alert".

**Comportement souhaité**

- [x] Aller voir le PDF de l'audit pour avoir plus d'informations et le doc https://www.notion.so/fabnummas/Accessibilit-7ca5939493af4c1f98bdd0143870da02

- [x] Corriger les messages de statut sur DomiFa

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester une connexion (bon et mauvais mot de passe)
- [x] tester la création d'une structure
- [x] tester la création d'une demande de domiciliation
- [x] tester des ajouts d'interactions
- [x] tester la procuration / transfert
- [x] tester la modifications des notifications SMS / interface domicilié
- [x] tester l'import
- [x] tester un formulaire avec un champ non rempli (message d'erreur)
- [x] tester une validation de demande de domiciliation
- [x] tester un refus
- [x] tester une radiation

**Comment by ledugong** [comment]
Lien recette : https://domifa-feat-toast-rol.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

Safari

- [ ] Tous les messages sont énoncés en double
<img width="846" alt="Capture d’écran 2022-01-06 à 13 58 29" src="https://user-images.githubusercontent.com/59437305/148387214-4064c9eb-94fe-42cc-b722-c195dd2001b8.png">

- [ ] Tu peux mettre un vert plus foncé ? celui-là passera pas niveau accessibilité je pense
<img width="868" alt="Capture d’écran 2022-01-06 à 14 00 54" src="https://user-images.githubusercontent.com/59437305/148387122-7d66bae3-36b3-4a96-8227-513bce600daf.png">

- [ ] Quand j'enregistre du courrier depuis la pop-up de la liste des domiciliés, le voice over n'annonce pas le bandeau
<img width="1243" alt="Capture d’écran 2022-01-06 à 14 01 55" src="https://user-images.githubusercontent.com/59437305/148387272-a00c0e18-a5b1-41e0-a2ee-24d32e3fc32e.png">

**Comment by ledugong** [comment]
@pYassine 

Safari

- [ ] sur la liste des domicilié, la réception ET la distribution via pop-up n'est pas énoncée, on retombe directement sur la liste, des vidéos ci-dessous, tu entends pas mais tu vois dans le cadre qu'il l'annonce pas
https://user-images.githubusercontent.com/59437305/149147381-ca14dcbd-bda4-46cf-a004-6e0f0b80ae35.mov
https://user-images.githubusercontent.com/59437305/149147426-e2028999-bdc5-4ba3-b23e-1020f2cb6843.mov

**Comment by ledugong** [comment]
Recette sous Google Chrome

- [ ] Connexion mot de passe

- [ ] Création structure

- [ ] Liste des domiciliés

- [ ] Fiche domicilié

- [ ] Page compte

- [ ] Page utilisateurs

- [ ] Page Documents

- [ ] Page Importer

- [ ] Page Structure

- [ ] Page Notifications

- [ ] Page Portail Usager

- [ ] Page Statistiques

Recette sous Mozilla Firefox

- [ ] Connexion mot de passe

- [ ] Création structure

- [ ] Liste des domiciliés

- [ ] Fiche domicilié

- [ ] Page compte

- [ ] Page utilisateurs

- [ ] Page Documents

- [ ] Page Importer

- [ ] Page Structure

- [ ] Page Notifications

- [ ] Page Portail Usager

- [ ] Page Statistiques

**Comment by pYassine** [comment]
https://domifa-refacto-bootstrap-frontend.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

- [ ] Plus possible d'ajouter une note interne (et au passage passer les boutons à droite)
![Capture d’écran 2022-02-16 à 10 55 06](https://user-images.githubusercontent.com/59437305/154241241-d5d7e82c-e159-4339-9c85-26b4117d2d14.png)

**Comment by ledugong** [comment]
Bon on passe 
Recette PO OK
