### ISSUE TITLE
feat(STATS): mettre les stats 2021 à dispo

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1989]
**Situation Actuelle**

<img width="1037" alt="Capture d’écran 2021-12-27 à 16 02 01" src="https://user-images.githubusercontent.com/59437305/147483616-1c8f6a1a-543d-4df0-a4c7-788e5faadd0c.png">
Sur la page de statistiques, on peut maintenant mettre le rapport 2021 à dispo.

**Comportement souhaité**

- [ ] sur la page de stats, remplacer le rapport 2020 par le rapport 2021
- [ ] pareil sur le back office

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier les stats 2021 sur la page de stats
- [x] vérifier les stats 2021 sur le back office

**Comment by pYassine** [comment]
@ledugong 
https://domifa-fix-stats-2021.dev.fabrique.social.gouv.fr/stats/rapport-activite

**Comment by ledugong** [comment]
@pYassine

- [ ] La ligne 104 devrait être à la place de la ligne 103
<img width="656" alt="Capture d’écran 2022-01-06 à 13 40 21" src="https://user-images.githubusercontent.com/59437305/148384410-22781eb4-e2b8-4a83-8b4a-9c61d4e01fbf.png">

- [ ] Les interactions dans le fichier sont décalées par rapport à la page statistiques : le compteur des appels a sauté
<img width="709" alt="Capture d’écran 2022-01-06 à 13 41 06" src="https://user-images.githubusercontent.com/59437305/148384470-42a94c23-91c3-465a-86ad-70a5390abfb3.png">

<img width="967" alt="Capture d’écran 2022-01-06 à 13 43 17" src="https://user-images.githubusercontent.com/59437305/148384720-beba2a2e-7578-4e1e-890a-e79833c004ab.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
