### ISSUE TITLE
feat(EXPORT): ajouter colonne transfert/procuration dans l'export des domiciliés

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2023]
**Situation Actuelle**

Besoin d'une structure d'avoir un suivi des transferts et procurations chez les domiciliés.

**Comportement souhaité**

- [x] sur l'export des structures, ajouter une colonne à droite des notifs SMS, appelée "Transfert" et afficher OUI/NON pour chaque domicilié
- [x] puis ajouter une colonne à droite des transferts, appelée "Procuration" et afficher OUI/NON pour chaque domicilié
<img width="500" alt="Capture d’écran 2022-01-10 à 10 25 47" src="https://user-images.githubusercontent.com/59437305/148743351-da81893e-6e96-4c7f-baa6-5a05a911760e.png">

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier l'export
- [ ] tester avec / sans transfert
- [ ] tester avec / sans procuration

**Comment by pibouu** [comment]
https://domifa-2023-export-structure.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK
