### ISSUE TITLE
feat(INT_DOM): changer le message de bienvenue en haut de la page

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2027]
**Situation Actuelle**

Actuellement on écrit "Bonjour Prénom !", pas assez précis.

**Comportement souhaité**

- [x] écrire "Bonjour Prénom NOM - ID"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier nouveau texte

**Comment by pibouu** [comment]
https://domifa-2027-change-welcome-message.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pibouu le lien https://domifa-2027-change-welcome-message.dev.fabrique.social.gouv.fr/ ne fonctionne pas

**Comment by ledugong** [comment]
C'était sur la PP générale

Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
