### ISSUE TITLE
feat(RGAA): nouvelle déclaration à ajouter en HP

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2035]
**Situation Actuelle**

[2022-01-14_domifa_declaration-d-accessibilite.pdf](https://github.com/SocialGouv/domifa/files/7880168/2022-01-14_domifa_declaration-d-accessibilite.pdf)

**Comportement souhaité**

- [x] remplacer le doc actuel

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier le nouveau doc

**Comment by pibouu** [comment]
https://domifa-2035-update-access-doc.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
