### ISSUE TITLE
feat(DOC_PERSONNALISABLE): pouvoir ajouter plusieurs documents personnalisés "Autre"

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2040]
**Situation Actuelle**

Actuellement, une structure ne peux ajouter qu'un seul document personnalisé de type Autre. Si elle en ajoute un second, il remplace le premier.

**Comportement souhaité**

- [x] permettre l'ajout de plusieurs documents personnalisés Autre

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester plusieurs documents personnalisés Autre

**Comment by pYassine** [comment]
https://domifa-fix-dernier-passage.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

- [ ] si j'ajoute une attestation postale personnalisée, il n'y a pas la date ni le nom de l'utilisateur qui l'a ajouté (contrairement aux autres documents)
<img width="1250" alt="Capture d’écran 2022-01-21 à 10 54 07" src="https://user-images.githubusercontent.com/59437305/150506099-99c51190-d3b9-43c5-af6e-fec060bf290c.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
