### ISSUE TITLE
bug(INTERACTION): si je supprime la dernière interaction d'une fiche domicilié, la date de dernier passage ne se met pas à jour

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2041]
**Description du problème**

Si je déclare un passage (ou tout autre interaction) par erreur sur une fiche domicilié puis que je supprime ce passage, la date de dernier passage ne se remet pas à jour avec l'ancienne date.

**Comportement attendu**

- [x] si je supprime une interaction, mettre à jour la date de dernier passage en fonction 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] ajouter un appel puis le supprimer
- [x] ajouter un passage puis le supprimer
- [x] ajouter du courrier puis le supprimer

**Comment by pYassine** [comment]
https://domifa-fix-dernier-passage.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
@pYassine 

- [ ] testé sur un domicilié, mais une fois l'interaction supprimée, la date de dernier passage ne se met pas à jour
<img width="1269" alt="Capture d’écran 2022-01-24 à 10 48 06" src="https://user-images.githubusercontent.com/59437305/150759632-34f8ac70-d69b-4ea5-801d-4c05f31114b9.png">
<img width="465" alt="Capture d’écran 2022-01-24 à 10 48 22" src="https://user-images.githubusercontent.com/59437305/150759686-256b53d6-c6f1-4e6c-a2cd-e6e077416a3f.png"

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
