### ISSUE TITLE
feat(DOC_PERSONNALISABLE): récupérer les données des transfert et procuration

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2044]
**Situation Actuelle**

Les structures voudraient créer des courriers sur les transferts et procurations.

**Comportement souhaité**

- [x] me donner la liste des scopes sur le transfert (nom de l'établissement, adresse de l'établissement, date de début de validité et date de fin de validité)
- [x] me donner la liste des scopes sur la procuration (nom, prénom, date de naissance, date de début de validité, date de fin de validité)

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] récupérer les scopes
- [x] mettre le guide à jour

**Comment by pYassine** [comment]
@ledugong Données à rajouter au Doc

  // Transferts
  TRANSFERT_ACTIF: "Transfert actif ou non : (oui / non)",
  TRANSFERT_NOM: "Nom de l'établissement",
  TRANSFERT_ADRESSE: "Adresse de l'établissement",
  TRANSFERT_DATE_DEBUT: "Date de début de validité (jj/mm/aaaa)",
  TRANSFERT_DATE_FIN: "Date de fin de validité (jj/mm/aaaa)",
  // Procuration
  PROCURATION_ACTIF: "Procuration active ou non : (oui / non)",
  PROCURATION_NOM: "Nom du mandataire",
  PROCURATION_PRENOM: "Prénom du mandatair",
  PROCURATION_ADRESSE: "Adresse de l'établissement",
  PROCURATION_DATE_DEBUT: "Date de début de validité (jj/mm/aaaa)",
  PROCURATION_DATE_FIN: "Date de fin de validité (jj/mm/aaaa)",
  PROCURATION_DATE_NAISSANCE: "Date de naissance (jj/mm/aaaa)",

**Comment by pYassine** [comment]
https://domifa-fix-dernier-passage.dev.fabrique.social.gouv.fr/

**Comment by ledugong** [comment]
Recette PO OK
