### ISSUE TITLE
bug(STATS PUBLIQUES): Les stats ne sont pas affiché dans le bon ordre  

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2081]
**Description du problème**

Les stats ne s'affichent pas correctement. Le mois en cours ne devrait pas apparaitre. 
Tout à droite, il devrait y avoir le mois précédent.

![Capture d’écran 2022-02-02 à 11 27 42](https://user-images.githubusercontent.com/11486845/152136630-800fed02-8652-4e5c-9fad-ad6157dd774a.jpg)

**Comportement attendu**

Trier les stats de sorte à ce que de droite à gauche, on voit apparaitre les stats du mois précédent en premier, puis tous les mois précédent sur les 12 derniers mois 

 **Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier les stats des courriers sortants sur la page stat nationale
- [x] Vérifier les stats des domiciliés sur la page stat nationale
- [x] Vérifier les stats des courriers sortants sur la page d'une région 
- [x] Vérifier les stats des domiciliés sur la page d'une région 
- [x] tester une région bien avancée et une pas du tout pour voir que les stats des 12 derniers mois sont bien présentes, même si c'est à 0

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@pYassine 

- [ ] on a pas le même nombre de courriers enregistrés sur la HP et sur la page stats globale
<img width="229" alt="Capture d’écran 2022-02-03 à 14 20 54" src="https://user-images.githubusercontent.com/59437305/152350688-684aedbf-ed44-4a17-848d-0cbbfbd044ed.png">
<img width="256" alt="Capture d’écran 2022-02-03 à 14 21 02" src="https://user-images.githubusercontent.com/59437305/152350705-5be049e7-22c5-4d3e-9aa8-b71268786c1c.png">

**Comment by ledugong** [comment]
Recette Prod OK
