### ISSUE TITLE
bug(AYANTS-DROIT): La date de naissance de certains ayant-droit est mal enregistrée

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2082]
**Description du problème**

Les dates de naissance d'ayant-droit sont corrompus sur certains dossiers
Elles sont enregistré au format dd/mm/yyyy (format texte) au lieu d'une date classique

Les stats des structures touchées ne fonctionnent pas, le calcul ne pouvant se faire correctement.
L'affichage du Cerfa ne fonctionne pas sur un dossier corrompu 

Liste des structures touchées : 245, 209, 295, 65, 152, 5

Liste des usagers touchés :
![Capture d’écran 2022-02-02 à 11 38 08](https://user-images.githubusercontent.com/11486845/152138165-d62007dd-ae37-4a47-af7c-36666eefe534.jpg)
**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

Se connecter sur les comptes des structures anonymisés
- [x] Vérifier que les stats s'affichent bien
- [x] Aller sur les fiches des domiciliés, vérifier que l'affichage des ayant-droit fonctionne

En général : 
- [x] Re-tester l'ajout d'ayant-droit dans le formulaire de demande
- [x] Re-tester l'ajout d'ayant-droit sur les pages profils
- [x] Re-tester la modification d'un ayant-droit existant
- [x] Vérifier que le Cerfa fonctionne et que les données sont bien affichés

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@pYassine

Le domicilié 31 de la stucture 295 n'a aucun AD pourtant il est dans ta liste, normal ?
<img width="613" alt="Capture d’écran 2022-02-03 à 14 34 09" src="https://user-images.githubusercontent.com/59437305/152352804-006a6984-b3de-47fb-91c2-7d0a45079ea3.png">

**Comment by ledugong** [comment]
Recette PO OK
