### ISSUE TITLE
bug(PARAMÈTRES): certaines structures ont NULL au lieu de true/false

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2086]
**Comportement attendu**

- [x] find the bug and kill it
- [x] migrer les datas erronées

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] récupérer la liste des structures NULL
- [x] les prévenir et vérifier que tout va bien

**Comment by pibouu** [comment]
Liste d'id structure à fix (total 36 structures corrompues)

794
793
782
777
801
809
797
812
784
789
783
802
811
780
788
799
785
790
792
798
786
781
795
779
791
796
800
804
803
808
806
805
778
787
810
807

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
Mail envoyé aux structures listées ci-dessus.
