### ISSUE TITLE
bug(INT_DOM): bug affichage + ajout guide + activation par défaut

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2090]
**Comportement attendu**

- [x] la page du portail usager n'affiche plus l'option OUI / NON, la remettre
- [x] faire en sorte que les structures aient le portail automatiquement activé lorsqu'elle est validé par DomiFa
- [x] activer le portail chez les structures qui ne l'ont pas encore (et passer la moulinette pour ceux qui ont été activées depuis)
- [x] ajouter le guide comme sur la page des notifs SMS : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/Interface_Domicilié&openfile=128375 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Comment by pYassine** [comment]
https://domifa-fix-portail-usager-activation.dev.fabrique.social.gouv.fr/structures/portail-usager

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
