### ISSUE TITLE
feat(PROCURATION): déplacer l'historique des procurations & transfert 

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2093]
**Recette PO**

- [x] vérifier que l'historique des procus & transferts fonctionne toujours. Je l'ai déplacé dans la section "historique" avec les autres historiques 

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
Je valide le transfert de l'historique de la procuration et du transfert avec les mentions de création, modification et suppression
