### ISSUE TITLE
feat(INT_DOM): ajouter un bandeau d'information en cas de renouvellement

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2094]
**Situation Actuelle**

Si le domicilié est en cours de renouvellement, afficher un message comme sur la fiche domicilié.

**Comportement souhaité**

<img width="516" alt="Capture d’écran 2022-02-08 à 16 33 38" src="https://user-images.githubusercontent.com/59437305/153020395-6dc45cd0-45ab-497b-bf13-5fadf5c817e3.png">

- [x] entre la phrase "Bienvenue dans votre espace de suivi de courrier" et la section "Votre courrier", afficher un message "Demande de renouvellement actuellement en cours"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester avec un domicilié actif
- [x] tester avec un domicilié en cours de renouvellement

**Comment by celinelr** [comment]
Je valide la recette, merci

![Capture d’écran 2022-04-04 à 18 45 18](https://user-images.githubusercontent.com/86293911/161592091-dbd7939b-7a7b-4f98-aac3-5b3971162435.png)
