### ISSUE TITLE
feat(INT_DOM): afficher si le domicilié a une procuration / un transfert en cours

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2095]
**Situation Actuelle**

Plus d'informations et de lisibilité sur l'interface domicilié.

**Comportement souhaité**

<img width="494" alt="Capture d’écran 2022-02-08 à 16 40 10" src="https://user-images.githubusercontent.com/59437305/153021738-51c2b5b8-dbc0-4e4e-b1a6-93bd934a59f5.png">

- [x] en bas de la section "Votre courrier", avant la section "Votre domiciliation"
- [x] en cas de procuration, afficher un message "Une procuration au nom de Prénom NOM est active et valable jusqu'au XX/XX/XXXX"
- [x] en cas de seconde procuration, afficher le même message en-dessous de la première procuration
- [x] en cas de transfert, afficher un message "Un transfert est actif jusqu'au XX/XX/XXXX à l'adresse suivante : Nom de l'établissement et adresse de l'établissement"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester sans procuration et sans transfert
- [x] tester avec une procuration
- [x] tester avec deux procurations
- [x] tester avec un transfert

**Comment by pibouu** [comment]
Ticket en attente de la nouvelle structure de Procuration

**Comment by celinelr** [comment]
Dans le cas où la procuration a expiré le nom et prénom  du mandataire sont collés.

<img width="1393" alt="Capture d’écran 2022-04-05 à 11 36 15" src="https://user-images.githubusercontent.com/86293911/161725250-3053aa27-f82a-411b-82c3-97600ebc4e05.png">

- [ ] Ajouter un espace entre le nom et prénom du mandataire en cas d'expiration de la procuration

**Comment by celinelr** [comment]
Je valide lorsqu'il y a un transfert. 
<img width="712" alt="Capture d’écran 2022-04-05 à 12 06 58" src="https://user-images.githubusercontent.com/86293911/161730961-cdce90db-b336-4967-b049-4155a007a45f.png">



Je ne valide pas lorsqu'il y a un procuration

**Comment by celinelr** [comment]
Je valide l'ensemble et close le ticket même s'il reste à fix  ce ticket https://github.com/SocialGouv/domifa/issues/2190
