### ISSUE TITLE
feat(MONDOMIFA): Ajout des horaires d'ouverture de la structure côté domiciliés

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2144]
**Situation Actuelle**

Suite au ticket d'ajout des horaires au sein de la structure, les afficher aussi sur l'interface domicilié.

**Comportement souhaité**

- [ ] à côté des infos sur la structure, ajouter un bouton "horaires de la structure" (je crois que c'était sur les maquettes design initiales)
- [ ] en cliquant sur le bouton, les jours / horaires d'ouverture s'affichent
- [ ] en les mettant à jour dans la section Structure, elles se mettent à jour sur l'interface domicilié
- [ ] si la structure n'ajoute pas de jours / horaires, afficher un moment "information non communiquée" sur l'interface domicilié

**Recette PO**

- [ ] tester sans jours / horaires
- [ ] tester avec jours / horaires
- [ ] tester un changement de jours / horaires

**Comment by Chirazh** [comment]
Finalement nous avons fait passer le ticket permettant aux structures d'ajouter un message sur le portail, elles peuvent utiliser cette fonctionnalité pour ajouter les horaires.
