### ISSUE TITLE
feat(NUMÉRO_CONTACT): permettre l'ajout de numéro étranger au sein d'une structure

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2145]
**Situation Actuelle**

Il n'y a pas d'indicatif sur les structures. Problématique pour les structures en DOM-TOM, pour l'envoi des SMS il faut l'indicatif.

**Comportement souhaité**

Permettre l'ajout d'un indicatif sur les structures.

Indicatif prioritaire : 
France
FrenchGuiana
FrenchPolynesia
Guadeloupe
Martinique
Réunion
Mayotte
SaintPierreAndMiquelon

**Recette PO**
Coté backend
- [x] Migrations de tte les structures ayant renseigner le champs phone avec le Timezone correspondant (exemple : America/Martinique => indicatif "mq")
- [x] Vérifier qu'on affiche bien le numéro de téléphone dans l'email delete-structure
- [x] Vérifier qu'on affiche bien le numéro de téléphone dans l'email new-structure
- [x] Vérifier l'envoie de les SMS avec l'indicatif de Paris et des DOM TOM (tout type de SMS)
- [ ] Vérifier qu'il y a bien le numéro de téléphone de la structure dans le document CERFA

Coté frontend
- [x] Sur la page /structures/edit il y a le nouveau champs Téléphone qui est composé d'un dropdown avec les indicatifs ainsi que un champs texte pour le numéro de téléphone
<img width="308" alt="Screenshot 2022-05-09 at 10 38 57" src="https://user-images.githubusercontent.com/5468549/167372695-6ad39344-238c-430e-a91b-f6334f97ecd7.png">

- [x] Sur la page /structures/nouveau (il faut être déconnecté) le champs téléphone est avec un indicatif

**Comment by pibouu** [comment]
https://domifa-2145-new-new-add-indicatif-structure.dev.fabrique.social.gouv.fr/

**Comment by pibouu** [comment]
Les SMS c'est impossible à recetter proprement pour les DOM-TOMs

**Comment by celinelr** [comment]
Dans le champ téléphone de la structure, si je rentre un numéro  de téléphone avec 10 caractères j'ai un message d'erreur qui m'indique "Le numéro de téléphone est obligatoire" alors qu'il est précisé. 

1. Est ce normal d'être limité à 9 caractères ?
2. Il faut soit changer le message d'erreur en "Un numéro de téléphone valide est obligatoire" soit autorisée plus de 9 caractères. 
 @pYassine tu en penses quoi ?

**Comment by celinelr** [comment]
> Dans le champ téléphone de la structure, si je rentre un numéro de téléphone de plus de 10 caractères pour l'indicatif +33 (par exemple) j'ai un message d'erreur qui m'indique "Le numéro de téléphone est obligatoire" alors qu'il est précisé.
> 
> <img alt="Capture d’écran 2022-06-13 à 18 36 29" width="327" src="https://user-images.githubusercontent.com/86293911/173402422-c47942f4-0e9f-4e31-97ab-c231fd311c74.png">
> 
> Il faut changer le message d'erreur en "Un numéro de téléphone valide est obligatoire"

J'ai vu la correction sur la page structure, maintenant il y a l'erreur suivante "Veuillez vérifier le numéro de téléphone"
<img width="557" alt="Capture d’écran 2022-06-17 à 18 28 33" src="https://user-images.githubusercontent.com/86293911/174339078-3d55e7bb-daf0-4399-be16-c67a2a0bd32d.png">

Par contre dans le  formulaire d'inscription d'une structure j'ai toujours "Le numéro de téléphone est obligatoire"

**Comment by celinelr** [comment]
> Mon navigateur est en Français mais je vois "Search country" dans le champ téléphone de la structure. Est ce que tu peux changer cela s'il te plait ? <img alt="Capture d’écran 2022-06-13 à 18 33 52" width="498" src="https://user-images.githubusercontent.com/86293911/173401825-ba5797c9-d9ff-4086-8e3b-f8edcf030db6.png">

C'est corrigé merci

**Comment by celinelr** [comment]
> Sur le cerfa nous devons afficher l'indicatif non ? Ce n'est pas le cas.
> 
> <img alt="Capture d’écran 2022-06-13 à 18 49 34" width="229" src="https://user-images.githubusercontent.com/86293911/173404359-41f719c3-0962-4e0b-8f76-9eb5ee904b0b.png">
> 
> <img alt="Capture d’écran 2022-06-13 à 18 50 12" width="323" src="https://user-images.githubusercontent.com/86293911/173404450-9456ef68-519e-463a-9c9b-372800137616.png">

Je ne vois pas de correction pour ce point

**Comment by celinelr** [comment]
> Il ne me reste qu'à tester
> 
> * [ ]  Vérifier qu'on affiche bien le numéro de téléphone dans l'email delete-structure
> * [ ]  Vérifier qu'on affiche bien le numéro de téléphone dans l'email new-structure
> 
> Mais pour le moment je ne peux pas créer de structure, Yassine regarde le problème demain

Je confirme pour l'email de delete structure
<img width="301" alt="Capture d’écran 2022-06-17 à 18 35 45" src="https://user-images.githubusercontent.com/86293911/174340051-8a6d52e3-3f59-4660-b2bd-338edb6ff10d.png">



Par contre je ne peux pas tester l'email de new structure car j'ai une erreur 500 au niveau de la création de compte ![Capture d’écran 2022-06-17 à 18 38 24](https://user-images.githubusercontent.com/86293911/174340465-f2482850-1ef9-4470-9851-188841e82b54.png)

**Comment by celinelr** [comment]
Je valide avoir l'indicatif dans l'email des nouvelles structures 
<img width="253" alt="Capture d’écran 2022-06-21 à 10 33 23" src="https://user-images.githubusercontent.com/86293911/174754826-1a93c861-76ec-4c85-ba1a-4d0344e87528.png">

**Comment by celinelr** [comment]
> > Dans le champ téléphone de la structure, si je rentre un numéro de téléphone de plus de 10 caractères pour l'indicatif +33 (par exemple) j'ai un message d'erreur qui m'indique "Le numéro de téléphone est obligatoire" alors qu'il est précisé.
> > <img alt="Capture d’écran 2022-06-13 à 18 36 29" width="327" src="https://user-images.githubusercontent.com/86293911/173402422-c47942f4-0e9f-4e31-97ab-c231fd311c74.png">
> > Il faut changer le message d'erreur en "Un numéro de téléphone valide est obligatoire"
> 
> J'ai vu la correction sur la page structure, maintenant il y a l'erreur suivante "Veuillez vérifier le numéro de téléphone" <img alt="Capture d’écran 2022-06-17 à 18 28 33" width="557" src="https://user-images.githubusercontent.com/86293911/174339078-3d55e7bb-daf0-4399-be16-c67a2a0bd32d.png">
> 
> Par contre dans le formulaire d'inscription d'une structure j'ai toujours "Le numéro de téléphone est obligatoire" <img alt="Capture d’écran 2022-06-17 à 18 28 08" width="419" src="https://user-images.githubusercontent.com/86293911/174339171-0fcb4c49-4873-4ff3-9b55-1bf68d3375fa.png">
> 
> Il faudrait le changer pour "Veuillez vérifier le numéro de téléphone"

@pYassine j'ai toujours le meme message 
<img width="363" alt="Capture d’écran 2022-06-21 à 10 39 22" src="https://user-images.githubusercontent.com/86293911/174756497-6d37414c-dded-40b0-8345-7adbe9c34b57.png">
