### ISSUE TITLE
feat(CREATION_DOM): mieux visualiser les notes internes lors d'une création de domiciliation

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2154]
**Situation Actuelle**

Lors d'une création de domiciliation, il est possible d'ajouter des commentaires privés, ce qui crée une pastille avec des numéros
![Capture d’écran 2022-03-11 à 16 34 13](https://user-images.githubusercontent.com/59437305/157898273-149d8490-e73e-42a4-957d-6293cebc074d.png).
Or, si je clique dessus, rien ne se passe, il est pas très clair que les notes se trouvent en bas de page.

**Comportement souhaité**

- [x] en cliquant sur la pastille, faire descendre l'usager en bas de page pour visualiser les commentaires

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] tester le scroll down

**Comment by celinelr** [comment]
Je valide le scroll down sur toutes les étapes d'une première demande

**Comment by celinelr** [comment]
Je valide aussi le scroll down sur toutes les étapes d'un renouvellement

**Comment by celinelr** [comment]
Suite à la recette de ce ticket je constate ce bug : [bug(FORMULAIRE_DOMICILIE): Mon commentaire privé ne disparait pas lorsque je supprime le commentaire #2191](https://github.com/SocialGouv/domifa/issues/2191)
