### ISSUE TITLE
bug(UI): Bug Design suite à la Maj Bootstrap

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2188]
**Description du problème**
![Capture d’écran 2022-04-04 à 18 44 45](https://user-images.githubusercontent.com/86293911/161712317-34ebbcf6-2816-4443-b36e-279c7bf232c6.png)

Suppression d'un renouvellement > en haut à droite à  l'endroit pour fermer la pop-in il y a en sélectionné par défaut en carré bleu et sans croix. Y avait-il une croix avant a cet endroit la ?

**Comportement attendu**
- [ ] Pas de selection d'élément de l'UI par défaut
- [ ] Ajouter les croix pour fermer les popin s'il le faut

**Scénario de reproduction du problème**

1. Se connecter en tant que structure
2. Aller sur la page d'un domicilié en cours de renouvellement
3. Cliquer sur supprimer le renouvellement

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Verifier la pop-in de suppression de renouvellement

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
- La croix semble toujours sélectionnée. Je vois un encadré bleu. Je ne pense pas que ce soit le comportement attendu. Est-ce normal ?
- La croix ne devrait elle pas etre blanche plutôt que noire ? Comme je n'ai pas le passif de l'application je ne connais pas la situation avant le bug mais instinctivement j'imagine qu'elle devrait etre blanche puisque le titre est blanc dans le bandeau rouge

<img width="761" alt="Capture d’écran 2022-04-11 à 18 45 28" src="https://user-images.githubusercontent.com/86293911/162789809-116bbf49-63ab-4d1f-ae23-41417dc0dd71.png">

**Comment by pYassine** [comment]
@celinelr Le focus devrait être plutôt sur un des deux boutons. Concernant la couleur, on peut la mettre en blanc.

**Comment by celinelr** [comment]
Merci je confirme l'enlèvement de la croix et du focus sur celle ci sur les premières demandes et les renouvellements
<img width="661" alt="Capture d’écran 2022-04-12 à 17 07 09" src="https://user-images.githubusercontent.com/86293911/162993898-b410c94c-32cc-44f8-8022-92413625bbba.png">
