### ISSUE TITLE
bug(RENOUVELLEMENT): Lorsque je supprime une demande de renouvellement celle-ci ne se supprime pas 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2198]
**Description du problème**

La suppression des demandes de renouvellement ne supprimes plus les demandes de renouvellement.
C'est nouveau de cette dernière mise en pre-prod. Je n'avais pas ce problème ce matin.

**Scénario de reproduction du problème**

- Je vais sur la fiche domicilié 
- Depuis la fiche je clique sur "supprimer cette demande" OU compléter la demande > "supprimer cette demande" 
- J'ai un succès de suppression 
- pourtant la personne reste dans la liste des profils a compléter et avec le tag renouvellement

**Lien vers l'environnement de test**

Par défaut : https://domifa-fix-renouvellement-bug.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] verifier la suppression d'une demande de renouvellement

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
Dispo sur : https://domifa-fix-renouvellement-bug.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Dans le cas ou je clique sur "supprimer cette demande" en bas de page de la fiche du domicilié le bandeau "Demande de renouvellement actuellement en cours [Compléter la demande]" ne disparait pas. Il manque un refresh sur la page ? 
Car si je quitte la fiche du domicilié la demande de renouvellement a bien disparue. 

A ta dispo pour que je te fasse une demo

**Comment by celinelr** [comment]
Merci je confirme que cela fonctionne
