### ISSUE TITLE
feat(STATS): logguer les connexions au portail usager

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2202]
**Situation Actuelle**

Actuellement, seul la date de dernière connexion au portail-usager est prise en compte. 

**Comportement souhaité**

Il faudrait enregistrer toutes les connexion pour les mesurer

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Se connecter, regarder le compteur, vérifier qu'il s'incrémente bien

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
@pYassine done non ?
