### ISSUE TITLE
feat(ACCESSIBILITE):  Consultation 13.1 Pour chaque page web, l'utilisateur a-t-il le contrôle de chaque limite de temps modifiant le contenu (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2208]
# P06 : https://domifa.fabrique.social.gouv.fr/manage

Une limite de temps modifie tout ou partie du contenu de la page, ou l'utilisateur est redirigé automatiquement vers une autre.

Par exemple :
- Le site a une durée de session limitée, qui déconnecte l'utilisateur lorsque celle-ci est atteinte

Corrections :
- Proposer à l'utilisateur une méthode permettant de prolonger sa session, par exemple au moyen d'une fenêtre modale apparaissant peu de temps avant la fin de la session.

Todo : 

- [ ] Afficher une modale après 1h d'inactivité. Elle reste affichée 1 minute avant la deconnexion avec le texte suivant 
  - Titre : "Souhaitez-vous poursuivre votre navigation sur DomiFa ?"
  - Body : "Aucune activité n'a été enregistrée depuis une heure, vous allez être automatiquement déconnecté dans 1 minute."
  - Choix : "Oui, je reste connecté" (je reste connectée, le tocken se met à jour ? / "Non, je me déconnecte" ->déconnecter l'utilisateur

Si pas de réponse dans les 5 minutes l'utilisateur sera déconnecté automatiquement

La modale doit avec un role alert : https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/Roles/alert_role

**Comment by pYassine** [comment]
@celinelr https://domifa-feat-rgaa-disconnect.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Comme vu ensemble: 

- [ ] Ajouter la modale aussi sur Mon DomiFa
- [ ] Changer le wording
Titre : "Souhaitez-vous poursuivre votre navigation sur DomiFa ?"
Body : "Aucune activité n'a été enregistrée depuis une heure, vous allez être automatiquement déconnecté dans 1 minute."

**Comment by celinelr** [comment]
La modale doit avoir un role : 'alertdialog'
https://www.w3.org/TR/2009/WD-wai-aria-20091215/roles#alertdialog et https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/Roles/alertdialog_role

**Comment by celinelr** [comment]
Pop in sur DomiFa : 

<img width="761" alt="Capture d’écran 2023-02-08 à 17 25 19" src="https://user-images.githubusercontent.com/86293911/217590501-34ab47f8-5ba3-4bc0-8b34-79baf859667e.png">

Pop-in sur Mon DomiFa 
<img width="539" alt="Capture d’écran 2023-02-08 à 17 26 23" src="https://user-images.githubusercontent.com/86293911/217590508-a3568fd0-67c8-4e37-bcda-7380df4262b9.png">


Est ce possible de mettre le titre en évidence comme sur DomiFa ?

**Comment by celinelr** [comment]
J'ouvre sur mon navigateur "https://domifa-preprod.dev.fabrique.social.gouv.fr/" et dès que la page s'ouvre j'ai la pop-in qui m'invite à rester connecter alors que je suis la page de connexion, déconnecté . Je clique sur "rester connecter" et forcément je suis toujours déconnecté... 

Je ne devrais pas voir cette pop-in une fois deconnecté

**Comment by pYassine** [comment]
@celinelr tu as testé sur la préprod qui est bugguée, as-tu testé sur le lien que je t'ai donné ?

**Comment by celinelr** [comment]
> J'ouvre sur mon navigateur "https://domifa-preprod.dev.fabrique.social.gouv.fr/" et dès que la page s'ouvre j'ai la pop-in qui m'invite à rester connecter alors que je suis la page de connexion, déconnecté . Je clique sur "rester connecter" et forcément je suis toujours déconnecté...
> 
> Je ne devrais pas voir cette pop-in une fois deconnecté

Effectivement je n'ai pas vu ce problème sur l'environnement de test spécifique https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/manage

**Comment by celinelr** [comment]
> J'ai l'impression que lorsque je clique sur "Non, je me déconnecte" puis que je me reconnecte, alors je ne reverrais plus le pop-in se présenter...


@pYassine je ne vois pas le fix sur https://mon-domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/account 

<img width="558" alt="Capture d’écran 2023-02-14 à 10 48 20" src="https://user-images.githubusercontent.com/86293911/218699586-bdaf3d4a-b9ac-4f87-9819-49afc312889f.png">

**Comment by celinelr** [comment]
> J'ai l'impression que lorsque je clique sur "Non, je me déconnecte" puis que je me reconnecte, alors je ne reverrais plus le pop-in se présenter...

@pYassine Je viens de retester sur https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/manage et j'ai toujours ce problème.

Lorsque je clique sur "Non, je me déconnecte", puis qu'immédiatement je me reconnecte alors après quelques temps d'inactivité je ne vois plus la pop-in se representer (bug: je devrais voir la pop-in après 1 minutes d'inactivité dans le cadre de cet environnement de test) alors que si je clique sur "Oui, je reste connecté" la pop-in se represente après quelques temps d'inactivité (bon comportement)

**Comment by celinelr** [comment]
> > J'ai l'impression que lorsque je clique sur "Non, je me déconnecte" puis que je me reconnecte, alors je ne reverrais plus le pop-in se présenter...
> 
> @pYassine Je viens de retester sur https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/manage et j'ai toujours ce problème.
> 
> Lorsque je clique sur "Non, je me déconnecte", puis qu'immédiatement je me reconnecte alors après quelques temps d'inactivité je ne vois plus la pop-in se representer (bug: je devrais voir la pop-in après 1 minutes d'inactivité dans le cadre de cet environnement de test) alors que si je clique sur "Oui, je reste connecté" la pop-in se represente après quelques temps d'inactivité (bon comportement)

Je valide le fix sur : https://domifa-feat-duplicate-ref.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
> Pop in sur DomiFa :
> 
> <img alt="Capture d’écran 2023-02-08 à 17 25 19" width="761" src="https://user-images.githubusercontent.com/86293911/217590501-34ab47f8-5ba3-4bc0-8b34-79baf859667e.png">
> 
> Pop-in sur Mon DomiFa <img alt="Capture d’écran 2023-02-08 à 17 26 23" width="539" src="https://user-images.githubusercontent.com/86293911/217590508-a3568fd0-67c8-4e37-bcda-7380df4262b9.png">
> 
> Est ce possible de mettre le titre en évidence comme sur DomiFa ?

@pYassine je ne vois pas ce fix sur : https://domifa-feat-duplicate-ref.dev.fabrique.social.gouv.fr/
