### ISSUE TITLE
feat(ACCESSIBILITE): Consultation 13.3 Dans chaque page web, chaque document bureautique en téléchargement possède-t-il, si nécessaire, une version accessible (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2209]
# P12 : https://domifa.fabrique.social.gouv.fr/import

Au moins un document bureautique en téléchargement n'est pas accessible.

Par exemple :
- tuto-import.pdf : on constate des erreurs de contrastes, le document n'est pas structuré, il manque une table des matières...

Corrections :
- Corriger le document pour lui ajouter les styles, balises et autres éléments nécessaires à l'accessibilité.
- OU proposer une alternative équivalente (page HTML, document structuré Word ou LibreOffice) qui soit accessible.
- Les documents bureautiques en téléchargement répondent à des critères particuliers d'accessibilité que vous pouvez retrouver dans une documentation dédiée : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#version-accessible-pour-un-document-en-telechargement

## Ressources 

- [x]  Voici le tutoriel d'import  à changer : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/IMPORT&openfile=178279
- [x] modele_import_domifa.xlsx  
   -  [modele_import_domifa.xlsx](https://github.com/SocialGouv/domifa/files/10509440/modele_import_domifa.xlsx)
   - ou aussi dispo : https://nextcloud.fabrique.social.gouv.fr/apps/onlyoffice/178816?filePath=%2FDomiFa%2FDEVELOPPEMENT%2FIMPORT%2Fmodele_import_domifa.xlsx
- [x] Accès au portail domicilié : https://github.com/SocialGouv/domifa/issues/2553
- [x] Document_Explicatif_Portail_Domicilié https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/Interface_Domicili%C3%A9&openfile=178290 
- [x] Courrier de radiation : est déjà accessible 
- [x] Attestation postale : est déjà accessible 
- [x] Document_Explicatif_Notifications_SMS https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/Notifs_SMS/Document_Explicatif&fileid=111829
- [x] Document_Explicatif_Courriers_Paramétrables : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/Courriers_Param%C3%A9trables&openfile=178310
- [x] Stat : remplacer ce fichier [export-structure-stats.xlsx](https://github.com/SocialGouv/domifa/files/10482010/export-structure-stats.xlsx)
- [x] guide utilisateur : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/SUPPORT/GUIDE%20UTILISATEURS&openfile=178931
- [x] déclaration d'accessibilité : transformer le document en une page web comme les CGU actuellement par exemple

**Comment by celinelr** [comment]
@pYassine je ne sais pas ou est le doc pour les stats pour le modifier. Est ce que l'on peux regarder ensemble ?

**Comment by pYassine** [comment]
@celinelr le fichier Excel de l'import semble être corrompu
![Capture d’écran 2023-01-25 à 16 26 12](https://user-images.githubusercontent.com/11486845/214603817-669bf959-d2af-4366-ba24-c5dca6b05adc.jpg)

**Comment by celinelr** [comment]
Mince ! @pYassine C'est à cause de nextcloud ... Peux tu me donner celui que tu utilises actuellement ?

**Comment by celinelr** [comment]
@pYassine je viens de mettre à jour le document d'import. Dispo sur le ticket et nextcloud

**Comment by celinelr** [comment]
Je viens de mettre le document explicatif du  portail à jour

**Comment by celinelr** [comment]
Je viens de tester la nouvelle page d'accessibilité : 
Dans le section "Résultats des tests" certains liens n'ont pas un comportement correct lorsque je suis déconnecté
- [7. Domiciliés : Nouvelle demande](https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/nouveau) me redirige vers une page blanche avec un bandeau bleu "nouvelle demande"
<img width="1434" alt="Capture d’écran 2023-02-08 à 17 36 26" src="https://user-images.githubusercontent.com/86293911/217593271-783c3831-bf39-42d1-bdf9-f974620cc3f7.png">
Alors que je devrais être redirigé vers la page de connexion : https://domifa.fabrique.social.gouv.fr/connexion?returnUrl=%2Fusager%2Fnouveau 
<img width="1357" alt="Capture d’écran 2023-02-08 à 17 37 29" src="https://user-images.githubusercontent.com/86293911/217593563-24f663c3-d851-4dc9-9960-71455a56bfa5.png">
- 8. Domicilié : Actif n'est pas un lien cliquable alors qu'il devrait y avoir ce lien https://domifa.fabrique.social.gouv.fr/profil/general/9
- [11. Utilisateurs](https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/accessibilite/users/comptes) je suis redirigé vers une page 404... Est ce possible d'être redirigé comme les autres sur la page de connexion
-[12. Importer](https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/import) je suis redirigé directement sur la page d'import ... alors que je suis déconnecté. Je devrais être redirigé vers https://domifa.fabrique.social.gouv.fr/connexion?returnUrl=%2Fimport
<img width="1376" alt="Capture d’écran 2023-02-08 à 17 41 49" src="https://user-images.githubusercontent.com/86293911/217594663-2bdb37e0-b374-497a-9975-1ee0b739fe83.png">

**Comment by celinelr** [comment]
- [ ] Accès au portail domicilié : https://github.com/SocialGouv/domifa/issues/2553
- Le document sur ce ticket est accessible mais pas celui que j'ai téléchargé sur cet environnement de test
<img width="928" alt="Capture d’écran 2023-02-08 à 17 46 26" src="https://user-images.githubusercontent.com/86293911/217596114-3e1f9269-2a4d-4e4a-a5f0-deb08482d680.png">

**Comment by celinelr** [comment]
Je valide le reste

**Comment by celinelr** [comment]
> Je viens de tester la nouvelle page d'accessibilité : Dans le section "Résultats des tests" certains liens n'ont pas un comportement correct lorsque je suis déconnecté
> 
> * [7. Domiciliés : Nouvelle demande](https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/nouveau) me redirige vers une page blanche avec un bandeau bleu "nouvelle demande"
> 
> <img alt="Capture d’écran 2023-02-08 à 17 36 26" width="1434" src="https://user-images.githubusercontent.com/86293911/217593271-783c3831-bf39-42d1-bdf9-f974620cc3f7.png">
> 
> Alors que je devrais être redirigé vers la page de connexion : https://domifa.fabrique.social.gouv.fr/connexion?returnUrl=%2Fusager%2Fnouveau
> <img alt="Capture d’écran 2023-02-08 à 17 37 29" width="1357" src="https://user-images.githubusercontent.com/86293911/217593563-24f663c3-d851-4dc9-9960-71455a56bfa5.png">
> 
> * "8. Domicilié ": Actif n'est pas un lien cliquable alors qu'il devrait y avoir ce lien https://domifa.fabrique.social.gouv.fr/profil/general/9
> * [11. Utilisateurs](https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/accessibilite/users/comptes) je suis redirigé vers une page 404... Est ce possible d'être redirigé comme les autres sur la page de connexion
> * [12. Importer](https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/import) je suis redirigé directement sur la page d'import ... alors que je suis déconnecté. Je devrais être redirigé vers https://domifa.fabrique.social.gouv.fr/connexion?returnUrl=%2Fimport
> 
> <img alt="Capture d’écran 2023-02-08 à 17 41 49" width="1376" src="https://user-images.githubusercontent.com/86293911/217594663-2bdb37e0-b374-497a-9975-1ee0b739fe83.png">

Je valide le correctif de tout ces points sur  https://domifa-feat-idle-portail.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
J'ai vérifier l'accessibilité de tous les documents sur preprod c'est validé
