### ISSUE TITLE
feat(ACCESSIBILITE): Navigation 12.1 Chaque ensemble de pages dispose-t-il de deux systèmes de navigation différents, au moins (hors cas particuliers) ? / AUDIT Il existe 2 moyens de naviguer

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2212]
# P01	Accueil	https://domifa.fabrique.social.gouv.fr/

**Lien pour tester : [domifa-rgaa-livrable-1.dev.fabrique.social.gouv.fr](https://domifa-rgaa-livrable-1.dev.fabrique.social.gouv.fr/) **

Le site (ou l'ensemble de pages) ne dispose pas de deux systèmes de navigation.

Par exemple :
- Le site ne dispose que d'un menu de navigation.

**Corrections proposés :**
Chaque ensemble de pages doit disposer de deux systèmes de navigation parmi les 3 suivants : 
- Un menu de navigation ;
- Un plan du site ;
- Un moteur de recherche (le moteur de recherche est considéré comme un système de navigation s'il indexe toutes les pages du site).

**Corrections retenues**
- [x] Un menu de navigation ;

- [x] Un plan du site 
- Pour les non-connectés : liste les pages accessibles publiquement (faq, confidentialité, inscription, etc)
- Pour les connectés : gestion des comptes, domiciliés, etc.

**Corrections non retenues + explication **
Moteur de recherche : plus adapté à un site type blog qu'a Domifa qui n'a pas de pages dynamiques

**Comment by ErceauFloriane** [comment]
Environnement de test : https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/
@celinelr

**Comment by celinelr** [comment]
Je propose ce plan de site @pYassine ca te semble juste ? 

[[Page d’acceuil](https://domifa-preprod.dev.fabrique.social.gouv.fr/)](https://domifa-preprod.dev.fabrique.social.gouv.fr/) 

[[Nos statistiques](https://domifa-preprod.dev.fabrique.social.gouv.fr/stats)](https://domifa-preprod.dev.fabrique.social.gouv.fr/stats) 

[[Contacter l’équipe](https://domifa-preprod.dev.fabrique.social.gouv.fr/contact)](https://domifa-preprod.dev.fabrique.social.gouv.fr/contact)

[[FAQ](https://domifa-preprod.dev.fabrique.social.gouv.fr/faq)](https://domifa-preprod.dev.fabrique.social.gouv.fr/faq)

[[Accessibilité: non conforme](https://domifa-preprod.dev.fabrique.social.gouv.fr/assets/files/domifa_declaration-d-accessibilite.pdf)](https://domifa-preprod.dev.fabrique.social.gouv.fr/assets/files/domifa_declaration-d-accessibilite.pdf)

[[Mentions légales](https://domifa-preprod.dev.fabrique.social.gouv.fr/mentions-legales)](https://domifa-preprod.dev.fabrique.social.gouv.fr/mentions-legales)

[[CGU](https://domifa-preprod.dev.fabrique.social.gouv.fr/cgu)](https://domifa-preprod.dev.fabrique.social.gouv.fr/cgu)

[[Nouveautés](https://domifa-preprod.dev.fabrique.social.gouv.fr/news)](https://domifa-preprod.dev.fabrique.social.gouv.fr/news)

[[Statistiques](https://domifa-preprod.dev.fabrique.social.gouv.fr/stats)](https://domifa-preprod.dev.fabrique.social.gouv.fr/stats)

[[Contactez-nous](https://domifa-preprod.dev.fabrique.social.gouv.fr/contact)](https://domifa-preprod.dev.fabrique.social.gouv.fr/contact)

Nos partenaires

[[La fabrique numérique](https://www.fabrique.social.gouv.fr/)](https://www.fabrique.social.gouv.fr/) 

[[Beta.gouv.fr](https://beta.gouv.fr/)](https://beta.gouv.fr/)

[[France relance](https://www.gouvernement.fr/les-priorites/france-relance)](https://www.gouvernement.fr/les-priorites/france-relance)

[[Dihal](https://www.gouvernement.fr/delegation-interministerielle-a-l-hebergement-et-a-l-acces-au-logement)](https://www.gouvernement.fr/delegation-interministerielle-a-l-hebergement-et-a-l-acces-au-logement)

[[Ministère des solidarités et de la santé](https://www.gouvernement.fr/le-ministere-des-solidarites-et-de-la-sante)](https://www.gouvernement.fr/le-ministere-des-solidarites-et-de-la-sante)

[[UNCCAS](https://www.unccas.org/)](https://www.unccas.org/)

**Comment by celinelr** [comment]
Merci le plan de site est parfait. 

J'ai remarqué les comportement suivant : 

Message d'erreur si je n'ai pas la permission pour accèder à la page 
![Capture d’écran 2022-05-18 à 15 35 57](https://user-images.githubusercontent.com/86293911/169051479-135d6cb2-a78e-4a74-a23e-35c1eea44148.png)

Message d'erreur si je suis connecté et que je souhaite accéder à une page alors que je devrais etre déconnecté pour y accéder
![Capture d’écran 2022-05-18 à 15 36 39](https://user-images.githubusercontent.com/86293911/169051630-4c20dca6-9231-4064-9505-9c39cc1324c0.png)

Ces comportements sont acceptables. Si nous avons des retours au support nous ferons peut etre évoluer cela pour ne pas afficher les pages dont nous n'avons pas les accès.

**Comment by pYassine** [comment]
`<p>`

**Comment by Chirazh** [comment]
Une fois le ticket 8,6 finalisé, mettre à jour le plan du site pour les 3 catégories du haut "gérer les domiciliés" / "gérer ma structure" / "gérer mon compte"
