### ISSUE TITLE
feat(ACCESSIBILITE): Navigation 12.6 Les zones de regroupement de contenus présentes dans plusieurs pages web (zones d'en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche) peuvent-elles être atteintes ou évitées ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2213]
# P01	Accueil	https://domifa.fabrique.social.gouv.fr/

**Lien pour tester : [domifa-rgaa-livrable-1.dev.fabrique.social.gouv.fr](https://domifa-rgaa-livrable-1.dev.fabrique.social.gouv.fr/) **

Toutes les zones principales de la page ne peuvent pas être atteintes.

Exemples et corrections :
Ajouter les rôles suivants aux grandes zones de la page :
 - role="banner" pour l'en-tête principal du site (sur la balise <header>), 
 - role="main" pour le contenu principal (sur la balise <main>),
 - role="navigation" sur le menu principal, (sur la balise <nav>) ainsi qu'un aria-label="Menu principal", 
 - role="contentinfo" sur le pied de page (sur la balise <footer>), 
 - role="search" sur le conteneur du moteur de recherche.
 
 **Corrections retenues :**

- [x]  role="banner" pour l'en-tête principal du site (sur la balise <header>), 
- [x]  role="main" pour le contenu principal (sur la balise <main>)
- [x]  role="navigation" sur le menu principal, (sur la balise <nav>) ainsi qu'un aria-label="Menu principal", 
- [x]  role="contentinfo" sur le pied de page (sur la balise <footer>), 
- [x]  role="search" sur le conteneur du moteur de recherche.

**Corrections non retenues + explication :**
Toutes les corrections retenues sont faites

**Comment by ErceauFloriane** [comment]
Corrections:
_- role="banner" pour l'en-tête principal du site_ --> Mise en place `role="banner" `sur la div qui entoure la nav
_- role="main" pour le contenu principal_  --> Mise en place `role="main" `sur la div qui entoure le contenu 
- role="navigation" sur le menu principal + aria-label="Menu principal" --> Mise en place `role="navigation" `sur la div qui entoure le menu principal + ajout d'un `aria-label="Menu principal"`
_- role="contentinfo" sur le pied de page_ --> Mise en place `role="contentinfo" `sur la balise `<footer/>`
_- role="search" sur le conteneur du moteur de recherche_ --> Pas de conteneur de recherche

La sémantique des titres n'était pas correct (access + seo) --> Ajout d'un `role="heading" aria-level="2" ` sur le span après le h1 "Simplifiez la domiciliation" afin de rendre la sémantique correct (voir extension HeadingMap).
@celinelr

**Comment by ErceauFloriane** [comment]
Environnement de test : https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/
@celinelr

**Comment by celinelr** [comment]
onglet domicilié https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/manage

- [ ] Je ne vois pas de role main 
- [ ] Je ne vois pas de role search

Aussi faut il faire cela sur toutes les autres pages du site ?

**Comment by ErceauFloriane** [comment]
Nous avons besoin d'un seul role main celui qui va au contenu principal de site --> présentation du produit
Il n'y a pas de zone de recherche sur le site Domifa donc ce n'est pas utile de mettre un role search

**Comment by celinelr** [comment]
Je ne vois aucun role main sur les pages. D'ailleurs,  en inspectant le code je vois cela grace à mon extension "assistant rgaa"

![Capture d’écran 2022-05-18 à 15 25 02](https://user-images.githubusercontent.com/86293911/169049087-32ae32de-ea69-4356-af8e-2f1218aec57d.png)

**Comment by celinelr** [comment]
Après vérification pas besoin d'ajouter un role="main" puisque tu utilises

"The element has a role of main. Developers should use semantic HTML -- in this case -- over using ARIA."
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role

**Comment by celinelr** [comment]
@pYassine je ne pas pas recetter le ticket, l'environnement "[domifa-rgaa-livrable-1.dev.fabrique.social.gouv.fr](https://domifa-rgaa-livrable-1.dev.fabrique.social.gouv.fr/)" n'est pas accessible

**Comment by celinelr** [comment]
@pYassine Il faudrait ajouter un role search sur la page suivante : https://domifa-preprod.dev.fabrique.social.gouv.fr/structures/inscription

![image](https://user-images.githubusercontent.com/86293911/214005877-73b6a47a-d0de-42df-b118-16d7449127df.png)

**Comment by celinelr** [comment]
Merci, je valide

**Comment by celinelr** [comment]
Merci je valide
