### ISSUE TITLE
feat(ACCESSIBILITE):  Navigation 12.7 Dans chaque page web, un lien d'évitement ou d'accès rapide à la zone de contenu principal est-il présent (hors cas particuliers) ? / AUDIT Chaque page contient des liens d'accès rapide

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2214]
# P01	Accueil	https://domifa.fabrique.social.gouv.fr/

La page ne propose pas de lien d'accès rapide au rapide ou celui-ci n'est pas fonctionnel.

Par exemple :
- Il manque un lien d'accès rapide au contenu principal.

### Propositions de l'audit :
- Proposer au moins un lien d'accès rapide à la zone de contenu principal.
- Insérer un attribut tabindex="-1" sur la zone de contenu principal pour assurer une reprise de tabulation cohérente.
- Laisser le lien d’accès rapide visible ou s'assurer qu'il est visible au moins à la prise de focus.
- S'assurer que le lien d'accès rapide est fonctionnel, c'est-à-dire que le focus est bien déplacé sur la zone ciblée.

### Corrections apportés :
- [x] Proposer au moins un lien d'accès rapide à la zone de contenu principal : OK
- [x] Laisser le lien d’accès rapide visible ou s'assurer qu'il est visible au moins à la prise de focus : OK
- [x] S'assurer que le lien d'accès rapide est fonctionnel, c'est-à-dire que le focus est bien déplacé sur la zone ciblée.

### Corrections laissés de côté car peu pertinentes ou solution trouvée 
- [ ] Insérer un attribut tabindex="-1" sur la zone de contenu principal pour assurer une reprise de tabulation cohérente : inutile

**Comment by ErceauFloriane** [comment]
Reste à faire:

 *Mettre en place une prise de focus sur le lien "Découvrir la plateforme"
 Mise en place d'un lien d'accès rapide pour accéder au plan du site 
 Masquer les liens d'accès rapide --> voir les différents screens

**Comment by ErceauFloriane** [comment]
Corrections :

- _Proposer au moins un lien d'accès rapide à la zone de contenu principal_ 
--> Mise en place de 3 liens d'accès rapide:
1. Aller à la navigation --> Menu principal
2. Aller au contenu --> Ancre vers le contenu "Découvrir la plateforme"
3. Aller au plan du site --> Ancre vers le footer 
![Capture d’écran 2022-05-02 à 14 22 49](https://user-images.githubusercontent.com/67644911/166236605-7fbfc3bb-0389-4fad-bf33-0fe044bff925.png)
![Capture d’écran 2022-05-02 à 14 23 06](https://user-images.githubusercontent.com/67644911/166236609-9db628d2-90bf-4b6f-84ec-a5ce431c3695.png)


_- Insérer un attribut tabindex="-1" sur la zone de contenu principal pour assurer une reprise de tabulation cohérente._
--> Pas besoin de mettre en place de `tabindex="-1"` car le contenu "Découvrir la plateforme" est écrit sémantiquement avec les éléments interactifs <h1/> et <a/>

_- Laisser le lien d’accès rapide visible ou s'assurer qu'il est visible au moins à la prise de focus._
--> Les liens d'accès rapides sont visibles à la prise de focus (Tab)

_- S'assurer que le lien d'accès rapide est fonctionnel, c'est-à-dire que le focus est bien déplacé sur la zone ciblée._
--> Les liens d'accès rapides sont fonctionnels

**Plus:**
J'ai également rajouter un outline à la prise de focus sur le lien "Découvrir la plateforme"
![Capture d’écran 2022-05-02 à 14 50 09](https://user-images.githubusercontent.com/67644911/166236697-4aecf1b5-2e29-49b3-9302-bc6741b2f31e.png)

**Comment by ErceauFloriane** [comment]
Environnement de test : https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/
@celinelr

**Comment by celinelr** [comment]
Merci Floriane, Après la recette je constate que les liens fonctionnent bien que sur la home page de domifa. 

En effet, si je me situe autre par sur le site après avoir fait un refresh, par exemple, la fiche d'un domicilié, la page d'import etc. lorsque que je clique sur les boutons "Aller au contenu principal" ou "Aller à la navigation" Je suis redirigée sur la home page. 

Question : 
- Faut il supprimer ce lien d'accès rapide pour toutes les autres pages que la home page ? OU faut il définir le contenu principal et redirection vers la navigation pour toutes les autres pages du site ?

**Comment by pYassine** [comment]
https://domifa-fix-skip-links.dev.fabrique.social.gouv.fr/

**Comment by Chirazh** [comment]
En cas de changement de page il n'y a pas les liens d'accès rapide.
