### ISSUE TITLE
feat(ACCESSIBILITE): Liens 6.1 : Chaque lien est-il explicite (hors cas particuliers) ? / AUDIT Les actions sont explicites

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2215]
# P01	Accueil	https://domifa.fabrique.social.gouv.fr/
Au moins un intitulé de lien n'est pas pertinent.

Par exemple :
1. Le lien "Domifa - [nom utilisateur]" ;
2. Les liens du menu "Mon compte" possèdent des icônes qui ont un title (pas toujours cohérent avec l'intitulé du lien). Même si ces icônes sont cachées avec aria-hidden="true", il y a un risque que le title soit restitué.
3. Dans le footer, le lien "Mentions légales" a un title="FAQ".

**Corrections proposées:**
1. Supprimer le texte "Logo" dans l'alternative de l'image.
2. Supprimer les title sur les icônes "Mon compte"
3. Supprimer le title dans le lien mention légales

**Corrections retenues:**
- [x] - Supprimer le texte "Logo" dans l'alternative de l'image -> Texte supprimé OK
- [x] - Supprimer les title sur les icônes "Mon compte" -> OK
- [x] - Supprimer le title sur le lien "Mention légales -> OK

# P06	Domiciliés	https://domifa.fabrique.social.gouv.fr/manage
Au moins un intitulé de lien n'est pas pertinent.

Par exemple :
- Les liens dans le tableau

**Corrections proposées:**
- Ajouter des title sur les liens avec pour valeur tout le texte des 3 premières colonnes de la ligne, suivi de l'intitulé du lien. Par exemple pour le lien de la colonne "Passage" : title="Actif, 02, MARTINE Sembat, 12/10/2021".

**Corrections retenues:**

- [x] sera traité dans le ticket #2263--> traité --> attr.aria-label rajouté afin de récupérer les infos via lecteur d'écran --> done

# P12	Importer	https://domifa.fabrique.social.gouv.fr/import

Au moins un intitulé de lien n'est pas pertinent.

Par exemple :
- Le lien "ce document explicatif" a un title qui ne reprend pas l'intitulé.

**Corrections proposées:**
- Modifier le title : "ce document explicatif : Télécharger le tuto d'import domifa" (vous pouvez sortir "ce" de l'intitulé de façon à obtenir un title plus compréhensible).   

**Corrections retenues:**

- [x] - Mise en place d'un aria-label="Télécharger le tutoriel d'import domifa" sur le lien afin de le rendre pertinent + suppression "ce" sur "ce document explicatif"

**Comment by ErceauFloriane** [comment]
**P01 Accueil :**
Supprimer le texte "Logo" dans l'alternative de l'image -> _Texte supprimé_ 
Supprimer les title sur les icônes -> en cours 
Supprimer le title -> done
**P06 Domiciliés:**
Ajout d'un titre sur les icon avec que le lecteur d'écran le lise. ajout de la tabulation au clavier des btn action rapide (en cours)
**P12 Importer:**Titre modifié

**Comment by ErceauFloriane** [comment]
Fix: modif --> `<div class="icon-appel list-icon"></div> en <button class="icon-appel list-icon" title="Ajout d'un appel"></button>` ainsi les button sont navigables au clavier.
_Nota bene: Prévoir le focus sur ses btn_

**Comment by celinelr** [comment]
P06 Domiciliés https://domifa.fabrique.social.gouv.fr/manage

- [ ] pour tous les boutons (sauf pour "ajouter d'un appel" je n'ai pas de balise title. De fait, avec le lecteur d'écran je ne sais pas ou je me situe 

![Capture d’écran 2022-05-06 à 18 16 38](https://user-images.githubusercontent.com/86293911/167172242-d8e5a586-55d6-45ea-a298-9b76893a7549.png)

Aussi je ne vois pas la correction suivante 

- [ ] Ajouter des title sur les liens avec pour valeur tout le texte des 3 premières colonnes de la ligne, suivi de l'intitulé du lien. Par exemple pour le lien de la colonne "Passage" : title="Actif, 02, MARTINE Sembat, 12/10/2021".

**Comment by celinelr** [comment]
P01 Accueil https://domifa.fabrique.social.gouv.fr/
Je valide toutes les corrections

**Comment by celinelr** [comment]
P12 Importer https://domifa.fabrique.social.gouv.fr/import

Je ne valide pas : 

- [ ] Modifier le title : "ce document explicatif : Télécharger le tuto d'import domifa" (vous pouvez sortir "ce" de l'intitulé de façon à obtenir un title plus compréhensible).
![Capture d’écran 2022-05-06 à 18 20 33](https://user-images.githubusercontent.com/86293911/167172731-ffe67870-a83a-4875-ab47-7a7162f07a09.png)

**Comment by celinelr** [comment]
https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/structures/sms

- [ ] Ajouter un  title sur le lien "en cliquant ici"


![Capture d’écran 2022-05-06 à 18 24 53](https://user-images.githubusercontent.com/86293911/167173227-1888843c-0945-4863-8a76-db6ae9dfc2f2.png)

**Comment by celinelr** [comment]
La seule chose qui n'est pas à traiter dans ce ticket est " 

# P06 Domiciliés https://domifa.fabrique.social.gouv.fr/manage
Au moins un intitulé de lien n'est pas pertinent.

Par exemple :

Les liens dans le tableau
Corrections proposées:

Ajouter des title sur les liens avec pour valeur tout le texte des 3 premières colonnes de la ligne, suivi de l'intitulé du lien. Par exemple pour le lien de la colonne "Passage" : title="Actif, 02, MARTINE Sembat, 12/10/2021".
Corrections retenues:

[ ]
"

**Comment by pYassine** [comment]
@Chirazh à poser comme cas concret lors de l'atelier

Dans notre tableau, chaque ligne est cliquable, elle permet de renvoyer vers la fiche. Quelle est la meilleure pratique ? 
- Rendre chaque case du tableau cliquable ? 
- Retirer le fait que toute la tuile soit cliquable

**Comment by Chirazh** [comment]
Vérifier l'ensemble des liens de la plateforme en utilisant le site RGAA et en cochant 6.1

**Comment by Chirazh** [comment]
**AUDIT FLASH JUIN 2023**
Les actions sont explicites

## Observation

### Page de détail d’un domicilié :

- Le nom accessible (ici “Ajout détaillé d’un courrier”) doit contenir l’intitulé visible (ici “Réception”)

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/75f4f3e9-157e-4bde-8ed7-6b881759ddc1/Untitled.png)

### Manager sa structure :

- Les cellules cliquables du tableau n’ont pas d’intitulé

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/c0517bd8-7424-404d-ab01-3f9835081d82/Untitled.png)

## Pour qui

Tout le monde (mais plus particulièrement les personnes qui utilisent un lecteur d’écran, les personnes neuro-atypiques, les personnes avec une faible concentration)

---

## Recommandation

- [ ]  Vérifier les intitulés des liens (links) avec le [[bookmarklet a11y-outline](https://xi.github.io/a11y-outline/)](https://xi.github.io/a11y-outline/)

## Ressources

- **Critères RGAA**
    - Critère 6.1. Chaque lien est-il explicite (hors cas particuliers) ?
    - Critère 6.2. Dans chaque page web, chaque lien a-t-il un intitulé ?
    - Critère 11.9. Dans chaque formulaire, l’intitulé de chaque bouton est-il pertinent (hors cas particuliers) ?
- **Méthodologie**
    - Utiliser Andi et afficher le module “Links/Buttons”
    - 

![Image](https://github.com/SocialGouv/domifa/assets/61183619/d8ec6ec6-60e0-48da-9c7d-20299f2d2de1)



![Image](https://github.com/SocialGouv/domifa/assets/61183619/a29a9841-4ed1-40f3-b52c-33dc2be1c824)
