### ISSUE TITLE
bug(Historique): quand je supprime une demande, l'historique se met bien à jour

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2228]
**Description du problème**

Des dossiers présentent des entrées en doublon dans l'historique
Quand on supprime une demande sur certains dossiers. 

**Exemple :** 
https://mattermost.fabrique.social.gouv.fr/default/pl/jr1ttttm4insmeczjexpfctiqw

**Comportement attendu**

Quand je supprime une demande, la précédente décision doit être remise dans le dossier
- Si j'étais radié avant la nouvelle demande, je dois redevenir radié
- Si j'étais actif, avant la nouvelle demande, je dois redevenir actif

**Copies d'écran**
![Capture d’écran 2022-04-27 à 20 36 00](https://user-images.githubusercontent.com/11486845/165596054-b20dd42e-a87e-41e1-854a-feaca5e74cf8.jpg)

**Informations complémentaires:**

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Créer une demande à partir d'un dossier de chaque type de statut (radié, refusé, valide), la supprimer, vérifier l'historique
- [x] Vérifier le contenu de l'historique sur la préprod pour les structures suivantes :

#### Structure 45 :  admin-45-125@domifa-fake.fabrique.social.gouv.fr
- 1257
- 998
- 19
- 2760

#### Structure 6  : admin-6-2049@domifa-fake.fabrique.social.gouv.fr

- 215
- 554
- 649
- 254
- 276

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
Normalement la logique veut que l'historique soit toujours de cette manière 

Instruction --> Décision (refus, valide, radié) 
Ou
Instruction --> Attente Décision --> Décision (refus, valide)

A aucun moment on est censé avoir 2 instructions qui se chevauchent dans l'historique :
Instruction --> Instruction --> Décision

**Comment by celinelr** [comment]
Je valide ce ticket, les historiques sont corrects
