### ISSUE TITLE
feat(ACCESSIBILITE): Formulaires 11.1 : Chaque champ de formulaire a-t-il une étiquette ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2239]
# P05 : https://domifa.fabrique.social.gouv.fr/connexion

Au moins un champ de formulaire ne possède pas d'étiquette, son étiquette n'est pas visible ou son étiquette n'est pas correctement liée.
Par exemple :
- Les champs email et mot-de-passe du formulaire de connexion : les liaisons for/id sont cassées.
Corrections :
- Réparer les liaisons for/id : ajouter des attributs id sur les champs correspondant aux attributs for.

# P06 : https://domifa.fabrique.social.gouv.fr/manage

Au moins un champ de formulaire ne possède pas d'étiquette, son étiquette n'est pas visible ou son étiquette n'est pas correctement liée.
Par exemple :
- Le champ de recherche
Corrections :
- Ajouter un title sur le champ avec pour valeur le contenu du placeholder.

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)

Au moins un champ de formulaire ne possède pas d'étiquette, son étiquette n'est pas visible ou son étiquette n'est pas correctement liée.
Par exemple :
1. Étape : 1 : Dans la partie "ayants-droit", les liaisons <label for="id"> des champs "Date de naissance" sont cassées (les attributs for ont tous la même valeur).
2. Étape 2 : la liaison <label for="id"> du champ "Date de rendez-vous est cassée (pas d'id sur le champ).
3. Étape : : les champs "Précisions", "Par quelle structure" (liaison <label for="id"> cassée) et "Commentaires"
Corrections :
1, 2 et 3. Réparer les liaisons.
3. Utiliser des attributs title reprenant la valeur des placeholder sur les champs Précisions. Utiliser une liaison <label for="id"> pour le champ "Commentaires".

# P13 : https://domifa.fabrique.social.gouv.fr/stats/rapport-activite

Au moins un champ de formulaire ne possède pas d'étiquette, son étiquette n'est pas visible ou son étiquette n'est pas correctement liée.
Par exemple :
- Les champs "Du" et "Au"
Corrections :
- Utiliser des liaisons <label for="@id-champ">.

**Comment by Chirazh** [comment]
A tester sur tout le site (notamment les formulaires)
Outil Wave
Vérifier que chaque input est associé à une étiquette (carré vert avec étiquette blanche)
