### ISSUE TITLE
feat(ACCESSIBILITE): Formulaires 11.2 : Chaque étiquette associée à un champ de formulaire est-elle pertinente (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2240]
# P07	Domiciliés : Nouvelle demande	https://domifa.fabrique.social.gouv.fr/nouveau

Au moins une étiquette de champ de formulaire n'est pas pertinente.
Par exemple :
1. Étape 1 et 4 : Les placeholders des champs suivants contiennent des informations importantes qui ne sont pas reprises dans les étiquettes : "Nom" et "Ville de naissance" (1) ; "Nom du document" (4).
2. Étape 2 : Les textes qui suivent les boutons radio doivent être liés à ceux-ci.
3. Étape 2 : L'étiquette du champ "Heure" n'est pas traduite (aria-label="Hours").
4. Étape 3 : Le texte "1000 caractères maximum " doit être lié au champ "Commentaires"
5. Étape 4 : Le champ de téléchargement n'est pas lié au bon <label>
Corrections :
1. Ajouter sur les champs un title qui reprend le même niveau d'information. Par exemple pour le champ "Nom" : title="Précisez nom de naissance si nécessaire".
2 et 4. Utiliser des liaisons aria-describedby="[id-texte]" pour lier les textes descriptifs à leur champ.
3. Traduite l'étiquette.
5. Le champ doit être lié au <label> "Nom du document" et non "Parcourir". Le texte "Parcourir" devrait être un simple <p> et non un `<label>`.

# P09	Inscription	https://domifa.fabrique.social.gouv.fr/inscription

Au moins une étiquette de champ de formulaire n'est pas pertinente.
Par exemple :
1. Étape 1 : Les textes sous le champ "Raison sociale ..." doivent être liés à celui-ci.
2. Étape 1 : Certains placeholders contiennent des informations qui ne sont pas reprises dans les étiquettes.
Corrections :
1. Lier le texte en italique au moyen d'une propriété aria-describedby="id-texte" sur le champ.
2. Ajouter sur les champs un title qui reprend le même niveau d'information.

**Comment by Chirazh** [comment]
Vérifier avec l'outil Wave si l'ensemble des étiquettes label ont un libellé associé

**Comment by Chirazh** [comment]
Je vois des étiquettes label mais j'ai l'impression que les corrections listées dans le tickets ne sont pas prises en compte.
