### ISSUE TITLE
feat(ACCESSIBILITE): Formulaires 11.5 : Dans chaque formulaire, les champs de même nature sont-ils regroupés, si nécessaire ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2241]
# P07	Domiciliés : Nouvelle demande	https://domifa.fabrique.social.gouv.fr/nouveau

Des champs de même nature ne sont pas regroupés.

Par exemple :
1. Les boutons radio (étapes 1, 2, 3 et 5 (modale de refus))
2. Les champs relatifs à un même utilisateur dans la partie "ayants-droit" (étape 1)

Corrections :
1, 2. Utiliser l'élément <fieldset> pour regrouper les champs de même nature, et l'élément <legend> pour donner un titre aux regroupements.
- ou utiliser le role="group" et la propriété aria-label=[titre du regroupement] ou aria-labelledby="[@id_titre]"

Précisions :
1. Pour l'étape 2, le regroupement doit contenir les deux cadres contenant les boutons radio et avoir pour légende "Quand souhaitez-vous réaliser l'entretien de XXX ?".
2. Pour ayants-droits, créer autant de regroupements que d'ayants-droits. Chaque regroupement doit avoir pour légende : "Ayant-droit [n°].

Remarque :
Il ne s'agit pas d'une non-conformité mais non attirons votre attention sur le fait que les boutons radio ne possèdent pas d'attributs name comme c'est le cas habituellement. Ceci ne les rend pas inutilisables, néanmoins cela modifie la façon dont ils se comportent lorsqu'on les atteint au clavier. Notamment, l'utilisateur est obligé de passer sur tous les boutons radio d'un groupe alors que la tabulation lui permet de sortir du groupe lorsque les attributs name sont implémentés. Nous vous conseillons donc d'utiliser ces attributs afin d'améliorer l'expérience utilisateur au clavier.

# P09	Inscription	https://domifa.fabrique.social.gouv.fr/inscription

Des champs de même nature ne sont pas regroupés.

Par exemple :
1. Étape 1 et 2 : Les boutons radio "Vous appartenez à…"

Corrections :
- Utiliser l'élément <fieldset> pour regrouper les champs radio et l'élément <legend> pour donner un titre aux regroupements.
- ou utiliser le role="group" et la propriété aria-label=[titre du regroupement] ou aria-labelledby="[@id_titre]"

**Comment by Chirazh** [comment]
Recette : 
Outil RGAA et vérifier que les champs qui sont de même nature ont un label commun

**Comment by pYassine** [comment]
🚀 https://domifa-feat-refacto-structures.dev.fabrique.social.gouv.fr/
