### ISSUE TITLE
feat(ACCESSIBILITE): Formulaires 11.11 : Dans chaque formulaire, le contrôle de saisie est-il accompagné, si nécessaire, de suggestions facilitant la correction des erreurs de saisie ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2244]
# P07	Domiciliés : Nouvelle demande	https://domifa.fabrique.social.gouv.fr/nouveau	

Les champs de saisie en erreur, qui attendent un format particulier, ne sont pas accompagnés d'un exemple réel de saisie.
Par exemple :
- Les champs "Date de naissance", "Numéro de téléphone" et "Adresse e-mail".
Corrections :
- Modifier et compléter les messages d'erreur. Par exemple pour le champ e-mail : "Veuillez saisir une adresse e-mail valide. Par exemple : john.doe@domifa.fr".

# P09	Inscription	https://domifa.fabrique.social.gouv.fr/inscription

Les champs de saisie en erreur, qui attendent un format particulier, ne sont pas accompagnés d'un exemple réel de saisie.
Par exemple :
- Les champs "Code postal", "Numéro de téléphone" et "Adresse e-mail".
Corrections :
- Modifier et compléter les messages d'erreur afin de donner des exemples de saisie réelle.

# P13	Statistiques	https://domifa.fabrique.social.gouv.fr/stats/rapport-activite	Les champs de saisie en erreur, qui attendent un format particulier, ne sont pas accompagnés d'un exemple réel de saisie.
Exemple/Corrections :
- Modifier et compléter les messages d'erreur : "Veuillez saisir une date de début valide. Par exemple : 01/01/2021”

**Comment by Chirazh** [comment]
Recettes : Vérifier les indications en rouge des formulaires en cas de cases vides / erreurs
champs avec formats spéciaux = indication de format
champs obligatoires = invalides

**Comment by Chirazh** [comment]
Création de demande : champs obligatoires mis en évidence lorsque non remplis ok + format du mail demandé lorsque l'on clique sur la case ok 

Inscription d'une structures : messages d'erreurs, de formats pour tous les champs obligatoires ok 

Rapport d'activité : message d'erreur pour le format des dates de début et de fin ok
