### ISSUE TITLE
feat(ACCESSIBILITE): Formulaires 11.13 : La finalité d'un champ de saisie peut-elle être déduite pour faciliter le remplissage automatique des champs avec les données de l'utilisateur ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2245]
# P05	Authentification	https://domifa.fabrique.social.gouv.fr/connexion

Les champs qui attendent une donnée personnelle de l'utilisateur ne sont pas identifiés.
Exemples et corrections :
- Dans le formulaire de connexion, corriger la valeur de l'attribut autocomplete sur le champ "Adresse email" : autocomplete="email".
- Dans le formulaire de réinitialisation de mot de passe, ajouter l'attribut autocomplete="email" sur le champ "Adresse email".

# P09	Inscription	https://domifa.fabrique.social.gouv.fr/inscription

Les champs qui attendent une donnée personnelle de l'utilisateur ne sont pas identifiés.
Exemples et corrections :
Dans l'étape 2, implémenter un attribut autocomplete sur les champs suivants :
- Le champ "Email" : autocomplete="email"
- Le champ "Nom" : autocomplete="family-name"
- Le champ "Prénom" : autocomplete="given-name"
Liste des valeurs possibles : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#liste-des-valeurs-possibles-pour-l-attribut-autocomplete

# P10	Compte	https://domifa.fabrique.social.gouv.fr/mon-compte

Les champs qui attendent une donnée personnelle de l'utilisateur ne sont pas identifiés.
Exemples et corrections :
Implémenter un attribut autocomplete sur les champs suivants :
- Le champ "Email" : autocomplete="email"
- Le champ "Nom" : autocomplete="family-name"
- Le champ "Prénom" : autocomplete="given-name"
Liste des valeurs possibles : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#liste-des-valeurs-possibles-pour-l-attribut-autocomplete

**Comment by pYassine** [comment]
🚀 https://domifa-feat-refacto-structures.dev.fabrique.social.gouv.fr/

**Comment by Chirazh** [comment]
Erreur sur l'ajout d'utilisateurs 


![Image](https://github.com/SocialGouv/domifa/assets/61183619/c87cdf8a-40a4-40af-b1c6-f8fb709513d4)

**Comment by Chirazh** [comment]
Aussi, est ce que l'on doit ajouter un champ autocomplete sur le nom de la structure dans le formulaire de contact support ?

**Comment by Chirazh** [comment]
Dans le formulaire de contact ET dans la création d'utilisateur il est juste écrit "Label" mais il n'y a plus la mention "autocomplete=xxx"
