### ISSUE TITLE
feat(NUMERO_TELEPHONE): ajouter un indicatif de téléphone pour les usagers

### ISSUE THREAD

**Issue by pibouu** [SocialGouv/domifa#2254]
**Environnement**
**https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/**

**Situation Actuelle**

Il n'y a pas d'indicatif sur les usagers. Problématique pour les usagers en DOM-TOM, pour l'envoi des SMS il faut l'indicatif.

**Comportement souhaité**

Permettre l'ajout d'un indicatif sur les usagers.

**Recette PO**
Coté backend
- [ ] Migrations de tout les usagers ayant renseigner le champs phone vers telephone
- [ ] Migrations de tout les préférences usagers ayant renseigner le champs preference.phoneNumber vers preference.telephone (pour recevoir des SMS)
- [ ] Vérifier qu'on affiche bien le numéro de téléphone dans l'email delete-structure
- [ ] Vérifier qu'on affiche bien le numéro de téléphone dans l'email new-structure
- [ ] Vérifier l'envoie de les SMS avec l'indicatif de Paris et des DOM TOM (tout type de SMS)
- [ ] Vérifier qu'il y a bien le numéro de téléphone (avec indicatif) de l'usager dans le document CERFA
- [ ] Vérifier l'indicatif dans l'export des usagers

Coté frontend
- [ ] page création d'un nouveau usager numéro de téléphone + préférence
![Screenshot 2022-05-30 at 21 42 56](https://user-images.githubusercontent.com/5468549/171052048-9068154f-fadd-482a-883d-91aaa145113a.png)

- [ ] page courrier d'un domicilié (il faut que la structure ai les SMS activé) préférence
![Screenshot 2022-05-30 at 21 31 55](https://user-images.githubusercontent.com/5468549/171051863-ccc866f2-0a54-4733-8b96-e3e0ecc6a102.png)

- [ ] page dossier d'un domicilié modification 
![Screenshot 2022-05-30 at 21 45 35](https://user-images.githubusercontent.com/5468549/171052311-6ada931d-416a-44c0-bc99-241c4ac7e0a3.png)

- [ ] indicatif sur l'affichage de tout les numéros de téléphone
- [ ] verifier l'indicatif sur le cerfa de la structure

Coté portail usager
- [ ] page de l'usager section info numéro avec indicatif

**Comment by celinelr** [comment]
@pibouu Peux tu ajouter tous les endroits impactés et sur lesquels je vais devoir recetter s'il te plait ?

**Comment by pibouu** [comment]
@celinelr oui j'attendais d'avoir fini la feature pour voir tous les impacts sur toute l'application

**Comment by celinelr** [comment]
Ok, si tu as les infos avant notre point d'aujourd'hui ca serait top :)

**Comment by pYassine** [comment]
@celinelr  🚀 [domifa-feat-international-number-usagers.dev.fabrique.social.gouv.fr](https://domifa-feat-international-number-usagers.dev.fabrique.social.gouv.fr/)

**Comment by celinelr** [comment]
"Vérifier l'indicatif dans l'export des usagers" l'indicatif est dans l'export mais le numéros ressort avec le premier chiffre "0" ce n'est pas correct n'est ce pas ? 

Par exemple

<img width="818" alt="Capture d’écran 2022-07-08 à 16 35 42" src="https://user-images.githubusercontent.com/86293911/178013383-65b1ef62-045e-4c84-80d2-ec04188eac52.png">
 
Pour le +33 j'aurais du avoir "+331 01 01 01 01" non ?

**Comment by celinelr** [comment]
✅ J'ai le numéro de l'usager sur les documents (attestation, cerfa)

❌ Par contre, si je fais une demande de renouvellement le numéro de téléphone n'est pas renseigné alors qu'il l'etait sur le dossier

**Comment by celinelr** [comment]
# situation actuelle

**Comment by celinelr** [comment]
❌ Je ne peux pas recetter la création de demande 

https://user-images.githubusercontent.com/86293911/178024625-110f493d-8d78-4362-bc9e-d20416ca3b57.mov

<img width="443" alt="Capture d’écran 2022-07-08 à 17 36 50" src="https://user-images.githubusercontent.com/86293911/178024647-e86ad2ab-71ac-4a69-9c49-a9987449a53e.png">

- [ ] L'icone de l'agenda a disparue
- [ ] Je ne peux pas ouvrir select picker des indicatifs

**Comment by celinelr** [comment]
> "Vérifier l'indicatif dans l'export des usagers" l'indicatif est dans l'export mais le numéros ressort avec le premier chiffre "0" ce n'est pas correct n'est ce pas ?
> 
> Par exemple
> 
> <img alt="Capture d’écran 2022-07-08 à 16 35 42" width="818" src="https://user-images.githubusercontent.com/86293911/178013383-65b1ef62-045e-4c84-80d2-ec04188eac52.png">
> 
> Pour le +33 j'aurais du avoir "+331 01 01 01 01" non ?
> 
> Je constate la meme chose sur le CERFA ou les autres documents


Je vois que tu as decidé d'ajouter un colonne indicatif dans l'export pour résoudre le problème.
Je valide le bon fonctionnement
<img width="201" alt="Capture d’écran 2022-07-21 à 11 24 23" src="https://user-images.githubusercontent.com/86293911/180179381-9c15452f-3d51-4612-9bd9-518608b92ac1.png">

**Comment by celinelr** [comment]
> ✅ J'ai le numéro de l'usager sur les documents (attestation, cerfa)
> 
> ❌ Par contre, si je fais une demande de renouvellement le numéro de téléphone n'est pas renseigné alors qu'il l'etait sur le dossier ![Capture d’écran 2022-07-08 à 16 42 21](https://user-images.githubusercontent.com/86293911/178014611-09f8b012-95c4-4389-8954-e0c45ed946e2.png) ![Capture d’écran 2022-07-08 à 16 42 37](https://user-images.githubusercontent.com/86293911/178014663-02837857-fc0c-469c-8402-7adac7b537f2.png)


❌Je ne valide pas complètement ce point. Si la personne a un numéro avec un indicatif autre que +33 alors le champs se met en erreur (en anglais en plus) alors qu'il ne présente aucune erreur.  
Pour reproduire cela il suffit de prendre un dossier avec un numéro + indicatif hors+33 et de cliquer sur "renouvellement" alors, il sera impossible d'aller à l'etape suivante de prise de RDV car le champ numéro de téléphone indique une erreur 

<img width="918" alt="Capture d’écran 2022-07-21 à 11 30 59" src="https://user-images.githubusercontent.com/86293911/180181075-925dc217-c95a-48b6-bfec-7fe080f9eeaf.png">

**Comment by celinelr** [comment]
> ❌ Je ne peux pas continuer les tests sur les documents lors d'un renouvellement car je ne peux pas aller à l'étape suivante
> 
>  Enregistrement.de.l.ecran.2022-07-08.a.16.44.49.mov 
> Aussi, je remarque que le bouton pour revenir au statut précédant est présent mais sans texte ![Capture d’écran 2022-07-08 à 16 47 12](https://user-images.githubusercontent.com/86293911/178015505-b524e084-c7b5-4638-8be4-0372a12b85fb.png)

❌Je ne peux toujours pas aller à l'étape suivante cf #2379

**Comment by celinelr** [comment]
> ❌ Je ne peux pas recetter la création de demande
> 
>  Enregistrement.de.l.ecran.2022-07-08.a.17.35.03.mov 
> <img alt="Capture d’écran 2022-07-08 à 17 36 50" width="443" src="https://user-images.githubusercontent.com/86293911/178024647-e86ad2ab-71ac-4a69-9c49-a9987449a53e.png">
> 
> * [ ]  L'icone de l'agenda a disparue
> * [ ]  Je ne peux pas ouvrir select picker des indicatifs

✅ Je valide la création de démande

**Comment by celinelr** [comment]
Résumé de la recette 

**Recette PO**
Coté backend
- [ ] Migrations de tout les usagers ayant renseigner le champs phone vers telephone
- [ ] Migrations de tout les préférences usagers ayant renseigner le champs preference.phoneNumber vers preference.telephone (pour recevoir des SMS)
- [ ] Vérifier qu'on affiche bien le numéro de téléphone dans l'email delete-structure
- [ ] Vérifier qu'on affiche bien le numéro de téléphone dans l'email new-structure
- [ ] Vérifier l'envoie de les SMS avec l'indicatif de Paris et des DOM TOM (tout type de SMS)
- [ ] Vérifier qu'il y a bien le numéro de téléphone (avec indicatif) de l'usager dans le document CERFA
- [ ] Vérifier l'indicatif dans l'export des usagers

Coté frontend
- [ ] page création d'un nouveau usager numéro de téléphone + préférence
![Screenshot 2022-05-30 at 21 42 56](https://user-images.githubusercontent.com/5468549/171052048-9068154f-fadd-482a-883d-91aaa145113a.png)

- [ ] page courrier d'un domicilié (il faut que la structure ai les SMS activé) préférence
![Screenshot 2022-05-30 at 21 31 55](https://user-images.githubusercontent.com/5468549/171051863-ccc866f2-0a54-4733-8b96-e3e0ecc6a102.png)

- [ ] page dossier d'un domicilié modification 
![Screenshot 2022-05-30 at 21 45 35](https://user-images.githubusercontent.com/5468549/171052311-6ada931d-416a-44c0-bc99-241c4ac7e0a3.png)

- [ ] indicatif sur l'affichage de tout les numéros de téléphone
- [ ] verifier l'indicatif sur le cerfa de la structure


Coté portail usager
- [ ] page de l'usager section info numéro avec indicatif

**Comment by celinelr** [comment]
https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Je close en l'attente de validation de #2402
