### ISSUE TITLE
feat(TESTS): Permettre l'accès à un environnement de test pour les deets et le dreets 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2257]
**Situation Actuelle**

🚀 [domifa-env-ddets.dev.fabrique.social.gouv.fr](https://domifa-env-ddets.dev.fabrique.social.gouv.fr/)

Le besoin vient des agents deets ou dreets qui souhaiterait avoir accès à un environnement de test pour faire des démos de l'outil. 

Il faudrait que tu me documentes le process, les comptes tests, credentials etc 

Merci

**Comment by celinelr** [comment]
- [ ] Créer l'équivalent d'un environnement avec lien spécifique 
- [ ] Ajouter une nouvelle structure avec un nouveau mot de passe 
- [ ] enlever dans le menu "admin domifa" pour ce compte/environnement

**Comment by pYassine** [comment]
@celinelr  🚀 [domifa-env-ddets.dev.fabrique.social.gouv.fr](https://domifa-env-ddets.dev.fabrique.social.gouv.fr/)

**Comment by celinelr** [comment]
Merci tout fonctionne, je peux me connecter

**Comment by celinelr** [comment]
J'ai documenté cela
