### ISSUE TITLE
bug(PORTAIL DOMICILIE): Echec de Redirection vers la page de login 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2266]
**Description du problème**

En tant que domicilié  je me connecte à mon portail avec mon iphone, j'enregistre la page dans mes signets (https://mon-domifa.fabrique.social.gouv.fr/account)
SI je tente de me reconnecter à mon espace via ce lien je ne suis pas redirigée sur la page de login mais je suis dans une boucle infinie 

Note sur navigateur je n'ai pas ce problème, je suis redirigée vers : https://mon-domifa.fabrique.social.gouv.fr/auth/login?returnUrl=%2Faccount

**Comportement attendu**

Description du comportement souhaité

- [ ] Si je suis le lien https://mon-domifa.fabrique.social.gouv.fr/account je dois être rédirigée sur une page de login. Par exemple : https://mon-domifa.fabrique.social.gouv.fr/auth/login?returnUrl=%2Faccount

**Scénario de reproduction du problème**

1. Se connecter avec un iphone au portail domicilé
2. Enregistrer le signet
3. Se deconnecter
4. cliquer sur le signet enregistré
-> je suis dans une boucle infinie de rechargement de la page 

**Copies d'écran**

https://user-images.githubusercontent.com/86293911/168113167-02c75581-b326-4ec5-ab84-dbff978900a2.MP4

**Informations complémentaires:**

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier la bonne redirection du lien https://mon-domifa.fabrique.social.gouv.fr/account

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr le lien que tu indiques dans le ticket à une parenthèse en trop. C'est normal ou juste une erreur ?

 https://mon-domifa.fabrique.social.gouv.fr/accoun**_t)/ac_**count j

**Comment by celinelr** [comment]
> 
C'est bien un erreur dans le ticket. J'utilise ce lien``https://mon-domifa-preprod.dev.fabrique.social.gouv.fr/account``

**Comment by celinelr** [comment]
Merci, je n'ai plus le problème
