### ISSUE TITLE
bug(UI): Certains boutons ont changés de d'aspect

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2273]
**Description du problème**

Situation actuelle 
![Capture d’écran 2022-05-18 à 15 47 00](https://user-images.githubusercontent.com/86293911/169059549-2e0952d0-d293-4e2c-94e9-ad917ef48886.png)

**Comportement attendu**

Description du comportement souhaité

![Capture d’écran 2022-05-18 à 16 01 43](https://user-images.githubusercontent.com/86293911/169059674-2b8cbb2f-4652-4f6d-8f20-d16ac9d20708.png)

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Vérifier les boutons de la fiche d'un domicilé

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
Ticket done non ? :)

**Comment by pYassine** [comment]
Yes done !

**Comment by celinelr** [comment]
Comme il a été livré je le passe comme tel
