### ISSUE TITLE
feat(LEGAL): Actuellement sur le portail domicilié domifa il n'y a pas de footer avec les informations légales 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2292]
**Situation Actuelle**

Actuellement sur le portail domicilié domifa il n'y a pas de footer 

**Comportement souhaité**

Sur le portail domifa [mon-domifa.fabrique.social.gouv.fr](https://mon-domifa.fabrique.social.gouv.fr/auth/login) ajouter un footer  avec les informations suivantes: 
- Nos partenaires 
- [Accessibilité: non conforme](https://domifa.fabrique.social.gouv.fr/assets/files/domifa_declaration-d-accessibilite.pdf) comment aviez-vous généré ce document ? Il faudrait y faire des modifications, sinon je te propose de mettre celle jointe dans le fichier ZIP ci joint [Portail domicile.zip](https://github.com/SocialGouv/domifa/files/8929521/Portail.domicile.zip)

- Mentions légales : La version à utiliser est dans le fichier ZIP ci joint [Portail domicile.zip](https://github.com/SocialGouv/domifa/files/8929521/Portail.domicile.zip)

- [CGU](https://domifa.fabrique.social.gouv.fr/cgu) : mettre les memes que celles de domifa 
- Politique de confidentialité L: a version à utiliser est dans le fichier ZIP ci joint [Portail domicile.zip](https://github.com/SocialGouv/domifa/files/8929521/Portail.domicile.zip)

Faut il ajouter "Sauf mention contraire, tous les textes de ce site sont sous [licence etatlab-2.0](https://github.com/etalab/licence-ouverte/blob/master/LO.md)" ?

![Capture d’écran 2022-05-25 à 17 36 00](https://user-images.githubusercontent.com/86293911/170301054-e3c32b2f-082c-47d3-91a3-f2de2adb9ba3.png)

**Lien vers l'environnement de test**

**ENVIRONNEMENT 👍🏽**
🚀 [domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr](https://domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr/)

**Recette PO**

- [ ] Se connecter à l'admin et vérifer l'ajout du footer ainsi que des liens

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
pour les [CGU] voir mes retours sur #2334

**Comment by celinelr** [comment]
Pour la politique de confidentialité j'ai les memes retours que sur #2334 mais en plus  il fait mention "Passés ces délais de conservation, la DGCS s’engage à supprimer définitivement les données des personnes concernées." alors que ce devrait etre Domifa ... sur celle de domifa nous avons "Passés ces délais de conservation, https://domifa.fabrique.social.gouv.fr/ s’engage à supprimer définitivement les données des personnes concernées.". Je revois avec @OMoukoko en privé le document

**Comment by celinelr** [comment]
Le reste du footer est opérationnel, merci :)

**Comment by celinelr** [comment]
@pYassine voici les documents à jour et à intégrer s'il te plait
[24062022 - [Domifa] - Politique de confidentialité_portail_V2.docx.zip](https://github.com/SocialGouv/domifa/files/8975095/24062022.-.Domifa.-.Politique.de.confidentialite_portail_V2.docx.zip)

**Comment by celinelr** [comment]
@pYassine les CGU ne correspondent pas à la dernière version de celles-ci. cf. #2334 Pourquoi ? 

Sinon, je valide les autres documents

**Comment by pYassine** [comment]
🚀 [domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr](https://domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr/)

**Comment by celinelr** [comment]
Il ne reste plus qu'à valider sur préprod

**Comment by celinelr** [comment]
Je valide
