### ISSUE TITLE
feat(LEGAL): Mettre à jours les documents légaux de domifa 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2334]
**Comportement souhaité**

ENVIRONNEMENT 👍🏽 
🚀 [domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr](https://domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr/)

Sur Domifa https://domifa.fabrique.social.gouv.fr/connexion mettre à jour les pages suivantes 

- [x] Conditions_générales_d_utilisation[Domifa.zip](https://github.com/SocialGouv/domifa/files/8939502/Domifa.zip)
- [x] Politique de confidentialité [Domifa.zip](https://github.com/SocialGouv/domifa/files/8939502/Domifa.zip)

A savoir, les documents sont en "suivi des modifications" pour que ce soit plus simple à réintégrer les changements 
**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Conditions_générales_d_utilisation
- [ ] Politique de confidentialité

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
🚀 [domifa-fix-politique-confidentialite.dev.fabrique.social.gouv.fr](https://domifa-fix-politique-confidentialite.dev.fabrique.social.gouv.fr/)

**Comment by celinelr** [comment]
merci !

**Comment by celinelr** [comment]
Pour les [Domifa]_Conditions_générales_d_utilisation_V4

# Situation actuelle
1. Dans la rubrique "Fonctionnalités proposées" : il manque la phrase d'introduction "Le titulaire du compte administrateur dispose alors des fonctionnalités suivantes :"
2. Dans la rubrique "Fonctionnalités proposées" : Toutes les phrase s'enchaine sans point dans les sous-rubrique "Émission de documents" et  "Actions relatives à la domiciliation"
<img width="1049" alt="Capture d’écran 2022-06-22 à 12 12 53" src="https://user-images.githubusercontent.com/86293911/175004458-4044e146-5d18-4b24-93bb-6a4ffe39e11f.png">

4. Dans "Inscription au portail domicilié" il est dit :
"L’Usager peut demander et obtenir l’inscription au portail domicilié. L’usager reçoit un mail qui lui ouvre un lien vers [mon-domifa.fabrique.social.gouv.fr/auth/login](https://mon-domifa.fabrique.social.gouv.fr/auth/login)"

# Situation Souhaitée 
1. Dans la rubrique "Fonctionnalités proposées" : ajouter  la phrase d'introduction "Le titulaire du compte administrateur dispose alors des fonctionnalités suivantes :"
2. Dans la rubrique "Fonctionnalités proposées" : Toutes les phrase s'enchaine sans point dans les sous-rubrique "Émission de documents" et  "Actions relatives à la domiciliation" -> Mettre à la ligne chacune des phrase commençant par "L'agent"
![Capture d’écran 2022-06-22 à 12 13 05](https://user-images.githubusercontent.com/86293911/175004517-f3fdfc69-4bc3-45bf-b813-914bc862c869.png)

3. Dans "Inscription au portail domicilié"remplacer :
"L’Usager peut demander et obtenir l’inscription au portail domicilié. L’usager reçoit un mail qui lui ouvre un lien vers [mon-domifa.fabrique.social.gouv.fr/auth/login](https://mon-domifa.fabrique.social.gouv.fr/auth/login)" par "L’Usager peut demander à la structure et obtenir l’inscription au portail domicilié. L’usager reçoit un papier de la structure qui lui indique ces identifiant ainsi que le lien vers [mon-domifa.fabrique.social.gouv.fr/auth/login](https://mon-domifa.fabrique.social.gouv.fr/auth/login)"

**Comment by celinelr** [comment]
Pour les Conditions_générales_d_utilisation j'ai écris à @OMoukoko sur mattermost pour en rediscuter. J'ai un doute sur la version du document

**Comment by celinelr** [comment]
@pYassine voici les documents à jour et à intégrer s'il te plait
[Domifa document V2 .zip](https://github.com/SocialGouv/domifa/files/8975092/Domifa.document.V2.zip)

**Comment by celinelr** [comment]
Pour les [Domifa]_Conditions_générales_d_utilisation_V4

# Situation actuelle
- Dans la rubrique "Fonctionnalités proposées" : il manque la phrase d'introduction "Le titulaire du compte administrateur dispose alors des fonctionnalités suivantes :"
-  Dans la rubrique "Fonctionnalités proposées" : les deux premières rubriques "Suppression des domiciliés de la structure" et "Tableau de bord des demandes" font doublons 
![Capture d’écran 2022-07-06 à 18 33 26](https://user-images.githubusercontent.com/86293911/177600977-c1c27839-855f-421a-a7f0-0a67d6fd9792.png)

- Dans "Inscription au portail domicilié" il est dit :
"L’Usager peut demander et obtenir l’inscription au portail domicilié. L’usager reçoit un mail qui lui ouvre un lien vers [mon-domifa.fabrique.social.gouv.fr/auth/login](https://mon-domifa.fabrique.social.gouv.fr/auth/login)"


# Situation Souhaitée

- [ ] Dans la rubrique "Fonctionnalités proposées" : ajouter la phrase d'introduction "Le titulaire du compte administrateur dispose alors des fonctionnalités suivantes :"

- [ ] Dans la rubrique "Fonctionnalités proposées" : supprimer les deux premières rubriques "Suppression des domiciliés de la structure" et "Tableau de bord des demandes" qui font doublons 


- [ ] Dans "Inscription au portail domicilié" remplacer :
"L’Usager peut demander et obtenir l’inscription au portail domicilié. L’usager reçoit un mail qui lui ouvre un lien vers [mon-domifa.fabrique.social.gouv.fr/auth/login](https://mon-domifa.fabrique.social.gouv.fr/auth/login)" par "L’Usager peut demander à la structure et obtenir l’inscription au portail domicilié. L’usager reçoit un papier de la structure qui lui indique ses identifiants ainsi que le lien vers [mon-domifa.fabrique.social.gouv.fr/auth/login](https://mon-domifa.fabrique.social.gouv.fr/auth/login)"

**Comment by celinelr** [comment]
Pour  https://domifa-preprod.dev.fabrique.social.gouv.fr/confidentialite

# Situation actuelle

- Dans la rubrique "Finalités" il y a une coquille au dernier bullet point un "-" en trop
<img width="1063" alt="Capture d’écran 2022-07-06 à 18 50 17" src="https://user-images.githubusercontent.com/86293911/177602399-357338df-b7fc-409f-97b7-838422381ce0.png">

# Situation souhaitée

- Dans la rubrique "Finalités" il y a une coquille au dernier bullet point retier le "-" en trop

**Comment by pYassine** [comment]
https://domifa-fix-docs-legaux.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Merci, je valide tout

**Comment by celinelr** [comment]
A tester sur préprod
