### ISSUE TITLE
feat(LEGAL): Ajout des documents legaux sur le portail admin domifa

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2335]
**Situation Actuelle**

**ENVIRONNEMENT 👍🏽**
🚀 [domifa-fix-politique-confidentialite.dev.fabrique.social.gouv.fr](https://domifa-fix-politique-confidentialite.dev.fabrique.social.gouv.fr/)

Actuellement le portail admin de domifa https://admin-domifa.fabrique.social.gouv.fr/ ne dispose de footer avec des documents légaux 
<img width="1424" alt="Capture d’écran 2022-06-17 à 19 33 33" src="https://user-images.githubusercontent.com/86293911/174349278-b77030cc-b9dd-4995-af5a-195431af01a4.png">

**Comportement souhaité**

Copier le footer de domifa dans admin domifa 

**A faire après ce ticke**t [feat(LEGAL): Mettre à jours les documents légaux de domifa](https://github.com/SocialGouv/domifa/issues/2334#)
#2334 pour que tous les documents soient à jour

<img width="1430" alt="Capture d’écran 2022-06-17 à 19 34 00" src="https://user-images.githubusercontent.com/86293911/174349360-4994c7ab-aa2a-4db4-babb-058f617796f8.png">

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Vérifier que mon domifa dispose du footer et des documents 
- [ ] 
**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
**ENVIRONNEMENT 👍🏽**
🚀 [domifa-fix-politique-confidentialite.dev.fabrique.social.gouv.fr](https://domifa-fix-politique-confidentialite.dev.fabrique.social.gouv.fr/)

**Comment by celinelr** [comment]
@pYassine voici le document modifer et à intégrer s'il te plait
[24062022 - [Domifa] - Politique de confidentialité_portail_V2.docx.zip](https://github.com/SocialGouv/domifa/files/8975084/24062022.-.Domifa.-.Politique.de.confidentialite_portail_V2.docx.zip)

**Comment by celinelr** [comment]
cf remarques sur #2334

**Comment by celinelr** [comment]
A tester sur préprod

**Comment by celinelr** [comment]
Je valide
