### ISSUE TITLE
bug(STATS PUBLIQUE):  Les stats sont différentes entre la home et la page des stats

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2347]
**Description du problème**

L es stats sur la page d'accueil vs sur la page de stat publique sont différentes -> pas le meme nombre de structures ou de domiciliés

De ce que je sais :  Les stats de la home page sont mise en cache pendant 24h mais pas celles des stats générales

**Comportement attendu**

Le besoin est d'avoir sur les 2 pages les mêmes chiffres. Je te laisse décidé de la méthode approprié (retirer le cache sur la home, ou ajouter le cache sur la page de stat générale)

**Scénario de reproduction du problème**

1. Se connecter sur la prod https://domifa.fabrique.social.gouv.fr/ et sur https://domifa.fabrique.social.gouv.fr/stats
2. Comparer les chiffres 

**Copies d'écran**

Les chiffres sur https://domifa.fabrique.social.gouv.fr/ 
![Capture d’écran 2022-06-24 à 12 44 15](https://user-images.githubusercontent.com/86293911/175519362-f0bc5a9f-6673-46c9-a227-d0c6a0ad698b.png)

et sur https://domifa.fabrique.social.gouv.fr/stats

![Capture d’écran 2022-06-24 à 12 45 01](https://user-images.githubusercontent.com/86293911/175519361-effcab90-83f2-4e71-a295-04dbfeea8ec9.png)

![Capture d’écran 2022-06-24 à 12 45 06](https://user-images.githubusercontent.com/86293911/175519354-7904c46a-beb2-4c3a-b6af-4d4439d9d2d7.png)

**Informations complémentaires:**

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier la différence entre les chiffres sur https://domifa.fabrique.social.gouv.fr/  et sur https://domifa.fabrique.social.gouv.fr/stats

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
@pYassine Je n'ai pas ce problème sur la préprod, comment pourrais-je recetter ce ticket une fois livré  ?

**Comment by celinelr** [comment]
Méthodologie de recette : 

- Il faudrait faire un screen maintenant, créer des structures + interactions
- Ouvrir la home + les stats et actualiser demain voir si c'est les même chiffres

**Voici l'état actuel des stats :**

![Capture d’écran 2022-07-06 à 17 44 16](https://user-images.githubusercontent.com/86293911/177591791-676ee2dc-334f-476c-b543-c63aef23b233.png)

- J'ai ajouté une structure dans le 93 "structure test stat"
- J'ai validé le compte et créé un domicilié
- J'ai enregistré 2 courriers que j'ai distribué  
- J'ai ajouté un courrier qui est en attente de distribution

**Comment by celinelr** [comment]
<img width="1432" alt="Capture d’écran 2022-07-07 à 10 04 29" src="https://user-images.githubusercontent.com/86293911/177723312-9c08ddb1-ac4b-406b-af95-80d92d86b3d4.png">

@pYassine j'ai toujours les memes chiffres ce matin, est ce normal ?

**Comment by pYassine** [comment]
@celinelr oui c'est 24h après la création du cache donc a l'heure où t'as testé hier

**Comment by celinelr** [comment]
aaah ok !

**Comment by celinelr** [comment]
Après 24h voici les stats à jours 

![Capture d’écran 2022-07-08 à 12 09 27](https://user-images.githubusercontent.com/86293911/177971151-9ea8e584-d583-459e-87bf-d5d45dc242f1.png)


J'ai bien :
- une structure en plus 
- un domicilié en plus 
- 3 courriers enregistrés en plus dont 2 courriers distribués

Je valide l'US

**Comment by celinelr** [comment]
@pYassine J'ai toujours une différence sur la prod

<img width="871" alt="Capture d’écran 2022-07-19 à 11 44 04" src="https://user-images.githubusercontent.com/86293911/179720567-14c52231-bd8a-4c9f-99d7-9dd59e057253.png">
<img width="1181" alt="Capture d’écran 2022-07-19 à 11 43 21" src="https://user-images.githubusercontent.com/86293911/179720573-e5f63d2b-7857-4256-93ca-af18269b7327.png">

**Comment by celinelr** [comment]
Comme je ne peux pas tester ce ticket sur préprod, je le valide pour livraison prod

**Comment by achauve** [comment]
@pYassine tu avais fais quoi pour ce ticket finalement ?
Avec les 2 réplicas tu ne peux pas garder de cache local au backend, il faut passer par une base type Redis. Ou alors stocker les données précalculées dans une table SQL et les recalculer via un cron ou des procédures SQL.

Dans un premier temps, le plus simple est peut-être de désactiver le cache, on pourra suivre les perfs en prod via l'APM et voir si c'est ça joue beaucoup ou pas.

**Comment by pYassine** [comment]
@achauve Pour l'instant j'ai ajouté une génération à la mise en prod. Je pensais faire une tache cron qui regénère le cache tous les soir plutôt que repartir sur un stockage en DB ou Redis

**Comment by celinelr** [comment]
- [ ] Désactiver le cache sur la home et sur la page de stats

**Comment by pYassine** [comment]
@celinelr  https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/
J'ai supprimé tout le cache qu'il pouvait y avoir

**Comment by celinelr** [comment]
Merci Yassine, comme je ne peux pas recette sur cet environnement je le valide pour livraison prod et je checkerai en prod
