### ISSUE TITLE
bug(SMS): Investiguer l'erreur recurrente "sms-messages-consumer"

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2371]
**Description du problème**
Depuis quelques semaines nous avons cette erreur récurrente sur la prod : 

> Sms error: SMS | L'expéditeur est invalide.

**Pour tester :**
- Je remplis le nom de l'expéditeur avec un ou des espaces vides, je dois voir une erreur sur le formulaire
- Je mettre au moins un caractère pour que le formulaire soit valide

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr  Lien pour tester 
https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/structures/sms

**Comment by pYassine** [comment]
**A Tester aussi :** 
[] Quand j'édite les préférences de SMS d'un usager, je ne dois pas pouvoir ajouter de numéro de fixe. _Exemple, je ne peux pas écrire "0101010101" dans le champs numéro de téléphone pour les SMS._

**Comment by celinelr** [comment]
Ce qui est étrange ce que l'on propose dans le champs en exemple de rentrer un 01 alors que le texte au dessus demande un 06 

<img width="581" alt="Capture d’écran 2022-07-27 à 11 20 07" src="https://user-images.githubusercontent.com/86293911/181211063-66636382-bf16-4cf1-8ac7-098b119d6ff3.png">
11


Aussi, j'ai pu ajouter un numéro de téléphone fixe

<img width="1440" alt="Capture d’écran 2022-07-27 à 11 20 41" src="https://user-images.githubusercontent.com/86293911/181211160-24a20be1-6f0a-4e8b-84c9-9b46e1a04d84.png">
![Capture d’écran 2022-07-27 à 11 20 41 (2)](https://user-images.githubusercontent.com/86293911/181211178-6bb16d38-7419-4e8e-a92a-58a18d9ffc65.png)
1

**Comment by celinelr** [comment]
Je n'arrive pas à enregistrer de 07 pour la france métropolitaine

<img width="588" alt="Capture d’écran 2022-07-27 à 16 24 11" src="https://user-images.githubusercontent.com/86293911/181271581-f3ea7aea-daa2-49a6-a1af-2e1aa518ae10.png">


Je n'arrive pas à enregistrer de 06 pour les Dom Tom
<img width="574" alt="Capture d’écran 2022-07-27 à 16 27 44" src="https://user-images.githubusercontent.com/86293911/181272441-12ad4846-63ac-4f8b-b8ea-2b05e2b5ca9a.png">

**Comment by celinelr** [comment]
Merci, je valide ce ticket
