### ISSUE TITLE
feat(DATA): Automatiser la mise à jour de la préprod pour avoir des statistiques à jour sur Metabase

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2375]
**Situation Actuelle**

Les données de la preprod ne se mettent pas à jour automatiquement avec celles de la prod, ce qui pose problème pour les statistiques 

**Comportement souhaité**

Description du comportement souhaité

- [x] Rendre automatique la mise à jour de la preprod à 24h
- [x] Préciser sur Metabase la date de dernière mise à jour des données

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier que la préprod sur met à jour en comparant avec les données en prod
- [x] Vérifier que Metabase prend les données à jour et que la mention de la date de dernière mise à jour est inscrite

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine 

La mention de la date de dernière mise à jour n'est pas inscrite

Le nombre de structures est à 1309 sur la préprod contre 1384 an prod les autres chiffres semblent être proches de la prod sans être exactement pareil 

L'axe "Fonctionnement des structures" ne fonctionne pas en prod et préprod

Il manque le libellé " Non spécifié" dans les indicateurs Axe 1 "Répartition par nationalité" et Suivi des structures "Organismes agréés"

Les chiffres dans Axe 3 - Courrier colis avis de passage ont triplés je sais si c'est normal

**Comment by Chirazh** [comment]
@pYassine est ce que c'est normal que la date soit au 22/03/24 alors que les chiffres des domiciliés sont proches de ceux d'aujourd'hui ?
