### ISSUE TITLE
bug(TELEPHONE): Le champ SMS se met en erreur lorsque je modifie l'état civil d'un domicilié

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2379]
## Description du problème

- Je vais sur dans le dossier d'un domicilié. 
- Son numéro de téléphone est renseigné +262 0262 01 01 01
    - Dans l'onglet dossier le numéro de téléphone est renseigné
    - Dans l'onglet courrier il souhaite recevoir des sms et le numéro de téléphone est renseigné +262 0262 01 01 01
- Je vais dans l'onglet dossier et j'édite son etat civil. Dans le cas présent je retire le nom d'usage. 
- **Premier problème** : Le numéro de téléphone ce met en erreur alors qu'il n'y a pas d'erreur. J'enlève un caractère et j'en rajoute un et l'erreur disparait -> Ce n'est pas normal
- **Second problème** : Lorsque je vais dans courrier maintenant l'on m'indique que l'utilisateur ne souhaite pas utiliser les SMS et son numéro de téléphone n'apparait plus 
-
## Comportement attendu

- [ ] Lorsque je modifie l'état civil d'un domicilié, le champ numéro de téléphone ne doit pas se mettre en erreur, d'autant dans le cas où je n'y touche pas 
- [ ] Lorsque je modifie l'état civil d'un domicilié, le domicilié doit toujours pouvoir recevoir ces sms. Il faudrait mettre à jour le champ téléphone dans l'onglet courrier. Voici l'issue : #2380 

**Copies d'écran**

https://user-images.githubusercontent.com/86293911/178021733-54e10c29-636e-4aed-9769-059d0b88da89.mov

**Informations complémentaires:**

**Lien vers l'environnement de test**

**https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/**

**Recette PO**

- [ ] Etant donné que l'agent de la structure met à jour l'etat civil du domicilié sans toucher au numéro de téléphone lorsqu'il clique sur valider alors le formulaire s'enregistre sans erreur 
- [ ] verifier ce comportement sur un dossier 
- [ ]   verifier ce comportement sur un renouvellement

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
@pYassine Peux tu ajouter un test unitaire s'il te plait ?

Etant donné que l'agent de la structure ne modifie pas le numéro de téléphone lorsqu'il clique sur valider alors le formulaire s'enregistre sans erreur sur le champ téléphone

**Comment by pYassine** [comment]
@celinelr Noté, j'ajoute un test. Apparement le souci n'existe que pour les numéros de La réunion, le 0 qui est automatiquement ajouté empêche ensuite la validation du numéro :/

**Comment by celinelr** [comment]
Merci pour le test, ce qui est étrange alors c'est que le numéros de téléphone soit accepté au début. Car il est accepté et ce n'est qu'à l'édition de ce numéro que celui ressort en erreur

**Comment by celinelr** [comment]
https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Je close, ce ticket n'a pu lieu d'etre #2254
