### ISSUE TITLE
bug(DISTRIBUTION): Il manque une refresh sur la liste des radiés 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2400]
**Description du problème**

Lorsque je suis sur la liste des personnes radiées si j'ajoute du courrier ou que je le distribue, le bouton de distribution ne s'actualise pas. 

Je dois refresh la page pour que le bouton apparaisse ou disparraisse

**Comportement attendu**

Description du comportement souhaité

- [ ] Je vais sur la liste des radiés 
- [ ] J'ajoute du courrier "simple"
- [ ] Le bouton distribution apparait avec une pastille dessus
- [ ] En cliquant sur le bouton celui disparait si j'ai tout distribué

**Scénario de reproduction du problème**

1. Se connecter en tant qu'agent de structure
2. Aller sur la page 'radiés'
3. Cliquer sur 'ajout rapide d'un courrier'
4. Le bouton distribution n'apparait pas 

**Copies d'écran**

https://user-images.githubusercontent.com/86293911/180749437-df91ed85-5b57-4ddc-ba87-51b0b81895fa.mov

**Informations complémentaires:**

Il faudrait ajouter un test unitaire 

Scenario :Ajouter un courrier 
Étant donné que je suis un agent de structure et que je suis sur la page des radiés
Lorsque je clique sur ajouter du courrier 
Alors je dois voir apparaitre le bouton de distribution du courrier 

Scenario : Distribuer un courier 
Étant donné que je suis un agent de structure et que je suis sur la page des radiés 
Lorsque je clique sur distribuer un courrier 
Alors le bouton de distribution du courrier doit disparaitre 

**Lien vers l'environnement de test**

**https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/**

**Recette PO**

- [ ] Reproduire le scénario : Ajouter un courrier 
- [ ] Reproduire le scénario :  Distribuer un courier 

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
https://domifa-fix-international-phones-form.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
✅ Je valide le fait que lorsque j'enregistre du courrier le bouton "distribuer" apparait 

❌ par contre lorsque je clique pour distribuer le courrier celui ci devrait disparaitre mais ce n'est pas le cas

https://user-images.githubusercontent.com/86293911/181212558-93ff9e24-72ee-4cc2-a78b-edbe3238a9a4.mov

**Comment by celinelr** [comment]
Merci, je valide la reception et distribution de courrier pour les radiés

**Comment by celinelr** [comment]
Merci, je valide que je peux enregistrer et délivrer du courrier pour une personne radiée
