### ISSUE TITLE
feat(PROCURATION): Limiter le nombre de procuration  à 5

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2417]
**Situation Actuelle**

Actuellement je peux mettre que deux procurations maximum. 

**Comportement souhaité**

Il ne faudrait limiter ce nombre de procurations à 4 

Liste des domiciliés

- [x] Je dois voir une pastille "procurations". Au survol je dois voir toutes les procurations
<img width="1311" alt="Capture d’écran 2022-08-08 à 11 16 19" src="https://user-images.githubusercontent.com/86293911/183384650-e433d796-3a9a-46a9-a12e-303d8f32ce8b.png">

    - Enlever le mot "procuration" et ne garder que "actif" 
    - Afficher les 4 premières procurations

- [x]  Distribution du courrier : si j'indique que c'est un mandataire qui le récupère, je dois voir le nom et prénom du mandataire dans l'historique des courriers
- [x]  Si des mandataires sont présents, je dois pouvoir indiquer qui a réceptionné le courrier
<img width="646" alt="Capture d’écran 2022-08-08 à 11 18 49" src="https://user-images.githubusercontent.com/86293911/183384517-5817f047-a412-462e-b167-122a36365785.png">

- [ ]  Dans la création de documents personnalisés, je dois voir le premier mandataire s'afficher si j'utilise le mot "PROCURATION_NOM"

Fiche domicilié

- [ ]  Affichage des panneaux procurations dans la fiche domicilié

<img width="1300" alt="Capture d’écran 2022-08-08 à 11 15 33" src="https://user-images.githubusercontent.com/86293911/183384712-e6e61815-cde8-469c-8bf6-f6fe43313e93.png">

Interface domicilié 

- [ ] Affichage des panneaux procurations dans l'interface domicilié

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] tester 0, 1, 2 ,5 procuration

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Devoda** [comment]
Bonjour,
Je souhaite contribuer à votre projet.

Pourriez-vous m'apporter votre aide ? Je n'ai pas compris ce point :
- [ ] Dans la création de documents personnalisés, je dois voir le premier mandataire s'afficher si j'utilise le mot "PROCURATION_NOM"
![image](https://user-images.githubusercontent.com/113156134/192903554-9f08096f-38e1-4b22-9b3b-afba00a66615.png)

Si je me trompe de page, pourriez-vous me détailler comment accéder a la page "documents personnalisés".

-----

- [ ] Si des mandataires sont présents, je dois pouvoir indiquer qui a réceptionné le courrier
Cela sous entends qu'il faut identifier chaque courrier/colis.
Avez-vous fixé l'UX à utiliser ? Ou les proposition son libre ?

Bien à vous,

**Comment by Devoda** [comment]
Merci @celinelr d'avoir pris le temps de répondre à mes questions.
Oui c'est bien plus clair (je supposais qu'un domicilié pouvait récupérer ses colis en plusieurs fois voir à plusieurs).

J'ai encore une question :
Un domicilié peut-il ajouter/supprimer un mandataire depuis le portail-usagers ?

PS : Je ne travaille pas pour une structure de domiciliation. Je souhaite contribuer à votre projet pour deux raisons. Cela me permet d'apprendre et de me reconvertir professionnellement.

**Comment by celinelr** [comment]
Un domicilié peut récupérer soit  : tout; soit que les lettres simples, soit que les colis, soit que les avis de passage 

Non, l'espace usager est uniquement du display d'information. Vous pouves telecharger la doc sur le portail pour voir à quoi il ressemble :) 

Merci pour ces precisions ! N'hesitez pas à nous ecrire depuis github dans l'onglet discussions

**Comment by celinelr** [comment]
@pYassine voici les tests KO

- [ ] "Si des mandataires sont présents, je dois pouvoir indiquer qui a réceptionné le courrier"
La modale doit pouvoir contenir les 5 mandataires. 
Il faudrait les passer à la ligne. 
![Capture d’écran 2022-10-27 à 17 26 35](https://user-images.githubusercontent.com/86293911/198332529-bc0ab16d-eac5-4471-9bcd-428f7dee9250.png)


Aussi, j'ai une erreur 500 lorsque je tente de distribuer le courrier avec l'un des mandataires au dessus du 2eme mandataire 


![Capture d’écran 2022-10-27 à 17 27 08](https://user-images.githubusercontent.com/86293911/198333628-1706d039-cb9e-4dbc-af2e-c040d1772259.png)

![Capture d’écran 2022-10-27 à 17 26 55](https://user-images.githubusercontent.com/86293911/198333659-f0416356-9f82-4759-a101-78587ac5e949.png)

**Comment by celinelr** [comment]
Je valide :  

- L'ajout des 5 procurations
![Capture d’écran 2022-10-27 à 17 14 16](https://user-images.githubusercontent.com/86293911/198333853-00a31523-172c-4585-beb4-04cc02a77e6a.png)

- Les bandeaux d'information sur le dossier du domicilié
![Capture d’écran 2022-10-27 à 17 14 52](https://user-images.githubusercontent.com/86293911/198333874-e466fd6c-df79-4e91-818e-d0eda85f1b7e.png)

**Comment by pYassine** [comment]
https://domifa-fix-sentry-maintenance.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Je valide 

- Je dois voir une pastille "procurations". Au survol je dois voir toutes les procurations
    - Enlever le mot "procuration" et ne garder que "actif"
    - Afficher les 5 premières procurations

<img width="284" alt="Capture d’écran 2022-11-04 à 18 12 10" src="https://user-images.githubusercontent.com/86293911/200035302-4e39f53c-7ee6-419a-b1c4-5cc8b1fa44e7.png">

 "Si des mandataires sont présents, je dois pouvoir indiquer qui a réceptionné le courrier"
La modale doit pouvoir contenir les 5 mandataires.
<img width="612" alt="Capture d’écran 2022-11-04 à 18 18 22" src="https://user-images.githubusercontent.com/86293911/200036601-0e637197-86cd-4263-8e31-b6c515eda352.png">


Distribution du courrier : si j'indique que c'est un mandataire qui le récupère, je dois voir le nom et prénom du mandataire dans l'historique des courriers
<img width="507" alt="Capture d’écran 2022-11-04 à 18 19 15" src="https://user-images.githubusercontent.com/86293911/200036803-d26a608b-b0a5-440c-9e6e-3859d04aaefd.png">

**Comment by celinelr** [comment]
J'ai aussi testé l'accessibilité de la modale avec voice over notamment et Wave et cela me semble accessible et surtout compréhensible ! Merci :D

**Comment by celinelr** [comment]
Je valide pour livraison en prod

**Comment by celinelr** [comment]
Je valide tout sur preprod, go pour prod
