### ISSUE TITLE
feat(Portail): Donner la possibilité de choisir si la date de passage se met à jour en fonction de la connexion au portail usager

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2450]
**Situation Actuelle**

Actuellement la date de passage ne se met pas à jour si le domicilié se connecte à son compte usager. 

**Comportement souhaité**

Permettre à la structure de choisir si oui ou non une connexion au portail mettra à jour la date de passage  
- [ ] Logger les connexions sur le portail (date de connexion + ID usager)
- [ ] Dans la rubrique "Paramètres d'accès au portail usager pour votre structure" En dessous de "Activer l'accès au portail usager pour vos domiciliés oui/non" Si la réponse est oui alors  ajouter la question: "Mettre à jour la date de dernier passage du domicilié s'il se connecte au portail usager" réponse OUI/NON.
   - [ ] S'ils cochent oui: alors la date de passage du domicilié se met à jour dans son dossier et une ligne est ajouté dans l'historique "Connexion au portail usager enregistré"
   - [ ] S'ils cochent non : alors la date de dernier passage ne se met pas à jour et une ligne est ajouté dans l'historique "Connexion au portail usager enregistré"
 - [ ] Stat : Ajouter un nouvel item "Connexion au portail usager " dans la rubrique "3. Total des interactions " 
 - [ ] Dans l'export  des stat ajouter une colonne " Connexion au portail usager" 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier la date de dernier passage 
- [x] Vérifier l'historique
- [x] Vérifier que seul l'admin peut modifier ce choix
- [x] vérifier les stats 
- [x] verifier l'export des stats

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr https://domifa-feat-connexion-portail.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Par Contre je ne valide pas 
- Stat : Ajouter un nouvel item "Connexion au portail usager " dans la rubrique "3. Total des interactions " -> la rubrique aparait mais comme "enfant de "“Pli non distribuable enregistré”  alors quelle devrait placé à gauche
<img width="943" alt="Capture d’écran 2022-09-27 à 15 30 10" src="https://user-images.githubusercontent.com/86293911/192542110-ab9ca250-bcf3-44f5-b687-f3921cc9560c.png">
- Aussi, je ne vois pas apparaitre de chiffres à coté. Pas de décompte des connexions et pas de 0 dans le cas de 0 connexions

- Dans l'export des stat ajouter une colonne " Connexion au portail usager" Elle n'apparait pas 
<img width="770" alt="Capture d’écran 2022-09-27 à 15 31 57" src="https://user-images.githubusercontent.com/86293911/192542419-9f301848-ff58-4945-ab3d-28d32c00ca52.png">

**Comment by celinelr** [comment]
Je valide tout, à merger sur preprod

**Comment by celinelr** [comment]
Merci je valide en préprod
