### ISSUE TITLE
feat(Export): ajouter dans l'export des données une colonne "Numéro de distribution spéciale (BP, TSA, etc)"

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2452]
**Situation Actuelle**
Suite au ticket #2428 

**Comportement souhaité**

- Ajouter dans l'export une colonne "Numéro de distribution spéciale (BP, TSA, etc)"
- Renseigner ce champ s'il l'est dans le dossier du domicilié 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier avec un usager avec un numéro TSA 
- [ ] vérifier avec un usager sans un numéro TSA 

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr https://domifa-fix-edit-user.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Merci Yassine, je valide
