### ISSUE TITLE
feat(SMS): Mettre à jour le guide des SMS

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2453]
**Situation Actuelle**

Jusqu'à aujourd'hui nous pouvions connaitre le statut des sms et maintenant ce ne sera plus le cas. Il faut donc mettre à jour le guide explicatif des sms

**Comportement souhaité**

Remplacer le guide par cette version : 
[Document_Explicatif_Notifications_SMS.pdf](https://github.com/SocialGouv/domifa/files/9605469/Document_Explicatif_Notifications_SMS.pdf)

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier le guide dans mon compte > notification sms

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr https://domifa-fix-edit-user.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Merci yassine, je valide
