### ISSUE TITLE
feat(EMAIL): Supprimer le lien vers typeform dans l'email recu après activation d'un compte

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2474]
**Situation Actuelle**

Dans l'email "[DOMIFA] Votre compte Domifa a été activé" 

<img width="631" alt="Capture d’écran 2022-10-10 à 13 51 39" src="https://user-images.githubusercontent.com/86293911/194860037-2a29d871-024f-4a8c-a2be-d82ce8eaee33.png">

Il y a marqué : "Pour vous accompagner au mieux dans votre utilisation de DomiFa, il vous est possible de vous inscrire à une session de présentation en ligne sur le lien suivant :

[lien]"

**Comportement souhaité**

Remplace "Pour vous accompagner au mieux dans votre utilisation de DomiFa, il vous est possible de vous inscrire à une session de présentation en ligne sur le lien suivant :

[lien]"

Par 
Pour vous accompagner au mieux dans votre utilisation de DomiFa, il vous est possible de vous inscrire à une session de présentation en nous écrivant à l'adresse suivante : contact.domifa@fabrique.social.gouv.fr"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier le changement dans l'email recu suite à l'activation d'un compte

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr https://domifa-fix-sentry-errors.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Merci je valide

![Capture d’écran 2022-10-11 à 11 44 16](https://user-images.githubusercontent.com/86293911/195056539-1e19c41e-2444-45c9-8428-725465801238.png)
