### ISSUE TITLE
feat(COURRIER CUSTOM): Ajout et suppression/modification de champs dans le guide de courrier paramétrable

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2480]
**Situation Actuelle**
Il y a de nouvelle demandes de clés. 

**Comportement souhaité**

Voici le document à remplacer : 
[Document_Explicatif_Courriers_Paramétrables.pdf](https://github.com/SocialGouv/domifa/files/9763835/Document_Explicatif_Courriers_Parametrables.pdf)
Aussi téléchargeable ici : https://nextcloud.fabrique.social.gouv.fr/apps/files/?dir=/DomiFa/DEVELOPPEMENT/Courriers_Param%C3%A9trables&fileid=16167 

Voici les modification que j'ai apporté :
- Correction de coquilles 
- Correction de mise en page 
- Dans la section "Procuration" suppression de "Adresse de l’établissement"
- Dans la section "Entretien" précision des libellé {ENTRETIEN_DOMICILIATION_EXISTANTE} et {ENTRETIEN_REVENUS}
- Ajout des éléments suivants 
   - Le TSA  -> {USAGER_NUMERO_DISTRIBUTION_SPECIALE} Numéro de distribution spéciale (BP, TSA, etc) > dans la section 'Contact du domicilié'
   - La liste des ayants droits avec nom prénom et date de naissance > ajout de la section AD > {AYANTS_DROITS_LISTE} Tous les ayants droit : Nom, prénom et date de naissance
   - Le mail de la structure : {STRUCTURE_ADRESSE_EMAIL} Adresse e-mail de la structure > dans la section "Structure"
   - Le rattachement à une ville ou un arrondissement > "{ENTRETIEN_RATTACHEMENT} Rattachement à une ville ou un arrondissement" > dans la section "Entretien"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier chacun des nouveaux libellé

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr voici un document qui te permettra de tester la validité de tous les champs. Tu peux l'uploader sur une structure et le générer sur différents dossiers, ça te permettra de voir si les données se complètent bien

[Uploading test-doc-word-domifa.docx…]()

**Comment by pYassine** [comment]
@celinelr https://domifa-feat-custom-docs-ad.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
J'ai testé sur https://domifa-fix-sentry-maintenance.dev.fabrique.social.gouv.fr/news 

Merci, le document est le bon et j'ai testé le courrier paramétrable avec la nouvelle clé, elle fonctionne.
