### ISSUE TITLE
bug(ERREUR): comprendre quand s'affiche la pop-in maintenance

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2481]
**Description du problème**

Il semblerait que régulièrement la pop in de maintenance s'affiche sur DomiFa alors qu'il n'y a pas de MEP.
Il faudrait comprendre quand celle-ci s'affiche.

Je suspecte qu'elle s'affiche après déconnexion du user au bout de 1h ou un peu plus d'un heure

<img width="1439" alt="Capture d’écran 2022-10-13 à 14 53 58" src="https://user-images.githubusercontent.com/86293911/195602102-b677e6f0-df6a-4eea-ad49-69805010d143.png">

 Tracker la pop-in dans sentry ou matomo 

Il faudrait changer le wording de la pop-in pour inviter à rafraichir la page 

Le texte actuelle etant  "Veuillez nous excuser pour la gêne occasionnée.
Vous pourrez de nouveau utiliser DomiFa dans quelques minutes.
Cette fenêtre disparaitra dès la fin de la maintenance."

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr finalement j'ai totalement retiré le health check côté frontend. Ca va drastiquement réduire la charge sur le backend et les logs seront plus facile à décrypter en cas de souci

**Comment by celinelr** [comment]
Rien de spécial à valider de ma part, ok pour livraison sur prod
