### ISSUE TITLE
feat(CGU): En tant que responsable de structure je dois accepter les CGU pour créer mon compte de structure

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2576]
## **Situation Actuelle**

Actuellement il n'y a pas de CGU de responsable de structure et donc pas d'obligation des les accepter

## **Comportement souhaité**

Description du comportement souhaité

- [x] Ajouter dans la page CGU celles du Responsable structure https://nextcloud.fabrique.social.gouv.fr/apps/onlyoffice/176738?filePath=%2FDomiFa%2FJURIDIQUE%20-%20SECURITE%20-%20RGPD%2FRGPD%2F20221218_Domifa_CGU_Responsable_structure.docx 
- Dans la création d'une structure en dessous du bloc "Qui est le responsable légal ?"
 - [x] Ajouter un case à cocher " Je confirme que le responsable de la structure a lu les CGU du responsable de structure [lien vers la page qui doit s'ouvrir dans une autre tab au clic]"
<img width="945" alt="Capture d’écran 2022-12-23 à 17 03 03" src="https://user-images.githubusercontent.com/86293911/209364630-7e8702bb-489b-421e-905c-27d2c8082a92.png">
- [ ] Ajouter en dessous, "Le responsable de la structure accepte les CGU du responsable de structure[lien vers la page des CGU]". 

- Règle de gestion : 
  - s'il ne coche pas ces 2 cases, alors, il ne peut pas accéder à l'étape suivante un message d'erreur s'affiche "Vous ne pouvez pas passer à l'étape suivante sans avoir lu et accepté les CGU du responsable de structure"
  - S'il accepte alors garder une trace dans une table avec la date de l'acceptation

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] tester ce nouveau parcours 
- [x] Vérifier l'implémentation des nouvelles CGU dans le footer

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@celinelr la date d'acceptation sera forcément la date d'inscription, inutile d'en créer une autre

**Comment by celinelr** [comment]
OK !

**Comment by celinelr** [comment]
Merci, j'ai créer une structure sans problème et j'ai accepté les CGU du responsable.

Je valide pour livraison sur prod
