### ISSUE TITLE
feat(ListeDOM): Gérer en masse les suppressions et radiations - (étape 1/2)

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2611]
## **Situation Actuelle**

Actuellement les structures peuvent supprimer ou radier un domicilié un par un domicilié depuis leur dossier. 
Ceci est très chronophage.

## **Comportement souhaité**

En tant que structure je souhaite pouvoir radier ou supprimer en masse les domiciliés. 
Je suis censée pouvoir sélectionner des filtres puis après faire ma sélection dans cette liste filtrée ou meme tout selectionner 

Le prototype cliquable est accessible ici : https://www.figma.com/proto/Vaw23ZETph6ZVZTVqJEIPw/Domifa-(Florent)-(Copy)?node-id=2051%3A60802&scaling=min-zoom&page-id=2051%3A57008&starting-point-node-id=2051%3A57009&show-proto-sidebar=1 

Les design sont accessibles ici  : https://www.figma.com/file/Vaw23ZETph6ZVZTVqJEIPw/Domifa-(Florent)-(Copy)?node-id=2051%3A57009&t=ndZx3XlvJXd46yEo-0 

Qui à accès la gestion de masse ?
- [x] Seuls les gestionnaires et administrateurs pourront supprimer en masse les domiciliés 
- [x] Seuls les instructeurs, Gestionnaires et Administrateurs pourront radier en masse les domiciliés 

Comment accéder à la gestion de masse ?
- [x] Je peux sélectionner la radiation que dans l'onglet des domiciliés actifs =  Je ne peux pas radier les domiciliés, "radiés", "a compléter","en attente" ou "refusés". 
- [x] Dans l'onglet tous, je ne peux pas sélectionner de domiciliés et accéder à la gestion de masse de radiation. Car les domiciliés ont des statuts différents. Par contre, je vois la gestion de masse pour la suppression dans tous les onglets
- [x] Si je sélectionne des filtres et que je sélectionne des domiciliés puis que j'ajoute de nouveau un filtre en plus  -> cette action amène à décocher tous les domiciliés qui étaient déjà cochés. De la même façon, si je change d'onglet au court de ma sélection, les domiciliés déjà sélectionnés seront décochés.
- [x] Les domiciliés déjà cochés doivent rester cochés si je vais plus bas dans la liste des domiciliés.

## **Lien vers l'environnement de test**

https://domifa-feat-multiple-choice.dev.fabrique.social.gouv.fr/manage

## **Recette PO**

- [x] Je vois la gestion de masse pour la radiation que dans l'onglet actif 
- [x] Je vois la gestion de masse pour la suppression dans tous les onglets
- [x] Quand je clique sur "supprimer les X domiciliés", la fenêtre qui s'ouvrent indique le texte d'avertissement au pluriel. "Si vous supprimez ces X domiciliés, vous ne pourrez plus, etc"
- [x] Tester pour chacun des profils la gestions de masse instructeurs, Gestionnaires et Administrateurs  mais aussi facteur 
- [x] Facteur : n'a pas accès à la gestion de masse 
- [x] Gestionnaires et Administrateurs : peuvent radier et supprimer 
- [x] Instructeurs : peut seulement radier 
- [x] Selectionner des filtres et après supprimer ou radier les domiciliés
- [x] Sélectionner des filtres, cocher des personnes puis reselectionner de nouveaux filtres -> cela doit déselectionner les personnes précédemment sélectionnées
- [x] déselectionner toutes les personnes  : en ajoutant un filtre en cours de selection
- [x] déselectionner toutes les personnes : en cliquant sur la case titre de colonne après avoir sélectionné au moins un domicilié dans la liste. Alors, la case titre de colonne représente un signe moins "-" et permet de tout déselectionner. Pour l'accessibilité est il possible de mettre "Désélectionner tous les dossiers" dans ce cas ?
- [x] Je dois pouvoir supprimer ou radier un domicilié depuis sa fiche
- [x] Dans les statistiques, quand je supprime 2 dossiers, le nombre total de dossier doit correspondre (si 10 avant, je dois en avoir 8 après suppression)
- [x] Dans les statistiques, quand je radies 4 dossiers actifs, je dois voir le nombre de radiés augmenter de 4

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
Premiere recette @chiraz   :rocket: : 
https://domifa-feat-multiple-choice.dev.fabrique.social.gouv.fr/manage

Changements pris en compte : 
- Bug quand on clique sur le filtre "dernier passage" 
- Taille du logo revue
- Quelques améliorations dans le design pour que les filtres prennent moins de place

**Comment by pYassine** [comment]
[] Vérifier qu'on peut toujours radier ou supprimer un usager sur le profil
