### ISSUE TITLE
feat(ACCESSIBILITE): 10.13 : Dans chaque page web, les contenus additionnels apparaissant à la prise de focus ou au survol d'un composant d'interface sont-ils contrôlables par l'utilisateur (hors cas particuliers ) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2613]
# P06 : https://domifa.fabrique.social.gouv.fr/manage

L'utilisateur ne peut pas contrôler les contenus additionnels apparaissant à la prise de focus ou au survol.

Par exemple :
- Les tooltips ne peuvent pas être survolées.

## Correction :
Le contenu additionnel qui apparaît au survol ou à la prise de focus :
- doit pouvoir être survolé à la souris ;
- doit rester visible tant que la souris survole l'élément déclencheur ou que le focus est positionné dessus ;
- doit pouvoir être masqué sans que le focus ou la souris soit déplacé (par exemple par l'activation de la touche [ESCAPE]).

**Comment by Chirazh** [comment]
On ne peut pas survoler le contenu additionnel avec la souris

**Comment by pYassine** [comment]
🚀 https://domifa-feat-refacto-structures.dev.fabrique.social.gouv.fr/

**Comment by Chirazh** [comment]
Le survol du tag "Procuration" n'est pas sélectionnable contrairement aux autres
S'il n'y a pas de survol après une procuration le survol reste ouvert
