### ISSUE TITLE
feat(MONDOMIFA): Permettre aux domiciliés d'accéder à des informations externes sur le suivi social - Simulateur Aides Jeunes

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2647]
**Situation Actuelle**

Actuellement nous n'avons pas de rubriques "autres" sur Mon DomiFa

**Comportement souhaité**

Ajouter entre la rubrique "Votre domiciliation" et le bouton "me déconnecter" une rubrique "Mes liens utiles" 
<img width="540" alt="Capture d’écran 2023-02-08 à 17 07 02" src="https://user-images.githubusercontent.com/86293911/217587514-85fbe835-4de8-41be-89ae-7952c48bc4d1.png">

- [ ] Ajouter un lien de redirection vers mes aides financières de 1 jeune 1 solution : https://mes-aides.1jeune1solution.beta.gouv.fr/?utm_source=domifa

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Vérifier l'ajout de la rubrique ainsi que le lien de redirection de mes aides financières

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by alizeeeeeee** [comment]
test

**Comment by Chirazh** [comment]
Inspiration phrase d'introduction : 
"Découvrez les aides et prestations sociales auxquelles vous êtes éligibles en vous rendant sur le site AidesJeunes"
