### ISSUE TITLE
feat(SECURITE): Chiffrement des documents

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2676]
**Comportement souhaité**

- [ ] chiffrer les documents avec le nouveau système de chiffrement de la Fabrique 
- [ ] Compresser les documents

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Vérifier que l'on peut ouvrir tous les documents 

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
@pYassine je te laisse compléter le ticket avec tous les éléments tech + les specs pour la recette

**Comment by pYassine** [comment]
Note : tester la structure 
- 1286 | Attestation postale | 21/02/2023
