### ISSUE TITLE
feat(ACCESSIBILITE): Présentation 10.11 : Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à la fois à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou une largeur de 320px (hors cas particuliers ) ? / AUDIT Le site est responsive

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2696]
## P04 : https://domifa.fabrique.social.gouv.fr/faq

Dans une fenêtre de 320px de large, le contenu n'est plus totalement lisible (le contenu est tronqué) ou il est nécessaire d'utiliser la barre de défilement horizontal.

Par exemple :
- Les vidéos sont tronquées.

Correction :
- Modifier les directives CSS, notamment veiller aux points de rupture CSS, afin que l'ensemble du contenu puisse être consulté dans une fenêtre de 320px et ce, sans avoir recours à la barre de défilement horizontal.

## P06 : https://domifa.fabrique.social.gouv.fr/manage
Dans une fenêtre de 320px de large, le contenu n'est plus totalement lisible (le contenu est tronqué) ou il est nécessaire d'utiliser la barre de défilement horizontal.

Par exemple :
- Le titre de la page, le champ de recherche et le bouton "Créer une demande" se chevauchent.

Correction :
- Modifier les directives CSS, notamment veiller aux points de rupture CSS, afin que l'ensemble du contenu puisse être consulté dans une fenêtre de 320px et ce, sans avoir recours à la barre de défilement horizontal.

## P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)
Dans une fenêtre de 320px de large, le contenu n'est plus totalement lisible (le contenu est tronqué) ou il est nécessaire d'utiliser la barre de défilement horizontal.

Par exemple :
- Les numéros et textes des étapes se chevauchent.
- Étapes 4 et 5 : le tableau des pièces jointes est tronqué en largeur.

Correction :
- Modifier les directives CSS, notamment veiller aux points de rupture CSS, afin que l'ensemble du contenu puisse être consulté dans une fenêtre de 320px sans avoir recours à la barre de défilement horizontal (hormis pour les tableaux de données) et sans perte d'information (contenus tronqués ou chevauchements).
- Permettre le défilement horizontal sur le tableau de données.

## P11 : https://domifa.fabrique.social.gouv.fr/admin
Dans une fenêtre de 320px de large, le contenu n'est plus totalement lisible (le contenu est tronqué) ou il est nécessaire d'utiliser la barre de défilement horizontal.

Par exemple :
- Les contenus sont tronqués en largeur.

Correction :
- Modifier les directives CSS, notamment veiller aux points de rupture CSS, afin que l'ensemble du contenu puisse être consulté dans une fenêtre de 320px sans perte d'information et sans avoir recours au défilement horizontal (hormis pour le tableau de données).

**Comment by Chirazh** [comment]
Clique droit - inspecter - image téléphone - responsive - largeur 300 - zoom 100%

**Comment by Chirazh** [comment]
@pYassine dans les corrections qui sont demandées plus haut il y a la page admin qui est mentionnée mais cela me semble impossible avec le tableau. Les menus déroulants sont lisibles ainsi que les stats.

Reste des pages de la plateforme OK
