### ISSUE TITLE
feat(SMS): Désactiver l'envoi de SMS pour tous les numéros non conformes

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2698]
**Situation Actuelle**

Actuellement les sms sont envoyés aux numéros qui figurent dans le champs "numéro de téléphone". Cela concerne également les numéros erronés qui peuvent être saisis ex: 0606060606.
De ce fait, certains sms sont envoyés à des numéros non valides et cela engendre une dépense de crédit inutile.

**Comportement souhaité**

Pour tous les numéros erronés, ne pas leur envoyer les sms.

- [ ] (DRAFT à préciser avec Yassine)
- [x] Bloquer la saisie des numéros non conformes
- [x] Bloquer l'import de numéros non conformes
- [ ] Prévenir les structures que les sms n'ont pas été envoyés aux numéros identifiés comme non conforme en précisant l'ID et nom et prénom du domicilié concerné

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Assigner un numéro non conforme à un dossier domicilié
- [ ] Importer un domicilié avec un numéro non conforme 
- [ ] (DRAFT Mettre à jour lorsque les actions seront définies)

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine ajouter nombre de sms envoyés avec un retour d'erreur ou nombre de numéros non conformes / nombre total de dossiers avec sms activés

**Comment by pYassine** [comment]
- Affichage qui indique qu'on ne peut pas envoyer de sms aux numéros étrangers
- La liste déroulante des pays s'affiche correctement
