### ISSUE TITLE
feat(ACCESSIBILITE): Présentation 10.7 : Dans chaque page web, pour chaque élément recevant le focus, la prise de focus est-elle visible ? / AUDIT Le site est utilisable au clavier

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2703]
# P01 : https://domifa.fabrique.social.gouv.fr/

La prise de focus n'est pas visible pour tous les éléments de la page.
Par exemple :
- Les éléments interactifs (boutons, liens) qui ont l'apparence de boutons (classe CSS "btn")

Corrections :
- Supprimer toutes les directives (outline: none, outline-color, etc.) visant à dégrader ou supprimer l'indication visuelle de focus.
- OU surcharger ces directives pour rétablir l'indication visuelle du focus.
- OU définir un style du focus qui soit suffisamment contrasté (ratio minimum de 3:1 entre les couleurs du focus et les couleurs environnantes).

# P05 : https://domifa.fabrique.social.gouv.fr/connexion

La prise de focus n'est pas visible pour tous les éléments de la page.
Par exemple :
- Les champs de formulaire

Corrections :
- Supprimer toutes les directives (outline: none, outline-color, etc.) visant à dégrader ou supprimer l'indication visuelle de focus.
- OU surcharger ces directives pour rétablir l'indication visuelle du focus.
- OU définir un style du focus qui soit suffisamment contrasté (ratio minimum de 3:1 entre les couleurs du focus et les couleurs environnantes).

**Comment by celinelr** [comment]
@Chirazh avant de le passer en todo il faudrait le tester, car d'après notion, il aurait pu être réglé

**Comment by Chirazh** [comment]
Recette : 
Que chaque élément sélectionné avec la tabulation soit mis en évidence (contour, gras etc)
Maj + Tab pour revenir en arrière
"Créer une demande" à améliorer

**Comment by Chirazh** [comment]
Homepage : les deux premiers logos sont entourés mais pas les autres, on peut retirer je pense
Dans toutes les pages : Le titre de la page "Nouveautés" 
Page Nouveautés : les différentes pop-up 
Page Domiciliés : "Créer une demande" pas assez évident
Page Mon compte - Document : "Télécharger le guide" pas assez évident
Page Mon compte - SMS : "Vidéo explicative" et "Télécharger le guide" pas assez évident
Page Mon compte - Portail Domicilié : "Télécharger le guide" pas assez évident et le "Non" de la première question
Le bouton aide "?" n'est jamais sélectionnable

**Comment by Chirazh** [comment]
Aussi, comment vérifier que les ratios entre les couleurs sont ok ?

**Comment by pYassine** [comment]
@Chirazh Le bouton aide est sélectionné des la 2eme tabulation normalement

**Comment by Chirazh** [comment]
Homepage : les deux premiers logos de structures sont entourés mais pas les autres, on peut retirer je pense
Page Nouveautés : les différentes pop-up
