### ISSUE TITLE
feat(ACCESSIBILITE): Éléments obligatoires 8.6 : Pour chaque page web ayant un titre de page, ce titre est-il pertinent ? / AUDIT Le titre de la page est composé du titre du contenu suivi du nom du site

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2704]
# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9

Le titre de la page n'est pas pertinent.
Correction :
- Modifier le titre de la page de façon à reprendre l'id et le nom-prénom. Exemple : <title>Fiche d'un domicilié : M. Garidaud ALFRED - 01</title>.

# P11 : https://domifa.fabrique.social.gouv.fr/admin

Le titre de la page n'est pas pertinent.
Correction :
- Modifier le titre de la page sur le modèle : <title>Utilisateurs Domifa</title> ou <title>Membres actifs Domifa</title>

Recette 
-Partir du plan du site
-Vérifier que le nom de la page dans l'onglet est pertinent

**Comment by celinelr** [comment]
@Chirazh avant de le passer en todo il faudrait le tester, car d'après notion, il aurait pu être réglé. Il faudrait aussi vérifier les autres pages de DomiFa

**Comment by Chirazh** [comment]
Demande de renouvellement et création de demande --> est-ce qu'on laisse "Etat-Civil" ou bien est ce que l'on précise "Création de demande étape Etat-Civil", le commentaire est valable pour toutes les étapes
Gestion la structure --> Modifier les informations de votre structure

**Comment by Chirazh** [comment]
Harmoniser avec mon/ma les catégories et les titres de pages

![Image](https://github.com/SocialGouv/domifa/assets/61183619/91c827f2-a2d1-46c3-9edd-37f4145f0724)
