### ISSUE TITLE
feat(ACCESSIBILITE): Couleurs 3.1 : Dans chaque page web, l'information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2705]
# P06 : https://domifa.fabrique.social.gouv.fr/manage

Au moins une information donnée uniquement par la couleur n'a pas d'alternative.
Par exemple :
- L'indication de filtre "statut" actif

Corrections :
- Ajouter une mise en forme (soulignement, changement de taille, inversion des contrastes, bordure, etc.).

# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9
Au moins une information donnée uniquement par la couleur n'a pas d'alternative.
Par exemple :
- L'indication de lien actif dans la navigation par onglets

Corrections :
- Pour l'indication de lien actif, ajouter une mise en forme (mise en gras, changement de taille, inversion des contrastes, soulignement) et un attribut title sur le modèle "[Intitulé] - page active"

**Comment by pYassine** [comment]
Page de liste des domiciliés 
La solution mise en place est un fond blanc et un contour pour mettre en avant l'onglet sur lequel nous sommes actuellement.

![Capture d’écran 2023-04-28 à 00 46 26](https://user-images.githubusercontent.com/11486845/235006759-23b6d174-98c3-4637-b21a-1f7c407c5a16.jpg)
