### ISSUE TITLE
feat(ACCESSIBILITE): Script 7.3 : Chaque script est-il contrôlable par le clavier et par tout dispositif de pointage (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2706]
# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)

Au moins un composant ou une fonctionnalité JavaScript n'est pas utilisable au clavier.
Par exemple :

- [x] 1. Les n° des étapes
- [x] 2. Étape 1 et 3 : Les icônes (?) faisant apparaître des tooltips au survol
- [x] 3. Étape 1 : Dans la partie "ayants-droit", les boutons de suppression et le bouton "Ajouter"
- [x] 4. Étape 2 : boutons "Réaliser l'entretien maintenant" et "Modifier la date du rendez-vous"

Corrections :
1. Utiliser des liens <a>. Inclure le texte des étapes dans ces liens.
2, 3, 4. : Utiliser des <button>.
2. Donner un intitulé au bouton au moyen d'un aria-label="info". La propriété aria-describedby ajoutée sur l'icône à l'affichage de la tooltip doit être déplacée sur ce bouton.
3. Donner des intitulés aux boutons de suppression au moyen d'attributs title reprenant les légendes de regroupements (voir 11.5), par exemple : "Supprimer ayant-droit 2".

# P09 : https://domifa.fabrique.social.gouv.fr/inscription (tout le processus d'inscription)
Au moins un composant ou une fonctionnalité JavaScript n'est pas utilisable au clavier.
Par exemple :
- Étape 1 : Les boutons radio "Vous appartenez à…"

Correction :
- Supprimer la propriété display:none et positionnez-les hors écran.

# P12 : https://domifa.fabrique.social.gouv.fr/import
Au moins un composant ou une fonctionnalité JavaScript n'est pas utilisable au clavier.
Par exemple :
- Étape 1 : Le bouton de téléchargement (<input type="file">)

Correction :
- Supprimer la propriété display:none et positionnez l'<input> hors écran.

**Comment by celinelr** [comment]
@Chirazh  avant de le passer en todo il faudrait le tester, car d'après notion, il aurait pu être réglé

**Comment by Chirazh** [comment]
Tester avec la tabulation
