### ISSUE TITLE
feat(ACCESSIBILITE): Présentation 10.3 : Dans chaque page web, l'information reste-t-elle compréhensible lorsque les feuilles de styles sont désactivées ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2708]
# P01 : https://domifa.fabrique.social.gouv.fr/	

L'ordre de lecture des éléments n'est pas toujours cohérent.
Par exemple :
- Le message relatif à la collecte des données devrait se trouve juste avant le footer dans le code de la page.

Corrections :
- Déplacer le message en tout premier dans le code de la page, avant le lien d'accès rapide au contenu principal (voir 12.7).

# P06 : https://domifa.fabrique.social.gouv.fr/manage	
L'ordre de lecture des éléments n'est pas toujours cohérent.
Par exemple :
- Le lien "Créer une demande" se trouve entre le champ de recherche et les éléments permettant de filtrer les résultats de la recherche.

Corrections :
- Déplacer le lien avant le champ de saisie dans le code HTML. Visuellement, il peut rester à la même place.

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
L'ordre de lecture des éléments n'est pas toujours cohérent.
Par exemple :
1. Étape 4 : Le tableau des fichiers téléchargés se trouve après le bouton permettant de passer à l'étape suivante dans le code HTML.
2. Étape 5 : Le récapitulatif de la demande se trouve après les boutons décisionnels dans le code HTML.

Corrections :
1. Déplacer le tableau entre le formulaire et le bouton. OU implémenter un lien d'accès rapide (caché hors écran si nécessaire) au tableau avant les boutons.
2. Déplacer le récapitulatif après les boutons. OU implémenter un lien d'accès rapide (caché hors écran si nécessaire) au récapitulatif avant les boutons.

**Comment by pYassine** [comment]
Pas encore traité : 


Déplacer le récapitulatif après les boutons. OU implémenter un lien d'accès rapide (caché hors écran si nécessaire) au récapitulatif avant les boutons.
