### ISSUE TITLE
feat(ACCESSIBILITE): Couleurs 3.3 : Dans chaque page web, les couleurs utilisées dans les composants d'interface ou les éléments graphiques porteurs d'informations sont-elles suffisamment contrastées (hors cas particuliers ) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2709]
# P05 : https://domifa.fabrique.social.gouv.fr/connexion
Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- Bordures des champs de formulaire : #ced4da / #ffffff (ratio 1,49)

Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P06 : https://domifa.fabrique.social.gouv.fr/manage	
Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- La zone de saisie de texte dans les modales "Réception" et "Distribuer" : #cfcfd9 / #f9f9fc (ratio 1,47)

Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- L'icône des étapes terminées : #00E457 / #FFFFFF (ratio 1,72)

Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9	
Au moins un composant d'interface ou un élément graphique porteur d'information n'est pas suffisamment contrasté.
Par exemple :
- Le bouton de fermeture de la modale de Suppression : #6D1A22 / #DC3545 (ratio 2,55)

Corrections :
- Contrôler tous les contrastes des composants d'interface et des éléments graphiques et vérifier qu'ils sont suffisants (3:1).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

**Comment by celinelr** [comment]
@Chirazh avant de le passer en todo il faudrait le tester, car d'après notion, il aurait pu être réglé

**Comment by Chirazh** [comment]
Mon compte - Utilisateurs - Flèches noires sur fond vert - dans le tableau des utilisateurs
