### ISSUE TITLE
feat(ACCESSIBILITE): Tableaux 5.6 : Pour chaque tableau de données, chaque en-tête de colonnes et chaque en-tête de lignes sont-ils correctement déclarés ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2710]
# P04 : https://domifa.fabrique.social.gouv.fr/faq	
Les cellules d'en-têtes ne sont pas correctement déclarées pour au moins un tableau de données.
Par exemple :
- Les en-têtes de colonne du tableau dans "En cas d’incident majeur sur la plateforme..."

Corrections :
- Implémenter les cellules d'en-tête de ligne dans des éléments <th scope="row">.

# P06 : https://domifa.fabrique.social.gouv.fr/manage	
Les cellules d'en-têtes ne sont pas correctement déclarées pour au moins un tableau de données.
Par exemple :
- La dernière cellule de la première ligne, qui contient le bouton "Imprimer", ne constitue pas une cellule d'en-tête.

Corrections :
- Utiliser un élément <td> au lieu de <th> pour cette cellule.
- Optionnellement, toutes les autres cellules <td> de cette colonne étant vides, vous pouvez les cacher pour les technologies d'assistance au moyen de propriétés aria-hidden="true".

# P11 : https://domifa.fabrique.social.gouv.fr/admin
Les cellules d'en-têtes ne sont pas correctement déclarées pour au moins un tableau de données.
Par exemple :
- Les en-têtes de ligne du tableau des rôles utilisateurs

Corrections :
- Implémenter les cellules d'en-tête de ligne dans des éléments <th scope="row">.

# P13 : https://domifa.fabrique.social.gouv.fr/stats/rapport-activite	
Les cellules d'en-têtes ne sont pas correctement déclarées pour au moins un tableau de données.
Par exemple :
- Tous les tableaux

Corrections :
- L'utilisation de tableaux semble peu pertinente dans ce cas, et les solutions pour les rendre conformes seraient peu satisfaisantes à l'utilisation.
Nous vous recommandons d'utiliser des listes au lieu de tableaux.
Exemple :
````<ul>
<li>Total des domiciliés actifs + leurs ayants-droit : 26
<ul>
<li>Nombre de domiciliés : 12</li>
<li>Nombre d'ayants-droit : 14</li>
</ul>
<ul>
<li>Nombre de domiciliés actifs par sexe
<li>Femme : 5</li>
<li>Homme : 7</li>
</ul>
</li> (...)
</ul>
OU autre possibilité :
<h5>Total des domiciliés actifs + leurs ayants-droit : 26</h5>
<ul>
<li>Nombre de domiciliés : 12</li>
<li>Nombre d'ayants-droit : 14</li>
</ul>
<h5>Nombre de domiciliés actifs par sexe</h5>
<ul>
<li>Femme : 5</li>
<li>Homme : 7</li>
</ul> (...)````

**Comment by celinelr** [comment]
@Chirazh avant de le passer en todo il faudrait le tester, car d'après notion, il aurait pu être réglé

**Comment by Chirazh** [comment]
Tous les endroits du site où il y a des tableaux
Commande vocale + Wave vérifier si colonne header

**Comment by Chirazh** [comment]
J'aimerais vérifier avec toi que le tableau des utilisateurs se lit correctement avec le guide vocal
