### ISSUE TITLE
feat(ACCESSIBILITE): Tableaux 5.7 : Pour chaque tableau de données, la technique appropriée permettant d'associer chaque cellule avec ses en-têtes est-elle utilisée (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2711]
# P06 : https://domifa.fabrique.social.gouv.fr/manage	
Les cellules de données ne sont pas correctement liées aux cellules d'en-tête pour au moins un tableau de données.
Par exemple :
1. Les cellules d'en-tête de colonne ne possèdent pas d'attribut scope.
2. Les cellules de données de la colonne "Nom Prénom" possèdent un attribut scope="row"

Corrections :
1. Ajouter les attributs scope="col" sur les balises `<th>`.
2. Supprimer les attributs scope dans la colonne "Nom Prénom".

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
Les cellules de données ne sont pas correctement liées aux cellules d'en-tête pour au moins un tableau de données.
Par exemple :
- Étapes 4 et 5 : le tableau de pièces jointes

Corrections :
- Ajouter des attributs scope="col" sur les balises `<th>`.

# P11 : https://domifa.fabrique.social.gouv.fr/admin	
Les cellules de données ne sont pas correctement liées aux cellules d'en-tête pour au moins un tableau de données.
Par exemple :
- Les en-têtes de colonne du tableau des rôles utilisateurs

Corrections :
- Ajouter les attributs scope="col" sur les balises `<th>`.

# P12 : https://domifa.fabrique.social.gouv.fr/import	
Les cellules de données ne sont pas correctement liées aux cellules d'en-tête pour au moins un tableau de données.
Par exemple :
- Le tableau à l'étape 2

Corrections :
- Ajouter les attributs scope="col" sur les balises `<th>`

**Comment by Chirazh** [comment]
Vérifier dans tout le site, où il y a des tableaux
Wave - que chacun intitulé de colonne a un column header

**Comment by Chirazh** [comment]
Tableau des utilisateurs - fonctionnalités est "Column header cell" alors que les autres sont "Table header cell" est-ce que c'est normal ?
