### ISSUE TITLE
feat(ACCESSIBILITE): Structuration 9.1 : Dans chaque page web, l'information est-elle structurée par l'utilisation appropriée de titres ? / AUDIT La hiérarchie des titres est cohérente

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2712]
# P01 : https://domifa.fabrique.social.gouv.fr/	
La hiérarchie des titres n'est pas pertinente.
Par exemple :
1. Dans la modale "Les dernières nouveautés ...", les textes en gras devraient être des titres.

Corrections :
1. Utiliser des titres de niveau 5..
Remarque : si l'utilisation des éléments titres html est problématique, il est possible de créer des titres avec les propriétés aria-level et role="heading" : `<div role="heading" aria-level="1">XXX</div>`

# P06 : https://domifa.fabrique.social.gouv.fr/manage	
La hiérarchie des titres n'est pas pertinente.
Exemple/Corrections :
- Le titre de la page, "Domiciliés" doit être un `<h1>`.
- Si l'utilisation des éléments titres html est problématique, il est possible de créer des titres avec les propriétés aria-level et role="heading" : `<div role="heading" aria-level="1">XXX</div>`

P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
La hiérarchie des titres n'est pas pertinente.
Par exemple :
- Étape 5 : La hiérarchie des titres n'est pas cohérente

Corrections :
- Les titres du récapitulatif doivent être de inférieur au titre "Le dossier de XXX est complet". Ce titre devrait être un `<h1>` et les suivants des `<h2>`.
- Si l'utilisation des éléments titres html est problématique, il est possible de créer des titres avec les propriétés aria-level et role="heading" : `<div role="heading" aria-level="1">XXX</div>`

# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9	
La hiérarchie des titres n'est pas pertinente.
Exemple/Corrections :
- Le texte en haut de page dans le bandeau bleu doit être un `<h1>`.
- Si l'utilisation des éléments titres html est problématique, il est possible de créer des titres avec les propriétés aria-level et role="heading" : `<div role="heading" aria-level="1">XXX</div>`

**Comment by Chirazh** [comment]
Homepage : 
Simplifiez la domiciliationpour les personnes sans --> ajouter un espace

Nouveautés : 
Dans la modale "Les dernières nouveautés ...", les textes en gras devraient être des titres.

Page Manage : OK

Page Création de dom : OK

Page Dossier domicilié : OK

**Comment by pYassine** [comment]
Homepage : l'espace est bien présent, HeadingMaps ne le comprend pas simplement, mais il est bien là

Page nouveautés : Les titres qui devraient être en "h2" sont les dates. Et comme ça ne sont que des dates, les basculer en titre n'apporterait rien à la navigation des personnes.
