### ISSUE TITLE
feat(ACCESSIBILITE): Structuration 9.2 : Dans chaque page web, la structure du document est-elle cohérente (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2713]
# P01 : https://domifa.fabrique.social.gouv.fr/	
La structure du document n'est pas pertinente.
Par exemple :
- Il manque l'élément `<header>` et l'élément `<main>`.

Corrections :
- Implémenter les éléments suivants :
- `<header role="banner">` sur la zone d'en-tête ;
- `<main role="main">` sur le contenu principal.
- Extraire les liens vers la page d'accueil de l'élément `<nav>`.
Remarque :
Bien que ce ne soit pas une non-conformité, afin d'améliorer l'expérience utilisateur, nous vous recommandons de ne pas créer de "sauts" dans la hiérarchie des titres, par exemple passe d'un `<h1>` ou `<h2>` à un `<h4>`.

# P04 : https://domifa.fabrique.social.gouv.fr/faq	La structure du document n'est pas pertinente.
Par exemple :
- Il manque un élément `<nav>` sur les ancres.
Corrections :
Implémenter `<nav role="navigation" arial-label="Sommaire">` sur autour de la liste des ancres.

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
La structure du document n'est pas pertinente.
Par exemple :
- Il manque l'élément `<nav>`sur la liste des étapes.

Corrections :
Implémenter un élément `<nav role="navigation" aria-label="Etapes">` autour de la liste des étapes.

# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9	
La structure du document n'est pas pertinente.
Exemple/Corrections :
Implémenter un élément `<nav role="navigation" aria-label="Menu secondaire">` sur les liens présentés en onglets.

**Comment by Chirazh** [comment]
Tester les ancres
Regarder dans le code les`nav`

**Comment by Chirazh** [comment]
Home page : je vois le `main` et le `footer` mais pas le `header`

FAQ : est ce que les ancres ce sont les 5 encadrés suivants uniquement ?


![Image](https://github.com/SocialGouv/domifa/assets/61183619/ec49d692-d3de-4a14-872f-11cda19bafca)


Création de dom : menu de navigation autour de la liste des étapes ok 

Dossier domiciliés : manque le menu de navigation autour des onglets
Implémenter un élément <nav role="navigation" aria-label="Menu secondaire"> sur les liens présentés en onglets.

**Comment by pYassine** [comment]
https://domifa-fix-skip-links.dev.fabrique.social.gouv.fr/
