### ISSUE TITLE
feat(ACCESSIBILITE): Structuration 9.3 : Dans chaque page web, chaque liste est-elle correctement structurée ? 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2714]
# P04 : https://domifa.fabrique.social.gouv.fr/faq	
Au moins un contenu présenté sous forme de liste n'est pas structuré correctement.
Par exemple :
- La suite d'ancres

Corrections :
- Utiliser des éléments de liste `<ul>/<li>`.

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
Au moins un contenu présenté sous forme de liste n'est pas structuré correctement.
Par exemple :
- Les étapes du processus

Corrections :
- Utiliser une liste ordonnée `<ol> / </li>`

P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9	
Au moins un contenu présenté sous forme de liste n'est pas structuré correctement.
Par exemple :
- La suite de liens présentés en onglets

Corrections :
- Utiliser un élément de liste `<ul>/<li>`.

# P10 : https://domifa.fabrique.social.gouv.fr/mon-compte	
Au moins un contenu présenté sous forme de liste n'est pas structuré correctement.
Par exemple :
- La suite rendez-vous

Corrections :
- Utiliser un élément de liste `<ul>/<li>`.

# P11 : https://domifa.fabrique.social.gouv.fr/admin	
Au moins un contenu présenté sous forme de liste n'est pas structuré correctement.
Par exemple :
- La liste d'utilisateurs

Corrections :
- Utiliser un élément de liste `<ul>/<li>`.

**Comment by pYassine** [comment]
A tester avec l'extension RGAA
Les onglets de la page "profil" des usagers ne sont pas en liste, un menu a été privilégié
