### ISSUE TITLE
feat(ACCESSIBILITE): Couleurs 3.2 : Dans chaque page web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2725]
# P01 : https://domifa.fabrique.social.gouv.fr/	
Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- Le lien dans le message relatif à la collecte des données : #4164F5 / #BCD1FF (ratio : 3,14)
- Les textes de couleur #4164F5 sur fond #ECEFFE, de taille de police < 24px ou < 18,5px en gras (ratio 4,2)
- Les textes en gris #777777 sur fond blanc #FFFFFF (ratio 4,48)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agrandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P05 : https://domifa.fabrique.social.gouv.fr/connexion	
Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- La couleur des astérisques : #FF0000 / #FFFFFF (ratio : 4)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agrandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P06 : https://domifa.fabrique.social.gouv.fr/manage	
Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- Le nombre de courriers dans le bouton "Distribuer" : #FCFCFC / #FC8686 (ratio 2,3)
- Le texte de la colonne "ID" : #6480F4 / #FCFCFC (ratio 3,45)
- Le statut "Refusé" : #C14141 / #FCE7E1 (ratio 4,31)
- Le nombre de courriers dans les modales "Réception" et "Distribuer" : #FFFFFF / #50E3C2 (ratio 1,6)
- Le texte des courriers désactivés dans la modale "Distribuer" : #A6A8A9 / #FFFFFF (ratio 2,39)
- Le placeholder du champ de recherche : #d9e0fd / #4164F5 (ratio : 3,687)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agrandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- Les textes en gris dans la liste des étapes : #AFAFAF / #FFFFFF (ratio 2,19)
- Étape 2 : l'étiquette du bouton radio non actif : #808080 / #FFFFFF (ratio 3,95)
- Étape 2 et 5 : boutons "Réaliser l'entretien maintenant" et "Modifier la date du rendez-vous" et "Accepter le dossier" : #FFFFFF / #50E3C2 (ratio 1,6)
- Étape 3 (modale de confirmation) : bouton "Continuer" : #FFFFFF / #28A745 (ratio 3,13)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agrandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9	
Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- Bouton de Suppression : #DC3545 / #F2F2F2 (ratio 4,04)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agrandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P09 : https://domifa.fabrique.social.gouv.fr/inscription (tout le processus d'inscription)	Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- Étape 2, indication sur le format de mot de passe en vert : #28A745 / #FFFFFF (ratio 3,13)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agrandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

# P11 : https://domifa.fabrique.social.gouv.fr/admin	
Au moins une couleur de police n'est pas suffisamment contrastée.
Par exemple :
- Le statut "Gestionnaire : #FFFFFF / #50E3C2 (ratio 1,6)

Corrections :
- Contrôler tous les contrastes de textes (HTML, textes en images, textes incrustés) et vérifier qu'ils sont suffisants (4.5 en taille normale, 3 en taille agarandie).
- Pour les contrastes insuffisants, modifier les couleurs pour atteindre les minimums requis ou proposer à l'utilisateur un dispositif pour renforcer les contrastes (style switcher).

**Comment by celinelr** [comment]
@Chirazh je crois que sur la page 1 cela a été corrigé mais pas les autres pages. A vérifier

**Comment by Chirazh** [comment]
Mon compte - Utilisateurs - Flèches noires sur fond vert - dans le tableau des utilisateurs
Label "Améliorations" dans la page https://domifa-preprod.dev.fabrique.social.gouv.fr/news
Bouton "connexion" dans la page https://mon-domifa-preprod.dev.fabrique.social.gouv.fr/auth/login
Les chiffres de la domiciliation dans la page https://admin-domifa-preprod.dev.fabrique.social.gouv.fr/structures/stats
Asterix et bouton "confirmer" dans la pop-up de radiation
Entretien - Asterix et bouton "confirmer" dans la pop-up de refus
Entretien - Lorsque dossier en attente de décision et qu'on clique sur une étape précédente "message en orange"
Entretien - étape accepter le dossier dans la pop-up de validation champs "optionnel" et "confirmer la décision"
