### ISSUE TITLE
feat(ACCESSIBILITE): Éléments obligatoires 8.9 : Dans chaque page web, les balises ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2727]
# P01 : https://domifa.fabrique.social.gouv.fr/	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
Plusieurs textes sont structurés uniquement avec des `<div>` ou des `<span>`; par exemple les textes sous le bandeau bleu en haut de page, les statistiques, les textes au-dessus des logos des structures, le texte dans le footer le texte relatif à la collecte des données, ...

Corrections :
- Remplacer les balises `<div>` et `<span>` par des `<p>` ou entourez le texte avec des balises `<p>`. Traiter également les éventuels problèmes dans les modales.

# P02 : https://domifa.fabrique.social.gouv.fr/mentions-legales	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Il n'est fait aucun usage de paragraphes (`<p>`) sur cette page.

Corrections :
- Utiliser des `<p>` pour donner de la sémantique aux contenus.

# P03 : https://domifa.fabrique.social.gouv.fr/cgu	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Il n'est fait aucun usage de paragraphes (`<p>`) sur cette page.

Corrections :
- Utiliser des `<p>` pour donner de la sémantique aux contenus.

# P04 : https://domifa.fabrique.social.gouv.fr/faq
rien de marqué dans l'excel

# P05 : https://domifa.fabrique.social.gouv.fr/connexion	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Le message d'erreur du champ "email" est uniquement structuré avec des `<div>`.

Corrections :
- Remplacer les balises `<div>` par des `<p>` ou entourez le texte avec des balises `<p>`.

# P06 : https://domifa.fabrique.social.gouv.fr/manage	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Le texte dans la modale "Distribuer"

Corrections :
- Remplacer les balises `<div>` par des `<p>` ou entourez le texte avec des balises `<p>`.

# P07 : https://domifa.fabrique.social.gouv.fr/nouveau (tout le processus de création)	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Les messages d'erreur et les descriptions de champs sont uniquement structurés avec des `<div>`.
- Étape 3 : le texte dans le cadre bleu, le texte de la modale de confirmation.
- Étape 4 et 5 (dont modales) : tous les textes.

Corrections :
- Remplacer les balises `<div>` par des `<p>` ou entourez le texte avec des balises `<p>`.
- Étape 5 : Pour les textes du récapitulatif, utiliser des éléments de liste `<ul>/<li>`pour les contenus de l'État civil et de l'Entretien.

# P08 : https://domifa.fabrique.social.gouv.fr/profil/general/9	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Tous les textes de cette page ne sont structurés qu'avec des `<div>` ou des `<span>`.

Corrections :
- Utiliser des `<p>` ou des `<ul>/<li>` pour structurer les contenus "Doosiers" et "Courrier en attente".
- Utiliser des `<ul></li>`pour structurer les contenus "Historique des courriers" et "Notes".
- Utiliser également des `<p>` pour les textes des modales. La modale de Suppression contient du texte dont chaque ligne commence par un "-". Ce texte doit être structuré avec un `<ul>/<li>`.
- Supprimer les <br> successifs et reproduire les espacements au moyen de règles CSS.

# P09 : https://domifa.fabrique.social.gouv.fr/inscription (tout le processus d'inscription)	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Les textes sont uniquement structurés avec des `<div>`.

Corrections :
- Structurer les textes avec `<p>`.

# P10 : https://domifa.fabrique.social.gouv.fr/mon-compte	
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Exemple/Corrections :
- Utiliser des `<p>` pour structurer les textes.

# P12 : https://domifa.fabrique.social.gouv.fr/import	Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Étape 2 : le texte "3 domiciliés seront importés sur Domifa…" est uniquement structuré avec des `<div>`.

Corrections :
- Remplacer les balises `<div>` et `<span>` par des `<p>` ou entourez le texte avec des balises `<p>`.

# P13 : https://domifa.fabrique.social.gouv.fr/stats/rapport-activite
Au moins une balise est utilisée uniquement pour créer des effets de présentation.
Par exemple :
- Les textes sont uniquement structurés avec des `<div>`.

Corrections :
- Remplacer les balises `<div>` par des `<p>` ou entourez le texte avec des balises `<p>`.

**Comment by Chirazh** [comment]
RECETTES PO : https://domifa-fix-form-rgaa.dev.fabrique.social.gouv.fr/

Sélectionner les zones de textes (phrases) clique droit - inspecter - vérifier que les zones sont précédées et suivi de balises <p> dans le code

**Comment by Chirazh** [comment]
Homepage : 
- dans la partie "Ces structures vous font confiance" - la phrase "De nombreux organismes domiciliataires utilisent DomiFa : CCAS, CIAS ou associations." est entourée par des valises `div`
