### ISSUE TITLE
feat(HISTORIQUE): Restructurer l'onglet historique d'un dossier domicilié 

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2748]
**Situation Actuelle**

L'historique des interactions se trouve dans le dossier du domicilié onglet "Courrier" alors que les autres historiques se trouvent dans un onglet à part.
De plus, il faut dérouler la page pour lire l'ensemble des historiques ce qui manque de visibilité et ne permet pas l'ajout de paginations.

**Comportement souhaité**

Description du comportement souhaité

- [x] Récupérer l'historique des interactions dans l'onglet "Courrier" pour le mettre dans l'onglet "Historique"
- [x] Créer des onglet dans la partie historique dans l'ordre suivant : Décisions, Interactions, Transferts, Procurations, SMS, Notes

Cf Maquette : 
https://www.figma.com/proto/x1iZGSOrzB8Zmixx9WzQrv/Domifa-(Florent)?page-id=1842%3A9400&node-id=2069-19370&viewport=248%2C48%2C0.37&scaling=min-zoom&starting-point-node-id=1862%3A11489

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier que l'historique des interactions a été déplacé de l'onglet "Courrier" à l'onglet "Historique"
- [x] Vérifier que l'onglet "Historique" est réorganisé en colonne avec la création des catégories
- [x] Vérifier que les catégories sont toutes présentes : Décisions, Interactions, Transferts, Procurations, Notes, SMS

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
Lien de test : https://domifa-feat-history-tabs.dev.fabrique.social.gouv.fr/profil/historique/7
