### ISSUE TITLE
feat(HISTORIQUE): Ajouter une pagination dans les historiques et un nombre de lignes plus important d'interaction

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2749]
**Situation Actuelle**

L'affichage actuelle dans l'historique est limité à 30 lignes or il est facilement possible, notamment sur la partie des interactions de dépasser rapidement ce chiffre (avec les connexions au portail par exemple).

**Comportement souhaité**

Description du comportement souhaité

- [ ] Augmenter le nombre de lignes affiché à 50 lignes au lieu de 30
- [ ] Ajouter une pagination 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Ajouter un nombre conséquent d'interactions et tester la pagination (50/ page)

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
🚀 https://domifa-feat-interactions-pagination.dev.fabrique.social.gouv.fr/

**Comment by Chirazh** [comment]
https://domifa-feat-history-tabs.dev.fabrique.social.gouv.fr/profil/historique/7
