### ISSUE TITLE
Tech : basculer supprimer Redux et basculer sur NgRx

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2795]
**Situation Actuelle**

Redux est utilisé sur le frontend pour gérer le cache côté navigateur.

**Comportement souhaité**

Basculer vers NgRx, plus adapté à l'environnement Angular
Concrètement, ça permetterait de mettre à jour les données dans tous les onglets sans recharger la page

- [ ] Exemple : quand j'épingle une note, la note s'affiche directement dans le profil

Recette : https://domifa-fix-form-rgaa.dev.fabrique.social.gouv.fr/

**Comment by Chirazh** [comment]
RECETTE PO : Si j'édite une info (ayant droit, note, ajout de courrier, données de l'entretien etc) les informations doivent être mises à jour automatiquement
