### ISSUE TITLE
feat(UTILISATEURS): Permettre le tri des utilisateurs d'une structure

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2818]
**Situation Actuelle**

Dans la page "Mon Compte" - "Utilisateurs" il y a peu d'informations sur les comptes et pas d'option de tri ce qui peut être problématique pour les grandes structures ayant parfois des dizaines d'utilisateurs.

**Comportement souhaité**

Description du comportement souhaité

- [ ] Ajouter tri par nom/prénom et date d'inscription 
- [ ] Ajouter une colonne avec "date d'inscription" des utilisateurs (à la date de création du compte)
- [ ] Ajouter une colonne "statut" avec le tag "validé" ou "en cours" selon si la personne à créé son mot de passe ou non 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Ajouter plusieurs utilisateurs à des dates différentes et valider une partie avec la création d'un mot de passe
- [ ] Trier par ordre alphabétique
- [ ] Trier par date d'inscription
- [ ] Vérifier les statuts "validé" ou "en cours"

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
La colonne statut est remplacé par "Actif" "Inactif" 
Inactif = non connecté depuis plus de 2 mois
