### ISSUE TITLE
bug(STATISTIQUES): Retours de structures sur statistiques erronnées 

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2847]
**Description du problème**

![image](https://github.com/SocialGouv/domifa/assets/61183619/17ad6df5-0d74-485c-a617-1bcc6e317ab7)

![image](https://github.com/SocialGouv/domifa/assets/61183619/3a828bb4-8869-4fa5-a3b7-7e5d8f21de00)

![Image](https://github.com/SocialGouv/domifa/assets/61183619/85eb79e3-fda8-4b29-bc11-d52303307ab2)

**Comportement attendu**

Description du comportement souhaité

- [ ] Investiguer les deux remontées de structures

**Comment by pYassine** [comment]
Quand un dossier a été radié, mais qu'avant la radiation des éléments ont été changé ( "createdEvent": "update-usager"), la date de fin de la statistique correspondant à la période ou le dossier était "Valide" ne se met pas à jour.

**Comment by pYassine** [comment]
Malakoff :
Dans la majorité des cas, le nombre d'attestation délivrés dans l'année est inférieur au nombre de domiciliés
Le nombre de domiciliés en 2022 comprend à la fois les domiciliés dont la domiciliation débute en 2022, mais aussi toutes les personnes domiciliés en 2021 qui n'ont pas été radié, ou dont la date de fin de dom est en 2022

Cas particuliers ou vous pouvez avoir un nombre d'attestation supérieur au nombre de domiciliés:
Si plusieurs personnes sont domiciliés plusieurs fois dans la même année. Admettons qu'une personne est domicilié le 1er février, radiée le 3 mars, et re-domiciliée le 10 juin. Vous aurez dans les statistiques
- 1 domicilié
- 1 attestation de radiation
- 2 attestations de domiciliations

**Comment by pYassine** [comment]
Collectif fraternite salonaise
Il y a une erreur de compréhension. Le nombre de passage indiqué concerne les passages sans récupération de courrier. 
Les personnes ont du cliquer sur le bouton des passages en plus de la réception de courrier. Ca n'est pas un bug de notre côté

![Image](https://github.com/SocialGouv/domifa/assets/11486845/df51617f-cd7f-403c-a533-221156e53e51)
