### ISSUE TITLE
bug: quand j'inscris un mail déjà utilisé, le message d'erreur n'apparaît pas

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2897]
**Description du problème**

Quand on inscrit un email déjà utilisé, le message d'erreur ne s'affiche pas.

**Comportement attendu**

Quand j'inscris un email déjà utilisé, un message d'erreur doit apparaitre pour m'indiquer que l'adresse est déjà utilisée.

Pages concernées
- [x] Inscription d'un utilisateur
- [x] Inscription d'une structure
- [x] Edition de mes informations 
- [x] Ajouter un utilisateur depuis l'administration

**Comment by Chirazh** [comment]
J'arrive à remplir le formulaire de création d'une structure avec une adresse mail déjà utilisée pour un utilisateur dans une autre structure.

Je n'arrive pas à accéder à l'admin préprod pour tester d'ajouter un admin sur une autre structure.
