### ISSUE TITLE
feat(ACCESSIBILITE): Corrections à la marge suite relecture PDF Audit

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2901]
**Comportement souhaité**

Description du comportement souhaité

- [x] Contraste des couleurs dans le bandeau rouge d'un dossier refusé
- [x] Tableau de gestion des utilisateurs -  **_Tableau de gestion des utilisateurs: mise en place de aria-expanded et aria-controls_**

![Image](https://github.com/SocialGouv/domifa/assets/61183619/29a1f886-e2dd-460e-b04c-fed04d46a2d0)

- [x] Liste des tri

![Image](https://github.com/SocialGouv/domifa/assets/61183619/4c674ad0-38cd-46a4-814d-4c395f19c548)

- [x] Modale ajout de courriers détaillés

![Image](https://github.com/SocialGouv/domifa/assets/61183619/d020c05a-31cd-48f9-960b-aca7c396472f)

- [x] Alertes sur la page statistiques publiques et mesure d'impact - OK no script + vidéo non sous-titrée
- [x] Alertes sur la FAQ - OK no script + vidéos tutos non sous-titrées + lien PDF
- [x] Alerte sur formulaire de contact - OK no script
- [x] Alerte sur mentions légales - OK no script
- [x] Alerte sur CGU - OK no script
- [x] Alertes politiques de confidentialité - OK no script + lien en doublon
- [x] Alertes plan du site - OK no script + lien en doublon
- [x] 1 alerte sur la homepage - OK no script

![Image](https://github.com/SocialGouv/domifa/assets/61183619/7dc9148f-03bb-4f38-bedc-7e1c1c7a877b)

- [x] 5 alertes sur la page import - **_Négligeable, l'alerte apparait pour tous les documents excel, word ou PDF. Normalement tous les docs sont accessibles à part les PDF peut-être_** - OK

![Image](https://github.com/SocialGouv/domifa/assets/61183619/6c86f8df-77cc-49c7-924b-e59d3bf11d7b)

- [x] 2 erreurs et 5 alertes sur la page de connexion à la page admin

![Image](https://github.com/SocialGouv/domifa/assets/61183619/b9ce3915-203b-49ab-a02f-5dacc6a3cb2d)

- [x] 1 erreur de contraste et 2 alertes sur le tableau de l'admin

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
Il reste 2 erreurs de contraste quand tu vérifies avec l'extension : 
- 1 sur la page de connexion à l'admin
- 1 sur la page du tableau des structures dans la page admin (aussi le titre "tableau des structures" est en bas c'est bizarre non ?)

**Comment by pYassine** [comment]
🚀 https://domifa-fix-portail-rgaa.dev.fabrique.social.gouv.fr/
