### ISSUE TITLE
feat(INTERACTIONS): Amélioration des parcours d’édition-suppression des interactions

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2915]
**Situation Actuelle**

Actuellement il est possible de supprimer la dernière interaction (passage, appel, courrier) dans la liste des historiques.
Il arrive souvent que les structures se trompent sur des interactions plus anciennes.

**Comportement souhaité**

Description du comportement souhaité

- [ ] Permettre la suppression d'interactions les unes après les autres pour permettre de supprimer une interactions plus ancienne.
- [ ] Vérifier la mise à jour des compteurs et statistiques associés.
- [ ] Vérifier la mise à jour de la date de dernier passage 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Ajouter plusieurs interactions 
- [ ] Supprimer plusieurs interactions
- [ ] Vérifier la mise à jour des statistiques et de la date de dernier passage

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@Chirazh  au vue des données, je suis d'avis de réfléchir à une séparation des interactions et des connexions au portail

On ne doit pas pouvoir supprimer le fait que quelqu'un se soit connecter au portail domicilié
Aussi, les connexions au portail ne comptabilisés dans les stats / rapport d'activité. 

[ ] Dans l'historique, ajouter un onglet "connexions au portail" 
[ ] Dans la base de donnée, séparer les connexions au portail des interactions

![Image](https://github.com/SocialGouv/domifa/assets/11486845/49f54800-8c01-4140-b3cc-f2e72cb98621)

**Comment by Chirazh** [comment]
@pYassine ok !

Est ce que l'on doit vérifier qu'en cas de suppression d'un courrier avant le mardi ou jeudi soir il n'y a aucun sms d'envoyé ou est ce que c'est fait automatiquement et qu'il n'y a pas de risques d'erreur ?

**Comment by pYassine** [comment]
> @pYassine ok !
> 
> Est ce que l'on doit vérifier qu'en cas de suppression d'un courrier avant le mardi ou jeudi soir il n'y a aucun sms d'envoyé ou est ce que c'est fait automatiquement et qu'il n'y a pas de risques d'erreur ?

Ce qu'on peut faire c'est te mettre les SMS à envoyer dans l'historique comme ça tu peux les voir et vérifier. Une fois OK on retirera l'affichage. En théorie oui c'est prévu, les SMS sont vérifies après chaque suppression et supprimer si aucune interaction n'est en attente

**Comment by Chirazh** [comment]
@pYassine ajouter le panneau de confirmation avant suppression
