### ISSUE TITLE
feat(ACCESSIBILITE): Modifier la déclaration d'accessibilité suite au contre audit

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#2925]
Lien vers la nouvelle déclaration d'accessibilité: https://nextcloud.fabrique.social.gouv.fr/apps/onlyoffice/191525?filePath=%2FDomiFa%2FACCESSIBILITE%2F14.08.2023_Contre%20Audit%2FMod%C3%A8le%20declaration%20accessibilite%20RGAA%204.1.2.docx

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
1/ Ajouter un espace entre les deux phrases suivantes : 

La réalisation d’un contre-audit le 14 août 2023.
Cette déclaration d’accessibilité s’applique au site https://domifa.fabrique.social.gouv.fr/.

2/ Ajouter un espace entre les deux phrases suivantes et les ":" après Dans le détail

L’audit de conformité au RGAA 4.1.2 réalisé par la société Numerik-ea révèle que 85,29% des critères RGAA 4.1.2 sont respectés.
Dans le détail

3/ Ajouter le lien hypertexte de 8. Domicilié : Actif

4/ Ajouter le lien hypertexte de https://domifa.fabrique.social.gouv.fr/contact

**Comment by pYassine** [comment]
@Chirazh on ne peut pas mettre le lien vers "actif", il faudrait un vrai dossier et être connecté pour ça

**Comment by Chirazh** [comment]
Ok ! je te laisse me dire quand les autres corrections sont ok
