### ISSUE TITLE
bug(REFUS): Corriger les données érronées de Bordeaux

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#2981]
**Description du problème**

Lors de l'import des données, certains dossiers ont été importé sans date de refus valable.
Cela engendre des bugs d'affichage et dans les statistiques

- [x] Importer des dates pour les refusés

**Scénario de reproduction du problème**

1. Se connecter en tant que Bordeaux
2. Aller sur un dossier refusé
3. Vérifier que la date de refus s'affiche bel et bien

**Comment by Chirazh** [comment]
Le fichier comportant les erreurs est disponible sur Nextcloud - Déploiement - CCAS de Bordeaux
