### ISSUE TITLE
bug(RECHERCHE ID): La recherche successive d'un même ID domicilié ne fonctionne pas

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3024]
**Description du problème**
Il n'est pas possible de rechercher deux fois de suite un même ID domicilié dans le curseur de recherche.
Lorsque l'on clique sur la croix et que l'on indiquer de nouveau le même ID la recherche ne fonctionne plus.
Si on sélection à la main la recherche et que l'on efface avec la touche delete alors la recherche fonctionne de nouveau.

Le bug nous a été remonté par la CRF de Toulouse qui a tenté la manip en scannant l'ID avec une douchette.

**Comportement attendu**

Description du comportement souhaité

- [x] Pouvoir chercher de façon successive un même ID domicilié en cliquant sur la croix pour supprimer la recherche puis en ressaisissant le même numéro 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Indiquer un ID 
- [x] Cliquer sur la croix
- [x] Rechercher le même ID que précédemment 

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
🚀 https://domifa-fix-input-manage.dev.fabrique.social.gouv.fr/
