### ISSUE TITLE
feat(STATISTIQUES): Calculer la durée médiane ou moyenne ? d'une domiciliation sur une période donnée - CCAS de Bordeaux

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3068]
**Situation Actuelle**

Nous n'avons pas d'information sur la durée moyenne ou médiane d'une domiciliation.

**Comportement souhaité**

Description du comportement souhaité

- [ ] Avoir le nombre de jours médian / moyens d'une domiciliation à partir des domiciliés (première demande ou renouvellement) et radiés d’une même année

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
Pour pouvoir faire ce ticket, il faudrait ajouter une information dans les décisions 
- Date réelle de fin de domiciliation
-

**Comment by Chirazh** [comment]
Colonne "Statut de la domiciliation" Sélectionner les radiés de l'année choisie (les personnes en cours de domiciliation ne peuvent pas faire partie du calcul car cela fausserait la durée moyenne)
Colonne "Date de fin de domiciliation" Filtrer sur les dossiers de l'année choisie "2023"
L'année 2022 ne peut pas être traitée car la date de début de domiciliation est également à la date de radiation dans le fichier qui a été importé donc les durées de domiciliation sont égales à 0 jours.
Ajouter colonne "Nombre de jours" avec formule =DATEDIF(colonne date de début de dom;colonne date de fin;"D") et tirer jusqu"à la dernière ligne
Calcul moyenne =MOYENNE(premier résultat en jours:dernier résultat en jours)
Calcul médiane =MEDIANE(premier résultat en jours:dernier résultat en jours) 
Nous avons retiré du calcul le dossier avec une durée de domiciliation à 7671 jours ainsi que le dossier qui a une date de début future à une date de fin.
