### ISSUE TITLE
feat(STATISTIQUES): Permettre aux structures de télécharger leurs rapports d'activités sur les 3 années précédentes 

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3118]
**Situation Actuelle**

Description de la situation actuelle

**Comportement souhaité**

Description du comportement souhaité

- [ ] action 1
- [ ] action 2...

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] test 1
- [ ] test 2...

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
🚀 https://domifa-fix-stats-type-dom.dev.fabrique.social.gouv.fr/
