### ISSUE TITLE
feat(REPORTING DGCS): Créer un focus "suivi domiciliés" avec des indicateurs supplémentaires qui ne sont pas dans le rapport d'activité

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3131]
**Situation Actuelle**

**Comportement souhaité**

Description du comportement souhaité

- [x] Faire le tri avec les indicateurs disponibles dans la page suivante (certains indicateurs seront à mettre dans la page rapport d'activité, d'autres à laisser dans le focus suivi domicilié) :

https://metabase-domifa-preprod.dev.fabrique.social.gouv.fr/public/dashboard/25903f0c-4689-4e46-8557-a42a06543c01?d%25C3%25A9but_de_la_p%25C3%25A9riode=2018-08-29&fin_de_la_p%25C3%25A9riode=2024-02-04

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] test 1
- [ ] test 2...

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine pour finaliser l'écriture de ce ticket j'ai besoin que tu me dises si le total des mineurs dans le rapport d'activité, là où il y a les tranches d'âge, ne prend en compte que les domiciliés actifs ou bien les ayants-droit également ?

**Comment by Chirazh** [comment]
Distinguer sur deux dashboard Metabase : 
- Dashboard DGCS - Rapport d'activité (avec onglet rapport d'activité et suivi des domiciliés)
- Dashboard DGCS - Suivi DomiFa (avec suivi structures, utilisateurs, portail, sms)

**Comment by pYassine** [comment]
Ticket à réévaluer lors des échanges avec Emilie
