### ISSUE TITLE
feat(RAPPORT D'ACTIVITE): Ajouter nombre total de domiciliations avec un accompagnement social

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3134]
**Situation Actuelle**

Nous avons l'information dans l'entretien social mais il ne figure pas dans le rapport d'activité

**Comportement souhaité**

Description du comportement souhaité

- [x] Ajouter dans l'Axe 1 le "Nombre de domiciliés bénéficiants d'un accompagnement social" avant le rattachement avec la commune.

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@Chirazh ca doit être ajouté aux stats ?

**Comment by Chirazh** [comment]
@pYassine peux-tu mettre l'indicateur dans le fichier excel et le rapport de stat dans le même ordre que l'entretien social
