### ISSUE TITLE
feat(COURRIERS): Permettre le retour à l'expéditeur des courriers pour les dossiers radiés

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3144]
**Situation Actuelle**

Lorsqu'une personne est radiée, il arrive que des courriers restent en attente de distribution dans son dossier.
Dans les faits, la structure renvoie ces courriers vers l'expéditeur mais ne peut pas le notifier sur DomiFa. Si elle confirme la distribution de ces courriers, cela est faux car la date de dernier passage se met à jour comme si le domicilié était venu récupérer les courriers.

La seule action possible actuellement pour un dossier radié est de mettre le dossier en "pli non distribuable" pour ne plus saisir le nouveau courrier reçu.

Les structures demandent la possibilité de signifier que le courrier en attente au moment de la radiation a été remis à l'expéditeur.
Elles ne remontent pas le besoin de préciser que le courrier reçu après la radiation va être retourné vers l'expéditeur, il ne sera pas saisi en réception, vu que le dossier est en pli non distribuable.

Voici un exemple de retours structures : 

Retour Structure n°1

_Bonjour, Serait-il possible d'ajouter une action "courrier réexpédié" ? Actuellement, nous ne pouvons que choisir de remettre le courrier alors que nous avons aussi à réexpédier du courrier soit à l'expéditeur, soit à une autre adresse. Je pense que ces options pourraient se situer dans cette case (cf capture d'écran), lorsque l'on clique sur le courrier à distribuer. A votre disposition si vous souhaitez plus d'informations et merci d'avance. Cordialement_

_La fonction retour à l'expéditeur sera utilisée uniquement pour les dossiers radiés.  
Elle sera utilisée uniquement pour vider les courriers qui sont en attente au moment de la radiation
Oui on utilise la fonctionnalité pli non distribuable et on voudrait que la fonction retour à l'expéditeur vienne en plus de la fonction pli non distribuable._

![Image](https://github.com/SocialGouv/domifa/assets/61183619/777223ff-c3f4-43fc-8613-d10c5bdb3d6f)

Retour Structure n°2
_Serait-il possible dans les options de remise de courrier qu’il existe une fonctionnalité « retour à l’expéditeur » ?
Sur le même principe que ce qui existe pour les dossiers pour lesquels il existe une procuration(capture ci-dessous)._
 
__En effet, quand une personne est radiée et qu’il reste du courrier dans sa BAL, La Poste vide la boîte et le renvoie aux expéditeurs, mais il n’y a rien dans l’application Domifa pour matérialiser ce renvoi. La Poste est obligée d’utiliser la fonction de remise du courrier, ce qui laisse à penser que le courrier a été remis à la personne domiciliée, ce qui d’une part est faux et d’autre part peut induire en erreur._
 
_Avec le nombre de dossiers radiés chaque jour et de courriers renvoyés aux expéditeurs, cette fonctionnalité serait d’une grande aide pour la bonne tenue de nos dossiers.__

![Image](https://github.com/SocialGouv/domifa/assets/61183619/5ac6c80a-acf3-4859-a3df-171c2618cfd0)

**Comportement souhaité**

Description du comportement souhaité

- [x] Pour l'ensemble des dossiers, dans la popup de distribution ajouter une rubrique qui indique le transfert lorsqu'il est actif avant de demander la confirmation
- [x] Pour les dossiers radiés, dans la pop-up de distribution, ajouter une possibilité de distribution en plus de domicilié, mandataire, transfert, qui s'intitulerait "Retour à l'expéditeur"
- [x] S'assurer que le retour à l'expéditeur ne compte pas comme un passage dans les statistiques et ne mette pas à jour la date de dernier passage d'un domicilié
- [x] Réouvrir la réception / distribution pour les dossiers indiqués avec "Pli non distribuable" + panneau attention 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Ajouter des courriers à un domicilié puis le radier
- [x] Réaliser un retour à l'expéditeur
- [x] Vérifier que la date de dernier passage ne se modifie pas
- [x] Vérifier que le retour à l'expéditeur n'est pas possible pour les autres statuts hormis les radiés
- [x] Vérifier que si le pli non distribuable est activé puis désactivé, la possibilité du retour à l'expéditeur est toujours possible

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine complément de réponse du CCAS de Paris 

      Est-ce qu'elle doit être disponible pour tous les dossiers ? ou bien uniquement les radiés ?
_Elle doit être disponible pour les dossiers radiés et les dossiers refusés._
 
·         Est-ce que le besoin est de vider les courriers en attente au moment de la radiation, ou de pouvoir également saisir un retour à l'expéditeur à tout moment pour un dossier déjà radié qui recevrait de nouveaux courriers ?
_Le besoin est de pouvoir vider dans DomiFa les courriers en attente au moment de la radiation ou du refus (et du vidage physique de la boîte aux lettres) afin que les informations dans DomiFa ne laissent pas à penser qu’il y a toujours du courrier disponible alors que celui-ci a été réexpédié.Après avis pris auprès du service courrier, il n’y a pas d’intérêt à pouvoir tracer les courriers qui seraient amenés à arriver après la date de radiation ou de refus._
 
·         Dans le cas des radiés, utilisez-vous la fonctionnalité "pli non distribuable" disponible actuellement ? Si oui, est ce que le retour à l'expéditeur viendrait en plus ou en remplacement ?
_Actuellement, lors de la radiation d’un dossier, la fonctionnalité « pli non distribuable » est utilisée uniquement si la boîte aux lettres du domicilié est vide. En effet, si elle est utilisée sur un dossier pour lequel il y a encore du courrier enregistré, le service courrier ne peux plus vider la boîte aux lettres dans DomiFa.
La fonctionnalité « pli non distribuable » permet au service courrier de ne pas risquer d’enregistrer du courrier par erreur sur un dossier radié.
Il faut donc que la fonctionnalité « retour à l’expéditeur » vienne en plus de la fonctionnalité « pli non distribuable » car ces 2 fonctionnalités nous servent pour 2 cas de figure différents._

**Comment by pYassine** [comment]
🚀 https://domifa-feat-return-to-sender.dev.fabrique.social.gouv.fr/

**Comment by pYassine** [comment]
🚀 https://domifa-feat-return-to-sender.dev.fabrique.social.gouv.fr/

La partie stat se fera dans un 2eme temps quand les travaux sur les stats seront terminés

**Comment by Chirazh** [comment]
@pYassine le commentaire précédent n'a pas été traité.

**Comment by Chirazh** [comment]
@y
