### ISSUE TITLE
feat(REPORTING DGCS): Ajouter les indicateurs du rapport d'activité structures dans une page Metabase qui deviendra le dashboard DGCS

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3153]
**Situation Actuelle**

Description de la situation actuelle

La DGCS souhaite accéder à un rapport consolidé des rapports d'activités structures.

**Comportement souhaité**

Description du comportement souhaité

- [x] Afficher les statistiques que les structures voient au niveau national

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier la présence de l'ensemble des indicateurs

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
- Axe 1 : 
- il manque le nouvel indicateur "Nombre de domiciliés actifs par type de demande"
- est ce que l'on peut mettre dans le même ordre que le rapport des structures ?

- Est ce que l'on peut mettre les axe 2 et 3 l'un à la suite de l'autre et étirer les titres des stats à chaque fois pour que ça apparaisse une seule ligne ?

- Axe 2 : 
- "En dehors des critères du public domicilié" et "Nombre total de refus d'élection de domicile (y compris refus" sont inversés

- Axe 3 : 
- il manque les connexions au portail et un type de passages et le total des passages

- Est ce que tu peux mettre les même ordres à chaque fois dans les indicateurs stp 

- Ajouter la date de dernière mise à jour des données

- Ajouter dans les titres des axes "au 31/12/XX"

- Ajouter les filtres

**Comment by Chirazh** [comment]
Comment il peut y avoir des non renseigné sur cet indicateur ?

![Image](https://github.com/SocialGouv/domifa/assets/61183619/e700d2c8-d548-4951-84ac-8109d665dfef)

**Comment by Chirazh** [comment]
@pYassine on revoit ce ticket ensemble car tu n'as pas pris en compte les dernières remarques.

**Comment by Chirazh** [comment]
@pYassine il manque dans le dashboard DGCS les informations suivantes : 

AXE 1 : 
- Nombre de domiciliés actifs par type de demande (première demande et renouvellement)
- Nombre de domiciliés actifs par tranche d'âge
- Situation professionnelle
- Répartition accompagnement social

AXE 2 : 
- Dans les motifs de radiations il y a 2 motifs autres et il manque des motifs du rapport structures à vérifier stp

AXE 3:
- Les courriers / avis de passage / colis réexpédiés en réception et en distribution
- Les passages et les appels
- Les connexions au portail

**Comment by pYassine** [comment]
Le motif de radiation

**Comment by Chirazh** [comment]
@pYassine 

Axe 1 les totaux ne sont pas équivalents / les tranches d'âge ne sont pas classées
Axe 2 il y a 2 "autres" dans les motifs de radiation
Liste des structures : on ne peut pas classer par total des domiciliés + est ce que le total des domiciliés est le nombre des actifs ou avec ayants-droits inclus ?

**Comment by pYassine** [comment]
Les 2 autres sont dues au fait qu'ils n'ont que peu de données. J'ai réglé pour tout afficher par défau

Le décalage de stats sera corrigé par le ticket  #3292 

Pour la liste, on ne peut pas classer quand il s'agit d'une requête native. Pour pouvoir le faire, il faudrait que je fabrique des données dédiées 

![Image](https://github.com/SocialGouv/domifa/assets/11486845/d6d39e8a-9c1b-49dc-bbf3-f7abfdc7a5db)

**Comment by Chirazh** [comment]
@pYassine 
Liste structure : 
- renommer le titre de la colonne avec le nombre de domiciliés par "Total domiciliés actifs" et faire coincider avec le total de l'axe 1

Axe 1 : 
supprimer les données H/F
Ajouter indicateur nationalité
