### ISSUE TITLE
bug(ENTRETIEN): Faire apparaitre les numéros de téléphone enregistrés dans les dossiers en cours d'instruction avant la séparation des informations de contact

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3226]
**Description du problème**

Description du problème

Auparavant, dans l’onglet « Dossier », les informations d’état civil, d’ayants-droits et de contact étaient dans le même bloc et lors de l’instruction d’un dossier, idem.
Désormais, les informations de contact font l’objet d’une saisie distincte.
Problème, pour les dossiers en cours d’instruction, si l’on corrige l’une des informations d’état civil, lorsque l’on enregistre les modifications, le numéro de téléphone qui avait été renseigné disparait.

**Comportement attendu**

Description du comportement souhaité

- [x] Vérifier que le numéro de téléphone enregistré dans les dossiers en cours d'instruction avant la séparation des informations de contacts soit bien enregistré

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] test 1
- [ ] test 2...

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
https://domifa-feat-add-stats-in-new-format.dev.fabrique.social.gouv.fr/
