### ISSUE TITLE
feat(SMS): Préciser le texte du sms envoyé lors de l'arrivée à échéance

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3264]
**Situation Actuelle**

Description de la situation actuelle

Le texte du sms qui indique l'échéance de la domiciliation n'invite pas explicitement à prendre rendez-vous pour le renouvellement.

**Comportement souhaité**

Description du comportement souhaité

- [x] Modifier le texte actuel : 
Bonjour,
Votre domiciliation expire dans 2 mois, nous vous invitons à vous rendre dans votre structure.

Par : 
Bonjour,

Votre domiciliation expire dans 2 mois, nous vous invitons à prendre rendez-vous dans votre structure pour votre renouvellement.

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] test 1
- [ ] test 2...

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine nouveau texte : 

Bonjour,

Votre domiciliation expire dans 2 mois, pensez à contacter votre structure pour votre renouvellement.

**Comment by pYassine** [comment]
https://domifa-refactor-common.ovh.fabrique.social.gouv.fr/

**Comment by Chirazh** [comment]
@pYassine tu n'as pas pris en compte le nouveau texte 



![Image](https://github.com/SocialGouv/domifa/assets/61183619/3b8fc03e-8e4f-4f98-800c-7fdebf56f3e0)

**Comment by Chirazh** [comment]
@pYassine le texte n'est pas bon en préprod
