### ISSUE TITLE
feat(DEMANDE DGCS RAPPORT D'ACTIVITE): Ajouter deux motifs de domiciliation: "Exercice d'une activité professionnelle" et "Lutte contre toute forme de violence (mise à l'abri)"

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3266]
**Situation Actuelle**

Description de la situation actuelle

**Comportement souhaité**

Description du comportement souhaité

- [x] Ajouter les deux motifs dans l'entretien lors de la demande
- [x] Ajouter les deux motifs dans l'import de données
- [x] Ajouter les deux motifs dans l'export de données

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Tester les deux motifs dans une demande et vérifier l'impact sur les statistiques du rapport d'activité
- [x] Vérifier que les motifs apparaissent dans le Dashboard DGCS

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
https://domifa-refactor-common.ovh.fabrique.social.gouv.fr/
