### ISSUE TITLE
feat(DEMANDE DGCS RAPPORT D'ACTIVITE): Modification de la question "Cause de l'instabilité du logement"

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3308]
**Situation Actuelle**

Description de la situation actuelle
![image](https://github.com/SocialGouv/domifa/assets/61183619/1a2deeb8-ef27-4e52-8758-a2538b9a55fc)

**Comportement souhaité**

Description du comportement souhaité

- [ ] Retirer l'errance et l'hébergement" --> on en reparle de vive voix selon l'impact
- [x] Renommer "personnes itinérantes" par Mode de vie (itinérants, gens du voyage)

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

Vérifié l'impact des changements dans : 
- rapport des statistiques
- Metabase DGCS
- courriers personnalisés
- import des données
- export des données

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
Finalement Errance reste là, on le conserve

**Comment by pYassine** [comment]
@Chirazh le fichier est ok de mon côté

![Image](https://github.com/SocialGouv/domifa/assets/11486845/6b8e013e-a5b6-45bb-aa00-a957f6eb3054)
