### ISSUE TITLE
feat(DEMANDE DGCS RAPPORT D'ACTIVITE): Ajout d'une section ayants-droit dans le tableau de bord DGCS

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3360]
**Situation Actuelle**

La DGCS souhaiterait connaitre la répartition par type de lien (conjoint, parents, enfants) des ayants droits dans le tableau de bord.

**Comportement souhaité**

Description du comportement souhaité

- [x] Ajouter une section avec les indicateurs des ayants droits 

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier que le total de la répartition par lien est le même que le total des ayants-droit

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
@Chirazh 

- [ ] Répartition par type de lien
- [ ] Répartition par âge

On a rien d'autre à caser à priori non ?
