### ISSUE TITLE
Metabase en prod avec DB anonymisée

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/domifa#3411]
- [x] Mise en place d'un Metabase en prod
- [x] Connecter la DB anonymisée au Metabase de prod
- [x] Injecter le dump anonymisée dans la DB anonymisée de prod
- [x] Automatiser le process:
  - [x] Activer le cron qui créé les dumps anonymisé et pousse dans S3
  - [x] Tache github à déclencher manuellement

---

- [x] Injecter les données metabases de preprod en prod: tous les dashboards et le config Metabase créée par l'équipe Domifa sur son instance de prepod.
- [x] Rendre possible l'insertion du dump anonymisé dans la base de preprod de domifa (fonctionne en théorie, to be tested)
- [x] Supprimer le Metabse de preprod (a la toute fin)

**Comment by matmut7** [comment]
En attente de la recette de Yassine, il a été occupé par les pannes Domifa ces derniers temps. À relancer quand ça se sera calmé
