### ISSUE TITLE
Déplacer le statut dans une colonne dédiée

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#3419]
**Situation Actuelle**

Les statuts sont dans l'objet "decision" 

**Comportement souhaité**

Description du comportement souhaité

- [x] Dupliquer le statut dans une colonne dédiée
- [x] Créer un index qui permet de chercher sur le statut 
- [x] Vérifier la recherche par "nom prénom" quand on créer une décision

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier que la liste des domiciliés se charge bien avec et sans radiés

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine 
Je ne peux pas tester, lorsque je cliquer sur "afficher tous les radiés", il y a un message d'erreur


![Image](https://github.com/user-attachments/assets/e63e8666-c1e6-42eb-86a9-368b5f8673f3)
