### ISSUE TITLE
Déplacer la base de metabase preprod vers la prod

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#3420]
**Comportement souhaité**

Les stats sont dans une DB de préprod

- [ ] Brancher l'API de DomiFa sur le nouveau metabase

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] Vérifier la cohérence des stats affichées (comparer tableau de bord prod et préprod puis page stat prod et page stat préprod)
- [x] Depuis l'admin domifa, je dois pouvoir voir les stats issus de Metabase

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Chirazh** [comment]
@pYassine 

Le nombre de structures est à 1309 sur la préprod contre 1384 en prod les autres chiffres semblent être proches de la prod sans être exactement pareil 

L'axe "Fonctionnement des structures" ne fonctionne pas en prod et préprod

Il manque le libellé " Non spécifié" dans les indicateurs Axe 1 "Répartition par nationalité" et Suivi des structures "Organismes agréés"

Les chiffres dans Axe 3 - Courrier colis avis de passage ont triplés je sais si c'est normal

**Comment by Chirazh** [comment]
@pYassine les retours ci-dessus n'ont pas été pris en compte sauf le fait d'avoir mis 1309 structure sur la même ligne.
