### ISSUE TITLE
feat(EXPORT): Remettre les informations liées au transfert dans l'export global des domiciliés

### ISSUE THREAD

**Issue by Chirazh** [SocialGouv/domifa#3448]
**Situation Actuelle**

Les informations relatives aux courriers et interactions des domiciliés ont été retirées depuis le changement du modèle d'export.
Les structures ont besoins de pouvoir export les listes transferts en cours car cela n'est pas possible depuis la liste des domiciliés sur DomiFa

**Comportement souhaité**

Description du comportement souhaité

- [ ] Ajouter une colonne "Transfert actif : Oui / Non" "Date de début" "Date de fin"
- [ ] Ajouter une colonne "Procuration active : Oui / Non" "Nombres de procurations"

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Ajouter des transferts et vérifier la présence des informations dans l'export Excel

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
J'ai ajouté Nom + Adresse du transfert

**Comment by Chirazh** [comment]
@pYassine les commentaires de l'entretien dans l'onglet 2 dernière colonne n'apparaissent pas.
