### ISSUE TITLE
🐞 Bug - Cannot find module '@domifa/common'

### ISSUE THREAD

**Issue by B-Prod** [SocialGouv/domifa#3576]
### 🖥️ Site(s) concerné(s)

- [ ] DomiFa - côté structures
- [ ] Mon DomiFa - portail domiciliés
- [ ] Admin DomiFa
- [ ] Metabase

### 🚫 Description du problème

When lauching the backend using the provided docker-compose file, we can access the container and install the dependencies:

```shell
yarn install
...
Done with warnings in 4s 911ms
```

Then we try to start the application:

```shell
yarn start
...
TSError: ⨯ Unable to compile TypeScript:
src/util/file-manager/FileManager.ts(8,27): error TS2307: Cannot find module '@domifa/common' or its corresponding type declarations.
```

This error make the application fail to build.

### 🔮 Comportement attendu

The `yarn start` should not display typescript error and the application should be running.

**Comment by B-Prod** [comment]
Note that there is the same errors for the other application, for example for the frontend:

```shell
✘ [ERROR] TS2307: Cannot find module '@domifa/common' or its corresponding type declarations. [plugin angular-compiler]
     src/_common/mocks/AuthServiceMock.ts:1:30:
       1 │ import { UserStructure } from "@domifa/common";
```

**Comment by pYassine** [comment]
Hello ! You need to build "@domifa/common" first
`yarn workspace @domifa/common build`

**Comment by B-Prod** [comment]
Thank you, this fixes the issue. Maybe it could be added to the "dev" documentation?
