### ISSUE TITLE
bug(EQUIPE): [statistiques déploiement] erreur_région

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#849]
**Description du problème**
Suite au ticket https://trello.com/c/MYPP9clY/538-etq-responsable-de-déploiement-je-visualise-lensemble-des-régions-sur-ma-page-de-stats 2 structures apparaissent encore en "ERREUR_REGION".

À priori ces 2 structures sont en Corse - 2B.
En base de données, le département est bien présent, mais pas la région.
{'$or':[{nom: "xxx"}, {nom: "Centre Communal d'Action Sociale", ville: "CALVI"}]}

Screenshot dans le ticket Trello car données confidentielles : https://trello.com/c/s9uvBj5y/560-erreurrégion-sur-2-structures-dans-les-stats-déploiement 

**Comportement attendu**

- la liste des régions ne comportent aucune "ERREUR_REGION"
- la région Corse affiche bien 2

**Scénario de reproduction du problème**

1. Se connecter en tant que 'admin'
2. Aller sur la page 'statsdomifa'
3. Visualiser la liste des régions
4. Constater l'apparition de "ERREUR_REGION"

<img width="317" alt="ERREUR_REGION" src="https://user-images.githubusercontent.com/59437305/94815715-20fc1c80-03fb-11eb-9e86-8ecc49fcab7b.png">

**Recette PO**

1. Se connecter en tant que 'admin'
2. Aller sur la page 'statsdomifa'
3. Visualiser la liste des régions
4. Constater l'absence de "ERREUR_REGION"
5. Vérifier la présence de "Corse" et le nombre de structures à 2

**Comment by Toub** [comment]
La correction de ce problème avait été faite, mais non mergée: https://github.com/SocialGouv/domifa/pull/812/files

**Comment by Toub** [comment]
Du coup, il faut repasser le patch

**Comment by ledugong** [comment]
Recette PO OK

Les 2 structures ne sont plus en ERREUR_REGION mais apparaissent bien en Corse
