### ISSUE TITLE
feat(Sécurité): créer un nouvel environnement en pré-prod

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#851]
**Situation Actuelle**

L'environnement de pré-production actuel n'est pas complètement iso-production.

**Comportement souhaité**

Avoir un environnement de PP iso-prod pour l'audit de sécurité.

**Comment by ledugong** [comment]
Tests fonctionnalités OK
Tests Email : 
- création d'une structure OK
- suppression d'une structure OK (mais le mail était dans les spams @Toub)

**Comment by Toub** [comment]
Le problème des spams est adressé via la migration vers tipimail: https://github.com/SocialGouv/domifa/issues/880

Concernant le message d'erreur, je pense que le lien était expiré, car je viens de tester en préprod et ça fonctionne.

**Comment by ledugong** [comment]
@Toub 
Ok je reteste la suppression de la structure.
Par contre, même si le lien était périmé, pourquoi le message disait "la structure n'a pas être validée" alors que je cliquais sur le bouton "confirmer la suppression" ?

**Comment by Toub** [comment]
J'ai regardé le code, et le message d'erreur est le même quelque soit la raison de l'erreur et qu'il s'agisse d'une suppression ou d'une validation de structure.

Il faudrait améliorer ça, mais on sort du scope de ce ticket, et sans doutes pas vraiment prioritaire vu que ça concerne l'admin domifa. Tu peux donc créer un ticket à part si besoin.

**Comment by ledugong** [comment]
@Toub ok c'est noté

Nouveau test de suppression d'une structure non concluant, j'ai encore le même message d'erreur.
J'ai du coup remarqué que l'heure affichée sur le mail n'est pas la bonne, j'ai reçu le mail à 9h59 mais le mail affiche 7h59.

**Comment by Toub** [comment]
Le problème de l'heure du mail n'est pas lié à notre plateforme:

![image](https://user-images.githubusercontent.com/367762/95305588-d9f4a800-088e-11eb-8d11-ed766faab803.png)

Je viens de cliquer sur le lien de ton test de suppression, et ça a fonctionné:

![image](https://user-images.githubusercontent.com/367762/95305238-605cba00-088e-11eb-873a-9029e6b7c248.png)

A retester ensemble.

**Comment by ledugong** [comment]
Test suppression OK

Recette PO OK
