### ISSUE TITLE
feat(Sécurité): revue de sécurité sur les endpoint API

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#855]
**Situation Actuelle**

En vue de l'audit de sécurité à venir, faire une revue de sécurité sur les endpoint API
Ticket lié : https://github.com/SocialGouv/domifa/issues/816

**Comportement souhaité**

Review de:

- [x] UsagersController https://github.com/SocialGouv/domifa/issues/858
- [x] UsersController https://github.com/SocialGouv/domifa/issues/856
- [x] AgendaController
- [x] DocsController
- [x] ExportController
- [x] ImportController
- [x] SearchController
- [x] StructuresController
- [x] DashboardController
- [x] StatsController
- [x] InteractionsController
- [x] AuthController

**Comment by Toub** [comment]
Revue commencée, mais à terminer lundi.

**Comment by ledugong** [comment]
Pas recettable PO

**Comment by ledugong** [comment]
Pas recettable Prod
