### ISSUE TITLE
feat(Sentry): Ajouter l'info prod/préprod

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#859]
**Situation Actuelle**

Suite à la création du nouvel environnement de PP, il conviendrait d'ajouter l'info à Sentry

**Comportement souhaité**

- Ajouter l'info prod/préprod à Sentry
- Faire un tour des tickets

**Comment by Toub** [comment]
Pour filtrer par environnement: https://sentry.fabrique.social.gouv.fr/incubateur/domifa-backend/?query=serverName%3A%22preprod%22
