### ISSUE TITLE
bug(STRUCTURE): [entretien] errorTypeError: Object doesn't support property or method 'values'

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#865]
**Description du problème**

Sur la page `/usager/${id}/edit/entretien`, avec IE, l'erreur suivante apparait:

> errorTypeError: Object doesn't support property or method 'values'

**Comportement attendu**

Faire en sorte que ça fonctionne sous IE.

**Scénario de reproduction du problème**

1. Se connecter en tant que 'admin STRUCTURE'
2. Aller sur la page 'création entretien'
3. Regarder le message d'erreur dans la console

**Informations complémentaires:**

Bug sentry: https://sentry.fabrique.social.gouv.fr/incubateur/domifa-frontend/issues/13871/?query=is:unresolved

__Solution__: utiliser `Object.keys`: https://stackoverflow.com/questions/44091075/script438-object-doesnt-support-property-or-method-values

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Testé sous IE version 11.508 et je n'ai pas reproduit le bug en production. Mais les visuels étaient tout décalés, sans couleur etc, est-ce une question de version non supportée @Toub ?

**Comment by pYassine** [comment]
@ledugong Possible qu'il y ait des soucis de couleurs et de décalages, certaines regles CSS ne sont pas supportés par IE11.
Faudrait programmer une passe sur IE11 comme on avait fait il y a quelques mois pour corriger les très grosses erreurs de design qu'il peut y avoir

**Comment by Toub** [comment]
Il faut déjà que l'on détermine quels navigateurs sont supportés.

Mais à priori, ie11 va être dans la liste, donc tu peux créer un ticket pour régler les problèmes visuels en effet.

**Comment by ledugong** [comment]
@Toub @pYassine ok pour les problèmes visuels.
Par contre, si je n'arrive pas à reproduire le bug en production sous IE11, je peux pas vraiment recetter... vous avez encore le souci de votre côté en prod ?

**Comment by Toub** [comment]
Pas de IE11 pour tester actuellement.

**Comment by ledugong** [comment]
À vérifier avec la structure une fois la MEP passée
