### ISSUE TITLE
bug(STRUCTURE): Adresse de réception de courrier différente ne s'affiche pas sur le cerfa

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#869]
**Description du problème**

J'ai pu en effet créé une adresse de réception du courrier différente de celle de la structure mais elle n'apparait pas sur le CERFA.

**Comment by ledugong** [comment]
@pYassine 
Cerfa attestation de dom OK
Cerfa attestation de demande de dom : est-ce que l'adresse à laquelle a lieu l'entretien n'est pas censée être celle où l'on reçoit le courrier ? C'est actuellement l'adresse officielle de la structure qui s'affiche.

**Comment by ledugong** [comment]
@pYassine 
Pas de réponse pour le cerfa attestation de demande, on verra si les structures nous font le retour.
Du coup recette PO OK.
