### ISSUE TITLE
bug(STRUCTURE): [domiciliés] mauvaise date de radiation (date future)

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#875]
**Description du problème**

Une structure nous a fait remonter un bug de date de radiation.
La personne a effectué une radiation sur la plateforme DomiFa le 02/10/2020 et la date du 14/11/2020 apparait sur la fiche du domicilié (en haut de la fiche et dans l'historique de domiciliation).
La radiation a bien été faite sur la plateforme et non par import.

Pour rappel, lors d'une radiation sur la plateforme, il n'est pas possible de choisir la date de radiation, c'est forcément la date du jour.

J'ai testé de changer la date sur mon ordinateur mais ceci ne change pas la date de radiation sur la plateforme.
En plus (screenshots en pj), on voit bien la date du 02/10 sur l'écran.

**Comportement attendu**

Description du comportement souhaité

- Investiguer le souci de date future
- Sera-t-il possible de corriger le cas de la structure ?

**Scénario de reproduction du problème**

Pas réussi à reproduire le bug.

![Bug1](https://user-images.githubusercontent.com/59437305/95204540-8af23880-07e4-11eb-9b4f-54508afd9c6b.jpeg)
![Bug2](https://user-images.githubusercontent.com/59437305/95204554-8fb6ec80-07e4-11eb-92fa-ae55d0e803fb.jpeg)

**Recette PO**

Valider avec la structure

**Comment by pYassine** [comment]
@ledugong il s'agit d'un dossier importé !
L'erreur vient donc de la date de l'import dans la base de donnée. 
Je suis sur a 99% que c'est ça, étant donné que le motif est "AUTRES" non précisé et que sur la plateforme tu as obligation de préciser le motif. Et on voit bien que l'import est avant, qu'il n'y a aucune dom avant

**Comment by ledugong** [comment]
@pYassine top merci, je lui ai envoyé un mail, j'attends juste sa réponse avant de fermer le ticket

**Comment by ledugong** [comment]
@pYassine réponse structure "Merci pour votre réactivité et implication." allez hop on ferme.
