### ISSUE TITLE
bug(STRUCTURE): [statistiques] affichent 0

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#876]
**Description du problème**

Une structure nous a fait remonter un bug sur les statistiques : ceci semble être un cas isolé.
La personne a effectué un import de domiciliés aux alentours du 25/09 et assure que, depuis cette date, les statistiques affichent 0.
En pj la liste des domiciliés anonymisés, peut-être que l'import a été compromis et du coup les domiciliés mal comptabilisés mais nous avons normalement des messages d'erreur si l'import est mauvais.

**Comportement attendu**

Que les statistiques de la structure s'affichent bien.

TODO:

- [x] https://github.com/SocialGouv/domifa/pull/901 prendre en compte uniquement le champ `createdAt` et rendre le traitement plus robuste
- [ ] patcher `createdAt` et supprimer `date`

**Scénario de reproduction du problème**

Pas réussi à reproduire le souci.
Tableau des données utilisées sur Trello.

**Recette PO**

Valider avec la structure que les stats s'affichent bien

**Comment by Toub** [comment]
Lié à https://sentry.fabrique.social.gouv.fr/incubateur/domifa-backend/issues/13321/

**Comment by Toub** [comment]
Pas sûr que ça soit lié, mais on a trouvé un problème, que l'on va corriger.

Il faudra sans doutes revoir un peu l'UX, mais c'est prévu apparemment.

Après mise en prod, si ça se reproduit, il faut demander un screenshot horodaté à l'utilisateur.

**Comment by ledugong** [comment]
@Toub je ne crois pas avoir de compte sur Sentry...
Quel est le souci niveau UX ?

**Comment by ledugong** [comment]
À vérifier avec la structure une fois la MEP passée
