### ISSUE TITLE
mig(mail): terminer la migration vers tipimail - part 1

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#880]
**Situation Actuelle**

Certains mails sont envoyés via tipimail, d'autres via mailjet.

**Comportement souhaité**

Tout envoyer via tipimail.

TODO:
- migrer les mails "mailjet" vers tipimail (__dans l'ordre de priorité__):
- [x] MailJetService.__newStructure__: "Nouvelle structure sur Domifa"
- [x] MailJetService.__confirmationStructure__: "Votre compte Domifa a été activé"

- étudier et modifier la segmentation si besoin

**Comment by ledugong** [comment]
Ordre de priorité @Toub 
- MailJetService.newStructure: "Nouvelle structure sur Domifa"
- MailJetService.confirmationStructure: "Votre compte Domifa a été activé"
- MailJetService.newUser: "Nouvelle création de compte à valider"
- MailJetService.confirmUser: "Votre compte Domifa a été activé"
- MailJetService.newPassword: "Changement du mot de passe Domifa"
- MailJetService.hardReset: "Code de confirmation Domifa"

**Comment by ledugong** [comment]
@Toub lors de la création d'une structure, je reçois un message d'erreur alors que les champs sont tous bien remplis : 
<img width="1158" alt="Capture d’écran 2020-10-26 à 17 42 01" src="https://user-images.githubusercontent.com/59437305/97201311-98cb2600-17b2-11eb-9eba-ad168851bfeb.png">

**Comment by ledugong** [comment]
@Toub malgré le message d'erreur, je reçois quand même le mail de création d'une structure.
Dans ce mail, si je clique sur "supprimer le compte", j'ai bien l'écran de non validation qui apparait. Par contre, si suite à ça je clique sur "valider le compte", la structure est validée, pas logique non ?

<img width="459" alt="Capture d’écran 2020-10-26 à 17 48 59" src="https://user-images.githubusercontent.com/59437305/97202166-8d2c2f00-17b3-11eb-99d7-aec07182e599.png">
<img width="1240" alt="Capture d’écran 2020-10-26 à 17 47 00" src="https://user-images.githubusercontent.com/59437305/97202191-94ebd380-17b3-11eb-8217-a623934d63ce.png">

**Comment by ledugong** [comment]
Du coup, 
Mail "Nouvelle structure sur Domifa" --> retours ci-dessus
Mail "Votre compte Domifa a été activé" -> OK

**Comment by Toub** [comment]
Je viens de tester la création de compte en pré-prod, et j'ai aussi des problèmes:
- erreur 504, pas de réponse du serveur
- je re-clique sur valider, erreur 404 le compte existe déjà

![image](https://user-images.githubusercontent.com/367762/97203192-8efeee00-17c5-11eb-8418-f3912199a5b6.png)

**Comment by ledugong** [comment]
@pYassine @Toub pour info le message d'erreur apparaît aussi lorsque je crée un compte avec une structure déjà existante

**Comment by pYassine** [comment]
@ledugong  
Problème corrigé. 
Pour Supprimer une structure, il faut obligatoirement être connecté en tant que Domifa

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
