### ISSUE TITLE
bug(STRUCTURE): Message d'erreur lors du changement du responsable légal

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#884]
**Description du problème**

Une structure a remonté qu'elle ne peut pas changer le nom et prénom de son responsable légal. Un message d'erreur "Une erreur est survenue" apparait.

**Comportement attendu**

La structure doit pouvoir modifier les champs nom/prénom de son responsable légal.

**Scénario de reproduction du problème**

Bug non reproduit, ci-dessous une capture d'écran avec la date et l'heure précise de l'apparition de l'erreur, à voir sur Sentry.

![ErreurResponsableLégal](https://user-images.githubusercontent.com/59437305/95318019-3d360880-0896-11eb-86f8-648d04031092.jpeg)

**Recette PO**

Valider avec la structure

**Comment by Toub** [comment]
Problème non reproduit.

Proposer à la structure soit:
- de changer le nom pour eux
- de le faire avec eux via un partage d'écran

**Comment by ledugong** [comment]
@Toub mail envoyé à la structure, je te tiens au courant

**Comment by ledugong** [comment]
Call prévu avec la structure le 13/10

**Comment by ledugong** [comment]
Nouvel échange prévu le 19/10

**Comment by Toub** [comment]
A re-tester après livraison en prod de https://github.com/SocialGouv/domifa/issues/919

**Comment by ledugong** [comment]
Retour de la structure, bug toujours d'actualité

**Comment by ledugong** [comment]
Changement du responsable légal OK côté structure
