### ISSUE TITLE
feat(ADMIN_TECHNIQUE): [statistiques] fonction export

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#885]
**Situation Actuelle**

Il serait utile d'avoir une fonction export sur la page de stats déploiement.

**Comportement souhaité**

Ajouter un bouton "Export" en haut de la page à gauche (comme celui de l'export des domiciliés par exemple).
Le template d'export est en pj, basé sur les données visibles sur la page stats au 07/10.
Je l'ai divisé en 2 onglets pour que ce soit plus lisible côté déploiement.

[Export_Stats_Déploiement.xlsx](https://github.com/SocialGouv/domifa/files/5339857/Export_Stats_Deploiement.xlsx)

**Recette PO**

- Se connecter etq admin technique
- Se rendre sur la page de stats déploiement
- Cliquer sur le bouton export
- Vérifier la forme et le fond du fichier téléchargé

**Comment by Toub** [comment]
Test ko en preprod.

Du au fait que le template n'est pas recopié sur l'image docker au moment du déploiement:

![image](https://user-images.githubusercontent.com/367762/96708212-937c6e80-13a1-11eb-804d-43f575e9d0b9.png)

![image](https://user-images.githubusercontent.com/367762/96708246-9d9e6d00-13a1-11eb-89fb-ce03c0b1f634.png)

**Comment by Toub** [comment]
Corrigé, à tester sur prochain déploiement.

**Comment by ledugong** [comment]
@Toub les adresses mail sont tous en "fake fabrique", c'est parce que c'est en PP c'est ça ? ça sera les bons mails en production ?

**Comment by ledugong** [comment]
Parfait, recette PO OK

**Comment by ledugong** [comment]
@Toub question, sur l'export l'heure indiquée est h-1 par rapport à l'heure normale, histoire de passage à l'heure d'hiver ?

**Comment by Toub** [comment]
Plutôt un bug lié à la timezone du serveur.

**Comment by Toub** [comment]
C'est l'heure GMT qui est affichée je pense.

**Comment by ledugong** [comment]
ok merci

**Comment by Toub** [comment]
Bug suivi via ce ticket: https://github.com/SocialGouv/domifa/issues/943

**Comment by ledugong** [comment]
Recette Prod OK
