### ISSUE TITLE
mig(mail): terminer la migration vers tipimail - part 2

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#890]
**Situation Actuelle**

Certains mails sont envoyés via tipimail, d'autres via mailjet.

**Comportement souhaité**

Tout envoyer via tipimail.

TODO:
- migrer les mails "mailjet" vers tipimail (__dans l'ordre de priorité__):
- [x] MailJetService.__newUser__: "Nouvelle création de compte à valider"
- [x] MailJetService.__confirmUser__: "Votre compte Domifa a été activé"

- étudier et modifier la segmentation si besoin

**Comment by ledugong** [comment]
Vérifier le bug du call support @Toub une fois la mep passée

**Comment by ledugong** [comment]
@pYassine @Toub 
Je ne reçois pas le mail "Nouvelle création de compte à valider" et je pense qu'il n'existe pas, je ne me souviens pas en avoir vu avant, une idée ?

Mail "Votre compte Domifa a été activé" --> OK

**Comment by pYassine** [comment]
@ledugong si ce mail existe bel et bien, il buguait, c'est réparé.
Il s'agit du mail qu'un admin de structure reçoit quand une personne s'inscrit dans sa structure.

**Comment by ledugong** [comment]
@pYassine je viens de retester le mail "Nouvelle création de compte à valider" mais je ne reçois rien. Qui est censé recevoir le mail exactement ? Tous les administrateurs ? L'administrateur qui a crée la structure seulement ?

**Comment by Toub** [comment]
Seul l'admin spécial pré-prod reçoit ces mails

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
