### ISSUE TITLE
bug(STRUCTURE): Firefox, bouton suivant étape 1 ne fonctionne pas

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#892]
**Description du problème**

Une structure nous remonte le bug suivant : 
En créant une demande de renouvellement, le bouton suivant de l'étape 1 ferme la demande et la met dans "à compléter".
Comme si le bouton Suivant était le bouton Continuer plus tard, or ce bouton n'est pas accessible sur l'étape 1.

Vu sous Firefox.

**Comportement attendu**

Pouvoir faire un renouvellement

**Scénario de reproduction du problème**

1. Se connecter en tant que 'admin'
2. Aller sur la fiche d'un domicilié
3. Cliquer sur 'créer un renouvellement'
4. Remplir l'étape 1 et cliquer sur Suivant

![Bug_Renouvellement](https://user-images.githubusercontent.com/59437305/95605925-ec6f0d00-0a59-11eb-9bf6-01bd33a6ca04.jpeg)

Pour chercher sur Sentry, testé le 08/10/2020 à 17h57.

**Recette PO**

Le bug n'a pas été reproduit donc valider avec la structure.

**Comment by Toub** [comment]
Comme si un bug avait interrompu la demande, et redirigé l'utilisateur.

Pas reproduit non plus, et rien trouvé sur sentry.

**Comment by ledugong** [comment]
Call prévu avec la structure le 13/10

**Comment by ledugong** [comment]
Nouvel échange prévu le 19/10

**Comment by Toub** [comment]
A re-tester après livraison en prod de https://github.com/SocialGouv/domifa/issues/919

**Comment by ledugong** [comment]
Retour de la structure, bug toujours d'actualité

**Comment by ledugong** [comment]
Nouveau call prévu le 18/11

**Comment by Toub** [comment]
La structure n'a pas eu de réponse du service informatique, qu'elle va relancer ce jour.

On attend donc leur retour pour reprogrammer un call, et on relance dans 15 jours si pas de nouvelles.

Si le problème de Teamviewer ne trouve pas de solution, on pourra essayer de lui faire enregistrer une session firefox (F12, onglet "réseau", enregistrer en HAR), et de nous l'envoyer.

**Comment by ledugong** [comment]
Plus de retour, on abandonne
