### ISSUE TITLE
feat(UPLOAD): bloquer les boutons télécharger et supprimer les pièces-jointes quand on clique dessus 

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#894]
**Situation Actuelle**

On peut cliquer sur télécharger et supprimer plusieurs fois d'affilé.

**Comportement souhaité**

Les boutons doivent afficher un petit loading pendant le traitement de la demande

- [x] Afficher le loading quand on télécharge un fichier
- [x] Afficher le loading quand on supprime

**Recette PO**

- [x] télécharger une PJ
- [x] supprimer une PJ

**Comment by ledugong** [comment]
@pYassine ce souci c'est sur une fiche de domicilié et/ou lors de la création d'une demande de dom ?

**Comment by ledugong** [comment]
Recette PO OK (création de dom + fiche domicilié)
