### ISSUE TITLE
dev(sentry): ajout d'informations liées au contexte

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#895]
**Situation Actuelle**

Peux d'informations permettant d'analyser les problèmes.

**Comportement souhaité**

- [ ] backend: ajout de tags liés au contexte (structure, user, usager...) => idem `frontend`

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by pYassine** [comment]
L'intercepteur natif de Sentry renvoi déjà user id + email. Ticket abandonné
