### ISSUE TITLE
bug(sentry): can not delete file

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#896]
**Situation Actuelle**

De temps à autre, erreur`fatalCANNOT_DELETE_FILE`: https://sentry.fabrique.social.gouv.fr/incubateur/domifa-backend/issues/4601/

**Comportement souhaité**

Eviter cette erreur

- [x] augmentation du timeout ?
- [x] ajout d'infos dans les logs sentry ? (lié au timeout?)
- [x] en cas d'erreur, regarder si le fichier existe toujours? => si il n'existe plus, catcher l'erreur pour ne pas interrompre le traitement, mais la logger dans sentry ? https://github.com/SocialGouv/domifa/issues/899
- [x] en cas d'erreur, ré-essayer une fois, après un court délai?

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Toub** [comment]
@pYassine tu as traité ce ticket? Si oui, tu as fait quoi? Sinon, peux-tu le remettre dans "En cours" stp?

**Comment by ledugong** [comment]
@pYassine et comment je recette ce ticket ?

**Comment by pYassine** [comment]
@ledugong étant donné que ça arrive de manière épisodique, il faudrait faire plusieurs uplaods et tenter de les supprimer. Si tu ne vois aucun message d'erreur c'est bon.
De notre côté on peut le garder en surveillance sur Sentry

**Comment by Toub** [comment]
@ledugong je vais implémenter les points que j'avais mis dans le ticket pour le prochain sprint, je le repasse en TODO

**Comment by ledugong** [comment]
En attente de reproduction du bug

**Comment by pYassine** [comment]
https://domifa-fix-cannot-delete-file.dev.fabrique.social.gouv.fr/

**Comment by pYassine** [comment]
@ledugong  pour recetter le ticket il faut :

- Uploader toute sortes de fichier vérifier que tout fonctionne
- Supprimer un fichier
- Supprimer un usager entièrement

**Comment by ledugong** [comment]
@pYassine 

- [ ] Bug sur la suppression d'un usager
https://domifa-fix-cannot-delete-file.dev.fabrique.social.gouv.fr/profil/documents/7

**Comment by ledugong** [comment]
@pYassine 

- [ ] sur cette fiche https://domifa-fix-cannot-delete-file.dev.fabrique.social.gouv.fr/profil/documents/1 je ne peux pas télécharger la pj déjà sur la fiche

**Comment by pYassine** [comment]
@ledugong les PJ ne sont pas conservés d'une branche à l'autre. C'est un fichier que tu as mis quand ?

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
