### ISSUE TITLE
feat(backend): logger les erreurs nest dans sentry 

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#899]
**Situation Actuelle**

Les erreurs nest sont loggées dans la console, mais ne génèrent pas de trace sentry (sauf si une exception est lancée).

**Comportement souhaité**

Pouvoir logger des traces sentry sans propager l'erreur.

- [ ] étendre le logger `nest` pour que `Logger.error` envoie une trace dans `sentry`: https://docs.nestjs.com/techniques/logger#extend-built-in-logger
- [ ] remplacer les "Logger.error + throw error" par des "Logger.warn + throw error" pour ne pas générer de traces en double

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Pas recettable PO

**Comment by ledugong** [comment]
Pas recettable Prod
