### ISSUE TITLE
bug(STRUCTURE): [création structure] texte à corriger

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#905]
**Description du problème**

Lors de la création d'une structure, un des messages d'erreur n'est pas correct.

**Comportement attendu**

Corriger le message d'erreur pour "Veuillez sélectionner un des types d'organismes suivants : CIAS/Commune, CCAS ou organisme agréé"

**Scénario de reproduction du problème**

1. Cliquer sur s'inscrire
2. Ne pas remplir le formulaire et cliquer sur "Enregistrer votre structure"
3. Le message d'erreur en haut de page est incorrect

<img width="815" alt="CréationStructure_MessageErreur" src="https://user-images.githubusercontent.com/59437305/95844650-6e588200-0d49-11eb-9a51-27f36be59aa3.png">

**Recette PO**

Créer une nouvelle structure et vérifier le message d'erreur.

**Comment by pYassine** [comment]
@ledugong  j'ai glissé celui-ci dans la dernière mise en préprod

**Comment by ledugong** [comment]
Recette PO OK
