### ISSUE TITLE
bug(STATISTIQUES): bug date de début

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#917]
**Description du problème**

Test fait sur le compte TEST STATISTIQUES de préprod.
14/10 : création d'une de demande de domiciliation suivie d'un refus
16/10 : visualisation des stats, tout est à 0

**Comportement attendu**

Que les stats s'affichent correctement (dans ce cas-ci, visualisation d'un refus).

**Scénario de reproduction du problème**

1. Se connecter en tant que 'admin' sur la structure TEST STATISTIQUES en PP
2. Aller sur la page 'statistiques'
3. Cliquer sur 'actualiser les statistiques'
4. Constater que les stats sont toutes à 0 malgré un refus dans la liste des usagers

**Informations complémentaires:**

Vu avec @Toub , à priori un problème de date car en choisissant la date 18/10 comme date de début, et pas de date de fin, ça fonctionne. 

**Recette PO**

Recréer des refus et des dom valides, vérifier que les stats se mettent bien à jour.

**Comment by Toub** [comment]
Corrigé via https://github.com/SocialGouv/domifa/pull/952

**Comment by ledugong** [comment]
@Toub les stats sont toujours toutes à 0, il faut que je recrée des dom pour recetter ?

**Comment by Toub** [comment]
Peux-tu préciser ton test stp?

Sur preprod, avec les dates 15-16 octobre, je vois 2 refus

![image](https://user-images.githubusercontent.com/367762/98667837-0a34d800-2360-11eb-87f6-40887169526c.png)

**Comment by ledugong** [comment]
Sur le compte "TEST STATISTIQUES" en PP, il y a actuellement un refus fait le 14/10 visible sur Manage.
Or, dans les stats, tout est à 0. J'ai testé avec différentes dates de début (13, 14, 15, 16 octobre) et pareil pour les dates de fin. Mais tout est toujours à 0.

**Comment by ledugong** [comment]
@Toub Nouveaux domiciliés crées sur le compte TEST STATISTIQUES en PP, à voir s'ils s'affichent correctement sur les stats : 
1 actif, 1 à compléter, 1 en attente de décision, 1 refusé et 1 radié

**Comment by ledugong** [comment]
@Toub des stats apparaissent cette fois sauf qu'on a toujours qu'un seul refusé (alors qu'il y en a eu 2) et on voit 2 "Nombre d'attestations d'élection de domicile délivrées" alors qu'il n'y a qu'un actif

**Comment by ledugong** [comment]
Nouveau ticket pour régler le souci des stats du premier jour qui n'apparaissent pas : https://github.com/SocialGouv/domifa/issues/975 

Sinon recette PO OK
