### ISSUE TITLE
sec(cors): configure cors

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#919]
**Description du problème**

Suivant la configuration de l'environnement utilisateur, certaines requêtes sont bloquées en raison de la configuration cors non sécurisée (wildcard).

**Comportement attendu**

Configurer CORS correctement, et vérifier que le problème est résolu pour la structure concernée.

**Scénario de reproduction du problème**

A reproduire sur l'environnement de la structure, via les tickets suivants:

- https://github.com/SocialGouv/domifa/issues/856
- https://github.com/SocialGouv/domifa/issues/884

**Copies d'écran**

![image](https://user-images.githubusercontent.com/367762/96453179-c5b39200-1222-11eb-9b9f-1121811b0a96.png)

**Recette PO**

- [x] en pré-prod, vérifier la valeur de l'entête de la réponse
- [ ] en prod, idem + faire test avec l'utilisateur

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Toub** [comment]
Test ok en pré-prod:

![image](https://user-images.githubusercontent.com/367762/97185412-0f672400-17b1-11eb-8025-12893a7e0900.png)

**Comment by ledugong** [comment]
Pas recettable PO

**Comment by ledugong** [comment]
Pas recettable Prod
