### ISSUE TITLE
feat(STATISTIQUES): date de début = date inscription structure

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#922]
**Situation Actuelle**

Sur la page statistiques structure, la date de départ est le 01/01/2020 par défaut. Or, les stats ne sont disponibles qu'à partir de mai, ce qui crée quelques bugs. 
L'idéal serait que la date de début par défaut soit la date de création de la structure.

Et si la structure faire un hard reset, mettre la date de ce hard reset en date de début.

**Comportement souhaité**

Que la date de début affichée par défaut soit la date d'inscription de la structure.
Que la date de début affichée soit la date de hard reset en cas de hard reset.

**Recette PO**

Créer une nouvelle structure et vérifier la date affichée dans les stats.
Tester un hard reset et vérifier la date affichée dans les stats.

**Comment by Toub** [comment]
Si la structure existe avant la date de première stat (6/5/2020), ne vaut-il  pas mettre cette dernière date comme date de début par défaut?

**Comment by ledugong** [comment]
Recette PO OK
