### ISSUE TITLE
debt(mongo): migration postgresql - proto typeorm + postgres

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#929]
Ticket parent: #793

## Description

Sur une branche, intégrer un proto `typeorm` permettant de migrer le document `stats` vers postgres:

- [x] déterminer la version de postgres (`v10`)
- [x] ajout de postgres à la doc d'install, au docker-compose de dev
- [x] ajout de typeorm et configuration pour postgres
- [x] définition du schéma `StatsTable.typeorm.ts` inspiré de `Stats.class.ts`
- [x] ajout du sytème de migrations typeorm
- [x] migration: création de la structure de la table
- [x] migration: copie des données depuis mongo
- [x] remplacement de `mongoose` par `typeorm` sur les services utilisant `Model<StatsDocument>` (sauf migrations):
  - [x] `StatsGeneratorService`
  - [x] `StatsService`
- [x] ajout de postgres au docker-compose de prod
- [x] configuration .env de pre-prod
- [x] configuration .env de prod
- [x] intégration de postgres à travis
- [x] déploiement en pré-prod
- [x] tests de non régression
- [x] script de backup des données et config cron

Recette:

- [x] tests de non régression de tout ce qui est lié aux stats

**Comment by ledugong** [comment]
Recette PO OK
