### ISSUE TITLE
debt(e2e): mise à jour des e2e pour execution en local

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#939]
**Description du problème**

Pour assurer le bon suivi de la migration, il sera nécessaire de mettre à jour les tests e2e.

**Comportement attendu**

Description du comportement souhaité

- [x] Mettre à jour le fichier dump_test.gzip
- [x] Faire en sorte que la DB de test soit utilisé lors du lancement des tests
- [x] Créer un fichier test pour les stats 

**Scénario de reproduction du problème**

**Informations complémentaires:**

**Recette PO**

**Comment by Toub** [comment]
Test ok sur travis, à fermer.
