### ISSUE TITLE
debt(mongo): migration du document users

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#965]
Ticket parent: #793

**Comportement souhaité**

Migration du document __users__ de mongo à postgres.

- migration des données
  - [x] création du modèle et patch sql
  - [x] migration des données mongo=>pg

- migration des services
  - [x] BACKEND: UsersService
  - [x] BACKEND: CronMailsService
  - [x] BACKEND: DashboardService (mineur)
  - [x] BACKEND: DashboardController (populate structure)

**Recette PO**

- [x] s'assurer qu'il n'y a pas de régressions sur l'ensemble de l'application
- [x] tester l'envoi des mails automatiques (guide et import) 
- [x] création de structures
- [x] création d'utilisateurs
- [x] ré-initialisation de mot de passe
- [x] modification d'un utilisateur
- [x] supression d'un utilisateur
- [x] tester le hard reset d'une structure

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@Toub pour info, pour tester les envois de mail automatiques (guide et import), faudra attendre 15 jours

**Comment by Toub** [comment]
On va raccourcir ça à 30mn en préprod via ce ticket : https://github.com/SocialGouv/domifa/issues/987

**Comment by ledugong** [comment]
Recette PO suspendue en attente de la correction des mails et du hard reset

**Comment by ledugong** [comment]
Hard reset fait le 03/12 en fait, à vérifier demain ce que ça donne

**Comment by ledugong** [comment]
Fait

S'assurer qu'il n'y a pas de régressions sur l'ensemble de l'application :
- connexion / déconnexion 
- modification informations personnelles
- changement des rôles utilisateur
- suppression utilisateur
- création/suppression domicilié
- interactions courrier/passage/appel
- ayant-droit/transfert/procuration/pj
- téléchargement cerfa
- radiation
- import

Création structure

Création d'utilisateurs :
- ajout d’un utilisateur via l’interface structure
- ajout via le bouton inscription (testé refus et validation)

Ré-initialisation de mot de passe :
- via page de connexion
- via page mon compte

Envoi des mails automatiques (guide et import)

Hard reset d'une structure
