### ISSUE TITLE
debt(mongo): migration du document interactions

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#968]
Ticket parent: #793

**Comportement souhaité**

Migration du document __interactions__ de mongo à postgres.

**Migration des données**
  - [x] création du modèle et patch sql
  - [x] migration des données mongo=>pg

- migration des services Interactions

- [x] create
- [x] find
- [x] findOne
- [x] deuxDerniersPassages
- [x] findLastInteraction
- [x] delete
- [x] deleteByUsager
- [x] deleteAll
- [x] totalInteraction

- Migration des services dans les stats et dashboard
- [x] Stats générator : totalInteraction
- [x] Dashboard: getInteractionsCountByType

**Recette PO**

- [x] Vérifier sur un profil que les interactions s'affichent dans l'ordre décroissant
- [x] Ajouter une interaction depuis la liste et bien vérifier que le compteur s'incrémente bien
- [x] Supprimer une interaction et retrouver l'état précédent : si on supprime 2 courriers distribués, revoir 2 courriers en attente
- [x] Vérifier la cohérence des chiffres des interactions dans le dashboard Domifa et sur la homepage

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
@Toub @pYassine "Vérifier sur un profil que les interactions s'affichent dans l'ordre décroissant" je comprends pas ce qui s'affiche par ordre décroissant... les bandeaux bleus avec le nbre de courrier/colis/adp en attente ?

**Comment by pYassine** [comment]
@ledugong le panneau des dernières interactions. On affiche bien les interactions du plus récent au plus vieux
![Capture d’écran 2020-11-25 à 09 45 15](https://user-images.githubusercontent.com/11486845/100203559-0ded6080-2f03-11eb-9499-be23531ac8ee.jpg)

**Comment by ledugong** [comment]
@pYassine toutes les interactions sont "bloquées" au 25/11 à 14h07. J'ai fait un enregistrement de mon écran si besoin. 
<img width="511" alt="Capture d’écran 2020-11-26 à 17 11 03" src="https://user-images.githubusercontent.com/59437305/100373016-5fccde00-300a-11eb-92d1-6ead537c58b4.png">

**Comment by ledugong** [comment]
Un actif et un refusé ajouté aujourd'hui sur le compte Domifa Test en PP, à vérifier demain

**Comment by ledugong** [comment]
Stats actif et refusé bien ajoutées sur PP
