### ISSUE TITLE
bug(STATISTIQUES_DÉPLOIEMENT): colonne région/département inversée et mauvais noms régions

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#972]
**Description du problème**

Dans l'export des stats déploiement, les colonnes "région" et "département" ont été inversées.
De même, la nomenclature des régions n'est pas la bonne, les noms ne sont pas les bons (déjà vu avec @pYassine par le passé).
Ci-dessous la bonne nomenclature : 
![Image collée à 2020-11-13 14-21](https://user-images.githubusercontent.com/59437305/99195378-8c206900-2785-11eb-855c-03d893cb312c.png)

**Comportement attendu**

Nom des colonnes correct.
Bonne nomenclature des régions.

**Comment by Toub** [comment]
Liste ici: https://www.regions-et-departements.fr/regions-francaises

Corrections:
- Alsace-Champagne-Ardenne-Lorraine => Grand Est
- Nord-Pas-de-Calais-Picardie => Hauts-de-France
- Aquitaine-Limousin-Poitou-Charentes => Nouvelle-Aquitaine
- Languedoc-Roussillon-Midi-Pyrénées => Occitanie

**Comment by ledugong** [comment]
Noms colonnes OK
Nouvelles régions OK
Export OK

Recette PO OK
