### ISSUE TITLE
bug(STATISTIQUES): jour 1 des stats structure ne s'affichent pas

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#975]
**Description du problème**

Sur le compte test PP Stats, un refus a été crée le jour de la création de la structure et celui-ci ne s'affiche pas sur les stats.

**Comportement attendu**

Que ce refus du premier jour de la structure (à priori le 13/10) soit bien comptabilisé dans les stats.
Il semblerait que les stats du jour de création d'une structure ne s'affichent pas, corriger cela.

**Recette PO**

Vérifier les stats:
- [ ] sur une structure sur la quelle on a créé des stats dès le première jour
- [ ] sur une structure sur la quelle on n'a créé des stats dès le première jour
- [ ] tester le reset
- [ ] vérifier que le bug n'apparait pas non plus sur les structures pré-existantes

TODO:

- [ ] à la création d'une structure, créer une stat à 0 pour la veille
- [ ] lors du reset d'une structure, créer une stat à 0 pour la veille
- [ ] ajouter une stat à 0 pour les structures déjà existantes, la veille de la première stat

**Comment by ledugong** [comment]
@Toub @pYassine en créant une structure, la page de stats initiale est celle ci-dessous : 
<img width="1271" alt="Capture d’écran 2020-11-26 à 10 24 44" src="https://user-images.githubusercontent.com/59437305/100332523-c84b9900-2fd1-11eb-85cd-132760dc87f5.png">

Est-ce que du coup on peut mettre la date J+1 en date de début et griser le tout ? Car actuellement ça fait bug.

**Comment by Toub** [comment]
Ce bug devrait disparaitre une fois que @pYassine aura traité ce ticket, car il y aura des données.

**Comment by Toub** [comment]
A re-tester après avoir mergé ce ticket: https://github.com/SocialGouv/domifa/issues/975

**Comment by ledugong** [comment]
Hard reset fait sur DomiFa Test en PP le 03/12 et le même jour, un actif et un refusé ajoutés, à voir demain

**Comment by ledugong** [comment]
Les stats du 03/12 sont bien visibles

**Comment by ledugong** [comment]
Structure crée en production le 16/12 avec ulipybeba-5158@yopmail.com, ajout de stats le même jour (1 actif, 1 refusé, 1 appel, 1 courrier), à voir le 17/12 si les stats s'affichent bien

**Comment by ledugong** [comment]
Prod OK
