### ISSUE TITLE
dev(env): cleaning environnements docker dev/test

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#976]
**Description du problème**

Difficile de s'y rentrouver entre les différents environnement:

- local: dev + test
- travis
- dist: prod, preprod

**Comportement attendu**

Uniformiser les environnements dev et travis
- [x] uniformiser docker-compose.local.yml et docker-compose.travis.yml
- [x] scripts sh pour lancer l'environnement de dev

Simplifier la configuration des environnements
- [ ] charger l'environnement avant de lancer l'application, plutôt que de déterminer quel fichier d'env charger à l'intérieur de l'app
- [x] configurer le maximum d'options par défaut, en fonction du type d'environnement (dev, test, dist...)
- [ ] réduire le nombre de fichiers env différents

Scripts base de données:
- [x] réduire le nombre de scripts, en leur passant les options en paramètres

- [x] mise à jour documentation

**Comment by Toub** [comment]
On laisse ça de côté:
>  charger l'environnement avant de lancer l'application, plutôt que de déterminer quel fichier d'env charger à l'intérieur de l'app

Il y aurait d'autres choses à faire, mais ça suffit pour le moment.

**Comment by ledugong** [comment]
@Toub il manque 2 coches dans les actions, c'est de ton côté ou du mien ?

**Comment by Toub** [comment]
Ca sera traité ultérieurement, dans un autre ticket. On laisse comme ça. Rien à faire pour toi ici.

**Comment by ledugong** [comment]
Ok non recettable PO
