### ISSUE TITLE
feat(EXPORT): ajout colonnes de suivi des actions par utilisateur

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#983]
**Situation Actuelle**

Suite aux OpenLab, une demande d'ajouts de colonnes sur l'export a été évoquée, à savoir le nom de l'utilisateur ayant procédé à un refus, une radiation, une première dom ou un renouvellement.

**Comportement souhaité**

Ajout des colonnes suivantes : 
- colonne "Utilisateur ayant refusé" à droite de la colonne "Motif si refusé"
- colonne "Utilisateur ayant radié" à droite de la colonne "Motif si radié"
- colonne "Utilisateur ayant validé la 1ere dom" à droite de la colonne "Date 1ere dom"
- colonne "Si renouvellement, utilisateur l'ayant validé" à droite de la colonne "Utilisateur ayant validé la 1ere dom"

Afficher le nom prénom de l'utilisateur ayant fait l'action.
Concernant la colonne "Si renouvellement, utilisateur l'ayant validé", la laisser vide s'il n'y a pas de renouvellement.

**Recette PO**

Faire l'export, vérifier les colonnes et les noms d'utilisateur.

**Comment by Toub** [comment]
A priori, on a cette info dans `usager.historique.userName`, @pYassine tu confirmes?

**Comment by pYassine** [comment]
@Toub exact !

**Comment by ledugong** [comment]
@pYassine en cas de renouvellement suite à une 1ere dom, peut-on remplir aussi la case "Utilisateur ayant validé la 1ere dom" ?

**Comment by ledugong** [comment]
@pYassine j'ai testé une création de dom validée par une personne puis un renouvellement validé par une autre personne et dans l'export c'est la personne qui a renouvelé qui apparait dans les 2 cases
<img width="1054" alt="Capture d’écran 2020-12-01 à 17 57 37" src="https://user-images.githubusercontent.com/59437305/100771424-b5382f00-33fe-11eb-8b9e-e76ff2b156c4.png">

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
@pYassine pourras-tu me dire ici quand tu auras corrigé le souci de colonnes ?

**Comment by ledugong** [comment]
Recette PO OK

Première domiciliation
Renouvellement validé (avec utilisateur différent)
Renouvellement refusé (avec utilisateur différent)
Radiation

**Comment by ledugong** [comment]
Recette Prod OK
