### ISSUE TITLE
feat(cron): configurer différemment les délais d'envoi de mails en prod/préprod/dev

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#987]
**Situation Actuelle**

Les mails sont envoyés après 7 jours dans `CronMailsService`

**Comportement souhaité**

En dev et en préprod, pouvoir configurer un délai beaucoup plus court, pour les tests.

Suggestion:
- 1mn en dev
- 30mn en préprod

**Recette PO**

- [ ] vérifier que les mails sont envoyés au bout de 30mn

**Comment by ledugong** [comment]
@Toub j'ai crée la structure Test Stats PP ce matin avec l'adresse ulepurre-7871@yopmail.com. J'ai bien reçu le mail de validation de la structure par DomiFa mais je n'ai pas reçu les mails de guide et d'import.

**Comment by Toub** [comment]
Ok. Ils auraient du arriver sous moins d'1h, dis-moi si ils arrivent demain, et repasse ce ticket dans ma TODO stp.

**Comment by ledugong** [comment]
@Toub toujours pas de mails aujourd'hui, le ticket est remis dans en cours :)

**Comment by Toub** [comment]
Les crons étaient désactivés en préprod, les mails devraient partir d'ici 1h

**Comment by ledugong** [comment]
@Toub nouvelle structure crée avec aqommete-6728@yopmail.com vers 18h15 mais pas de mail automatique reçu 30min après (mais mail de validation de la structure reçu).

**Comment by ledugong** [comment]
Création d'une structure OK
Réception du mail de validation de la structure OK
Réception du mail guide + import 5min après OK
