### ISSUE TITLE
bug(users): user fantôme, associé à aucune structure.

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#990]
**Description du problème**

Un compte a été repéré comme étant complètement isolé, lié à une structure supprimée.

**Comportement attendu**

- [ ] Vérifier qu'il n'en existe pas d'autres
- [ ] Le cas échéant, trouver un moyen de les nettoyer
- [ ] Rechercher d'où peut venir ce bug (suppression des structures ?)

**Scénario de reproduction du problème**

1. Se connecter en tant que '...'
2. Aller sur la page '....'
3. Cliquer sur '....'
4. Le ... est incorrect

**Copies d'écran**
![Capture d’écran 2020-11-24 à 16 04 58](https://user-images.githubusercontent.com/11486845/100111874-e2209b00-2e6e-11eb-810b-c5a3daf13870.jpg)

**Recette PO**

- [ ] Se connecter avec le compte fantôme, vérifier qu'il n'est plus accessible
- [ ] test 2...

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by Toub** [comment]
Ce bug peut se produire à la création d'une structure, car on fait 2 appels API.

Si le second pète, l'user est quand même créé.

Il faudrait les réunir en une seule.

**Comment by ledugong** [comment]
@pYassine peux-tu me donner le compte fantôme en question ?
Je dois juste valider que je ne peux plus me connecter ?

**Comment by pYassine** [comment]
@ledugong domifa@yopmail.com

**Comment by ledugong** [comment]
@pYassine sans mot de passe ?

**Comment by ledugong** [comment]
Pas possible de demander un nouveau mdp, l'adresse mail n'existe donc plus

**Comment by ledugong** [comment]
Pas de connexion possible
Pas possible de demander un nouveau mdp, l'adresse mail n'existe donc plus

Recette Prod OK
