### ISSUE TITLE
feat(INTERFACE_STRUCTURE): ajouter l'upload de pj pour la structure

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#994]
**Situation Actuelle**

Le but est d'ajouter une section dans l'interface structure pour uploader des documents internes style règlement, charte etc.

**Comportement souhaité**

- [x]  1. Déjà on va homogénéiser le wording : dans Ma Structure, corriger "Informations de ma structure" pour "Informations de votre structure".

- [x]  2. En-dessous de la section "Vos données", ajouter une section "Vos documents" avec le module d'ajout de pj comme sur la fiche domicilié : donc avec un champ texte pour le titre de la pj et des boutons télécharger et supprimer une fois la pj uploadée.

ATTENTION, enlever le texte en surbrillance sur le champ du titre de la pj (qui dit "cerfa, pièce d'identité etc.") car ça ne sera pas les mêmes documents.

- [x] 3. Cette nouvelle section est disponible seulement pour les admins.

- [x] 4. Ajouter une ligne "Ajout documentation interne structure" sur le doc de gestion des rôles. L'ajouter en-dessous de "Modification des informations de votre structure" avec une coche pour Admin.

Sinon aller voir le document des rôles et accès sur le drive, il est à jour.

**Recette PO**

Vérifier les textes, uploader les docs, les télécharger et les supprimer.
Vérifier le tableau de gestion des profils.

**Comment by ledugong** [comment]
@pYassine est-ce que tu pourrais renommer la section "Ma Structure" en "Structure" ? Car c'est la seule section avec un possessif dans l'interface.

**Comment by ledugong** [comment]
@pYassine ya encore les possessifs "Mon compte" et "Ma structure" dans l'interface usager structure, peux-tu les enlever ?

Si j'essaye d'uploader un fichier non supporté sur une fiche domicilié (testé avec le modèle de l'import donc format xlsx), j'ai bien un message d'erreur mais la barre de chargement reste à 100%
<img width="945" alt="Capture d’écran 2020-12-22 à 10 28 17" src="https://user-images.githubusercontent.com/59437305/102872813-90087080-4440-11eb-807d-9104676c0d2f.png">

Pour le profil gestionnaire, j'attends que tu redéploy pour tester.

**Comment by pYassine** [comment]
Corrigé ! @ledugong

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
